### ISSUE TITLE
Consider non Spring Applications

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#10]
We may want to consider non Spring Applications by reducing the number of dependencies and providing a mechanism for configuring with Filter parameters.

**Comment by vpavic** [comment]
At the moment `spring-session-core` only depends on `spring-jcl`, which has a minimal footprint and doesn't pull in any other Spring modules - I think this is as good as it gets regarding core. Actually all other dependencies are optional.

Other modules (Redis, JDBC) implement session repositories using Spring specific data store integration support so we can't reduce anything there. As for Hazelcast module, theoretically something could be done there but at the expense of the consistency of configuration capabilities which I don't believe is reasonable thing to do.

With all this in mind, can we close this @rwinch?
