### ISSUE TITLE
Getting session_id from cookie?

### ISSUE THREAD

**Issue by littlehome-eugene** [spring-projects/spring-session#1000]
I know `session_id` is stored in cookie and it is used to retrieve user info upon requests.

However when I look at the cookie value in chrome, and databasse (SPRING_SESSION table), there's no matching session_id.  

Also, it perflexes me that SPRING_SESSION has primary_id as primary key and there's no index on session_id. 

How can I get the session_id as in `request.getSession.getId()` from reading cookie ?

**Comment by vpavic** [comment]
Starting with Spring Session 2.0, session cookie is Base64 encoded by default. See #736 and [`DefaultCookieSerializer` source](https://github.com/spring-projects/spring-session/blob/815cbf4ee8b288862024ba6f7fa29e64b4a83dc5/spring-session/src/main/java/org/springframework/session/web/http/DefaultCookieSerializer.java#L56).

Also starting with 2.0, support for `Session#changeSessionId` has been added in #835. This means that session stores had to adjust to be able to support changing the session id. For a relational database, this means that original session id is used as primary key, while a separate column keeps track of the current session id.

Regarding reading the session id from cookie, you can either disable Base64 encoding of session cookie or do Base64 decode on the client.

**Comment by littlehome-eugene** [comment]
Thank you for the answer.
