### ISSUE TITLE
When two machines share session, does clock difference matter when getting a session?

### ISSUE THREAD

**Issue by littlehome-eugene** [spring-projects/spring-session#1001]
When session clustering, does the clock difference between two machines matters?

Because I see `JdbcOperationsSessionRepository::findById` calls `isExpired` and it seems to depend on system time

```
   @Override
   public boolean isExpired() {
     return isExpired(Instant.now());
   }

   boolean isExpired(Instant now) {
     if (this.maxInactiveInterval.isNegative()) {
       return false;
     }
     return now.minus(this.maxInactiveInterval).compareTo(this.lastAccessedTime) >= 0;
   }
```

**Comment by gregturn** [comment]
Probably does. For something tied to time, it’s critical that clocks be synchronized.

**Comment by littlehome-eugene** [comment]
Oh, so is it a standard practice to rely on clocks being synchronized for session clustering? 

I'm so new to this concept and wonder if it's acceptable solution by industry?

**Comment by gregturn** [comment]
LOTS of issues can arise when servers aren’t synchronized.

**Comment by littlehome-eugene** [comment]
I see! 
what's the one of prefered way of synchronizing clock? ntpd fine?

**Comment by littlehome-eugene** [comment]
@vpavic I have a related question.  

I have two servers.  
Only one server creates a session, and another server tests if a user has a session created by the first server.

If I use Redis session backend, and uses `SessionExpiredEvent` to delete session data in the redis myself, can I make sure that session is removed from the redis even when clock is not synchronized?
