### ISSUE TITLE
Expiring Key support for JDBC Session

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1002]
I came across a scenario that each key has a specific TTL and are expired passively. Do you think that does it make sense to support such a feature? What do you think?

**Comment by cemo** [comment]
https://gist.github.com/joelittlejohn/5565410

I was considering something like this

**Comment by vpavic** [comment]
Hi @cemo, can you clarify what exactly do you mean by "each key"? A session attribute key or something else?

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
