### ISSUE TITLE
How does spring-session associate a user to a session?

### ISSUE THREAD

**Issue by littlehome-eugene** [spring-projects/spring-session#1003]
This might not be specific to spring-session.  

I know a `session_id` is stored in the user browser cookie (with base64 encoded)

Given `session_id`, server looks up session by `sessionRepository.findById(session_id)` and grabs user's pk? 
Is that the way how session associates a user to a session?

So if whoever can store a someone else's `session_id` in his browser cookie, he could impersonate someone else?  
Is there any guard against such attack? 

**I would like to know if there's any guard after a malicious user successes modifying his browser cookie with someone else's `session_id` .** 

Of course there could be some guard against modifying cookie or getting someone else's session_id in the first place. (is Https a solution for this type of vulnerability?)

**Comment by eleftherias** [comment]
It is possible to impersonate someone by having access to their session ID.
This type of attack is called "Session Hijacking".
HTTPS is a good prevention method, and there are many more prevention measures to consider.
There are a lot of good resources on the web that you can find by doing a search for "Session Hijacking".

Please re-open this issue if you have a concern about spring-session.
