### ISSUE TITLE
Upgrade to Spring Boot 2.0.0.RELEASE

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-session#1007]

**Comment by jayzch** [comment]
After upgrade to Spring Boot 2.0.0.RELEASE , spring session doesn't work!

**Comment by vpavic** [comment]
@jayzch This ticket tracks the upgrade of Boot based sample apps to `2.0.0.RELEASE`. If you believe you've found a problem, please open a new issue and provide some details about the problem.
