### ISSUE TITLE
MapSessionRepository doesn't issue app session events

### ISSUE THREAD

**Issue by alex-konkov** [spring-projects/spring-session#1015]
Make MapSessionRepository capable of issuing `SessionCreatedEvent`/`SessionDeletedEvent`/`SessionExpiredEvent` as its done by other session repo impls.

**Comment by vpavic** [comment]
Thanks for the report @alex-konkov.

The event publishing capability of a `SessionRepository` implementation is highly coupled to the capabilities of the underlying data store. For instance, a relational database has no publish-subscribe mechanism (like Redis and Hazelcast do) and as such `JdbcOperationsSessionRepository` does not support event publishing.

With `MapSessionRepository`, handling of session expiry (and by extension, event publishing) is the responsibility of the supplied `Map` implementation. For those reasons, `MapSessionRepository` isn't considered a production grade `SessionRepository` implementation.

**Comment by alex-konkov** [comment]
Let me clarify. My use case is exactly like that (non production) and related to integration tests. Our system relies on session events and we want to have integration test working without real session store (Redis in our case). Having no configuration option (which can be disabled by default) for firing such events makes it impossible to implement such tests.

**Comment by vpavic** [comment]
Well, if you insist of using `MapSessionRepository`, you'd have to handle the expiration and event publishing yourself depending on the implementation of the `Map` that was supplied to the `MapSessionRepository`. Note that we don't know anything implementation specific about the supplied `Map`.

As a sidenote, for integration testing I'd suggest you to use [TestContainers](https://www.testcontainers.org/). This is what we actually use ourselves for integration testing of `SessionRepository` implementations.
