### ISSUE TITLE
get current spring session token 

### ISSUE THREAD

**Issue by dario-frongillo** [spring-projects/spring-session#1020]
Hi All, 
if in authenticated controller i execute the following code;
```
        ServletRequestAttributes attr = (ServletRequestAttributes) RequestContextHolder.currentRequestAttributes();

        HttpSession session = attr.getRequest().getSession(true);

       String token = session.getId();

```

in token i have the jsessionid but not the spring session custom token. how can i retrieve the current spring session token ?

**Comment by vpavic** [comment]
Hi @dario-frongillo,

Can you clarify a bit what do you mean by _in token i have the jsessionid but not the spring session custom token_?

I see no problem with the code snippet you provided, it works for me as expected.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
