### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by semchev** [spring-projects/spring-session#1023]
spring-boot-version is not defined in spring-session/docs/spring-session-docs.gradle to replace placeholder in:

- docs/src/docs/asciidoc/guides/boot-jdbc.adoc
- docs/src/docs/asciidoc/guides/boot-redis.adoc
- docs/src/docs/asciidoc/guides/grails3.adoc

causing dead links to be referenced in the resulting html documentation.

```
asciidoctor {
	def ghTag = snapshotBuild ? 'master' : project.version
	def ghUrl = "https://github.com/spring-projects/spring-session/tree/$ghTag"

	attributes 'docs-itest-dir': "$rootProject.projectDir.path/docs/src/integration-test/java/",
			'docs-test-dir': "$rootProject.projectDir.path/docs/src/test/java/",
			'docs-test-resources-dir': "$rootProject.projectDir.path/docs/src/test/resources/",
			'download-url': "https://github.com/spring-projects/spring-session/archive/${ghTag}.zip",
			'gh-samples-url': "$ghUrl/samples/",
			'gh-url': ghUrl,
			'hazelcast-version': versions['com.hazelcast:hazelcast'],
			'lettuce-version': versions['io.lettuce:lettuce-core'],
			'samples-dir': "$rootProject.projectDir.path/samples/",
			'session-jdbc-main-resources-dir': "${project(':spring-session-jdbc').projectDir.path}/src/main/resources/",
			'spring-data-redis-version': versions['org.springframework.data:spring-data-redis'],
			'spring-framework-version': versions['org.springframework:spring-core'],
			'spring-security-version': versions['org.springframework.security:spring-security-core'],
			'spring-session-version': project.version,
			'version-milestone': milestoneBuild,
			'version-release': releaseBuild,
			'version-snapshot': snapshotBuild
}
```

see:
[spring-session/docs/spring-session-docs.gradle](https://github.com/spring-projects/spring-session/blob/45807998f62d8a22fc6f548c798ba19fd40ddeda/docs/spring-session-docs.gradle)
[docs/src/docs/asciidoc/guides/boot-jdbc.adoc](https://github.com/spring-projects/spring-session/blob/ebd4b349d238f21e4c3d1141fe920634442159d7/docs/src/docs/asciidoc/guides/boot-jdbc.adoc)
[docs/src/docs/asciidoc/guides/boot-redis.adoc](https://github.com/spring-projects/spring-session/blob/ebd4b349d238f21e4c3d1141fe920634442159d7/docs/src/docs/asciidoc/guides/boot-redis.adoc)
[docs/src/docs/asciidoc/guides/grails3.adoc](https://github.com/spring-projects/spring-session/blob/ebd4b349d238f21e4c3d1141fe920634442159d7/docs/src/docs/asciidoc/guides/grails3.adoc)

**Comment by vpavic** [comment]
Thanks for the report @semchev. I can see that some links are broken indeed.
