### ISSUE TITLE
Spring Boot server.session.timeout no effect

### ISSUE THREAD

**Issue by nagyzsolthun** [spring-projects/spring-session#1024]
I configured my Spring Boot app based on https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html, however server.session.timeout seems to have no effect on Session expiration.

Sample project: https://github.com/nagyzsolthun/spring-boot-session-timeout
Expiration timestamps in redis indicate that timeout duration is 30 mins, and not 10 seconds as I configured in application.properties.

**Comment by vpavic** [comment]
Thanks for the report @nagyzsolthun and providing a sample app.

You are using a deprecated `server.session.timeout` which was replaced with `server.servlet.session.timeout` in Spring Boot 2.0. With the change from PR I've opened against your sample repo (nagyzsolthun/spring-boot-session-timeout#1) the desired session timeout is applied correctly.

Please take time to [Spring Boot 2.0 Migration Guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide) and consider using `spring-boot-properties-migrator` module.

**Comment by nagyzsolthun** [comment]
Thanks for the prompt answer @vpavic. Can you also update the referenced document with the correct property-name? (as I see you are one of the authors)

**Comment by vpavic** [comment]
Are you referring to our [HttpSession with Redis Guide](https://docs.spring.io/spring-session/docs/2.0.2.RELEASE/reference/html5/guides/boot-redis.html)? It does use outdated Spring Boot application properties, thanks for pointing that out! I've opened #1025 to address that.
