### ISSUE TITLE
RedisOperationsSessionRepository's changeSessionId causes SessionDestroyedEvent warnings

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1029]
The `RedisOperationsSessionRepository.RedisSession#changeSessionId` added in Spring Session 2.0 causes the following `SessionDestroyedEvent` warnings:

```
2018-03-23 21:31:57.160  WARN 18514 --- [enerContainer-3] s.s.d.r.RedisOperationsSessionRepository : Unable to publish SessionDestroyedEvent for session b965668d-4c83-445a-a951-325375be9eeb
```

This is caused by `RedisOperationsSessionRepository.RedisSession#saveChangeSessionId` implementation, which renames the session key but leaves the expiration key for the previous session id intact. So when this key expires, `SessionDestroyedEvent` handling is invoked for the session record that doesn't exist.

The problem can be reproduced using Spring Security with default web security config, or something as simple as:

```java
http
	.formLogin()
		.and()
	.authorizeRequests()
		.anyRequest().authenticated();
```

After logging in, the existing session has its session id changed, after which the expiration key for old session id can be observed in Redis.

Note: Although the effect of this bug is basically the same to one reported in #499, this is a different issue that doesn't occur in `1.3.x`, where `changeSessionId` is not implemented natively but rather by deleting session and creating a new one.

**Comment by vpavic** [comment]
@pch851130 Thanks for the report, but closed issues are not ideal way of reporting issues.

Please open a new issue and provide as much details as possible (exact versions you're using, relevant config) or, even better, a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) that we can use to reproduce the problem.

**Comment by gelonggld** [comment]
I have the same problem with spring boot 2.0.3,how to fix it

**Comment by vpavic** [comment]
@gelonggld I've you believe you're facing the same problem with Spring Session `2.0.3.RELEASE` or newer please open a new issue, ideally coupled with a sample that can be used to reproduce the problem.
