### ISSUE TITLE
Restarting Redis server causes session destroyed events to stop working

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1030]
While investigating #1017, I came across scenario that breaks session destroyed `HttpSessionEvent` support for Spring Session Redis.

If Redis server is stopped after an app that uses Spring Session has started, and then started again, app will not received Redis keyspace notifications until itself has been restarted. This in turn will prevent session destroyed `HttpSessionEvent` support from working. The problem affects both Spring Session 1.3 and 2.0, regardless of the Redis driver used.

Perhaps we could look into detecting that the re-connection event has occurred, and attempt re-attaching message listeners.

/cc @rwinch

**Comment by rwinch** [comment]
@vpavic Without looking into this any, this sounds more like an issue with Spring Data. Thoughts?

**Comment by vpavic** [comment]
It might as well be the case.

Pinging @christophstrobl and @mp911de for their insight on the scenario described above.

**Comment by mp911de** [comment]
Care to elaborate the kind of events you're looking for?

I tried to reproduce the issue by using `RedisMessageListenerContainer`, subscribe to events and restart Redis while the app is running. Subsequent `PUBLISH` commands will work.

It sounds as if you rely on keyspace events (`CONFIG SET notify-keyspace-events …)` that must be configured and written to a config file explicitly.

**Comment by vpavic** [comment]
I should've provided more context upfront, sorry about that.

Yes, keyspace notifications are the subject here, see [this code](https://github.com/spring-projects/spring-session/blob/master/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java#L131-L133).

**Comment by mp911de** [comment]
Starting a plain Redis server without a config file always requires explicit configuration. We currently don't have a mechanism to hook into connect/reconnect and execute callbacks.

**Comment by vpavic** [comment]
Thanks for the explanation @mp911de.

It turns out we have this Redis configuration requirement [documented](https://docs.spring.io/spring-session/docs/2.0.2.RELEASE/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent), which I somehow managed to miss.

This makes the issue invalid, thanks for your help and sorry for the noise.
