### ISSUE TITLE
Migrate tests to JUnit 5

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1033]
With Gradle 4.6 introducing support for JUnit 5, we can now consider a migration of our tests to JUnit 5.

Prerequisites:
 - `@Rule` usages - see #1032
 - TestContainers rely on `@ClassRule` - see testcontainers/testcontainers-java#87

**Comment by bsideup** [comment]
@vpavic FYI you can use `.start()/.stop()` on Testcontainers' objects, `@ClassRule` is just a helper which calls them. Also FYI: we're working on native JUnit 5 support (will be also provided as a set of helpers on top of framework-neutral API)

**Comment by vpavic** [comment]
Thanks for following up on this @bsideup.

We already use this approach, as I believe you're aware, in our Tomcat/gretty based integration tests where TestContainers are registered as `@Bean`s.

However, TestContainers still has a dependency on JUnit 4 which leaks out to some public APIs. That's why we're tracking issue linked in opening comment as a prerequisite for migration to JUnit 5, as I'd like to avoid having a mix of JUnit 4 & 5 on the classpath and do a complete migration instead.

**Comment by bsideup** [comment]
@vpavic got it :)

**Comment by vpavic** [comment]
With Testcontainers adding first-class support in recently released `1.10.0` we can take a closer look at this for 2.2.
