### ISSUE TITLE
performance issues using spring session backed by infinispan cache

### ISSUE THREAD

**Issue by shivendra-kumar** [spring-projects/spring-session#1036]
Hi,
We are currently using spring session 2.0.1 backed by infinispan as our cache store in a clustered environment. We are currently facing performance issues as the commitSession() method of SessionRepositoryFilter always in turn calls save() method of MapSessionRepository which leads to too many infinispan cache puts over the network.

My question here is shouldn't the save() method of MapSessionRepository  be called only once session attributes are updated, removed and added?

Also, in one of our requirements in production environment we need our sessions to be sticky. So, does spring session support sticky session yet?

Regards,
Shivendra

**Comment by vpavic** [comment]
Thanks for the report @shivendra-kumar.

There's not support for sticky sessions yet, you can track #6 for that.

Regarding the question on number of invocations of `#save`, you might find some useful info in [#198 (comment)](https://github.com/spring-projects/spring-session/issues/198#issuecomment-95268087) and [reference documentation](https://docs.spring.io/spring-session/docs/current/reference/html5/#custom-sessionrepository).
