### ISSUE TITLE
spring session redis don't refresh the expired time

### ISSUE THREAD

**Issue by zjengjie** [spring-projects/spring-session#1039]
I find the redis session TTL only refresh if you access the first url before login(the `SPRING_SECURITY_SAVED_REQUEST`), any other request didn't update the TTL.

And the TTL didn't affected by `server.session.timeout` property.

version 2.0.2.RELEASE.

**Comment by zjengjie** [comment]
Only the session have attributes update the TTL will refresh.

**Comment by vpavic** [comment]
Thanks for the report @zjengjie. Are you referring to Servlet to WebFlux sessions?

**Comment by zjengjie** [comment]
Only on WebFlux, didn't test on servlet.

**Comment by vpavic** [comment]
I've reproduced the problem with TTL being refreshed only if attributes are changed.

Regarding the other question, `server.session.timeout` application property doesn't exist any more in Boot 2.0. The replacement for Servlet apps is `server.servlet.session.timeout` while for WebFlux apps you should use `spring.session.timeout`.

**Comment by vpavic** [comment]
> while for WebFlux apps you should use `spring.session.timeout`

Scratch that, I was wrong. It seems `server.servlet.session.timeout` is applied for WebFlux apps as well which I find confusing. I've opened spring-projects/spring-boot#12906

**Comment by vpavic** [comment]
Upon closer inspection, this doesn't appear to be the problem with `ReactiveRedisOperationsSessionRepository` but rather `SpringSessionWebSessionStore` as `SpringSessionWebSessionStore#retrieveSession` doesn't actually update the `lastAccessTime` as [required by the API](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/server/session/WebSessionStore.java#L45-L46).
