### ISSUE TITLE
Sessions are always dirty by default in JDBC implementation

### ISSUE THREAD

**Issue by okohub** [spring-projects/spring-session#1042]
Hello,

We are using Spring Session project widely in our projects, but we encountered a strange situation when we traced lifecycle of our requests.

```
org.springframework.session.jdbc.JdbcOperationsSessionRepository.SessionResultSetExtractor
```

When sessions are fetched from database, this extractor creates sessions.  At first that is okay, but  setAttribute method is making sessions default dirty. (I mean differences in delta)

So, even there is no update on session attributes, there are always SQL operations for writing them to spring_session_attributes table. We think it causes a performance problem.

In the other hand; if security context or principal name index name, or both of them, exist in attributes, it also marks session as changed, and there comes a new query for update session.

Correct me if I am wrong, If we imagine a logged in user in simple website, there will be minimum 3 update queries for each request even there is no operation on session.

What are the motivations, or applied best practices for this implementations and api designs?

**Comment by cemo** [comment]
Disclaimer: I am in the same team with @okohub 

@vpavic This is another issue we hit. 

It might be easily fix this issue by setting `session.clearChangeFlags()` at the end of `SessionResultSetExtractor` ?

What do you think?

**Comment by vpavic** [comment]
Thanks for the report @okohub and @cemo. We really appreciate your continuous feedback and help on getting Spring Session better.

I took a brief glance at this yesterday, and what you're proposing seems reasonable. Don't worry, this one's in my queue and I'll provide more feedback when I get a closer look.
