### ISSUE TITLE
SessionRepositoryFilter is fetching session multiple (4) times per request 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1048]
We are using JDBCSessionRepository and started to profile our application. On line 303 and 306 session is fetched twice: 

https://github.com/spring-projects/spring-session/blob/d97ad2ca3e2315f03203116a3ec74c1f7dab4fb5/spring-session-core/src/main/java/org/springframework/session/web/http/SessionRepositoryFilter.java#L303-L313

Here is the relevant `getRequestedSessionId` part. 

https://github.com/spring-projects/spring-session/blob/d97ad2ca3e2315f03203116a3ec74c1f7dab4fb5/spring-session-core/src/main/java/org/springframework/session/web/http/SessionRepositoryFilter.java#L354-L361

@vpavic I think this is a regression since I do not remember twice select before.

**Comment by cemo** [comment]
@rwinch @vpavic 

I think this issue is very important since `getRequestedSessionId` is buggy now. This method is used in many places. For a simple request `findById` is called at least called 4 times.

**Comment by vpavic** [comment]
Thanks for the report @cemo.

Why do you think the `SessionRepositoryRequestWrapper#getRequestedSessionId` is buggy? It does what it has to do in order to accommodate the changes to `HttpSessionIdResolver` (the successor to `HttpSessionStrategy`). For background on those changes see #275, #362 and #906.

That being said, I see your point with multiple retrieval of session as a part of `SessionRepositoryRequestWrapper#getSession(boolean)`. I'll see what can we do to optimize that.

**Comment by cemo** [comment]
Sorry @vpavic. I did not mean buggy. In fact it has some performance issues. I think it can cache session in `getRequestedSessionId` as well.

**Comment by vpavic** [comment]
Thanks for clarification @cemo. I think the `SessionRepositoryRequestWrapper#getRequestedSessionId` itself is fine, however some of its usages within the `SessionRepositoryFilter` could be optimized to avoid double retrieval from the session repository. That's the direction I'm currently looking into, will post back here when I have further updates.

**Comment by cemo** [comment]
Thanks @vpavic. Please let me know after you optimized it. I can test for you.

**Comment by cemo** [comment]
Please also note that it was called not only beginning of the request. At the end of request lifecycle it was called again multiple times. 

`org.springframework.session.web.http.SessionRepositoryFilter.SessionRepositoryRequestWrapper#commitSession`

`commitSession` session is called twice.

**Comment by vpavic** [comment]
@cemo I've pushed some WIP changes in #1050. This should optimize things a bit by not using `SessionRepositoryRequestWrapper#getRequestedSessionId` internally, where possible, and instead reusing retrieved session.

It seems that `SessionRepositoryRequestWrapper#commitSession` is a bit harder to avoid.

If you can give these changes a shot, that would be great.

**Comment by cemo** [comment]
@vpavic I will give a try but I think that we have a fundamental mistake.

from javax.servlet.http.HttpServletRequest#getRequestedSessionId:

```
    /**
     * Returns the session ID specified by the client. This may
     * not be the same as the ID of the current valid session
     * for this request.
     * If the client did not specify a session ID, this method returns
     * <code>null</code>.
     *
     * @return		a <code>String</code> specifying the session
     *			ID, or <code>null</code> if the request did
     *			not specify a session ID
     *
     * @see     #isRequestedSessionIdValid
     */
```

I think validating it by fetching from repository may not be correct behaviour. This might be better to be addressed in `isRequestedSessionIdValid`.  

I will also others implementation as well and let you know.

**Comment by cemo** [comment]
As I guessed, it has fixed behaviour. Please see imlementation:

https://github.com/eclipse/jetty.project/blob/977fb521a0be5a5440434b840533ba9e006966ce/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L2148-L2151

And 

It has set only from SessionHandler in without checking its validity.

https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java#L1605-L1690

Please let me know what do you think?

**Comment by cemo** [comment]
I see your point. I have double checked Jetty's implementation. They addressed same concern by setting `session` and `session id` at the same time. Here is the relevant part https://github.com/eclipse/jetty.project/blob/21365234f8cf036829f7a03e5c7b89a9572444f9/jetty-server/src/main/java/org/eclipse/jetty/server/session/SessionHandler.java#L1605-L1690

They are iterating all cookies and after a successful match they break the loop and than trying to set at the end of the method both `session` and `session id`.

**Comment by cemo** [comment]
Dear @vpavic, is there a due date for 2.0.3?

**Comment by vpavic** [comment]
We don't have any dates set yet, we'll update the [milestones page](https://github.com/spring-projects/spring-session/milestones) when we do.

**Comment by cemo** [comment]
@vpavic I think that this issue has not resolved by this commit. Should I open another one? I had written my findings at https://github.com/spring-projects/spring-session/commit/751375338c73136b9b758e069539790620e51c5e#r28863608

**Comment by vpavic** [comment]
> Should I open another one?

Please do as both closed issues and commit comments are not ideal places to discuss further improvements in this area.
