### ISSUE TITLE
JDBC Batch operations on Persisting Session Attributes 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1051]
This is not a major issue for us but I think it is good idea to have use batch operations for saving attributes.

**Comment by vpavic** [comment]
This already is the case, see [here](https://github.com/spring-projects/spring-session/blob/master/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L385-L402). Is this what you had in mind @cemo?

**Comment by cemo** [comment]
Sorry, I think I missed it.

**Comment by cemo** [comment]
@vpavic Sorry for confusion but I did not check correctly at my previous reply. Here is the relevant part I was referring. The `delta` is persisted in a loop.

https://github.com/spring-projects/spring-session/blob/d97ad2ca3e2315f03203116a3ec74c1f7dab4fb5/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L426-L452

**Comment by vpavic** [comment]
That is because when updating the session, the delta can contain additions, updates and removals of session attributes so we cannot batch those since they translate into different operations (insert/update/delete). This is in contrast to session creation, where all attributes are additions and can be inserted in a batch.

**Comment by cemo** [comment]
This is true but It can be done in a batch fashion as well. Batch operations returns `int[]` which can be used as same purpose as current. 

Also this can be improved in the first place. This requires some changes on delta object unfortunately. Introspecting `delta.entrySet()` provides only deleted items and ambiguity between insert and update. However when putting a variable into session it is clear that an addition or update is done. If a variable does not exist in the session before, setting it is a "addition". In same way, if it is already exists, it is an update operation. I mean the differentiation can be done in the first place.

**Comment by vpavic** [comment]
I see your point @cemo, I think we could do something about this without changes to delta representation.

**Comment by vpavic** [comment]
I've got some WIP optimizations in [this branch](https://github.com/vpavic/spring-session/tree/gh-1051). I did change the delta after all, but it was trivial since values weren't actually used anywhere, only the keys were.
