### ISSUE TITLE
What happened to the HttpSessionManager?

### ISSUE THREAD

**Issue by smorandi** [spring-projects/spring-session#1056]
I was looking at the example for using spring session for handling multiple sessions (https://docs.spring.io/spring-session/docs/2.0.0.M3/reference/html5/guides/java-users.html)

However, the HttpSessionManager class or rather the whole session management funcitonality for mutiple sessions has been removed?

Has there been any reason or is this supposed to be handled in a different way?

please forgive my question, but i am pretty new to spring session.

**Comment by vpavic** [comment]
Hi @smorandi - `HttpSessionManager` has been superseeded by `HttpSessionIdResolver` in Spring Session 2.0. That change was made in #906.

**Comment by smorandi** [comment]
Thank you for your reply.

Though I am not sure if i understood correctly. When i look at #917. Does it mean that for the time being there is no possibility to do the same described in the example above? Since the above example was specifically targeted to support multiple session for a single user (aka google accounts).

So is my assumption correct, that unless #917 is being done, there is no possbility to use spring session to support multiple session per user?

**Comment by vpavic** [comment]
That is correct, the support for multiple sessions in a single browser instance was removed as a part of this. We also have this documented in the [reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#dropped-support).

Vote on #917 if you're interested in this feature.

**Comment by smorandi** [comment]
OK, thanks for clarifying this, much appreciated.
