### ISSUE TITLE
Improve JdbcSession#setAttribute for updates

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1064]
I propose to add additional check when updating session:

https://github.com/spring-projects/spring-session/blob/751375338c73136b9b758e069539790620e51c5e/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L738-L740

This check can be improved as this:

```
			else if (this.delegate.getAttribute(attributeName) != null) {
                                // attributeValue is not null here since it is checked before
                                // calling attributeValue's equals is important since it can be override by user
                                if(!attributeValue.equals(this.delegate.getAttribute(attributeName))){
				      this.delta.put(attributeName, DeltaValue.UPDATED);
                                 }
			}
```

This improvement may prevent update calls to DB.

**Comment by candrews** [comment]
This change assumed that attribute values are immutable, which is not necessary the case.

For example, what if the value is a StringBuffer. A controller does getAttribute to get the StringBuffer object, calls .append on it, then calls setAttribute to persist it. Currently, this would behave as expected. With this proposed changed, the appended data would be lost, as the object reference has not changed (and the same object reference .equals itself).

**Comment by cemo** [comment]
@candrews Would you give me please an example. I have thought on this a little bid but seems I am missing something.

**Comment by candrews** [comment]
In request 1:
```
request.getSession().setAttribute("test", new StringBuilder("a"));
```

In request 2:
```
StringBuilder sb = (StringBuilder) request.getSession().getAttribute("test");
Assert.isTrue(sb.toString().equals("a"));
sb.append("b");
Assert.isTrue(sb.toString().equals("ab"));
request.getSession().setAttribute("test", sb);
```


In request 3:
```
StringBuilder sb = (StringBuilder) request.getSession().getAttribute("test");
Assert.isTrue(sb.toString().equals("ab"));
```

Currently, if you do 1, then 2, then 3 (in separate requests, so using separate controller methods, for example), all assertions will pass. Using your proposed change, the assertion in request 3 will fail.

**Comment by vpavic** [comment]
For the reasons outlined by @candrews the proposed approach isn't something we can implement in a reliable manner. Therefore I'm closing this as invalid.

**Comment by cemo** [comment]
Given the fact that such bad implementations can exist, this issue can be implemented for common types such as String and Number classes of JDK?

**Comment by cemo** [comment]
@candrews primitives types are ok but I think It would make sense to support `String` as well since it is immutable as well.
