### ISSUE TITLE
Improve `setLastAccessedTime` usage 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#1065]
Many web applications' user sessions are longer than a couple of minutes. Especially for mobile applications it can be longer than of a few days. I propose to call `setLastAccessTime` only if a customizable amount of time passed. For example let's say that session timeout is 30 day. A setLastAccessTime strategy with 1 day means only after one day's request will set session's `lastAccessTime`. In order to prevent breaking changes it can be set 0 for default and it can improve dramatically calling updates. Since most of the times a session does not change.

**Comment by vpavic** [comment]
I'm afraid this isn't something we should be doing, as the [`HttpSession`](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html) contract is explicit about when `lastAccessedTime` should be updated and we shouldn't violate this.
