### ISSUE TITLE
Using JDBC, setting new attribute multiple times results in an UPDATE not an INSERT

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-session#1069]
When using JDBC, setting a new attribute multiple times results in an SQL UPDATE not an INSERT. Because there is no row to update, the session attribute is not actually saved to the table.

For example, in a request handler (a Spring MVC controller, servlet, filter, etc):
```
Assert.isTrue(request.getSession().getAttribute("test")==null);
request.getSession().setAttribute("test", "someValue");
request.getSession().setAttribute("test", "someValue");
```

I would expect a row to be added to the `SPRING_SESSION_ATTRIBUTES` table with the `ATTRIBUTE_NAME` of "test" and the `ATTRIBUTE_VALUE` of "someValue"

However, what actually happens is that an UPDATE statement is executed resulted in no row being added to `SPRING_SESSION_ATTRIBUTES`.

The problem appears to be at https://github.com/spring-projects/spring-session/blob/2.0.3.RELEASE/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L738 - I believe the line should be:
```
else if (this.delta.get(attributeName) != DeltaValue.ADDED && this.delegate.getAttribute(attributeName) != null) {
```

**Comment by candrews** [comment]
Opened a pull request: #1070

**Comment by candrews** [comment]
An alternative solution would be to use an UPSERT for the update SQL instead of an UPDATE... but there's no standard UPSERT support in the SQL standard, so that's probably not a workable approach.

**Comment by vpavic** [comment]
Thanks for the report @candrews! Closing in favor of PR #1070.
