### ISSUE TITLE
SPRING_SESSION_ATTRIBUTES are not removed during logout

### ISSUE THREAD

**Issue by broth-eu** [spring-projects/spring-session#1074]
I'm currently using Spring Session 1.3.2 with its JDBC connector and a MySQL database 5.7.22.

After a successful logout, I would expect that the corresponding SPRING_SESSION row and its SPRING_SESSION_ATTRIBUTES rows have been deleted. For SPRING_SESSION, that's the case, but unfortunately **not** for SPRING_SESSION_ATTRIBUTES. 
Is it a bug or is it the wanted behavior?

**Comment by vpavic** [comment]
Thanks for the report @broth-eu. Can you provide us with details about your Spring Session tables i.e. output of MySQL's `DESC` command?

**Comment by broth-eu** [comment]
Yes, of course. Here is the output for both session tables:

```
mysql> describe cmauth.SPRING_SESSION;
+-----------------------+--------------+------+-----+---------+-------+
| Field                 | Type         | Null | Key | Default | Extra |
+-----------------------+--------------+------+-----+---------+-------+
| SESSION_ID            | varchar(36)  | NO   | PRI | NULL    |       |
| CREATION_TIME         | bigint(20)   | NO   |     | NULL    |       |
| LAST_ACCESS_TIME      | bigint(20)   | NO   | MUL | NULL    |       |
| MAX_INACTIVE_INTERVAL | bigint(20)   | NO   |     | NULL    |       |
| PRINCIPAL_NAME        | varchar(255) | YES  |     | NULL    |       |
+-----------------------+--------------+------+-----+---------+-------+

mysql> describe cmauth.SPRING_SESSION_ATTRIBUTES;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| SESSION_ID      | varchar(36)  | NO   | PRI | NULL    |       |
| ATTRIBUTE_NAME  | varchar(200) | NO   | PRI | NULL    |       |
| ATTRIBUTE_BYTES | blob         | YES  |     | NULL    |       |
+-----------------+--------------+------+-----+---------+-------+
```

**Comment by vpavic** [comment]
Thanks for the feedback - sorry, I forgot that MySQL's `DESC` doesn't output foreign key constraint information. Could you please execute the statement below, or verify by some other means that `SPRING_SESSION_ATTRIBUTES_FK` foreign key constraint is in place:

```
select *
from information_schema.key_column_usage
where referenced_table_name = 'SPRING_SESSION';
```

I suspect you're missing this foreign key constraint, which should include a `ON DELETE CASCADE` clause to ensure child records are deleted together with parent.

**Comment by broth-eu** [comment]
You're right. I simply forgot to add `ON DELETE CASCADE` when specifying the `SPRING_SESSION_ATTRIBUTES_FK`.
Thanks for your quick help. 👍

**Comment by vpavic** [comment]
Thanks for following up.
