### ISSUE TITLE
Is HazelcastSessionRepository thread-safe?

### ISSUE THREAD

**Issue by aritzbastida** [spring-projects/spring-session#1075]
As stated in the Javadoc, MapSession has no synchronization, so it is best to use the copy constructor when working on multiple threads (which is exactly the case in a servlet environment)
https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/MapSession.html

However, I just reviewed `HazelcastSessionRepository` repository implementation based on `MapSession`, and it does not use a copy constructor. As a result, even if a new instance of `HazelcastSession` is created each time in `findById()`, the "delegate" attribute is always the same `MapSession` instance. I just tried out the sample application `spring-session-sample-javaconfig-hazelcast`, with the following result:

thread 1:
`org.springframework.session.hazelcast.HazelcastSessionRepository$HazelcastSession@4078fa51
org.springframework.session.MapSession@33644dc2`

thread 4:
`org.springframework.session.hazelcast.HazelcastSessionRepository$HazelcastSession@2bfef0fa
org.springframework.session.MapSession@33644dc2`

That is, the same `MapSession` is shared in two `HazelcastSession` instances, so the `HashMap` could be corrupted and/or there could be side-effects between threads after calling `setAttribute()` / `removeAttribute()`.

Am I missing something here? Of course, this would not be a problem if `IMap.get()` would return a different instance each time, but that is not what I saw in the test program, and at a minimum it would require careful configuration. This is, by the way, the same behavior I experienced integrating Oracle Coherence backend with Spring Session (`NamedCache.get()` returns the same instance over and over for the same key). Thanks. Any clarification is appreciated.

**Comment by vpavic** [comment]
Thanks for the report @aritzbastida.

> Of course, this would not be a problem if IMap.get() would return a different instance each time, but that is not what I saw in the test program, and at a minimum it would require careful configuration.

Are you sure that is the case? That shouldn't be the case as it would violate [`com.hazelcast.core.IMap#get` contract](http://docs.hazelcast.org/docs/3.8/javadoc/com/hazelcast/core/IMap.html#get-java.lang.Object-) which clearly states that the clone is returned.

**Comment by aritzbastida** [comment]
Sorry, my fault. I was mislead with the output of `Object.toString()` which just prints the hashcode, but not the memory address (or equivalent, whatshoever). After debugging the `MapSession` objects with `System.identityHashCode()`, I found that indeed the contract of `IMap` is not broken.

`System.identityHashCode(this)
	 (int) 759979149
	 (int) 1707553308
	 (int) 1902497201`

...so everything is working fine, and we can just close this issue :)

**Comment by vpavic** [comment]
Thanks for following up @aritzbastida.
