### ISSUE TITLE
JDBC session : session will not timeout if user continuously refresh page

### ISSUE THREAD

**Issue by brianchan661** [spring-projects/spring-session#1085]
I am trying to use JBDC session for my application.  
By setting the MaxInactiveInterval, I expected after a user access the /login page, the session will be invalidated after 30 seconds. 
 
It works well if the user do not refresh the page, while if he continuously refresh the page, the session will never timeout.   

I looked into the [JdbcOperationsSessionRepository](https://github.com/spring-projects/spring-session/blob/1.3.x/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java) (I am using v1.3.1, and is not able to upgrade to v2.0 due to implementation) and I think the reason is the

> UPDATE_SESSION_QUERY  --> update the last access time on every refresh
> DELETE_SESSIONS_BY_LAST_ACCESS_TIME_QUERY  --> delete session based on last access time

Is it possible to:  
1. disable the update LAST_ACCESS_TIME?, or  
2. delete the session based on the CREATION_TIME?
3. or some better idea?

Thanks

```
@RequestMapping(path = "login", method = GET)
    public String login() {
        request.getSession().setMaxInactiveInterval(30);
        ...
        return "login";
    }

    @EnableJdbcHttpSession()  // only setting for jdbc session
    @Configuration
    public class MyConfig extends WebMvcConfigurerAdapter {
        // no setting else related to session
    }

```

**Comment by vpavic** [comment]
Hi @brianchan661 - that's the expected behavior since Spring Session provides implementation of Servlet API's `HttpSession`.

With that in mind, the following expectation is not reasonable:

> By setting the MaxInactiveInterval, I expected after a user access the /login page, the session will be invalidated after 30 seconds.

Please refer to [`HttpSession#getMaxInactiveInterval` javadoc](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpSession.html#getMaxInactiveInterval--), which states the following:

> `int getMaxInactiveInterval()`
>
> Returns the maximum time interval, in seconds, that the servlet container will keep this session open **between client accesses**. After this interval, the servlet container will invalidate the session. The maximum time interval can be set with the `setMaxInactiveInterval` method.
>
> A return value of zero or less indicates that the session will never timeout.

See also #922.

**Comment by brianchan661** [comment]
Thanks @vpavic for your help
I got some ideas on how should I do in #922
