### ISSUE TITLE
Provide Session Id Generation Strategy

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#11]
We are currently using UIDs for session id generation. It may be better to include other characters to increase the entropy. We should be careful in how we use SecureRandom See http://www.cigital.com/justice-league-blog/2009/08/14/proper-use-of-javas-securerandom/ Last, we may want to make generating ids a strategy interface so that users can swap this out
- See PR #204

**Comment by artgramlich** [comment]
+1
Thanks for closing the other issue, somehow I didn't see this issue.

**Comment by artgramlich** [comment]
I submitted a pull request #204.

**Comment by derylspielman** [comment]
This would be very helpful so that we can customize the session ID with a suffix of the jvmRoute. We have legacy code that requires the .jvmRoute at the end and currently calling `httpRequest.getSession().getId()` 
 comes without the jvmRoute. Any progress on this?

**Comment by abhishekjoy1** [comment]
Hi, I am trying to overwrite the session-id generated through framework as follows:


`
       @EnableSpringHttpSession
        public class CustomSessionRepository implements SessionRepository<MapSession> {

            private Integer defaultMaxInactiveInterval;
            private  Map<String, Session> sessions = new ConcurrentHashMap<>();

            public CustomSessionRepository() {
                 this.sessions = sessions;
            }

            public void setDefaultMaxInactiveInterval(int defaultMaxInactiveInterval) {
                 this.defaultMaxInactiveInterval = defaultMaxInactiveInterval;
            }
       
            public void save(MapSession session) {
                if (!session.getId().equals(session.getOriginalId())) {
                    this.sessions.remove(session.getOriginalId());
               }

              this.sessions.put(session.getId(), new MapSession(session));
            }

            public MapSession findById(String id) {
                 Session saved = (Session)this.sessions.get(id);
                 if (saved == null) {
                     return null;
                 } else if (saved.isExpired()) {
                      this.deleteById(saved.getId());
                      return null;
                 } else {
                     return new MapSession(saved);
                 }
            }

            public void deleteById(String id) {
                this.sessions.remove(id);
            }

           public MapSession createSession() {
               MapSession result = new MapSession(myCustomId());
               if (this.defaultMaxInactiveInterval != null) {
                  result.setMaxInactiveInterval(Duration.ofSeconds((long)this.defaultMaxInactiveInterval));
             }

           return result;
         }
       }

`

**Comment by PvanHengel** [comment]
Hi where do we stand on this enhancement, our security team feels that the session ids being generated are not random enough (eg long enough), and would like a way to modify it.  Does anyone know if there is an alternative and/or how we can get this PR updated and merged in?

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-session/pull/2286
