### ISSUE TITLE
Spring Session 2.0.1.RELEASE not available in mvn repository

### ISSUE THREAD

**Issue by nani2ratna** [spring-projects/spring-session#1104]
Hi,

I see spring-session 2.X versions already released but are not available in mvn repository.
https://docs.spring.io/spring-session/docs/2.0.5.BUILD-SNAPSHOT/reference/html5/

Please check this link - https://mvnrepository.com/artifact/org.springframework.session/spring-session only has up until 1.3.3.RELEASE. All the sub-modules like spring-session-jdbc / spring-session-context, spring-session-core has 2.X versions available in mvn repository.

Please make them available in mvn repository. I also builds are available in travis. https://travis-ci.org/spring-projects/spring-session/branches

**Comment by vpavic** [comment]
Hi @nani2ratna. Note that the project underwent some structural changes in 2.0 which had impact on published modules. The `org.springframework.session:spring-session` artifact doesn't exist anymore, while we now have `org.springframework.session:spring-session-core`. These changes are documented in [the reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#modules) and have been mentioned in the [`2.0.0.RELEASE` announcement](https://spring.io/blog/2018/01/16/spring-session-2-0-0-released) as well.

As a side note, you generally shouldn't directly depend on `org.springframework.session:spring-session-core` (unless you're providing your own `SessionRepository` implementation) but rather to one of the modules that are specific to session store implementation.
