### ISSUE TITLE
No qualifying bean of type 'org.springframework.session.FindByIndexNameSessionRepository<org.springframework.session.Session>' available

### ISSUE THREAD

**Issue by Jafee** [spring-projects/spring-session#1112]
FindByIndexNameSessionRepository's sessionRepository injection error.
This is config file.

    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.context.annotation.Bean;
    import org.springframework.http.HttpMethod;
    import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
    import org.springframework.security.config.annotation.web.builders.HttpSecurity;
    import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
    import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
    import org.springframework.security.core.userdetails.User;
    import org.springframework.security.web.authentication.RememberMeServices;
    import org.springframework.session.FindByIndexNameSessionRepository;
    import org.springframework.session.Session;
    import org.springframework.session.security.SpringSessionBackedSessionRegistry;
    import org.springframework.session.security.web.authentication.SpringSessionRememberMeServices;
    
    @EnableWebSecurity
    public class SecurityConfig extends WebSecurityConfigurerAdapter {
    
        @Autowired
        private FindByIndexNameSessionRepository<Session> sessionRepository;
    
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http
                    .sessionManagement()
                    .maximumSessions(1)
                    .sessionRegistry(sessionRegistry());
    
            http
                    .authorizeRequests()
                    .antMatchers(HttpMethod.GET, "/", "/login").permitAll()
                    .anyRequest().authenticated()
    
                    .and()
                        .formLogin()
                        .loginPage("/login")
                        .defaultSuccessUrl("/")
    
                    .and()
                        .rememberMe()
                        .rememberMeServices(rememberMeServices())
    
                    .and()
                        .logout()
                        .logoutUrl("/logout")
                        .logoutSuccessUrl("/")
    
                    .and()
                        .csrf()
                        .disable();
        }
    
    
        @Override
        protected void configure(AuthenticationManagerBuilder auth) throws Exception {
            auth.inMemoryAuthentication().withUser(User.withUsername("user")
                    .password("{noop}password").roles("USER").build());
    
        }
    
        @Bean
        RememberMeServices rememberMeServices() {
            SpringSessionRememberMeServices rememberMeServices = new SpringSessionRememberMeServices();
            return rememberMeServices;
        }
    
        @Bean
        SpringSessionBackedSessionRegistry sessionRegistry() {
            return new SpringSessionBackedSessionRegistry<>(this.sessionRepository);
        }
    }

This is pom.xml file.

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.3.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

**Comment by vpavic** [comment]
Hi @Jafee, you should use `FindByIndexNameSessionRepository<? extends Session>`. For example:

```java
@Autowired
FindByIndexNameSessionRepository<? extends Session> sessionRepository;
```

Does this work for you?

Also note that it's a good idea to search existing issues first - see #694.

**Comment by Jafee** [comment]
@vpavic Thanks for your help, but it's not work.

        @Autowired
        FindByIndexNameSessionRepository<? extends Session> sessionRepository;

This code could not autowire either.

I uploaded the [project](https://github.com/Jafee/demo) to github for easy viewing.

**Comment by vpavic** [comment]
Thanks for providing the sample app @Jafee, we really appreciate that.

The problem is that you're missing `spring-boot-starter-data-redis` dependency (and more importantly the Redis driver the starter pulls in) so Spring Session doesn't actually get auto-configured at all. After addressing that as in Jafee/demo#1 the sample app starts as expected.

**Comment by Jafee** [comment]
Great, the solution is very fast and the explanation is very clear. Thanks very much @vpavic .

In addition, your avatar(small avatar) looks like Michael Fassbender, cool!
