### ISSUE TITLE
spring 2.x spring-session redis is wrong config

### ISSUE THREAD

**Issue by hxiugangxh** [spring-projects/spring-session#1115]
Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.autoconfigure.session.RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.setCleanupCron(Ljava/lang/String;)V

**Comment by ThomasBem** [comment]
@hxiugangxh I see you closed the issue. Did you find a fix for it? We are having the same issue in a project I am working on.

**Comment by jianqing1990** [comment]
I see you closed the issue. Did you find a fix for it? We are having the same issue in a project I am working on.

**Comment by jianqing1990** [comment]
> I see you closed the issue. Did you find a fix for it? We are having the same issue in a project I am working on.

I modified pom.xml to change <artifactId>spring-session</artifactId> to <artifactId>spring-session-data-redis</artifactId>

**Comment by jianqing1990** [comment]
> @hxiugangxh I see you closed the issue. Did you find a fix for it? We are having the same issue in a project I am working on.

I modified pom.xml to change <artifactId>spring-session</artifactId> to <artifactId>spring-session-data-redis</artifactId>

**Comment by jiaxiaogang** [comment]
spring-session后来换名字了,不过如果你更新了springboot2.x,建议你替换spring-session-data-redis试下,版本的话,可以到https://mvnrepository.com/查下版本发布时间,只要和你的springboot发布时间接近的,一般是兼容的;
