### ISSUE TITLE
Add error logging to the DefaultCookieSerializer#base64Decode

### ISSUE THREAD

**Issue by x-x-z** [spring-projects/spring-session#1117]
The org.springframework.session.web.http.DefaultCookieSerializer#base64Decode method is used to decode session cookies. If the cookie is of an incorrect format, then the method returns **null** and does not log an error.
I think it's necessary to add error logging for this method (debug level). 

I spent several hours debugging code to understand why there is no session. Later I found out that the session has a decoded value and this method simply returned a null, because it could not convert the decoded value twice.
Logging could help to quickly detect an error.

Another solution is to return the original value back. This will help to use the sessions that come in any format. If there is no such session, it will simply not be found at another level.

**Comment by vpavic** [comment]
Thanks for the suggestion @x-x-z!
