### ISSUE TITLE
cleanup task run every minute

### ISSUE THREAD

**Issue by 18703876065** [spring-projects/spring-session#1119]
@Override
	public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
		taskRegistrar.addCronTask(() -> sessionRepository().cleanupExpiredSessions(),
				this.cleanupCron);
	}

### This task  run every minute,  we use one redis cluster ,if my userService deploy many server node, this task will be run many time  in same time ,  I think this design is not friendly，what about you?

**Comment by 18703876065** [comment]
According to your needs
This task can be switched off

**Comment by candrews** [comment]
This setting is configured on `@EnableRedisHttpSession` see https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/data/redis/config/annotation/web/http/EnableRedisHttpSession.html#cleanupCron--

The reason for this schedule task is to be able to notify any listeners you may have registered of session expiration events. If you don't have such listeners, then you can set the cron expression to be much higher (10 years or something) and that will solve your problem.

**Comment by vpavic** [comment]
Thanks for helping out on this @candrews.

@18703876065, as per suggestion from @candrews, you can use `EnableRedisHttpSession#cleanupCron` to set the cleanup job to run at different schedule on all nodes. If you're using Spring Boot to auto-configure Spring Session, you can use `spring.session.redis.cleanup-cron` application property.

Does this address your question?

**Comment by rwinch** [comment]
@saiya Thanks for the feedback. I think a formal way of disabling the cleanup task would be beneficial. Can you please create a ticket with the details you provided here? Are you able to submit a pull request? I think the first step is making it so that Spring Session supports the feature and then we will want to ensure that it is easy to enable in Spring Boot (that might not be an additional step)

**Comment by saiya** [comment]
@rwinch Thank you for response! 
I filed a issue #1159, and I will try to make a pull request in a way as described in the issue.
If you have a comment, please tell me.

**Comment by vpavic** [comment]
Thanks @saiya, for opening #1159. I'm going to close this one in favor of newly created issue.
