### ISSUE TITLE
CookieHttpSessionStrategy should provide a possibility to further define the cookie

### ISSUE THREAD

**Issue by tux4ever** [spring-projects/spring-session#112]
At the moment it is only possible to configure the name of the cookie, but not further properties. e.g. context path. It would be great if the CookieHttpSessionStrategy.createSessionCookie is refactored to a new bean which could be replaced or the CookieHttpSessionStrategy should not be final.

Relates to #106

**Comment by domdorn** [comment]
#155 is more or less a specific version of this... maybe it might be better to just make createSessionCookie protected and allow users to override it in a subclass?

**Comment by tsachev** [comment]
:+1:. Either create `createSessionCookie` protected and `CookieHttpSessionStrategy` non final or allow customization of the cookie with something like CookieCustoizer.
Please advice which approach you think is better and maybe I could provide  a pull request for this feature.

**Comment by tsachev** [comment]
#243 is also related. This seems to be common request.

**Comment by praptin** [comment]
+1 I hope in the next release it will provide more customization like to set domain. For my own need I create my own implementation.

**Comment by zxkane** [comment]
+1 I hope we can specify the `domain` to share it among all subdomains.

**Comment by rwinch** [comment]
Thanks for the great request! I'm trying to aggregate all the feature requests for cookies, so we can solve this problem more holistically. Therefore, I'm closing this in favor of #299 which takes this feature into account.

**Comment by rwinch** [comment]
This is now resolved via #299 See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html for details.

**Comment by praptin** [comment]
Thanks Rob, when will the release version will be released?

**Comment by rwinch** [comment]
@praptin We plan to release a milestone next week and go GA Q1 of next year.
