### ISSUE TITLE
Delete all of users sessions: Not really deleted in redis

### ISSUE THREAD

**Issue by tbrannt** [spring-projects/spring-session#1136]
I'm using Spring Boot 2.0.3 with Spring Session Redis without Spring Security.  When the user logs in I set the sessions principal index attribute:

```
session.setAttribute(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, String.valueOf(userId));
```
my session timeout value is 60 days:
```
server.servlet.session.timeout=5184000
```

I now log in 2 times with one user. I can see the following entries in redis:

```
1) "spring;session:sessions:b3766187-c205-4815-b015-51eadbc5cd7c"
2) "spring;session:sessions:expires:b3766187-c205-4815-b015-51eadbc5cd7c"
3) "spring;session:sessions:3c12f29e-ed9e-4d97-a1a0-3ff00c7dfdad"
4) "spring;session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:16"
5) "spring;session:expirations:1537873020000"
6) "spring;session:sessions:expires:3c12f29e-ed9e-4d97-a1a0-3ff00c7dfdad"
```

What I'm trying to accomplish now is deleting all of the users sessions when he logs out.
I do it like this:

```
Map<String, ? extends Session> usersSessions = findByIndexNameSessionRepository.findByIndexNameAndIndexValue(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, String.valueOf(currentUserId));

usersSessions.values().forEach(s -> {
    findByIndexNameSessionRepository.deleteById(s.getId());
    logger.info("deleted session {}", s.getId());
});
```

After doing that it in the two browser windows it correctly appears as if both users sessions have been deleted. But actually it is not the case. This is how my redis looks:

```
1) "spring;session:sessions:b3766187-c205-4815-b015-51eadbc5cd7c"
2) "spring;session:sessions:expires:b3766187-c205-4815-b015-51eadbc5cd7c"
3) "spring;session:sessions:3c12f29e-ed9e-4d97-a1a0-3ff00c7dfdad"
4) "spring;session:expirations:1537873620000"
5) "spring;session:expirations:1532689620000"
```

Only one of both sessions have been deleted. `3c12f29e-ed9e-4d97-a1a0-3ff00c7dfdad` still has it's original ttl of >5184k. While debugging I found out that actually when setting a breakpoint after the last #deleteById call redis is in a correct state and only holds
```
1) "spring;session:sessions:b3766187-c205-4815-b015-51eadbc5cd7c"
2) "spring;session:sessions:3c12f29e-ed9e-4d97-a1a0-3ff00c7dfdad"
3) "spring;session:expirations:1537873620000"
4) "spring;session:expirations:1532689620000"
```
with the TTLs set to 5 minutes as expected.
But after I leave the method I reach the wrong redis state described above. I guess it has something to do with my RedisFlushMode setting of `ON_SAVE`, so after I leave the method some wrong state is written.

**Comment by vpavic** [comment]
If I understood your use case @tbrannt, you're using `SessionRepository#deleteById` to delete all sessions for current user, including the session that's bound to the current request. Since that session wasn't invalidated, it will get persisted again when the response is committed, however it won't contain all the attributes that were previously stored in session, but rather only the changed one (due to only delta being persisted). That's why you're logged out (i.e. principal attribute isn't present any more), but the session itself is still present is store.

So you should really be using `HttpSession#invalidate` on the current request. On a side note, why aren't you using Spring Security to handle these concerns for you?

**Comment by tbrannt** [comment]
I did that. I also invalidated the session for the current request separately like so: 

```
sessions.forEach(s -> {
    findByIndexNameSessionRepository.deleteById(s.getId());
   logger.info("deleted session {}", s.getId());
});

currentSession.invalidate();
```

That also resulted in weird redis states. 
I now solved this.. the missing piece was to additionally set maxInactiveInterval to zero like so: 

```
sessions.forEach(s -> {
    findByIndexNameSessionRepository.deleteById(s.getId());
    logger.info("deleted session {}", s.getId());
});

currentSession.invalidate();
currentSession.setMaxInactiveInterval(0);
```
which seems rather "quirky" to me.

_side note_: What I like so much about spring boot is that it offers many extensions but none of them are really mandatory. So you can pick which you want to use and which you do not want to use. After using spring security in some projects I decided to not use it in my current project. There are cases where you like to know/control exactly what's going on. In these cases doing it yourself makes sometimes more sense than customizing what's given.

**Comment by vpavic** [comment]
Thanks for following up @tbrannt, glad to hear you had this resolved.
