### ISSUE TITLE
Document that @EnableRedisHttpSession requires Redis 2.8.0+

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#115]
* We should document that `@EnableRedisHttpSession` requires Redis 2.8.0+ and why
* We should document if not using WebSockets and need earlier version of Redis can work around (see comment on #113)

Related #113

**Comment by ghillert** [comment]
Please document that `embedded-redis` which is used by the samples, uses an old Redis version. See also:

* `embedded-redis` GitHub issue: https://github.com/kstyrc/embedded-redis/issues/23
* `spring-session` GitHub issue: https://github.com/spring-projects/spring-session/issues/113
