### ISSUE TITLE
Make RedisOperationsSessionRepository.RedisSession public

### ISSUE THREAD

**Issue by vijayaggarwal** [spring-projects/spring-session#1154]
I use spring-session in a non-HTTP setup. I grab an instance of `RedisOperationsSessionRepository` and use it to create and save sessions. However, `RedisOperationsSessionRepository` creates sessions to type `RedisSession`, which is non-Public. This severely limits my ability to work with `RedisSession`s.

```java
@Autowired
RedisOperationsSessionRepository sessionRepo;

Session session = sessionRepo.createSession();
session.setAttribute("key", "value");
sessionRepo.save(session); // Compiler error: save() expects argument of type RedisSession

RedisSession redisSession = (RedisSession) session; // Compiler error: RedisSession is not visible here
sessionRepo.save(session);
```

PS: I found #114 and #725 to be somewhat related to this one, so mentioning them here.

**Comment by vpavic** [comment]
@vijayaggarwal You should code against Spring Session's public APIs, rather than implementation. Here's an example from [find by username sample app guide](https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-findbyusername.html#finding-sessions-for-a-specific-user):

```java
@Autowired
FindByIndexNameSessionRepository<? extends Session> sessions;

@RequestMapping("/")
public String index(Principal principal, Model model) {
    Collection<? extends Session> usersSessions = this.sessions
            .findByIndexNameAndIndexValue(
                    FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME,
                    principal.getName())
            .values();
    model.addAttribute("sessions", usersSessions);
    return "index";
}
```

See also #744, #849.

Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.

**Comment by vijayaggarwal** [comment]
Thanks for the reply @vpavic! Your example works as you are not calling `SessionRepository#save` (I guess servlet container calls that method in your case). However, since I am not using a servlet container, I need to call `save` myself. Reproducing my code sample:

```
@Autowired
SessionRepository<? extends Session> sessionRepo;

Session session = sessionRepo.createSession();
session.setAttribute("key", "value");
sessionRepo.save(session); **// Compiler error**
```

I can use raw type (i.e. `SessionRepository` instead of `SessionRepository<? extends Session>`), but that would be far from ideal.

**Comment by vijayaggarwal** [comment]
@vpavic Also, I cannot re-open this issue. Please consider re-opening it or suggest some other way forward. Thanks a lot!

**Comment by vpavic** [comment]
Sorry for confusion @vijayaggarwal, I've pasted the wrong example in my answer (though I've linked an issue that contained it) - I've updated the previous comment to address that.

**Comment by vijayaggarwal** [comment]
Thanks @vpavic! I will definitely prefer `ParameterizedConsumer` as it provides better type safety. However, to create an instance of `ParameterizedConsumer`, I need to specify a concrete type for its wildcard type parameter `<? extends Session>`.

If I try to create an instance of `ParameterizedConsumer<Session>`, autowiring of `FindByIndexNameSessionRepository` inside `ParameterizedConsumer` fails. I guess that's because the bean I am configuring is of type `RedisOperationsSessionRepository` which implements `FindByIndexNameSessionRepository<RedisOperationsSessionRepository.RedisSession>`, which is not compatible with `FindByIndexNameSessionRepository<Session>`, even if `RedisSession` implements `Session`, as generic types in Java are invariant.

So, I can't use your parameterized type approach as I can't create an instance of `ParameterizedConsumer` that successfully autowires my `RedisOperationsSessionRepository`. I can use the raw type approach, but I would not want to use it as it bypasses all type checking.

Also, if `RedisOperationsSessionRepository` is a `public` class, I think `RedisSession` should also be `public`, especially given that multiple methods of `RedisOperationsSessionRepository` accept/return `RedisSession` thereby "leaking" `RedisSession` in public API.

**Comment by vpavic** [comment]
> However, to create an instance of `ParameterizedConsumer`, I need to specify a concrete type for its wildcard type parameter `<? extends Session>`.

That shouldn't be the case. We have quite a few `SessionRepository` consumers in our own codebase that use this pattern, e.g. `SessionRepositoryFilter`, `SessionRepositoryMessageInterceptor`, `SpringSessionBackedSessionRegistry`, `SpringSessionBackedSessionInformation`.

**Comment by vijayaggarwal** [comment]
> That shouldn't be the case.

AKAIK, that's how Java works.

I looked through `spring-session` codebase as well. The classes you mentioned are themselves parameterized (e.g., `SessionRepositoryFilter<S extends Session>`, `SessionRepositoryMessageInterceptor<S extends Session>`) so the responsibility of specifying the concrete type is passed downstream. In a few places, I found the use of raw types with unchecked casts to bypass type checks, e.g., https://github.com/spring-projects/spring-session/blob/003996a1b3e9c720b8b54236362bbb5d070693cd/spring-session-core/src/main/java/org/springframework/session/web/socket/config/annotation/AbstractSessionWebSocketMessageBrokerConfigurer.java#L81-L82 and https://github.com/spring-projects/spring-session/blob/003996a1b3e9c720b8b54236362bbb5d070693cd/spring-session-core/src/main/java/org/springframework/session/web/socket/config/annotation/AbstractSessionWebSocketMessageBrokerConfigurer.java#L127-L130

Suppressing type checks works but isn't desirable. There should be a better way.

**Comment by vpavic** [comment]
> The classes you mentioned are themselves parameterized (e.g., `SessionRepositoryFilter<S extends Session>`, `SessionRepositoryMessageInterceptor<S extends Session>`) so the responsibility of specifying the concrete type is passed downstream.

Exactly, that's the point, hence the `ParameterizedConsumer` example. What's exactly preventing you to register `ParameterizedConsumer` as a bean and have it inject the `SessionRepository`? We do the same ourselves, for example in `SpringHttpSessionConfiguration`:

https://github.com/spring-projects/spring-session/blob/7fdf2876b26679e9bfc0f5bf7534d245feb47d2b/spring-session-core/src/main/java/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.java#L123-L131

**Comment by vijayaggarwal** [comment]
Ah, got it now! Registering as bean does the trick. If `ParameterizedConsumer` is a bean, I don't need to create it myself (as Spring creates it for me), and hence I don't need to provide a concrete type for its type parameter.

```java
@Component
class MyController<S extends Session> {
    @Autowired
    SessionRepository<S> sessionRepo;

    public void myMethod() {
        S session = sessionRepo.createSession();
        session.setAttribute("key", "value");
        sessionRepo.save(session);
    }
}
```

I never specified what `S` is. I don't even need to. With this, I could also code against the generic `SessionRepository` class instead of coding against a particular implementation.

Closing the issue. Thanks a lot for help @vpavic!

**Comment by vijayaggarwal** [comment]
Btw, somewhat in relation to #114 also, if you think it helps to add a sample project on custom SessionRepository, I can submit a PR.

**Comment by vpavic** [comment]
Thanks for following up @vijayaggarwal, glad to hear you had this resolved.

> Btw, somewhat in relation to #114 also, if you think it helps to add a sample project on custom SessionRepository, I can submit a PR.

Regarding this, please drop a note on #114 itself, since that issue is still open. Thanks!
