### ISSUE TITLE
Documentation on remember-me support misses out on CookieSerializer bean configuration

### ISSUE THREAD

**Issue by jbollacke** [spring-projects/spring-session#1157]
The documentation on [remember-me support](https://docs.spring.io/spring-session/docs/current/reference/html/spring-security.html#spring-security-rememberme) fails to display the required configuration of the CookieSerializer bean.

For remember-me to work one has to configure a DefaultCookieSerializer like this (note that code is in kotlin):

````kotlin
@Bean
fun cookieSerializer() = DefaultCookieSerializer().apply {
  setRememberMeRequestAttribute(SpringSessionRememberMeServices.REMEMBER_ME_LOGIN_ATTR)
}
````

Otherwise the cookies lifetime is undefined and therefore will be removed when the browser is closed.

**Comment by jbollacke** [comment]
Remember-me support was introduced in #667.

**Comment by sctianwei** [comment]
this can be solved by 
@Bean
public SpringSessionRememberMeServices springSessionRememberMeServices() {
    SpringSessionRememberMeServices rememberMeServices = new SpringSessionRememberMeServices();
    return rememberMeServices;
}

instead of 

@Bean
RememberMeServices rememberMeServices() {
    SpringSessionRememberMeServices rememberMeServices = new SpringSessionRememberMeServices();
    return rememberMeServices;
}

**Comment by jbollacke** [comment]
@sctianwei I have not tested it but according to https://github.com/spring-projects/spring-session/blob/3d2a742328128945376bd13d947ff7f6db32346f/spring-session-core/src/main/java/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.java#L192 I think your right.

Anyway that is missing in the documentation then.
