### ISSUE TITLE
Provide a way to disable cleanup cron

### ISSUE THREAD

**Issue by saiya** [spring-projects/spring-session#1159]
Hi, I want a way to disable cleanup cron in Spring Session Data Redis (as described in previous conversation: https://github.com/spring-projects/spring-session/issues/1119#issuecomment-413450799 ).

Here is a issue that describes about the matter.

# TL;DR

- Sometime user want to disable cleanup cron of Spring Session Data Redis and Spring Session JDBC
- There was a known workaround to set `cleanup-cron=0 0 5 31 2` (February 31st, never comes), but it does not work with recent version of spring-context
- It is difficult to override `RedisHttpSessionConfiguration` and `JdbcHttpSessionConfiguration` to prevent cleanup cron.
- What I want is a way to disable cleanup cron. And also enable to use property placeholder in `cleanupCron` attribute.

# Motivation

I want to disable cleanup cron because ...

- use case 1) When I have many web servers, I want to enable cleanup-cron on only one server and want to disable cleanup-cron on other servers to reduce DataStore load and connection pool usage.
- use case 2) When SessionDeletedEvent and SessionExpiredEvent seem not to be needed (also no need to close WebSocket connections associated with the session), I want to disable cleanup-cron entirely.

# Limitation of current implementation 

As shown in example code of https://github.com/spring-projects/spring-session/issues/1119#issuecomment-413450799, current `RedisHttpSessionConfiguration` and `JdbcHttpSessionConfiguration` does not formal way to disable cleanup cron.

My understanding is that above example code is a only way currently and such way is poor in maintainability.

# What I want

My proposal is to add following attributes to disable cleanup cron:

- Add `boolean enableCleanupCron = true` optional attribute into `@EnableRedisHttpSession` and `@EnableJdbcHttpSession`
  - Default value is `true`, it is same with existing behavior
  - When it is `false`, `RedisHttpSessionConfiguration` and `JdbcHttpSessionConfiguration` will not register CronTask
- Enable to use property placeholder in `disableCleanupCron` and `cleanupCron` attributes
  - As described in use case A, sometimes user want to vary cleanup cron setting by environment.
  - Use `StringValueResolver` to resolve placeholders seems to be a way to resolve placeholders (current implementation uses it on `redisNamespace` attribute but not on `cleanupCron`).
  - Current `cleanupCron` attribute seems to accept only cron form (e.g. `0 0 5 31 2`). Thus introducing StringValueResolver is not breaking change in my understanding.

**Comment by saiya** [comment]
I will try to make a pull request in a way as described above.
If someone have a opinion, please tell me.

**Comment by vpavic** [comment]
Rather than adding a new annotation attribute, we could look into direction of introducing a special value for current `cleanupCron` attribute that would disable it. Another benefit of that approach is that there is no additional work on Spring Boot to support new attribute via configuration property.

**Comment by vpavic** [comment]
Closing in favor of PR #1160.
