### ISSUE TITLE
Support Custom Serialization for JDBC

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#1166]
It would be nice to support custom serialization mechanisms for Spring Session JDBC. This would allow better performance and also working around scenarios where session attributes are not serializable.

Related #685 https://github.com/spring-projects/spring-security/issues/5378

**Comment by vpavic** [comment]
We actually already support this via `JdbcHttpSessionConfiguration#setConversionService` - the supplied `ConversionService` is responsible for serializing attributes (by default we use `SerializingConverter` and `DeserializingConverter` - see `JdbcHttpSessionConfiguration#createConversionServiceWithBeanClassLoader`).
