### ISSUE TITLE
Upgrade Reactor to Bismuth-SR11

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1180]

**Comment by gregturn** [comment]
@vpavic is there no better way to sync these 3rd party dependencies between Spring Session and Spring Session MongoDB than manually bumping up the versions in my Maven build file.

**Comment by vpavic** [comment]
Sorry for the late reply @gregturn, comments on closed issues tend to get lost. :)

Are you referring only Spring Session MongoDB side of things? From Spring Session core side, we'd like to have a trace for upgrades of dependencies that are published in our POMs.
