### ISSUE TITLE
when multi-threads call setAttribute and getAttribute method of RedisSession whether there is a race condition?

### ISSUE THREAD

**Issue by lixyou** [spring-projects/spring-session#1184]
Using MapSession in RedisSession, but the attribute in MapSession is HashMap. When multi-threads call setAttribute and getAttribute method of RedisSession whether there is a race condition?

The code fragment is as follows:

```
final class RedisSession implements ExpiringSession {
		private final MapSession cached;
		private Long originalLastAccessTime;
		private Map<String, Object> delta = new HashMap<String, Object>();
		private boolean isNew;
		private String originalPrincipalName;
```

```
public final class MapSession implements ExpiringSession, Serializable {
	/**
	 * Default {@link #setMaxInactiveIntervalInSeconds(int)} (30 minutes).
	 */
	public static final int DEFAULT_MAX_INACTIVE_INTERVAL_SECONDS = 1800;

	private String id;
	private Map<String, Object> sessionAttrs = new HashMap<String, Object>();
	private long creationTime = System.currentTimeMillis();
	private long lastAccessedTime = this.creationTime;
```

**Comment by rwinch** [comment]
Are you experiencing any problems?

`MapSessionRepository` creates a copy of `MapSession` when it is looked up so multiple threads will be operating on different instances.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
