### ISSUE TITLE
Enabling spring session breaks session management from Spring Security

### ISSUE THREAD

**Issue by jonathannaguin** [spring-projects/spring-session#1200]
Hello,

When integrating Spring Session with Spring Security, it seems we are breaking the session management functionalities provided by Spring Security. 

Specifically, Detecting Timeouts, https://docs.spring.io/spring-security/site/docs/current/reference/html/ns-config.html#ns-session-mgmt, as soon as we enable Sprint Session `invalid-session-url` stops working.

I have put together a sample web app that can be used to demonstrate the expected behaviour and the issue we are facing. The app is located in https://github.com/jonathannaguin/spring-session-bug.

Is this something already known as an issue?

Thanks,
Jonathan

**Comment by vpavic** [comment]
Hi @jonathannaguin.

Looking at your `SecurityConfig`, namely [this part](https://github.com/jonathannaguin/spring-session-bug/blob/41739118e3cadb24c596bfb4f433e57044c679ef/src/main/java/sample/config/SecurityConfig.java#L62):

```java
http.sessionManagement().invalidSessionUrl("/expired");
```

It appears that you're using Spring Security's default `SessionRegistry` implementation which isn't aware of Spring Session. You should use `SpringSessionBackedSessionRegistry` that we provide. See [_Spring Security Concurrent Session Control_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#spring-security-concurrent-sessions) of our reference manual for more details.

Does that help?

**Comment by jonathannaguin** [comment]
Thanks for your reply, I didn’t notice that piece of the documentation. I will give it a go and update this thread with the result.

**Comment by jonathannaguin** [comment]
@vpavic I tried adding `SpringSessionBackedSessionRegistry` but that didn't seem to help either. I can see the bean being taken by Spring but any of its methods are being actually called ever (I've added some breakpoints on `getAllSessions` and `getSessionInformation`. 
If it helps, I updated my GitHub sample project with this.

**Comment by vpavic** [comment]
Sorry for the delay @jonathannaguin. I've taken a look at your sample, however you still haven't configured thing right - your Spring Security session management configuration doesn't wire in the configured `sessionRegistry` bean:

https://github.com/jonathannaguin/spring-session-bug/blob/c6a76890e30842545b32e9d9e000284def97a3f4/src/main/java/sample/config/SecurityConfig.java#L68

Please take a closer look at sample from reference manual link in my previous comment.

**Comment by jonathannaguin** [comment]
Right! Let me try that than! Thanks

**Comment by jonathannaguin** [comment]
Hello @vpavic , I just tried that and unfortunately I got the same issue. Actually, as soon as I add `sessionRegistry()` I won't see the `/expired` redirect happening anymore even if I set `spring.session.store-type` to none.

**Comment by jonathannaguin** [comment]
@rwinch I have a sample project here: https://github.com/jonathannaguin/spring-session-bug.

**Comment by rwinch** [comment]
@jonathannaguin This is a duplicate of #1229 and was fixed in spring-session-core-2.1.1.RELEASE Please update to Spring Boot 2.1.1.RELEASE and that will resolve the issue.

**Comment by vpavic** [comment]
Thanks for updating the sample @jonathannaguin, and helping out @rwinch.

Also note that besides `2.1.1.RELEASE`, the `2.0.8.RELEASE` also contains the fix for this (see #1236).
