### ISSUE TITLE
Why does Spring Session use spring:session:expirations?

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-session#1215]
I have gone through the reply for this at url:
https://github.com/spring-projects/spring-session/issues/92
It makes lot of points clear but still everything abount the task
is not cleared? From where that task is comming. How that
task access expired keys so thet redis delete expired keys
in determinstic way. How spring:session:expirations is used
in whole process or how that task uses it. Please elaborate
on that task. As of now that task seems Magic.

**Comment by vpavic** [comment]
Thanks for opening a new issue @ankurpathak - this is much better way to handle it than the comment on closed one.

For now, I'll just c&p my comment from #92:

@ankurpathak The [`RedisOperationsSessionRepository` section](https://docs.spring.io/spring-session/docs/2.0.6.RELEASE/reference/html5/#api-redisoperationssessionrepository) of reference manual, as well as class javadoc on `RedisOperationsSessionRepository`, should provide all the required info - did you read those?

Also see `RedisHttpSessionConfiguration#configureTasks`:

https://github.com/spring-projects/spring-session/blob/3e9f6a35c477b3fb6381df95e6445d61f77391f1/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java#L246-L250

**Comment by ankurpathak** [comment]
@vpavic 
The points I got after reading are:
1. We create a cron task in RedisHttpSessionConfiguration that access expired keys once they expire using time stamps suffixes in spring:session:expirations * keys.
2. One we access them, since those keys having expired ttl redis delete them automatically.
Am I correct? If not please correct me with your additions.

**Comment by vpavic** [comment]
Yes @ankurpathak, that should be correct. With this, I'm closing this as answered.
