### ISSUE TITLE
Make JdbcOperationsSessionRepository and JdbcSession extendable

### ISSUE THREAD

**Issue by longwa** [spring-projects/spring-session#1217]
The `JdbcOperationsSessionRepository` seems to go out of it's way to not be extendable in any way. Specifically, the `JdbcSession` is final and cannot be overriden. We have some use cases to override the existing session repository to change the behavior slightly as well as overriding the `JdbcSession` to allow similar customization.

https://github.com/spring-projects/spring-session/blob/4c5f22900d2bdb9ba4b07f5259eea310428a9c21/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L663

It would be nice if we could re-use more of what's there without writing a completely custom repository.

**Comment by rwinch** [comment]
What use cases do you need to override it? Can you use composition vs inheritance?

**Comment by longwa** [comment]
It really comes down to how much code would need to be written to support our use case. What I'd like to do is override the the `JdbcSession` to omit a few attributes from being added to the delta (and thus serialized to the db). Specifically, this is a Grails application and I need to prevent the `flash` from being serialized in our case. If `JdbcSession` wasn't final, I could extend it and override the `setAttribute` method to do what I want. Then I can (already) override `JdbcOperationsSessionRepository.createSession()` to return my new session.

So honestly in this case, just not having the `JdbcSession` be final would be enough but perhaps this is a weird use case.

I could, of course, just create my own custom JdbcOperationsSessionRepository with my own session, etc. but I was trying to minimize the amount of code that I had to butcher.

**Comment by rwinch** [comment]
First...How would it work if you prevent flash from being serialized? If that happens, flash attributes will no longer work.

**Comment by longwa** [comment]
In our case, we can store the flash in just a MapSession instead of writing it out. It still works fine assuming in the clustered case you use come kind of sticky sessions. The flash is, by definition, transient anyway so at worst you risk losing one request worth of data in the case of a server failure in the cluster.

If you only have one server, storing the flash outside of JDBC session can definitely help to avoid extra writes to the database for just a single request/response cycle worth of data.

**Comment by rwinch** [comment]
To solve this you can create an implementation of SessionRepository that delegates to another implementation of SessionRepository. The implementation would then decorate the result of the delegate result to persist certain attributes differently and avoid adding them to the delegate.

This is preferable to exposing the internals of how the SessionRepository is implemented because we may want to change that later.

I'm closing this as answered, but if you still have issues please feel free to reopen.
