### ISSUE TITLE
Not reading Spring Security config to ignore static files

### ISSUE THREAD

**Issue by naivefun** [spring-projects/spring-session#122]
Seems if in spring security I have configured 

```
web.ignoring().antMatchers("/", "/static/**");
```

Spring session is still processing these URLs and reading/writing to redis server. 
1. it may bring unnecessary work loads to redis server
2. it may affect the accuracy of expiration timestamp

**Comment by rwinch** [comment]
How are you adding the Spring Session Filter? Can you provide your Spring Session / Spring Security configuration? Do you have a springSessionRepositoryFilter mapping in your web.xml or are you using `AbstractHttpSessionApplicationInitializer`?

**Comment by baspet** [comment]
hi,
i have the some problems
```
	protected void configure(HttpSecurity http) throws Exception {
		http
			.requestMatchers().antMatchers(
				"/", 
				"/login", "/logout",
				"/oauth/authorize", "/oauth/confirm_access")
			.and()
				.formLogin()
					.loginPage("/login")
					.permitAll()
			.and()
				.logout()
					.logoutSuccessUrl("/login")
					.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
					.permitAll()
			.and()
				.authorizeRequests()
					.anyRequest().authenticated()
		;
	}
```

spring session filter is added using @EnableRedisHttpSession

V.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
