### ISSUE TITLE
How to replace StoreType.HASH_MAP in SpringBoot 2.x?

### ISSUE THREAD

**Issue by arcuri82** [spring-projects/spring-session#1228]
Hi,
  I am trying to update a SpringBoot application from 1.5 to 2.x
I ended up with the problem that `spring.session.store-type=hash_map` does no longer exist. I saw the motivation behind it in #1043
But, by looking at the documentation, I did not find an easy way to replace it. There is a question on [SO](https://stackoverflow.com/questions/48906697/what-should-be-a-replacement-for-storetype-hash-map-in-spring-boot-2) which is 8 month old, but with no answer :(  

My business case is as follow: in production, I am using Redis, with a configuration like `spring.session.store-type=redis`. In the the integration tests, I do not have Redis, so I just want to replace it with a in memory map. I do not care if sessions are never expired there, as anyway it is just for testing. In SpringBoot 1.5 I could easily override Redis config with `spring.session.store-type=hash_map` under `src/test/resources/application.yml`. How to achieve the same in SpringBoot 2.x? 

thx

**Comment by rwinch** [comment]
For the test configuration expose an instance of `MapSessionRepository` and `@EnableSpringHttpSession` should cause the redis configuration to back out of the way and configure Spring Session

**Comment by arcuri82** [comment]
thx, adding the following (in Kotlin) under `src/test/kotlin` did the trick:

```
@EnableSpringHttpSession
@Configuration
class ReplaceRedisConfig {
    @Bean
    fun sessionRepository() = MapSessionRepository(ConcurrentHashMap())
}
```

however, as feature request, it could be good to have a "test" option in `store-type` which is equivalent to having that `sessionRepository` bean

**Comment by rwinch** [comment]
Glad to hear it is working. 

> however, as feature request, it could be good to have a "test" option in store-type which is equivalent to having that sessionRepository bean

This discussion belongs in Spring Boot since that is where the auto configuration is managed. However, if you really want an easy way to test, then I'd suggest using `store-type=none` which disables Spring Session all together and thus in memory sessions are being used.

I'm closing this as answered.
