### ISSUE TITLE
spring session some jar is empty

### ISSUE THREAD

**Issue by springAppl** [spring-projects/spring-session#1231]
spring-session-data-redis,spring-session-data-mongos,spring-session-data-gemfire are empty.
1 It's wired how maven import some dependencies?
2 I use spring boot . SessionConfigurationImportSelector will import all type xxxSessionConfiguration(I debug it).  I think spring.session.store-type will determine which xxxSessionConfiguration to import, but it is not. I think spring-session-data-redis will determine which xxxSessionConfiguration to import.  where and how？

**Comment by rwinch** [comment]
Which versions are empty? Where did you get the dependencies? The selection is done using the store-type. See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-session

**Comment by vpavic** [comment]
@springAppl Are you using Spring Session 1.x? While reporting issues please always take care to provide the info on which version of Spring Session (as well as other related dependencies, like Spring Boot) do you use, as that's vital for us to provide support.

That being said, if you do use Spring Session 1.x, note that up until Spring Session 2.0 all the code was placed in `org.springframework.session:spring-session` artifact and all the others (like `spring-session-data-redis`, `spring-session-jdbc`, etc.) were simply starter/dependency aggregator modules with no code. See #768 and [this blog post](https://spring.io/blog/2017/05/11/spring-session-2-0-0-m1-released) for more background on the change made in 2.0.

**Comment by springAppl** [comment]
Ok, I really remember those tips. I'm using Spring Boot 1.5.17.RELEASE and Spring Session 1.3.3.RELEASE.
Thanks, i have read #768 and got the answer.

**Comment by vpavic** [comment]
Thanks for following up!
