### ISSUE TITLE
How to change the default serialization of the framework to my own JSON serialization

### ISSUE THREAD

**Issue by masterchengsheng** [spring-projects/spring-session#1232]
```
 @Bean("reactiveRedisTemplate")
    public ReactiveRedisTemplate<String, Object> ReactiveRedisTemplate() {
        GenericFastJsonRedisSerializer jsonRedisSerializer = new GenericFastJsonRedisSerializer();
        RedisSerializationContext<Object, Object> serializationContext = RedisSerializationContext
                .newSerializationContext().key(jsonRedisSerializer).value(jsonRedisSerializer)
                .hashKey(jsonRedisSerializer).hashValue(jsonRedisSerializer).build();
        return new ReactiveRedisTemplate(lettuceConnectionFactory(), serializationContext);
    }
```

but  I find  

```
org.springframework.session.data.redis.config.annotation.web.server.RedisWebSessionConfiguration 
have a private method：
private ReactiveRedisTemplate<String, Object> createReactiveRedisTemplate() {
		RedisSerializer<String> keySerializer = new StringRedisSerializer();
		RedisSerializer<Object> valueSerializer = new JdkSerializationRedisSerializer(
				this.classLoader);
		RedisSerializationContext<String, Object> serializationContext = RedisSerializationContext
				.<String, Object>newSerializationContext(valueSerializer)
				.key(keySerializer).hashKey(keySerializer).build();
		return new ReactiveRedisTemplate<>(this.redisConnectionFactory,
				serializationContext);
	}
```
   ，  
My configuration does not work at all.

**Comment by masterchengsheng** [comment]
WebFlux Spring session

**Comment by rwinch** [comment]
Thanks for reaching out. Can you provide what the issue you are having is?

**Comment by vpavic** [comment]
@masterchengsheng From the code snippets you provided I assume you are using Spring Session 2.0? While reporting issues please always take care to provide the info on which version of Spring Session (as well as other related dependencies, like Spring Boot) do you use, as that's vital for us to provide support.

That being said, if you do use Spring Session 2.0, note that support for customizing serialization mechanism for reactive Redis support is only available from `2.1.0.RELEASE` - see #1149.

**Comment by masterchengsheng** [comment]
> Thanks for reaching out. Can you provide what the issue you are having is? Specifically try to provide what is happening, what you expect or want to happen, and all the details we need to reproduce it.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.aimsphm</groupId>
    <artifactId>gateway-server</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>gateway-server</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-boot-admin.version>2.0.3</spring-boot-admin.version>
        <spring-cloud.version>Finchley.SR1</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        
            
            
            
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.github.vladimir-bukhtoyarov</groupId>
            <artifactId>bucket4j-core</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aimsphm</groupId>
            <artifactId>reps-common</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.aimsphm</groupId>
            <artifactId>reps-mapper</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-dependencies</artifactId>
                <version>${spring-boot-admin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>


this is my maven pom.xml  

I want to change the default serialization method to the serialization method I want.

**Comment by masterchengsheng** [comment]
> Thanks for reaching out. Can you provide what the issue you are having is? Specifically try to provide what is happening, what you expect or want to happen, and all the details we need to reproduce it.

    @Bean
    public LettuceConnectionFactory lettuceConnectionFactory() {
        LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
                .commandTimeout(Duration.ofSeconds(10))
                .shutdownTimeout(Duration.ZERO)
                .build();
        RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration(host, port);
        configuration.setPassword(RedisPassword.of(password));
        configuration.setDatabase(database);
        return new LettuceConnectionFactory(configuration, clientConfig);
    }




    @Bean
    public RedisTemplate<Object, Object> redisTemplate() {
        RedisTemplate<Object, Object> template = new RedisTemplate<>();
        template.setDefaultSerializer(new GenericFastJsonRedisSerializer());
        template.setKeySerializer(new GenericFastJsonRedisSerializer());
        template.setHashKeySerializer(new GenericFastJsonRedisSerializer());
        template.setHashValueSerializer(new GenericFastJsonRedisSerializer());
        template.setConnectionFactory(lettuceConnectionFactory());
        return template;
    }


    @Bean("reactiveRedisTemplate")
    public ReactiveRedisTemplate<String, Object> ReactiveRedisTemplate() {
        GenericFastJsonRedisSerializer jsonRedisSerializer = new GenericFastJsonRedisSerializer();
        RedisSerializationContext<Object, Object> serializationContext = RedisSerializationContext
                .newSerializationContext().key(jsonRedisSerializer).value(jsonRedisSerializer)
                .hashKey(jsonRedisSerializer).hashValue(jsonRedisSerializer).build();
        return new ReactiveRedisTemplate(lettuceConnectionFactory(), serializationContext);
    }

**Comment by masterchengsheng** [comment]
> @masterchengsheng From the code snippets you provided I assume you are using Spring Session 2.0? While reporting issues please always take care to provide the info on which version of Spring Session (as well as other related dependencies, like Spring Boot) do you use, as that's vital for us to provide support.
> 
> That being said, if you do use Spring Session 2.0, note that support for customizing serialization mechanism for reactive Redis support is only available from `2.1.0.RELEASE` - see #1149.

spring-session-data-redis.2.0.6.RELEASE  I want to use fastJson serialization  replace the default serialization

**Comment by vpavic** [comment]
OK, so as suspected, you're using Spring Session 2.0.x (i.e. Apple) where we don't have a first-class support for supplying a custom serialization mechanism.

You have two options; either update to Spring Session 2.1.x (i.e. Bean) - note that we've just release `Bean-RELEASE` yesterday; if you cannot upgrade, you need to manually register `ReactiveRedisOperationsSessionRepository` and configure it with desired `ReactiveRedisTemplate`. For example:

```java
@EnableRedisWebSession
public class SessionConfiguration {

    @Bean
    public ReactiveRedisOperationsSessionRepository sessionRepository() {
        // either configure reactiveRedisTemplate for Spring Session here or inject it
        // ...
        ReactiveRedisOperationsSessionRepository sessionRepository =
            new ReactiveRedisOperationsSessionRepository(reactiveRedisTemplate);
    }

}
```

When you upgrade the Spring Session 2.1.x (i.e. Bean) you will simply replace the custom `ReactiveRedisOperationsSessionRepository` bean declaration with the `RedisSerializer<Object>`
named `springSessionDefaultRedisSerializer` that will be automatically picked up:

```java
@Bean
public RedisSerializer<Object> springSessionDefaultRedisSerializer() {
    // return you Redis serializer implementation
}
```

Does this help?

**Comment by masterchengsheng** [comment]
@Bean
RedisSerializer<Object> springSessionDefaultRedisSerializer() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new CoreJackson2Module());
    return new GenericJackson2JsonRedisSerializer(mapper);
}

OK  thank you!!!!!!!!!!!!!

Thank you very much,“DA NIU” (in Chinese it means a knowledgeable person)



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Vedran Pavic <notifications@github.com>
发送时间: Tuesday, October 30, 2018 12:47:36 PM
收件人: spring-projects/spring-session
抄送: 程胜; Mention
主题: Re: [spring-projects/spring-session] How to change the default serialization of the framework to my own JSON serialization (#1232)


OK, so as suspected, you're using Spring Session 2.0.x (i.e. Apple) where we don't have a first-class support for supplying a custom serialization mechanism.

You have two options; either update to Spring Session 2.1.x (i.e. Bean) - note that we've just release Bean-RELEASE yesterday; if you cannot upgrade, you need to manually register ReactiveRedisOperationsSessionRepository and configure it with desired ReactiveRedisTemplate. For example:

@EnableRedisWebSession
public class SessionConfiguration {

    @Bean
    public ReactiveRedisOperationsSessionRepository sessionRepository() {
        // either configure reactiveRedisTemplate for Spring Session here or inject it
        // ...
        ReactiveRedisOperationsSessionRepository sessionRepository =
            new ReactiveRedisOperationsSessionRepository(reactiveRedisTemplate);
    }

}

When you upgrade the Spring Session 2.1.x (i.e. Bean) you will simply replace the custom ReactiveRedisOperationsSessionRepository bean declaration with the RedisSerializer<Object>
named springSessionDefaultRedisSerializer that will be automatically picked up:

@Bean
public RedisSerializer<Object> springSessionDefaultRedisSerializer() {
    // return you Redis serializer implementation
}

Does this help?

―

**Comment by vpavic** [comment]
Thanks for the follow up and kind words @masterchengsheng. Closing this as answered.
