### ISSUE TITLE
Why  the value of the session can be accessed when the  session expires is necessary?

### ISSUE THREAD

**Issue by springAppl** [spring-projects/spring-session#1239]
I read [RedisOperationsSessionRepository document](https://github.com/spring-projects/spring-session/blob/2.0.x/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java), at row 166. I can't imagine any situation that I need access the value of the session when the session expires. Could you give some examples?

**Comment by rwinch** [comment]
To fire the `SessionExpiredEvent` which contains the information from the session.

**Comment by springAppl** [comment]
👍
