### ISSUE TITLE
HazelcastSession makes changed = true even if there are nothing changed

### ISSUE THREAD

**Issue by cdene** [spring-projects/spring-session#1241]
Hello everyone! 
I use HazelcastRepository and HazelcastSession

This is a part of class HazelcastSession 
```
final class HazelcastSession implements ExpiringSession {
		private final MapSession delegate;
		private boolean isNew;
		private boolean changed;
		private Map<String, Object> delta = new HashMap<String, Object>();
```
and the method setAttributes of that class like that 
```
public void setAttribute(String attributeName, Object attributeValue) {
			this.delegate.setAttribute(attributeName, attributeValue);
			this.delta.put(attributeName, attributeValue);
			this.changed = true;
			flushImmediateIfNecessary();
		}
```
marks my HazelcastSession changed every time I put any new attribute in there, even if the new one already exists in delegate map and has the same value

My question is - 
     Is that possible, _if this.delegate.getAttribute(attributeName) does exist_, just to compare the attributeValue to existing this.delegate.getAttribute(attributeName) and then decide was something changed or not? 

Thank you in advance

**Comment by rwinch** [comment]
It is possible to do dirty checking, but this adds a lot of complexity to the code. If you don't want the value to be saved, then it is recommended not to set it (you can compare before you set it)
