### ISSUE TITLE
SessionRepositoryFilter should commit session before an include dispatch

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-session#1242]
Related to https://github.com/spring-projects/spring-security/issues/5499

Headers cannot be written after an include dispatch (e.g. `request.getRequestDispatcher(path).include`), meaning that any header-based session id resolution strategy will fail to write the session id to the response.

**Comment by vpavic** [comment]
Thanks @jzheaux - I believe this is a duplicate of #1214. Also note that there's no need to open an issue if you plan to submit a PR straight away.

**Comment by vpavic** [comment]
Duplicate of #1214
