### ISSUE TITLE
Consider overhaul of project's GitHub labels

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1258]
We should consider aligning our GitHub labels to be consistent with ones Spring Boot has - see [here](
https://github.com/spring-projects/spring-boot/labels).

Of course, we should also add some that make sense from Spring Session's perspective. I've compiled an initial list some while ago:

```
status: blocked
status: declined
status: duplicate
status: feedback-provided
status: feedback-reminder
status: first-timers-only
status: ideal-for-contribution
status: invalid
status: on-hold
status: superseded
status: waiting-for-feedback
status: waiting-for-triage
status: waiting-for-votes

for: external-project
for: merge-with-amendments
for: stackoverflow
for: team-attention

type: blocker
type: bug
type: dependency-upgrade
type: documentation
type: enhancement
type: regression
type: task
type: wiki-documentation

store: map
store: redis
store: hazelcast
store: jdbc

integration: httpsession
integration: websession
integration: security
integration: websocket
```

**Comment by vpavic** [comment]
Here are the amendments as per our discussion few standups ago:

```
status: blocked
status: declined
status: duplicate
status: feedback-provided
status: feedback-reminder
status: first-timers-only
status: ideal-for-contribution
status: invalid
status: on-hold
status: pending-design-work
status: superseded
status: waiting-for-feedback
status: waiting-for-triage

for: external-project
for: merge-with-amendments
for: stackoverflow
for: team-attention

type: blocker
type: bug
type: dependency-upgrade
type: documentation
type: enhancement
type: regression
type: task

has: backports

store: map
store: map-reactive
store: redis
store: redis-reactive
store: hazelcast
store: jdbc

integration: httpsession
integration: websession
integration: security
integration: websocket
```

For reference, here are links to labels from:
* [Spring Boot](https://github.com/spring-projects/spring-boot/labels)
* [Spring Framework](https://github.com/spring-projects/spring-framework/labels)

Let me know what you think @rwinch before I proceed to apply these.

**Comment by rwinch** [comment]
Can we change integration to in as Spring Framework does?

**Comment by vpavic** [comment]
The `in:` prefix could work, but do we then need to make that _what_ part a bit wordier? For example, `in: map-reactive` sounds a bit vague compared to `store: map-reactive`. Same for say `in: security` vs `integration: security`.

**Comment by rwinch** [comment]
I see your point about the stores, but I don't think that `in: security and `integration: security` are quite comparable. I'd prefer if we can stick to the same prefixes Spring Framework is doing since this work is to better align with the rest of Spring. For that reason, I'd prefer if we do something like `in: map-reactive-store`

**Comment by vpavic** [comment]
I'm not sure I get you comment - I tried to say that I'm fine with `in:` prefix, but assuming `in: what` format, we need to make the _what_ part more descriptive.

Alternatively, and this would arguably be even more consistent with Framework's approach, we could simply limit the `in:` labels to:

```
in: core
in: redis
in: jdbc
in: hazelcast
```

**Comment by rwinch** [comment]
I like you most recent suggestion. I guess that leads to the question of...what (if anything) do we do about reactive. Spring Framework currently doesn't have any labels for reactive. However, I do think a distinction is valuable. I'm not really sure what to do with that though. Thoughts?

**Comment by vpavic** [comment]
I also like the most recent version. The reasons are simplicity, alignment with both Spring Framework and our also alignment with our modules - both of which I believe are very relevant to the user.

One can do so much with the labels, but IMO by far the most important are type (`type:`) and lifecycle (`status:`) related ones. Module related ones (`in:`) are a nice extra an once you filter e.g. `in: redis` it shouldn't be too hard to discern which are related to reactive.

**Comment by rwinch** [comment]
Ok fair enough. Let's proceed without the reactive label. If need be we can revisit that decision later. I'd like to also propose we change `has: backports` to `is: backported` and `is: backport` as Spring Framework will be moving to that model as well. See 

 To be clear here are the labels I am now expecting:

```
status: blocked
status: declined
status: duplicate
status: feedback-provided
status: feedback-reminder
status: first-timers-only
status: ideal-for-contribution
status: invalid
status: on-hold
status: pending-design-work
status: superseded
status: waiting-for-feedback
status: waiting-for-triage

for: external-project
for: merge-with-amendments
for: stackoverflow
for: team-attention

type: blocker
type: bug
type: dependency-upgrade
type: documentation
type: enhancement
type: regression
type: task

is: backported
is: backport

in: core
in: redis
in: jdbc
in: hazelcast
```

**Comment by vpavic** [comment]
Sounds good - I'll get into that today or tomorrow. BTW seems like you comment misses something (a link?) at the end of first paragraph.

**Comment by rwinch** [comment]
@vpavic Thanks. There was a missing link. I added it

**Comment by rwinch** [comment]
I've updated the labels. There were a few that have been changed to better reflect updates within the other projects, but generally the proposal was used.
