### ISSUE TITLE
A typo in RedisOperationsSessionRepository

### ISSUE THREAD

**Issue by domainname** [spring-projects/spring-session#1271]
The comment says:

> * One problem with relying on Redis expiration exclusively is that Redis makes no
> * guarantee of when the expired event will be fired if they key has not been accessed.

It should be "if **the** key has not been accessed".

**Comment by rwinch** [comment]
@domainname Thanks for the report! Would you be interested in submitting a PR?

**Comment by domainname** [comment]
@rwinch please see https://github.com/spring-projects/spring-session/pull/1273

**Comment by vpavic** [comment]
Closing in favor of PR #1273.
