### ISSUE TITLE
Make JdbcOperationsSessionRepository.JdbcSession visible

### ISSUE THREAD

**Issue by harbulot** [spring-projects/spring-session#1274]
(This is using Spring Session 2.1.1.)

Please consider making `JdbcOperationsSessionRepository.JdbcSession` visible. Some use cases have already been suggested in #943 and #1217, here is another one.

I'm trying to implement a `SpringSessionBackedSessionRegistry`  (mainly to implement `getAllPrincipals()`) backed by a `JdbcOperationsSessionRepository`, which itself implements `FindByIndexNameSessionRepository<JdbcOperationsSessionRepository.JdbcSession>`.

It would be good to be able to use the generic types:

```java
public class JdbcSpringSessionBackedSessionRegistry extends
        SpringSessionBackedSessionRegistry<JdbcOperationsSessionRepository.JdbcSession> {
    
    public JdbcSpringSessionBackedSessionRegistry(
        JdbcOperationsSessionRepository sessionRepository) {
            super(sessionRepository);
	    // ...
    }
    // ...
}
```

However, `JdbcSession` is not visible, so this can't be used in a different package.

Here is a workaround, but we lose the generics checks:

```java
@SuppressWarnings("rawtypes")
public class JdbcSpringSessionBackedSessionRegistry extends
        SpringSessionBackedSessionRegistry {

    @SuppressWarnings("unchecked")
    public JdbcSpringSessionBackedSessionRegistry(
        JdbcOperationsSessionRepository sessionRepository) {
            super(sessionRepository);
	    // ...
    }
    // ...
}
```

**Comment by vpavic** [comment]
As noted in the related issues we consider `JdbcSession` to be a `JdbcOperationsSessionRepository` implementation detail. With that in mind, you should really have your extension of `SpringSessionBackedSessionRegistry` parameterized with `<S extends Session>`.

Also could you clarify how this would help you implement `SessionRegistry#getAllPrincipals` since `FindByIndexNameSessionRepository` API doesn't expose an operation to retrieve all principals?

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please comment back if you can provide more details and we can re-open the issue.

**Comment by vpavic** [comment]
Sorry about late response to this @harbulot. If I understand correctly what you were trying to achieve, I'm not sure why simply something like this wouldn't work:

```java
public class JdbcSpringSessionBackedSessionRegistry<S extends Session>
		extends SpringSessionBackedSessionRegistry<S> {

	private final JdbcOperations jdbcOperations;

	public JdbcSpringSessionBackedSessionRegistry(
			FindByIndexNameSessionRepository<S> sessionRepository,
			JdbcOperations jdbcOperations) {
		super(sessionRepository);
		this.jdbcOperations = jdbcOperations;
	}

	@Override
	public List<Object> getAllPrincipals() {
		// ...
	}

}
```

If you're deeper into customization, providing a custom `SessionRepository` implementation might be needed. We're not keen on opening up `JdbcOperationsSessionRepository` implementation details as that increases our API surface and makes it harder to evolve down the road.
