### ISSUE TITLE
Thread lock combining spring-session-redis with sleuth

### ISSUE THREAD

**Issue by yarodinD** [spring-projects/spring-session#1283]
Hello.

I use Spring Boot 2.1.1. When I add both spring-cloud-starter-sleuth 2.1.0.RC2 and spring-session-data-redis 2.1.2.RELEASE into the classpath (together with spring-boot-starter-data-redis 2.1.1.RELEASE), I get a thread lock when starting the service.

As soon as I either remove sleuth or spring-session-data-redis from the classpath, the service starts again.

I'm not sure whether the cause is on sleuths side or comes from spring-session since main thread is going into "wait" state while trying to get a Redis connection. Here is the thread dump.

[thread_dump_greenwich_rc1.txt](https://github.com/spring-projects/spring-session/files/2675027/thread_dump_greenwich_rc1.txt)

I created a ticket in the sleuth project as well (https://github.com/spring-cloud/spring-cloud-sleuth/issues/1154), but since sleuth does not access redis (afaik) and the thread is stuck there, I opened this issue here.

**Comment by rwinch** [comment]
It appears that it is waiting on a connection to Redis. Is your Redis instance accepting connections? If you remove Spring Session and just have spring-boot-starter-redis do  you see any issues?

**Comment by yarodinD** [comment]
Yes, you're right. Sorry.
The setup I used was redis with sentinel and somehow this micro "cluster" didn't work.
The sentinel was connected but could not report a working redis instance back. That this leads to a block and no error or timeout though.
Sorry for the inconvenience.

**Comment by vpavic** [comment]
Thanks for letting us know @yarodinD, glad to hear you figured it out.
