### ISSUE TITLE
A question about the event mechanism in SpringSession

### ISSUE THREAD

**Issue by glmapper** [spring-projects/spring-session#1287]
I have a doubt when I am learning the SpringSession source code. In the RedisOperationsSessionRepository class, when trying to publish an event, such as SessionCreatedEvent, the publishEvent in eventPublisher is a null operation.

```java
private ApplicationEventPublisher eventPublisher = new ApplicationEventPublisher() {
   @Override
   public void publishEvent(ApplicationEvent event) {
   }

   @Override
   public void publishEvent(Object event) {
   }
};
```

**Comment by rwinch** [comment]
@gaborcs Thank you for using Spring Session and for your question!

This is the default eventPublisher. A custom implementation is typically injected in via [RedisOperationsSessionRepository.setApplicationEventPublisher](https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/data/redis/RedisOperationsSessionRepository.html#setApplicationEventPublisher-org.springframework.context.ApplicationEventPublisher-)

I'm closing this as answered. In the future please post questions to StackOverflow as this is our preferred mechanism for questions.
