### ISSUE TITLE
Session atrribute updates every 2 seconds

### ISSUE THREAD

**Issue by rhandersen** [spring-projects/spring-session#1296]
In our project we see that the spring session attributes are being updated every 2 seconds in production (Linux servers) for every user, causing quite a workload for the database. 

When developing and running it on a local windows tomcat we don't see the issue and the attributes are updated as expected. 

Any ideas on how we can get rid of these unneeded updates?

We use Spring Session 1.3.0 with JDBC

Thanks!

**Comment by rhandersen** [comment]
Thanks for a quick reply @vpavic.

We don't do ping/health check requests that often, so that doesn't explain it. Also the attributes should not be updated right? I know that the spring session table is updated for every request and that is fine, but it is a mystery to me why the attributes are updated even though no requests are made. 

Any ideas on how to debug this to figure out what is happning?

**Comment by vpavic** [comment]
Thanks for following up @rhandersen - we track a delta of attributes and only write the changes made there. You should somehow figure out what calls `javax.servlet.http.HttpSession#setAttribute`.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please comment back if you can provide more details and we can re-open the issue.
