### ISSUE TITLE
Allow dynamic Redis namespace configuration

### ISSUE THREAD

**Issue by danielfariati** [spring-projects/spring-session#1301]
Allow to dynamically define whats the current namespace for Redis.

The scenario is that I currently have a multi-tenant service (subdomain based) that will consult the Session Data within Redis, so I would like to define the tenant to be part of the namespace for the current request.

There is an option to customize the namespace via `@EnableRedisHttpSession(redisNamespace = "foo") `, but it is not dynamic, so it wouldn't change based on the current tenant.

Calling the `setRedisKeyNamespace` for the `RedisOperationsSessionRepository` would also not work well because, as far as I know, it is a singleton.

Also, overriding the `RedisOperationsSessionRepository` is currently a pain because there are some private methods that are using the `this.namespace` directly.

**Comment by danielfariati** [comment]
My main concern is that two different tenants end up with the same Session ID, and so the wrong session, for the wrong tenant is passed up.
I pass up the Session ID to other services with `HttpSessionIdResolver.xAuthToken()`. 
I don't know how the Session ID is generated, so I want to define the tenant as a part of the namespace just to be sure, but maybe this isn't even a real problem.

**Comment by vpavic** [comment]
@danielfariati Default session id generation strategy is `UUID` based so it shouldn't be an issue that they all share the same namespace. Having that in mind, dynamic resolution of namespace would be an overhead that doesn't actually address any apparent problem. Can you confirm that your concerns with multi tenant configuration are purely around conflicting session ids?

Also note that we have #11 still open to consider providing a custom session id generation strategy.

**Comment by danielfariati** [comment]
Yes, that was my only concern.
Thanks for the help!

**Comment by vpavic** [comment]
Thanks for following up @danielfariati!
