### ISSUE TITLE
Spring session / Hazelcast integration does not read application configuration spring.session.hazelcast.map-name

### ISSUE THREAD

**Issue by dougkei** [spring-projects/spring-session#1303]
The implementation only read the EnableHazelcastHttpSession annotation parameter, which is defined at compile time. It is sometimes desirable to define as application configuration at runtime.

Spring boot 1.5
8 / Spring session 1.3.1
Spring boot 1.5.18 / Spring session 1.3.4

**Comment by vpavic** [comment]
If you are using Spring Boot you should be able to use its auto-configuration support for Spring Session and `spring.session.hazelcast.*` configuration properties. See Spring Boot's reference manual on [Spring Session support](https://docs.spring.io/spring-boot/docs/1.5.x/reference/htmlsingle/#boot-features-session).

If you are using `@EnableHazelcastHttpSession` annotation then you are configuring Spring Session manually which means Spring Boot's auto-configuration backs off.

With that, I'm closing this as answered.
