### ISSUE TITLE
Spring session cross-domain issues

### ISSUE THREAD

**Issue by DazzlingSun** [spring-projects/spring-session#1323]
hi
I used redis to store sessions and cores to solve cross-domain problems.
Test session storage reads are normal in non-cross-domain cases.
In the cross-domain access, a Cookie named Session will appear in each access, and the value of the Cookie is changing all the time, and the server also continuously generates a new Session.
Redis :5.0.3. Spring :5.1.4. spring session:2.1.3.
Hope to provide some screening ideas
Thanks!

**Comment by rwinch** [comment]
I'm sorry, but I don't think understand what you are trying to report. Can you elaborate?

**Comment by DazzlingSun** [comment]
First of all, under the non-cross-domain condition, all functions of spring-session in my current project test are normal, which indicates that my configuration is correct.
In the case of cross-domain, the server can normally store sessions into Redis, but does not return a Cookie with the name of JSESSIONID.

### The request for the first time
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The Set - cookies: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1;Path = /;HttpOnly;SameSite = Lax
Than: Origin
### Request again:
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Cookie: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The content-type: text/plain.Charset = utf-8
Than: Origin

Neither of the above requests returns JSESIONID, but two sessions are generated in redis

**Comment by DazzlingSun** [comment]
First of all, under the non-cross-domain condition, all functions of spring-session in my current project test are normal, which indicates that my configuration is correct.
In the case of cross-domain, the server can normally store sessions into Redis, but does not return a Cookie with the name of JSESSIONID.

### The request for the first time
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The Set - cookies: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1;Path = /;HttpOnly;SameSite = Lax
Than: Origin

### Request again:
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Cookie: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The content-type: text/plain.Charset = utf-8
Than: Origin

Neither of the above requests returns JSESIONID, but two sessions are generated in redis

**Comment by DazzlingSun** [comment]
> I'm sorry, but I don't think understand what you are trying to report. Can you elaborate?

First of all, under the non-cross-domain condition, all functions of spring-session in my current project test are normal, which indicates that my configuration is correct.
In the case of cross-domain, the server can normally store sessions into Redis, but does not return a Cookie with the name of JSESSIONID.

### The request for the first time
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The Set - cookies: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1;Path = /;HttpOnly;SameSite = Lax
Than: Origin

### Request again:
**Request:**
The Request URL: http://localhost:8087/HproseServer
The Request Method: POST
The Status Code: 200 OK
Cookie: SESSION = ZTQyOGM1MDAtNWE3NS00ODVhLTg0NmYtMWU5MTcwNzI5OWI1
Host: localhost: 8087
Origin: http://localhost:8093
**The Response:**
Access - Control - Allow - Credentials: true
Access - Control - Allow - Origin: http://localhost:8093
Access - Control - Expose - Headers: Set - cookies
The Content - Length: 2448
The content-type: text/plain.Charset = utf-8
Than: Origin

Neither of the above requests returns JSESIONID, but two sessions are generated in redis

**Comment by DazzlingSun** [comment]
> I'm sorry, but I don't think understand what you are trying to report. Can you elaborate?

The reason is found because the DefaultCookieSerializer is used. The Cookie has set the HttpOnly attribute, so the cross-domain request cannot be carried to the Cookie. I want to modify this attribute, but I cannot find the entry to set this attribute.

**Comment by DazzlingSun** [comment]
> I'm sorry, but I don't think understand what you are trying to report. Can you elaborate?
