### ISSUE TITLE
RedisOperationsSessionRepository loadSession ClassCastException

### ISSUE THREAD

**Issue by aterleto** [spring-projects/spring-session#1330]
Hi, I'm using the following versions -
<spring.version>5.1.4.RELEASE</spring.version><spring.session.redis.version>2.1.2.RELEASE</spring.session.redis.version>

org.springframework.session.data.redis.RedisOperationsSessionRepository has a private class, _loadSession_, that casts some hard-coded session data. See in bold below -

private MapSession loadSession(String id, Map<Object, Object> entries) {
		MapSession loaded = new MapSession(id);
		for (Map.Entry<Object, Object> entry : entries.entrySet()) {
			String key = (String) entry.getKey();
			if (CREATION_TIME_ATTR.equals(key)) {
				**loaded.setCreationTime(Instant.ofEpochMilli((long) entry.getValue()));**
			}
			else if (MAX_INACTIVE_ATTR.equals(key)) {
				**loaded.setMaxInactiveInterval(Duration.ofSeconds((int) entry.getValue()));**
			}
			else if (LAST_ACCESSED_ATTR.equals(key)) {
				**loaded.setLastAccessedTime(Instant.ofEpochMilli((long) entry.getValue()));**
			}
			else if (key.startsWith(SESSION_ATTR_PREFIX)) {
				loaded.setAttribute(key.substring(SESSION_ATTR_PREFIX.length()),
						entry.getValue());
			}
		}
		return loaded;
	}

Since JdkSerializationRedisSerializer is used by default I get all kinds of garbage in the actual Redis database. As a workaround I have seen multiple people post about using StringRedisTemplate since it sets the StringRedisSerializer for the Key & Value Hashs. However when I tried this it throws an exception in the _loadSession_ method since the String cannot be cast down to a primitive int/long. I have also tried using the Jackson2JsonRedisSerializer, type-casting it to java.lang.Long, however this also breaks due to a ClassCastException between the Long and int.

Since most Hashs are stored in Redis as Strings it does make sense to use StringRedisTemplate, but for it to work on the hard-coded session fields wouldn't the code be safer if written as the following -

loaded.setCreationTime(Instant.ofEpochMilli(**new Long(entry.getValue() + "")**));
loaded.setMaxInactiveInterval(Duration.ofSeconds(**new Integer(entry.getValue()+"")**));
loaded.setLastAccessedTime(Instant.ofEpochMilli(**new Long(entry.getValue() + "")**));

Left as is, StringRedisSerializer will always throw an exception.

**Comment by vpavic** [comment]
Thanks for the report @aterleto. `RedisOperationsSessionRepository` is really intended to operate on session attribute values of `Object` as this is implied by `javax.servlet.http.HttpSession#setAttribute` contract - if you're using `StringRedisSerializer` for serializing hash values I'm not sure how are you even able to store the session as I would expect it to blow up here:

https://github.com/spring-projects/spring-session/blob/8fc2f1130a2b8bb1d4757c48dca97bd5b92e9e1c/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L830

Can you provide a sample of your configuration to get a better insight in what you're trying to do here?

**Comment by aterleto** [comment]
Thanks @vpavic.

To answer your question directly, I'm really not doing anything special. I reverted the config, but in my testing I was able to save session attributes to Redis using `StringRedisSerializer`. I debugged and saw that on lookup things blew up, specifically in the method I provided above. All my code is available here - https://github.com/aterleto/redis_spring_session_demos

The big picture problem is that the `JdkSerializationRedisSerializer` adds so much garbage to Hash Values that in large data scenarios its a blocker to use since you'll need more infrastructure. If there was a way to assign a Serializer per key than we would be good but since it has to be at a global session level there is a gap limiting Spring Session from larger applications. If I'm missing a known workaround please let me know.

With that said, I'm confused by your question. If `RedisOperationsSessionRepository` is only intended to operate on session attribute values of type `Object` then why do you allow to inject `StringRedisSerializer` at all? In addition a quick google search shows it promoted in other cases as a workaround which during my testing I found strange since it doesn't work due to the `ClassCastException` problem.

So unless one of my above assumptions is incorrect, other than the inefficient creation of a few more Strings, what would be the harm of my proposed fix? The current implementation is not the safest way to cast up hence the ClassCastException. Thoughts?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
