### ISSUE TITLE
Introduce @SessionAttribute for message-handling methods

### ISSUE THREAD

**Issue by marcus-held** [spring-projects/spring-session#1333]
Since we have the [HttpSessionHandshakeInterceptor](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/socket/server/support/HttpSessionHandshakeInterceptor.html) I'd love to have easier access to the session attributes by using an annotated parameter.

```
@MessageMapping("foo")
public String bar(@SessionAttribute("attribute") String myAttribute) {
...
}
```

**Comment by rwinch** [comment]
I believe this makes more sense for Spring Framework to implement. Is there a reason you logged it here vs in Spring Framework? If not, we can move it to https://github.com/spring-projects/spring-framework/issues

**Comment by mld-ger** [comment]
Honestly I'm a bit confused by the responsibilities in this topic. So I'd be okay moving it of course.

**Comment by vpavic** [comment]
I think this should be moved to Framework's issue tracker - @rwinch can you do this? I can't choose Framework as target repository, probably to the lack of permission.

**Comment by rwinch** [comment]
This was introduced in Spring Framework 4.3 https://docs.spring.io/spring-framework/docs/4.3.x/javadoc-api/org/springframework/web/bind/annotation/SessionAttribute.html
