### ISSUE TITLE
Setting up Cookie path and session time out dynamically based on the request path

### ISSUE THREAD

**Issue by jobinvjohn** [spring-projects/spring-session#1335]
We have requirement to set the cookie name and session time out dynamically based on the request path. 

for eg. 
    http://localhost:8080/path1
          CookiePath : /path1
          sessiontimeout: 30 mins
   http://localhost:8080/path2
        CookiePath : /path2
          sessiontimeout: 45 mins

Is it possible using spring session?

**Comment by rwinch** [comment]
You can implement a custom [CookieSerializer](https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/web/http/CookieSerializer.html] to customize the cookie and you can set the [HttpSession.html#setMaxInactiveInterval](https://docs.oracle.com/javaee/5/api/javax/servlet/http/HttpSession.html#setMaxInactiveInterval(int)] based upon whatever logic you like.

In the future please use StackOverflow for questions as this is the preferred way of asking questions (it gets more people answering them so you get faster results too).
