### ISSUE TITLE
Spring Session and Spring OAuth2 OpenId. 

### ISSUE THREAD

**Issue by dsu** [spring-projects/spring-session#1344]
I have ADFS open Id authentication in my application. But after adding Spring session and configuring HTTP headers instead of the session cookie I have exception as below during authentication:

>     13:45:55.070 [http-nio-8094-exec-1] DEBUG c.a.d.security.OpenIdConnectFilter - Request is to process authentication
>     13:45:55.071 [http-nio-8094-exec-1] DEBUG c.a.d.security.OpenIdConnectFilter - Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Could not obtain access token
>     org.springframework.security.authentication.BadCredentialsException: Could not obtain access token
>             at com.adidas.disip.security.OpenIdConnectFilter.attemptAuthentication(OpenIdConnectFilter.java:55)
>             at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at com.adidas.disip.security.GodLoginFilter.doFilter(GodLoginFilter.java:47)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
>             at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
>             at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
>             at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
>             at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:151)
>             at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
>             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
>             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>             at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>             at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>             at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>             at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
>             at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
>             at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
>             at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
>             at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
>             at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
>             at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
>             at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
>             at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
>             at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>             at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>             at java.lang.Thread.run(Thread.java:745)
>     Caused by: org.springframework.security.oauth2.common.exceptions.InvalidRequestException: Possible CSRF detected - state parameter was required but no state could be found
>             at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getParametersForTokenRequest(AuthorizationCodeAccessTokenProvider.java:255)
>             at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccessToken(AuthorizationCodeAccessTokenProvider.java:209)
>             at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:148)
>             at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:121)
>             at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
>             at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
>             at com.adidas.disip.security.OpenIdConnectFilter.attemptAuthentication(OpenIdConnectFilter.java:52)
> 

Spring Session configuration:

```
    @Configuration
    @EnableSpringHttpSession
    class HttpSessionConfig extends AbstractHttpSessionApplicationInitializer {
    
    
        @Bean
        public HttpSessionIdResolver httpSessionIdResolver() {
            return HeaderHttpSessionIdResolver.xAuthToken();
        }
    
        @Bean
        public MapSessionRepository sessionRepository() {
            return new MapSessionRepository(new ConcurrentHashMap<>());
        }
    }
```

**Comment by eleftherias** [comment]
Thanks for getting in touch @dsu and I'm sorry about the late reply.
Do you have a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
