### ISSUE TITLE
Set SessionRepositoryRequestWrapper in RequestContextHolder

### ISSUE THREAD

**Issue by damiancalabresi** [spring-projects/spring-session#135]
Some filter may use a session scoped bean in a custom filter. The SessionScope class gets the current request from the RequestContextHolder. The problem is the RequestContextHolder have the request: org.apache.catalina.connect.Request.

As a result, a new session is created using Tomcat session manager. Indeed. I have two cookies: SESSION and JSESSIONID.
I think the filter SessionRepositoryFilter must update the RequestContextHolder with SessionRepositoryRequestWrapper.

For example, at the end of the filter chain, ApplicationFilterChain (A Spring Web Framework filter) does it.

I removed my custom filter but the problem remains, another filter is creating a session using using org.apache.catalina.connect.Request instead of SessionRepositoryRequestWrapper.

**Comment by cemo** [comment]
duplicates #129

**Comment by damiancalabresi** [comment]
I don't think this issue is duplicated. The issue #129 is about an exception. In my case, the problem is in a filter that is executed after the SessionRepositoryFilter. This filter is creating another session just because the RequestContextHolder.

As a temporary fix, I have done the following:

Add a filter named RequestContextHolderUpdateFilter just to be called after the SessionRepositoryFilter, with the order:
SessionRepositoryFilter.DEFAULT_ORDER+1

This filter does this:
HttpServletRequest httpRequest = (HttpServletRequest) request;
RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(httpRequest));

I supose a good solution could be add the previous line to the SessionRepositoryFilter.

**Comment by rwinch** [comment]
Thanks for the report and suggestion @damiancalabresi!

Spring Session at its core (i.e. SessionRepositoryFilter) does not depend on anything but commons-logging and we would like to keep it that way. This ensures that we have a very light footprint for applications that are not otherwise using Spring.

The solution to your problem is to ensure that you add a  `RequestContextFilter` (provided by spring-web jar) after the `SessionRepositoryFilter` which will ensure that the `HttpServletRequest` is properly set. Is there a reason that this won't work for you?

**Comment by damiancalabresi** [comment]
Thanks for your answer. I didn't use the RequestContextFilter but it should be the right solution. Instead I created a custom filter that do practically the same. I will replace it with the RequestContextFilter.
I think this issue should be closed, probably this case could be added to the documentation in the future.

**Comment by rwinch** [comment]
@damiancalabresi Very good point on adding this use case to the documentation! I have created #137 to address this.
