### ISSUE TITLE
@EnableRedisHttpSession not found

### ISSUE THREAD

**Issue by fangchenhui3** [spring-projects/spring-session#1371]
Hello ! 
I found the annotation EnableRedisHttpSession is missing.
I followed the doc on the website https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-redis.html#httpsession-sample
step by step. But I found IDEA can not resolve the symbol @EnableRedisHttpSession.
Could you tel me the reason or something wrong?
Thanks!
pom.xml:
![image](https://user-images.githubusercontent.com/13816460/54514393-fff8e580-4994-11e9-8270-1f45e2dc5fcf.png)

problem:
![image](https://user-images.githubusercontent.com/13816460/54514414-0d15d480-4995-11e9-98fc-90bdc4104d01.png)

![image](https://user-images.githubusercontent.com/13816460/54514338-d63fbe80-4994-11e9-9e3d-3e2ed7b36188.png)

**Comment by fangchenhui3** [comment]
it works well when I change reimport the project ,I do not know the reason!

**Comment by BAbate** [comment]
Hey, @fangchenhui3 I faced the same problem, but I updated Maven and cleaned the projected. Then it worked perfectly fine. The reason why it worked well for you after the reimport was Maven was updated as you did 'reimport'.
