### ISSUE TITLE
SessionRepository not found when WebSocket sample start

### ISSUE THREAD

**Issue by kentkwan** [spring-projects/spring-session#1372]
RedisOperationsSessionRepository was be initialized, but cannot inject into AbstractSessionWebSocketMessageBrokerConfigurer.

**Comment by vpavic** [comment]
Can you provide more details @kentkwan? There's not enough information for us here to be able to figure out where the problem could be. Also note that we have a [sample app](https://github.com/spring-projects/spring-session/tree/master/samples/boot/websocket) that demonstrates this use case in our codebase.
