### ISSUE TITLE
some logic problem in method cleanExpiredSessions() of org.springframework.session.data.redis.RedisSessionExpirationPolicy.java

### ISSUE THREAD

**Issue by atlantisor** [spring-projects/spring-session#1376]
i found there may have some logic problem in following code snippet of org.springframework.session.data.redis.RedisSessionExpirationPolicy.java which try to clear expired session by accessing the session key(String sessionKey = getSessionKey((String) session);). However, session key's TTL is 5 minutes after the session actually expires but the each session expiration is also tracked to the nearest minute  after the session actually expires, so when accessing the session key here, the session key never expire actually. Does it need to change to access session expires key, instead of session key?

	public void cleanExpiredSessions() {
		long now = System.currentTimeMillis();
		long prevMin = roundDownMinute(now);

		if (logger.isDebugEnabled()) {
			logger.debug("Cleaning up sessions expiring at " + new Date(prevMin));
		}

		String expirationKey = getExpirationKey(prevMin);
		Set<Object> sessionsToExpire = this.redis.boundSetOps(expirationKey).members();
		this.redis.delete(expirationKey);
		for (Object session : sessionsToExpire) {
			String sessionKey = getSessionKey((String) session);
			touch(sessionKey);
		}
}

**Comment by eleftherias** [comment]
Thanks for bringing this up @atlantisor.
You are correct about the logic problem, although I believe the error is in the `onExpirationUpdated` method, which was fixed via 69285f2a9abe925cd7cdbe0d87fec8d1afdc7af8.
Let me know if you disagree and we can reopen this issue.
