### ISSUE TITLE
Create helicopter view documentation for deciders

### ISSUE THREAD

**Issue by flexguse** [spring-projects/spring-session#138]
Many developers like me need a helicopter view documentation for our bosses to convince them to use Spring Session.

In a small company with agile processes this seems not to be necessary but if you are part of a bigger organisation this kind of documentation is necessary.

The documentation should contain:
- how is the architecture of a standard webapplication and how in a multi application / multi servlet container situation using Spring Session? (chart / diagram, see attached images)

![without spring session](https://cloud.githubusercontent.com/assets/4136568/6037546/0b98c87e-ac55-11e4-863f-294dc0b03e4e.jpg)

![with spring session](https://cloud.githubusercontent.com/assets/4136568/6037552/207675ac-ac55-11e4-9907-43758839d149.jpg)
- are there any security risks by sharing session information across multiple applications
- some performance figures
- some advertisement which is always loved by bosses ;)

**Comment by vpavic** [comment]
Thanks for the suggestion, but I don't think something like this is desirable in Spring Session reference manual as it would both require going into topics (general webapp architecture) that are broader than the core problem Spring Session addressed and be very generic (i.e. we cannot mention Tomcat or Redis as those are just pluggable options) which again wouldn't address the requirement.

In short, this really feels like something that should be done on a per project basis.
