### ISSUE TITLE
RedisSessionExpirationPolicy's cleanExpiredSessions() doesn't remove the session id from Index

### ISSUE THREAD

**Issue by cuckoo3** [spring-projects/spring-session#1395]
RedisSessionExpirationPolicy's cleanExpiredSessions():

	public void cleanExpiredSessions() {
		long now = System.currentTimeMillis();
		long prevMin = roundDownMinute(now);

		if (logger.isDebugEnabled()) {
			logger.debug("Cleaning up sessions expiring at " + new Date(prevMin));
		}

		String expirationKey = getExpirationKey(prevMin);
		Set<Object> sessionsToExpire = this.redis.boundSetOps(expirationKey).members();
		this.redis.delete(expirationKey);
		for (Object session : sessionsToExpire) {
			String sessionKey = getSessionKey((String) session);
			touch(sessionKey);
		}

	}

It only remove the session but not the session key from the index PRINCIPAL_NAME_INDEX_NAME

Since the TTL of the index in Redis is -1, all the expired session key will be kept forever and the index will keep growing in size.

**Comment by yevgenb** [comment]
Will this fix get to 2.4.x branch?

**Comment by vpavic** [comment]
@cuckoo3 I'm afraid I can't reproduce the problem - can you provide more details about the how to reproduce it? A sample app would be most helpful.

Also, did you read the documentation on [events support for `RedisOperationsSessionRepository`](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent) and Redis documentation on [keyspace notifications](https://redis.io/topics/notifications)? Note that with automatic registration (that Spring Session does by default) if you restart Redis server the subscription will be lost, until you restart your application too.

**Comment by cuckoo3** [comment]
@vpavic Thanks for your explanation. I will double check if it's related to the AWS setting for missing the event notification when the session is expired. We are using the cronjob cleanupExpiredSessions() to remove the session before it's expired from the Redis server. However the cronjob didn't remove the session id from the index directly and we are facing a problem in glowing up of the index size.

BTW [1.4.x](https://github.com/spring-projects/spring-session/branches) cannot be built due to the logout.html are using  "https://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd". http should be used instead.

**Comment by vpavic** [comment]
I assume this was a configuration error @cuckoo3?

Regarding `1.4.x`, that's branch is obsolete and we never actually made a release from there.

**Comment by cuckoo3** [comment]
Got following error when I run the verification check on 1.4.x Spring-session-samples-boot-findbyusername:
Error message:
java.io.IOException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Unsupported entity requested with PUBLICID "null" and SYSTEMID "https://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd". Make sure a corresponding org.thymeleaf.doctype.resolution.IDocTypeResolutionEntry implementation is provided by you dialect (login:3)
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'CPX-6WCEMWKRLZJ', ip: '10.129.13.76', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: HtmlUnitDriver

![image](https://user-images.githubusercontent.com/36035082/56341664-5baecc80-61e8-11e9-97e9-34b1a7b57a87.png)

**Comment by cuckoo3** [comment]
For following error when I run the verification check for spring-session-samples-boot-findbyusername at 1.4.x 

java.io.IOException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Unsupported entity requested with PUBLICID "null" and SYSTEMID "https://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-3.dtd". Make sure a corresponding org.thymeleaf.doctype.resolution.IDocTypeResolutionEntry implementation is provided by you dialect (login:3)
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: '', ip: ', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: HtmlUnitDriver

![image](https://user-images.githubusercontent.com/36035082/56342007-6158e200-61e9-11e9-8da0-24f423f7a550.png)
