### ISSUE TITLE
Updating Authorities Stored In RedisSession?

### ISSUE THREAD

**Issue by shanewow** [spring-projects/spring-session#140]
Hi, Great work on this project. I have a webapp that is using @EnableRedisHttpSession. The app loads all of the users granted authorities from a sql instance when they login and stores them in the session. How would I access the session of a particular logged in user (by username) to edit those stored permissions/authorities without the user having to logout/login again to get the new permissions. Essentially what I would like to happen is when an admin changes the permissions of a user the app would check if said user has active session in the Redis repo then, retrieve session, update session and save again so on user's next request they will have the updated authorities in RedisSession. I was thinking I could create another RedisTemplate that stores the SessionID when they login using the user's email/username as the hash or key but I wanted to make sure there wasn't a way of doing this with the existing template and not having to create a second one. Thanks.

**Comment by rwinch** [comment]
Thanks for your interest in Spring Session. Currently Spring Session does not support querying by a user identifier. Please follow #7 and #17 for possible improvements that would make this possible.

That mechanism would likely work. You would need to take into account that sessions can expire. Of course if you get something working, we'd love a pull request!

I'm going to go ahead and close this. If you feel I didn't answer your question, feel free to reopen.
