### ISSUE TITLE
I found the SpringHttpSessionConfiguration and ServletSessionConfiguration conflict

### ISSUE THREAD

**Issue by xiamaohan** [spring-projects/spring-session#1402]
hello,
spring boot >2.1.0
org.springframework.boot.autoconfigure.session.SessionAutoConfiguration.ServletSessionConfiguration
Will construct DefaultCookieSerializer

org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration

`@PostConstruct
	public void init() {
		CookieSerializer cookieSerializer = (this.cookieSerializer != null)
				? this.cookieSerializer
				: createDefaultCookieSerializer();
		this.defaultHttpSessionIdResolver.setCookieSerializer(cookieSerializer);
	}`
createDefaultCookieSerializer() Will not be implemented
rememberMeRequestAttribute is null
SpringSessionRememberMeServices remember me not working

**Comment by vpavic** [comment]
Thanks for the report @xiamaohan!

This is a consequence of Spring Boot being responsible for configuring the `DefaultCookieSerializer` but not having the same remember-me integration aware handling logic - I've opened spring-projects/spring-boot#16513 to address this in Spring Boot so please track that PR.

I'm going to close this one, we can re-open later if needed depending on the outcome of Boot PR.
