### ISSUE TITLE
Session Attribute is only persisted once with JdbcOperationsSessionRepository.

### ISSUE THREAD

**Issue by joselfreire** [spring-projects/spring-session#1405]
Environment:
* Tomcat 7.0.92
* MyFaces 2.2.9
* Spring Session 1.3.5.RELEASE
* Spring 4.3.23.RELEASE
* JDK Amazon Correto 8.202

When evaluating the viability to use spring-session I noticed that the session attributes of my JSF application were persisted when they were first accessed (created), and then they would "freeze" in time, no longer being updated.

I only tested with `JdbcOperationsSessionRepository` which is the only option for me.

After some analysis I noticed that for an attribute state to be updated in the database it's required that `putAttribute()` is invoked, and being a session attribute whose **reference** never changes (only the **content**), `putAttribute()` is never invoked and the current state is lost since it's never persisted.

I'm not sure what the correct behaviour is, but shouldn't we assume that every session attribute content that is requested from the session has changed, and thus should be persisted?

To work around this issue I've implemented that behaviour by adding the session attribute to the delta map:

NOTE: This code applies to version 1.3.5, but I guess a similar approach is needed for the latest version.

```
public <T> T getAttribute(String attributeName) {
	T attributeValue = this.delegate.getAttribute(attributeName);
	/*
	 * We must assume that the content will change if requested.
	 */
	this.delta.put(attributeName, attributeValue);
	return attributeValue;
}
```
It appears to be working correcly now, but I'm not sure I took the correct approach.

**Comment by vpavic** [comment]
I'm not sure what method exactly were you referring by `putAttribute()`, but if that's `javax.servlet.http.HttpSession#setAttribute`, then answer is yes - you have to make session aware of updated attributes. This is in contrast with in-memory based session management, where you usually deal with a single instance of session object whereas with external session store you're dealing with object that are actually copies.

Another aspect are write optimizations that are here to both improve performance and reduce the possibility of race conditions, that's why we use delta to track only the changed attributes.

**Comment by joselfreire** [comment]
Yes, I was referring to `javax.servlet.http.HttpSession#setAttribute`, that I believe is implemented in `JdbcOperationsSessionRepository$JdbcSession#setAttribute`.

My reason to opening an issue is that a JavaServer Faces application (at least with MyFaces implementation), doesn't invoke `setAttribute` on every session scoped object on every request, and I think the reference implementation of JavaServer Faces doesn't do it either. This makes spring-session incompatible with a JavaServer Faces application (that uses session scope anyway), which is unfortunate because I think there's real potential with joining the two.

One way to work-around this issue would be to 'touch' *every* session object by setting it in the session on every request, but that would defeat the purpose of having a `delta` map, and all the session objects would be persisted on every request, even if they weren't needed for that request.

My little 'hack' on `JdbcOperationsSessionRepository$JdbcSession#getAttribute`, by adding the accessed session attribute to the delta map makes it possible to use JavaServer Faces applications with spring-session, and that I believe it's of great value.

Or am I thinking this wrong?

**Comment by vpavic** [comment]
I see. We might consider providing a configuration option to disable use of delta for writes. There's also some related discussion in #311. I'll discuss this with @rwinch.

**Comment by joselfreire** [comment]
A configuration option would be great, but I wouldn't go as far as disable the use of delta for writes, because I find it a very clever optimization mechanism.

Unless the configuration option would be something like:
* STRICT (default) - The current behavior. Attributes must be deliberately set in session to be persisted (by monitoring `setAttribute()`);
* LENIENT - My 'hack'. STRICT plus the attributes that are accessed in the request (by monitoring `getAttribute()`);
* FULL - All attributes are persisted in every request.

**Comment by dimaopen** [comment]
Another issue with this approach that Session Scoped beans cannot be stateful. But in this case there's no much sense in them.
I think the Spring users got used to the model when session scoped beans share their state within the user session.

**Comment by candrews** [comment]
> * STRICT (default) - The current behavior. Attributes must be deliberately set in session to be persisted (by monitoring `setAttribute()`);
> 
> * LENIENT - My 'hack'. STRICT plus the attributes that are accessed in the request (by monitoring `getAttribute()`);
> 
> * FULL - All attributes are persisted in every request.

I like this idea. I currently use a servlet filter to work around this issue; see https://github.com/spring-projects/spring-session/issues/648#issuecomment-388057938

Note that using this filter (which does what "LENIENT" describes) results in a lot of writes and can be very detrimental to performance. I suggest https://github.com/spring-projects/spring-session/pull/1071 be reconsidered if this configuration is added.

**Comment by vpavic** [comment]
We're going to take a look at this for `2.2.0.M3`. I've opened #1466.

**Comment by vpavic** [comment]
We're going with `SaveMode` that will be defined as:

```java
public enum SaveMode {

	/**
	 * Save only changes made to session, for instance using
	 * {@link Session#setAttribute(String, Object)}. In highly concurrent environments,
	 * this mode minimizes the risk of attributes being overwritten during processing of
	 * parallel requests.
	 */
	ON_SET_ATTRIBUTE,

	/**
	 * Same as {@link #ON_SET_ATTRIBUTE} with addition of saving attributes that have been
	 * read using {@link Session#getAttribute(String)}.
	 */
	ON_GET_ATTRIBUTE,

	/**
	 * Always save all session attributes, regardless of the interaction with the session.
	 * In highly concurrent environments, this mode increases the risk of attributes being
	 * overwritten during processing of parallel requests.
	 */
	ALWAYS

}
```

Closing this one in favor of #1466, as we'll handle the support for all the data stores there so please track that issue for future developments. Thanks for the report and discussion around this @joselfreire.
