### ISSUE TITLE
Secure flag of CookieHttpSessionStrategy 

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#141]
CookieHttpSessionStrategy is currently fixing secure flag of cookie by request. If user tries to redirect after a `https login page` -> `http page`, this will cause an unwanted surprise. 

Please provide an option to be set by user.

For those who are interested in this issue, @rwinch explained and gave some wonderful insights and please be careful such configurations at production. see SEC-2799 for more.

**Comment by cemo** [comment]
There is another todo for `set domain` as well. Maybe a customizer for cookie would be ideal.

**Comment by rwinch** [comment]
Thanks for the great request! I'm trying to aggregate all the feature requests for cookies, so we can solve this problem more holistically. Therefore, I'm closing this in favor of #299 which takes this feature into account.

**Comment by rwinch** [comment]
This is now resolved via #299 See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html for details.
