### ISSUE TITLE
Ensure compatibility with Java 12

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1422]

**Comment by vpavic** [comment]
It seems that `jdk12` is not available on Jenkins - @trevormarshall can you do anything about that?

With Java 12 being GA I think we should be able to ensure we are compatible.

/cc @rwinch

**Comment by trevormarshall** [comment]
Might be the label - Look for `openjdk12` in Jenkins, it is there.

**Comment by gregturn** [comment]
If you shift to a Docker based approach then JDK 12 is very easy to attain.

**Comment by vpavic** [comment]
> Might be the label - Look for `openjdk12` in Jenkins, it is there.

That worked - thanks!

> If you shift to a Docker based approach then JDK 12 is very easy to attain.

That would be ideal, but timewise too big of an effort ATM.
