### ISSUE TITLE
New session is created on unavailable pages (404)

### ISSUE THREAD

**Issue by heyarny** [spring-projects/spring-session#1430]
### Summary

I'm using sessions with redis enabled which all works great.
I started to notice that my client started losing sessions when accessing to 404 pages.
There are different sessions created with the same session-name and thus my client is having an invalid session when going back to a valid url.

I have a custom ErrorController which simply displays any error in the format needed for my application.

### Actual Behavior

My sessions look like this when accessing any valid URL:
YmFkZGRlMDMtZjdlMi00NzhjLWEzMWEtY2E3NmViNGU4MGUz

This is what I get when accessing any unavailable URL:
node0c0u0x7la04eb1h2057sm64t6b2.node0

Looks like the embedded server is overwriting sessions all of a sudden?

### Expected Behavior

Sessions should be the same on invalid pages as well.

### Configuration

Using Spring-Boot 2.1.4.
Redis enabled.
Jetty embedded server. (Tomcat is having the same issue)

**Comment by rwinch** [comment]
I'm closing this as a duplicate of gh-1308

**Comment by heyarny** [comment]
I see you've marked it as duplicate, but the other issue seems to be jetty-only.
I've tested the same example with tomcat and had the same issues.
This bug is not jetty-only issue.

**Comment by rwinch** [comment]
If I use tomcat in the sample you provided and access `/nothere`, I get the following cookie:

```
HTTP/1.1 404 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: en-US
Content-Length: 10
Content-Type: application/json;charset=UTF-8
Date: Fri, 17 May 2019 21:23:57 GMT
Expires: 0
Pragma: no-cache
Set-Cookie: sid=ZGY5MmUxMzctZmFkYy00NzBhLTg4ZTktMTVhNjgxZTFiY2Qw; Path=/; HttpOnly; SameSite=Lax
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

jsp test
```

The session id is formatted like spring session's id and it is marked as `SameSite=Lax`. This means that Spring Session is in control of the session on the error pages in Tomcat.

Are you experiencing something else?

**Comment by heyarny** [comment]
Oh, you're right. Just ran with tomcat and works as expected.
I though I had the same results with tomcat.

Ok, let's leave it here.
Thanks for your time.
