### ISSUE TITLE
Any plans to support ElasticSearch

### ISSUE THREAD

**Issue by aekoise** [spring-projects/spring-session#1448]
For folks already leveraging ElasticSearch, it will be nice to have Spring Session support ElasticSearch. Any plans to support ElasticSearch?

**Comment by vpavic** [comment]
There are no imminent plans to add support for new data stores, however we do encourage community to provide 3rd party extensions and we promote those via [Community Extensions](http://docs.spring.io/spring-session/docs/current/reference/html5/#community-extensions) section of the reference manual.
