### ISSUE TITLE
Make HazelcastSession public for HazelcastSessionRepository interaction

### ISSUE THREAD

**Issue by BenDol** [spring-projects/spring-session#1457]
I would like to query/interact with the `HazelcastSessionRepository` for some session management services, but unfortunately `HazelcastSession` is protected so I am unable to reference it.

Seems like this is an oversight? Let me know if there is something that I'm missing.

Cheers!

**Comment by vpavic** [comment]
We consider concrete `Session` implementations, such as `HazelcastInstance`, to be an internal implementation detail of parent `SessionRepository` implementation. The only API to interact with the session is `org.springframework.session.Session`.

Can you provide an example of concrete problem you're facing? Is it perhaps a similar situation like [this one](https://github.com/spring-projects/spring-session/issues/849#issuecomment-321742866)?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
