### ISSUE TITLE
Support for sticky sessions

### ISSUE THREAD

**Issue by Thilak-T** [spring-projects/spring-session#146]
It would be great if spring-session supports sticky sessions and optimizations aroud it, as we need this feature for our production deployment. Willing to put effort for this project if needed. Thanks

**Comment by chrylis** [comment]
What exactly do you mean by sticky sessions? That's usually an issue for the load balancer.

**Comment by Thilak-T** [comment]
I mean a way to tell spring-session that the app uses sticky session concept, so that the app primarily read-write on local session object and a replica is maintained on redis for fail-over. If the local session object is lost for some reason, spring-session tries to get from redis.

**Comment by rwinch** [comment]
This is a duplicate of #6
