### ISSUE TITLE
Numerous sessions are created because of crawlers

### ISSUE THREAD

**Issue by Thilak-T** [spring-projects/spring-session#147]
We have been testing the app behind a load balancer and found numerous sessions are created. Because the load balancer pings the app for every 30 sec and doesn't maintain any cookie state information, resulting in a new session every 30 sec. Is it possible to have something similar to Tomcat's Crawler Session Manager Valve

http://tomcat.apache.org/tomcat-7.0-doc/config/valve.html#Crawler_Session_Manager_Valve

**Comment by rwinch** [comment]
It sounds as though the load balancer is what is creating all the `HttpSession`s? If that is the case, can you setup the load balancer to hit a page that does not use the `HttpSession`?

**Comment by rwinch** [comment]
If you are interested in something like Tomcat's Crawler Session Manager Valve, please create a ticket to track that. I'm not guaranteeing we will create it, but it is best to have a distinct ticket to keep track of interest.

**Comment by rwinch** [comment]
Closing as this question appears to be answered (i.e. have the load balancer hit a page that does not create a session)
