### ISSUE TITLE
How to control concurrent httprequest on the same session?

### ISSUE THREAD

**Issue by hhfdna** [spring-projects/spring-session#1471]
Here is our situation:
We use Redis as backed session repository. configured bean RedisHttpSessionConfiguration in spring context.
When browser submits concurrent http requests  with same sessionId(we have this senario),  one request  set a session attribute, say, 
`session.setSessionAttribute("key1","value1");`
while, another request set another attribute, say,
` session.setSessionAttribute("key2","value2");`

after two requests are completed, only the second attribute is saved in redis. It seems like the second session cache overrides the first one. Here is my opinion after check the source code:
The two requests retrieved session from redis at first , but with different caches respectively,
then application does their business ,update session, and so on.
at the end, SessionRepositoryFilter committed session to redis, and the sencond cache override the first one.

is that make sense?

To verify this problem, we changed our frontend behavior to submit request once at a time, the session is fine

We try to fix this by adding synchronization on session,  it turns out we must modify SessionRepositoryFilter's doFilterInternal() method, something like follows:
`	synchronized(session)
               try {
			filterChain.doFilter(wrappedRequest, wrappedResponse);
		}
		finally {
			wrappedRequest.commitSession();
		}
`
further more, in cluster env, a distributed Lock ,for example, redisson, should be used.

if any reply , i'll be very appreciated!

**Comment by hhfdna** [comment]
The obstacle is many class in spring-session  is package or private, we can't reference them in subclass.

**Comment by vpavic** [comment]
Thanks for the report @hhfdna.

> When browser submits concurrent http requests with same sessionId(we have this senario), one request set a session attribute, say,
`session.setSessionAttribute("key1","value1");`
while, another request set another attribute, say,
`session.setSessionAttribute("key2","value2");`
>
> after two requests are completed, only the second attribute is saved in redis. It seems like the second session cache overrides the first one.

This shouldn't be happening as `RedisOperationsSessionRepository` tracks only delta of changes exactly to avoid this situation. By doing that, each request should only write the attributes it changes so nothing should be overwritten by concurrent request.

Can you provide a sample that exhibits this behavior?

**Comment by hhfdna** [comment]
sorry, the actually situation is like this,
request-1:   
`
Map data = session.getAttribute("dataKey");
data.put("key1","value1");
session.setAttribute("dataKey", data);
`
request-2:
`
Map data = session.getAttribute("dataKey");
data.put("key2","value2");
session.setAttribute("dataKey", data);
`
At the end,  only key2-value2 pair existed in redis under the key "dataKey"

**Comment by hhfdna** [comment]
Above is just an example using hashMap object.It's same for any customer class object.
 Essentially, how to control concurrent http requests modify the same object under the same session key is the point.

**Comment by vpavic** [comment]
Thanks for clarifying @hhfdna. This is a quite different situation and our delta based handling of attribute changes cannot help here. Is it possible for you to decompose the data you store in the session? Complex data structures are always trickier to handle.

**Comment by hhfdna** [comment]
Gotcha. It's difficulty to decompose all customer class. for a simplest Class:
`
public class Counter{
    private int counter;
    public void increase(){
         this. counter = this.counter+1;
     }
}
`
Concurrent requests will get wrong state when invoking increase()  and save counter object under session key.  It's impossible to modify all business logic.
At present, we figured out a solution, mentioned above, is to synchronize on session based on a distributed lock, how do u think? is that ok?

**Comment by hhfdna** [comment]
I extend SessionRepositoryFilter, overide doFilterInternal() method, as follows
```java
Public class MySessionRepositoryFilter extends SessionRepositoryFilter{
....
@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {

   if (synchronizeOnSession) {
       String sessionId = httpSessionStrategy.getRequestedSessionId(request);
       RLock lock = redisson.getLock(sessionId);
       try {
           if (lock.tryLock(timeout, TimeUnit.MILLISECONDS)) {
               try {
                   super.doFilterInternal(request, response, filterChain);
               } finally {
                   lock.unlock();
               }
           } else {
               throw new ServletException(String.valueOf(HttpServletResponse.SC_GATEWAY_TIMEOUT));
           }
       } catch (InterruptedException e) {
           throw new ServletException(String.valueOf(HttpServletResponse.SC_SERVICE_UNAVAILABLE));

       }
   } else {
       super.doFilterInternal(request, response, filterChain);
   }
}
....
}
```

and configured this Filter in web.xml instead of springSessionRepositoryFilter which is exposed by default.
It seems work well

**Comment by vpavic** [comment]
The counter example you provided looks like something I'd actually keep in some other store, rather than in session - that way you'd model increment as atomic operation against that other store. Handling this as session attribute, with externalized session store and concurrent requests is very tricky.

Locks in general, and especially distributed ones, are quite expensive and by resorting to that approach isn't something I'd recommend. Definitely not something we'd be willing to do in Spring Session.

**Comment by hhfdna** [comment]
Get it. It's a typical get-update-set scenario in multi-thread programing.
Your recommendation is very useful for us.
Thank you very much

**Comment by vpavic** [comment]
Thanks for the feedback @hhfdna. Closing this and marking as question.
