### ISSUE TITLE
Spring websession's CSRF with Redis fails with JSON serialization

### ISSUE THREAD

**Issue by apuravchauhan** [spring-projects/spring-session#1478]
### Spring websession with Redis fails with the attached exception. Below is the project config:

```
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
@EnableRedisWebSession 
public class WebfluxConfig implements BeanClassLoaderAware {

	private ClassLoader loader;

	@Bean
	public RedisSerializer<Object> springSessionDefaultRedisSerializer() {
		return new GenericJackson2JsonRedisSerializer(objectMapper());
	}

	private ObjectMapper objectMapper() {
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerModules(SecurityJackson2Modules.getModules(this.loader));
		return mapper;
	}

	@Override
	public void setBeanClassLoader(ClassLoader classLoader) {
		this.loader = classLoader;
	}

	@Bean
	public MapReactiveUserDetailsService userDetailsService() {
		User.UserBuilder userBuilder = User.withDefaultPasswordEncoder();
        UserDetails rob = userBuilder.username("rob")
            .password("rob")
            .roles("USER")
            .build();
        UserDetails admin = userBuilder.username("admin")
            .password("admin")
            .roles("USER","ADMIN")
            .build();
        return new MapReactiveUserDetailsService(rob, admin);
	}
	@Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange()
                .anyExchange().authenticated()
                .and()
            .httpBasic().and()
            .formLogin();
       	// http.csrf().disable();
        return http.build();
    }
	@Bean
	public LettuceConnectionFactory redisConnectionFactory() {
		return new LettuceConnectionFactory(); 
	}
}
```

#### If you disable csrf then things work fine.

Maven:

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.6.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>apuravsecurity</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>apuravsecurity</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis-reactive</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-data-redis</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

[exception-spring-redis-websession.log](https://github.com/spring-projects/spring-session/files/3418336/exception-spring-redis-websession.log)

**Comment by apuravchauhan** [comment]
@rwinch Any help or pointers will be appreciated. : )

**Comment by apuravchauhan** [comment]
@vpavic Thanks for looking into this. Let me know if I can help with any more information

**Comment by vpavic** [comment]
Thanks for the report @apuravchauhan, I've reproduced the problem.

This is due to Spring Security 5.1 not having WebFlux support for Jackson modules - this was added in Spring Security `5.2.0.M1` via spring-projects/spring-security#6305.

I've verified this in a sample project by upgrading Spring Security version to the latest 5.2 milestone (which is `5.2.0.M3` ATM).
