### ISSUE TITLE
OnCommittedResponseWrapper fails on static resources served by Tomcat 8.5

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-session#1489]
Related to https://github.com/spring-projects/spring-security/issues/7261

**Comment by jzheaux** [comment]
Spring Security's similar commit: https://github.com/spring-projects/spring-security/commit/1a233a58c77aacac2e44d418f51acc4c6e160955

**Comment by vpavic** [comment]
Thanks @jzheaux. Did you consider backporting this to `2.1.x`? From the description, it sounds more like a bug than an enhancement to me.

**Comment by jzheaux** [comment]
Going point, @vpavic, I'll make sure it gets backported. I'll also reclassify this as a bug.

**Comment by vpavic** [comment]
Thanks for confirmation - I've backported via #1490.
