### ISSUE TITLE
Embedded Redis fails to work on WildFly

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#150]
http://stackoverflow.com/questions/28569395/redis-error-in-spring-session-sample-using-maven-and-spring-boot

**Comment by danyunfu** [comment]
I have the same error on Tomcat

**Comment by rwinch** [comment]
@danyunfu Thanks for the report. Can you provide any additional details so I can reproduce it? How are you deploying it to Tomcat? Which version of Tomcat are you using? Are you just running it using Spring Boot and Gradle?

**Comment by danyunfu** [comment]
Maven+Spring Boot, Tomcat 8.0.12, deployed as a jar via Maven build, I tried embedded Redis 0.5 and 0.4. I'm also Windows (I noticed some of your other issues with embedded Redis may be a Windows issue?)

**Comment by kstyrc** [comment]
@danyunfu you couldn't use embedded redis 0.5, as it got release just today -,- It includes an update for windows binary to 2.8.19

**Comment by rwinch** [comment]
@danyunfu  Thanks for the feedback. Unfortunately, it appears that support embedded Redis support is not feasible at this point. This means we are changing all our samples to use an external Redis instance. See the discussion in https://github.com/spring-projects/spring-session/issues/121 for details
