### ISSUE TITLE
Support firing SessionDestroyedEvent on deletion in MapSessionRepository

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-session#151]
This would be useful so that MapSessionRepository can work correctly with web sockets. We currently have to use our own implementation.

In #4 you mention that MapSessionRepository is typically only used when testing since it cannot be clustered. However, is a simple single server system where clustering isn't a requirement not a valid use case?

If resource is an issue I could probably work on a PR.

**Comment by rwinch** [comment]
My concerns with doing this are:

* If a user uses a distributed map implementation, then they will likely expect that the event is fired on each node (like the Redis implementation)
* We would also need to ensure the SessionDestroyedEvent is fired when a session expires

**Comment by manderson23** [comment]
For your first point is it really realistic to support distributed maps generally in this way? It could be made clear in the javadoc. In the future we may look at using Hazelcast for clustering but I honestly wouldn't expect to be able to drop a map into the constructor and have it work flawlessly. 

Expiry is an issue though for now in our implementation we periodically check for expired entries and delete if required. Out of interest how does the Redis implementation handle expiry?

**Comment by gdelprete** [comment]
For what is worth, I'd like to vote this up, to keep consistency between SessionRepository implementations. Also, while documentation points out that RedisOperationsSessionRepository implements this behavior in the API section, no mention of it is in the WebSocket chapter. So I'd suggest to also improve documentation.

**Comment by manderson23** [comment]
@rwinch thinking about this more I'm not sure it would add much benefit. It isn't that hard to add this myself though maybe as @gdelprete suggests the documentation in relation to web sockets could be improved.

In the discussion above we mentioned distributed map implementations. I've recently starting porting the Spring Security example to use Hazelcast so am looking into handling expiry etc. I noticed the following in the Hazelcast javadoc for IMap
```
get method returns a clone of original values, modifying the returned value does not 
change the actual value in the map. One should put the modified value back to make
changes visible to all nodes. For additional info see get(Object). 
```
Is this behaviour compatible with how Spring Session uses the MapSessionRepository? (Not sure if there would have been a better place to ask this).

**Comment by manderson23** [comment]
From my experience of putting together a Hazelcast example that includes expiry I'm happy to close this. 

Maybe the web socket documentation could be improved to make this explicit. Another option would be adding a sample or some additional documentation for MapSessionRepository to show how firing SessionDestroyedEvent can be added. As I said I've done it myself and it isn't hard.
