### ISSUE TITLE
Improve Hazelcast client-server topology integration tests

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1527]
Instead of providing Hazelcast server config via system properties in our client-server topology integration tests, we could simplify things by copying config file to default location thus overriding the default one provided in the container.

This will also help us with adopting to changes from testcontainers/testcontainers-java#1814, that are preventing us to upgrade to Testcontainers `3.12.1+`.

**Comment by bsideup** [comment]
@vpavic wait... did https://github.com/testcontainers/testcontainers-java/pull/1814 break your code? o_O

It was supposed to be a backward-compatible change and, if it did, it sounds like a regression! 😨

**Comment by vpavic** [comment]
Yep, I've just left a comment there.
