### ISSUE TITLE
why RedisSessionExpirationPolicy#onDelete remove something not exist in the expirations SET?

### ISSUE THREAD

**Issue by Alwayswithme** [spring-projects/spring-session#1531]
the spring:session:expirations:${roundUpToNextMinute}  redis SET is store value call keyToExpire:
```
		String expireKey = getExpirationKey(toExpire);
		BoundSetOperations<Object, Object> expireOperations = this.redis.boundSetOps(expireKey);
		expireOperations.add(keyToExpire);
```
the keyToExpire is a string like expires:${sessionId}
https://github.com/spring-projects/spring-session/blob/927008bdc89701555f2f8f900f4f898df23b1476/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionExpirationPolicy.java#L97

however, when delete the session, it actually remove the session id not expires:${sessionId}
```
	this.redis.boundSetOps(expireKey).remove(session.getId());
```

https://github.com/spring-projects/spring-session/blob/927008bdc89701555f2f8f900f4f898df23b1476/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionExpirationPolicy.java#L70

Is this a defact or My misunderstanding?

**Comment by vpavic** [comment]
The behavior of session expiration handling for Redis session repository is described both in the `RedisOperationsSessionRepository` javadoc and [reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-storage).

Are you experiencing any particular issue here?

**Comment by Alwayswithme** [comment]
org.springframework.session.data.redis.RedisOperationsSessionRepository#delete will delete the expireKey,

**Comment by Alwayswithme** [comment]
@vpavic please take a look

**Comment by eleftherias** [comment]
Thanks for the report @Alwayswithme. 
I'm going to close this issue as a duplicate of gh-585.
Please follow gh-585 for updates.
