### ISSUE TITLE
session cant be created after invalidate the old one

### ISSUE THREAD

**Issue by hhfdna** [spring-projects/spring-session#1540]
in our project, we do the followings during user logging in
`
logger.debug(session.getId());
Session.invalidate();
Session=Request.getSession();
logger.debug(session.getId());
`
We expect to invalidate the old session and create a new one, but it turns out the old session is retrieved again, seems like invalidate() method doesn’t work.
Our environment is spring session1.3.3. Backed by redis.
Is there anything wrong? If any reply,I’ll be very appreciate

**Comment by hhfdna** [comment]
@vpavic can you offer any surggestion？

**Comment by vpavic** [comment]
@hhfdna, please note that `1.3.x` line is EOL, so you should really update to Spring Session `Bean`/`2.1.x` or newer.

Regarding the problem, it's really hard to diagnose with the information you've provided. A statement like _seems like invalidate() method doesn’t work_ could mean a number of different things. Please provide a sample app that reproduces the problem so that we can get a better sense what's going on.

**Comment by hhfdna** [comment]
I checked and compared the source code of SessionRepositoryFilter 1.3.3 with 2.*
the main differences is the invalidate() method and getSession method:

![image](https://user-images.githubusercontent.com/29792169/67665441-afbf1880-f9a4-11e9-877a-6246bb5ba289.png)

![image](https://user-images.githubusercontent.com/29792169/67665522-d54c2200-f9a4-11e9-8d0f-880e462d58d3.png)

the problem is produced in this senario:
User logged in and logged out immiediately,  and logged in,then logged out, and so on,
after about ten times, new session can't be created, old session is returned
![IMG_9698](https://user-images.githubusercontent.com/29792169/67666773-789e3680-f9a7-11e9-9465-8983a64def87.JPG)
![IMG_9699](https://user-images.githubusercontent.com/29792169/67666776-7936cd00-f9a7-11e9-94df-c19042dde542.JPG)

**Comment by hhfdna** [comment]
Problem solved. It turns out that the clocks of the machines where app host on is not in sync.
and ON_SAVE option will not  flush the lastAccessedTime attribute into redis.
spring use local machine's time to check if session is valid:
`
public boolean isExpired() {
	return isExpired(System.currentTimeMillis());
}

boolean isExpired(long now) {
	if (this.maxInactiveInterval < 0) {
		return false;
	}
	return now - TimeUnit.SECONDS
			.toMillis(this.maxInactiveInterval) >= this.lastAccessedTime;
}
`

**Comment by vpavic** [comment]
Thanks for letting us know. Glad you had it resolved.
