### ISSUE TITLE
"PRINCIPAL_NAME_INDEX_NAME" How to create multiple indexes？

### ISSUE THREAD

**Issue by KevinBlandy** [spring-projects/spring-session#1549]
### SpringBoot - Version
```
2.2.1.RELEASE
```
### I want to create two or more indexes. Like this
```java
// loginUser
User user = ...
HttpSession httpSession = request.getSession(Boolean.FALSE);
httpSession.setAttribute(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, user.getId() + "");
httpSession.setAttribute(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, "all_session");
```
The same user may log in to different clients and have different sessions. I want to index based on the user's ID. At the same time, I also need another index that contains all user sessions.

**Thanks**

**Comment by heeropunjabi** [comment]
@spring-issuemaster any update on the above query ?

**Comment by rwinch** [comment]
As of Spring Session 2.2.0, you can inject a custom `IndexResolver` See gh-1467
