### ISSUE TITLE
Can I use spring session to store session in two redis instances?

### ISSUE THREAD

**Issue by rohitkrishna094** [spring-projects/spring-session#1552]
From what I understand `@EnableRedisHttpSession` uses redis for storing sessions. So when user logs in for the first time, their session is stored in redis. The second time they login, the security context is built by reading the session cookie and then getting userdetails from corresponding redis instance.

Now my use case is that when writing userdetails to redis, I want to be able to write not only to primary redis instance, but also a duplicate redis. Can this be done with any annotations or should I do this manually? If manually, whats the right place to do it? In Controller or in some filter?

**Comment by rohitkrishna094** [comment]
I have also posted a question for this use case on stackoverflow here.

https://stackoverflow.com/questions/59160099/is-it-possible-to-store-session-in-two-different-stores-using-spring-session-and

**Comment by rohitkrishna094** [comment]
I want to know which class or method is responsible for storing data into redis when `@EnableRedisHttpSession` is used. I have a breakpoint on `SessionRepositoryFilter`'s `doFilterInternal` method, but I am unable to figure out where in the filterchain spring is storing the session into redis. 

I was wondering to see if I could hook into the code and understand how this is being done. Does anyone which all classes take part in saving to redis when `@EnableRedisHttpSession` is enabled? I am assuming some `RedisTemplate` (or similar) methods must be called right? which class exactly? Not much documentation is available for this. Thanks

**Comment by hugbgithub** [comment]
> I was wondering to see if I could hook into the code and understand how this is being done. Does anyone know which all classes take part in saving to redis when `@EnableRedisHttpSession` is enabled? I am assuming some `RedisTemplate` (or similar) methods must be called right? which class exactly? Not much documentation is available for this. Thanks
Redis session storing is made in the RedisIndexedSessionRepository.java.  Why do you need to store data in two redis instance ?  I think Redis master-slave duplication mechanism should meet your need.

**Comment by rwinch** [comment]
>
