### ISSUE TITLE
Increase visibility of RedisSession inner class in order to write custom behavior

### ISSUE THREAD

**Issue by Stoony** [spring-projects/spring-session#1553]
Hi,

I'm facing some issues with the default behavior of the spring-session-data-redis module which doesn't manage redis unavailability with a fallback strategy for example. I need to extend the RedisIndexedSessionRepository class in order to implement the desired behavior but I can't achieve this because some methods (save) signature use the RedisSession type and this one has got a package visibility only.

I also need to override the SessionRepositoryFilter class which requires the RedisSession type to be given as generic argument and led to the same issue.

Is it possible to set the visibility of the class RedisSession to public so we can use a custom implementation of the session repository staying with the use of standard annotations and session object to enable redis http session.

Thank by advance for considering this problem, I'd like to avoid to duplicate the entire module in my app to write the needed features.

**Comment by eleftherias** [comment]
@Stoony Could you use composition instead of inheritance?
For more details and examples take a look at these issues: #1217 and #849.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
