### ISSUE TITLE
Updating from 2.1.X to 2.2.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [spring-projects/spring-session#1558]
When I try to upgrade spring-session-data-redis from 2.1.X to 2.2.0. The following code breaks.
```
public class Demo{
	
	private int page;
	private int size;
	private Sort sort;
	
	public Demo(int page, int size, Direction direction, String... properties) {

		this(page, size, new Sort(direction, properties));
	}

	public Demo(int page, int size, Sort sort) {

		if (0 > page) {
			throw new IllegalArgumentException("Page index must not be less than zero!");
		}

		if (0 >= size) {
			throw new IllegalArgumentException("Page size must not be less than or equal to zero!");
		}

		this.page = page;
		this.size = size;
		this.sort = sort;
	}

}
```

The code should pass, but it throws an error:
```
Demo.java:[15,54] incompatible types: java.lang.String[] cannot be converted to java.util.List<java.lang.String>
```

**Comment by vpavic** [comment]
It's not clear how is this related to Spring Session, could you clarify?

Assuming `Direction` and `Sort` are the ones from Spring Data's web support, this appears to be related to Spring Data.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
