### ISSUE TITLE
Inaccurate note on custom cookie sample index page

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-session#1559]
After running the application, on the index page there is a note that states:
>  Notice that there is no JSESSIONID cookie.

However, in this example we customize the cookie name to be "JSESSIONID".

The above statement should be removed from the custom cookie sample.

**Comment by vpavic** [comment]
@eleftherias Could you backport this to `2.1.x`?

**Comment by eleftherias** [comment]
@vpavic Yes, it's done.
