### ISSUE TITLE
Why cleanupCron is null? 

### ISSUE THREAD

**Issue by kdevkr** [spring-projects/spring-session#1581]
**build.gradle**
```gradle
plugins {
    id 'org.springframework.boot' version '2.2.4.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'java'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'io.lettuce:lettuce-core'
}
```

I'm using spring-boot so, run application but it throw `IllegalArgumentException` from `SessionCleanupConfiguration`

**Debug Console**
```sh
java.lang.IllegalArgumentException: Cron expression must consist of 6 fields (found 0 in "null")
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:273) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:98) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:85) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:45) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.scheduling.config.CronTask.<init>(CronTask.java:42) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.scheduling.config.ScheduledTaskRegistrar.addCronTask(ScheduledTaskRegistrar.java:276) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$SessionCleanupConfiguration.configureTasks(RedisHttpSessionConfiguration.java:362) ~[spring-session-data-redis-2.2.0.RELEASE.jar:2.2.0.RELEASE]
```

I'm checked by auto-configure.

- RedisAutoConfiguration is import LettuceConnectionConfiguration, so apply RedisConnectionFactory bean.
- SessionAutoConfiguration bean is registered after RedisAutoConfiguration is registered
- RedisSessionConfiguration bean is registered if RedisConnectionFactory exists
- SpringBootRedisHttpSessionConfiguration in RedisSessionConfiguration registered

But, `SpringBootRedisHttpSessionConfiguration` uses RedisSessionProperties
```java
@Configuration
	public static class SpringBootRedisHttpSessionConfiguration extends RedisHttpSessionConfiguration {

		@Autowired
		public void customize(SessionProperties sessionProperties, RedisSessionProperties redisSessionProperties) {
			Duration timeout = sessionProperties.getTimeout();
			if (timeout != null) {
				setMaxInactiveIntervalInSeconds((int) timeout.getSeconds());
			}
			setRedisNamespace(redisSessionProperties.getNamespace());
			setFlushMode(redisSessionProperties.getFlushMode());
			setSaveMode(redisSessionProperties.getSaveMode());
			setCleanupCron(redisSessionProperties.getCleanupCron());
		}

	}
```

I declared @EnableRedisHttpSession in Configuration class.
Then it runs successfully. 😐
```java
@Configuration(proxyBeanMethods = false)
public class SessionConfig {

    @EnableRedisHttpSession
    @Configuration(proxyBeanMethods = false)
    public static class RedisSessionConfig {

    }
}
```

I don't understand this situation. 🤔 
simply @EnableRedisHttpSession import RedisHttpSessionConfiguration.

 Please explain what went wrong.

**Comment by chetanbaheti** [comment]
I see the same issue happening, on debugging this I found that in [RedisHttpSessionConfiguration.java](https://github.com/spring-projects/spring-session/blob/2.3.x/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java):
```
        @EnableScheduling
	@Configuration(proxyBeanMethods = false)
	class SessionCleanupConfiguration implements SchedulingConfigurer {

		private final RedisIndexedSessionRepository sessionRepository;

		SessionCleanupConfiguration(RedisIndexedSessionRepository sessionRepository) {
			this.sessionRepository = sessionRepository;
		}

		@Override
		public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
			taskRegistrar.addCronTask(this.sessionRepository::cleanupExpiredSessions,
					RedisHttpSessionConfiguration.this.cleanupCron);
		}

	}
```
In `RedisHttpSessionConfiguration.this.cleanupCron`, this points to a cglib proxy and `this.cleanupCron` comes up as null during startup.

**Comment by rwinch** [comment]
Can you please provide a sample of the issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by chetanbaheti** [comment]
I was extending the class RedisHttpSessionConfiguration to provide my own serializer and redis namespace. This got resolved  When I changed it to inject the serializer and use the customizers to set namespace, instead of extending the clas

**Comment by kdevkr** [comment]
feedback's too late. so, i cannot remember issue...
now, i'm use custom `RedisIndexedSessionRepository`.
so, i'm not use default RedisSessionConfiguration by @ConditionalOnMissingBean(SessionRepository.class)

**Comment by rwinch** [comment]
@chetanbaheti Can you please provide a complete working example?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
