### ISSUE TITLE
Session Cookie should be deleted on expired/invalid Session / InfiniteLoop

### ISSUE THREAD

**Issue by domdorn** [spring-projects/spring-session#159]
Right now, if the user accesses the webapp with an invalid Session cookie (e.g. by tampering, using an expired cookie or because of a wrong path in the cookie), the webserver redirects to the expired session url (when using Spring Security). 

Additionally to redirecting, the offending cookie should also be deleted, because if not, a redirect loop similar to #142 occurs.

I'll try to make a PR for this.

**Comment by rwinch** [comment]
Thanks for the report.

I believe Tomcat leaves the session alone if it is an invalid session id and the HttpSession is not requested, so I'm confused why this is a problem with Spring Session. Can you provide a sample of this?

**Comment by rwinch** [comment]
@domdorn Any updates on this? Can you provide a stacktrace, steps to reproduce, or a sample?

**Comment by domdorn** [comment]
Hmm.. I'm not sure, as I've got assigned a new work item.. steps to reproduce where

1. start redis instance
2. log in to the application
3. kill redis instance
4. reload web-page
-> session-cookie is valid, but session is not found in redis, instead of deleting the cookie, it redirects to login page, which instead of deleting the old cookie again redirects and so on..

**Comment by rwinch** [comment]
Thanks for the response. I am unable to reproduce this. Please create a new ticket if you are able to reproduce.
