### ISSUE TITLE
Ability to reset/clear a session

### ISSUE THREAD

**Issue by jsumners** [spring-projects/spring-session#160]
It'd be nice if `Session` had a `reset()` or `clear()` method.

**Comment by rwinch** [comment]
Why not just create a new session and delete the previous one? This is only two lines of code and does not involve adding another method to the Session API.

Perhaps you can you explain your use case a little better?

**Comment by jsumners** [comment]
I avoid passing in `HttpServletRequest` unless I absolutely have to. I try to keep my method signatures short. Also, if spring-session is providing a nicer API than `HttpSession` then I'd like to use it.

Here's a scenario where I think `reset()` or `clear()` is useful:

A user is presented with a few choices: activate account, lookup account, reset password. Each of these actions will involve state saved in the session. But each action should be totally separate. So, if the user started on one action but found out that was the wrong one and switched one of the others, then the session state should be reset or cleared. We could do that as you suggest:

```java
public ModelAndView startPoint(HttpSession session, HttpServletRequest request) {
  // Make sure the session is clean
  session.invalidate();
  HttpSession _session = request.getSession(true);

  // now use _session when we already had session
}
```

Or we could use an improved API:

```java
public ModelAndView startPoint(Session session) {
  // Make sure the session is clean
  session.clear();
 
  // go about our business
}
```

**Comment by rwinch** [comment]
Thanks for the response. Spring Session cannot add new methods to the Session interface. Additionally, we want to keep the Session API as simple as possible so that it is easy to implement. The way to implement this is very simple (two lines of code). If you want methods like this, you could easily create a wrapper that invokes those two lines.

For these reasons, I'm closing as invalid.
