### ISSUE TITLE
Request is not wrapped in case RequestDispatcher.forward or RequestDispatcher.include

### ISSUE THREAD

**Issue by codecracker2014** [spring-projects/spring-session#1605]
In case RequestDispatcher.forward or RequestDispatcher.include new instance of request is created from native request by container servlet implementation. Now if view resolver try to get session, native session is created which doesn't share anything with Spring session. This has been observed on jetty, tomcat, and jboss servers, i'm not sure about other containers.

**Comment by rwinch** [comment]
If I remember correctly the problem is that the response becomes committed as soon as you do one of these actions, so we cannot write the session cookie which means no session is allowed at that time. Can you please provide a minimal sample that reproduces the problem?

**Comment by codecracker2014** [comment]
In view i'm just trying to access session attributes, but as the underlying session is switched attributes can't be found. I'll share the issue sample soon, may be with fix as well.

**Comment by codecracker2014** [comment]
@rwinch I've created sample application to replicate this issue, which can be found [here](https://github.com/codecracker2014/spring-session-issue). Please review and share your view.

**Comment by codecracker2014** [comment]
Servlet API specification also describes that error page handlers would get unwrapped request and response. Refer section 10.9.3(page 104) in https://download.oracle.com/otn-pub/jcp/servlet-3.0-fr-eval-oth-JSpec/servlet-3_0-final-spec.pdf?AuthParam=1584775350_ab32c9a1fdc04d0775d0fbbcbd6f9071

It also talks about error filters, so may be we need to use one to wrap request object.

**Comment by codecracker2014** [comment]
ERROR dispatcher handling is already done with 593c126c03642f5afdd7cb162f6690e9439b4082, in order to fix this issue ERROR dispatcher needs to be configured as well along with REQUEST.
