### ISSUE TITLE
Does not work with GCP Redis (Memorystore)

### ISSUE THREAD

**Issue by markusheiden** [spring-projects/spring-session#1606]
Using spring-session-data-redis with a GCP Redis (Memorystore) does not work.
The GCP Redis blocks the `CONFIG` command, which spring-session-data-redis uses e.g. for `CONFIG GET notify-keyspace-events`. This make Spring Session fail.

**Comment by vpavic** [comment]
@markusheiden, did you read [this section](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisindexedsessionrepository-sessiondestroyedevent) of reference manual?

> If you use `@EnableRedisHttpSession`, managing the `SessionMessageListener` and enabling the necessary Redis Keyspace events is done automatically. However, in a secured Redis enviornment, the config command is disabled. This means that Spring Session cannot configure Redis Keyspace events for you. To disable the automatic configuration, add `ConfigureRedisAction.NO_OP` as a bean.

Regardless of the `CONFIG` command being often blocked in environments that offer managed Redis instance, the production recommendation is always to configure keyspace events explicitly on the Redis side.

Does that help?

**Comment by markusheiden** [comment]
Yes, sorry, that covers my problem. 

Anyway: Maybe a more meaningful exception message with a hint to that documentation would be fine. Maybe I again overlooked something, but the documentation does not describe what I need to do alternatively, when using ConfigureRedisAction.NO_OP, to receive the keyspace events.

**Comment by vpavic** [comment]
Thanks for the feedback @markusheiden - I've opened #1607 to improve the reference manual on this topic.
