### ISSUE TITLE
/auth endpoint not handled in samples

### ISSUE THREAD

**Issue by amirensit** [spring-projects/spring-session#1609]
I tried several samples provided [here](https://github.com/spring-projects/spring-session/tree/2.3.0.RC1/spring-session-samples).

The problem is that after login, the url '/auth' is not handled, so I get 404 error.

**Comment by rwinch** [comment]
@amirensit It isn't clear to me why you expect `/auth` URL to exist. Can you provide more specific steps of what you did, what you expect to happen (and why), and what actually happened?

**Comment by amirensit** [comment]
@rwinch I just logged in.
I restarted the app and It worked. I have don't have any idea.
Anyway the essential is that the sample works :)

**Comment by rwinch** [comment]
Thank you for the fast follow up. I'm glad you were able to get it working.
