### ISSUE TITLE
SpringSessionJDBC allow flexibility of injected TransactionManager

### ISSUE THREAD

**Issue by kirkHawksworth** [spring-projects/spring-session#1611]
Currently, when using Spring Session JDBC, the default / primary`PlatformTransactionManager` configured for an application is injected into 'JdbcHttpSessionConfiguration'.

In the case of an application with multiple transaction managers, it would be beneficial to allow which Transaction Manager is used to be configured by the user, in a similar way to how the Datasource is configured.

For example an annotation of the form:

```
@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.TYPE,
		ElementType.ANNOTATION_TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Qualifier
public @interface SpringSessionTransactionManager {

}
```

And then the injecting code for the TransactionManager

```
@Autowired
public void setTransactionManager(
			@SpringSessionTransactionManager  ObjectProvider<PlatformTransactionManager> springSessionTransactionManager,
			ObjectProvider<PlatformTransactionManager> transactionManager) {
  PlatformTransactionManager transactionManagerToUse = springSessionTransactionManager.getIfAvailable();
  if (transactionManagerToUse == null) {
    transactionManagerToUse = transactionManager.getObject();
  }
  this.transactionManager = transactionManagerToUse;
}
```
Is this worth me creating a pull request for? I wouldn't like to go to the effort of creating one if it isn't going to be looked at / reviewed?

Or am I missing something, is there a way to achieve what I would like to already?

Thanks,
Kirk

**Comment by vpavic** [comment]
Hi @kirkHawksworth,

There's already a way to customize the transactional behaviour of our JDBC session repository, and the way you do that is by providing a `TransactionOperations` bean named `springSessionTransactionOperations` (see [here](https://github.com/spring-projects/spring-session/blob/a824edd1c3bef1617ca36ab97e733194261463e6/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L197-L201)).

This way you can customize not only the `PlatformTransactionManager` being used, but also any other aspect of session repository's transactional behaviour (e.g. by default we use `TransactionDefinition.PROPAGATION_REQUIRES_NEW`).

Does that work for you?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kirkHawksworth** [comment]
Hi @vpavic ,

Thanks for the response, yes that does indeed help. I am on the 2.1.x branch and so didn't see that. I will upgrade to 2.2.x, I hadn't realised 2.1.x is 6 months old now.

Thanks again
Kirk

**Comment by BearKid** [comment]
> Hi @vpavic ,
> 
> Thanks for the response, yes that does indeed help. I am on the 2.1.x branch and so didn't see that. I will upgrade to 2.2.x, I hadn't realised 2.1.x is 6 months old now.
> 
> Thanks again Kirk

Hi, @kirkHawksworth , did your question really get resolved through vpavic's previous response?
The issue I encountered is that when there are multiple TransactionManager beans for different data sources in a Spring application, this piece of code causes the Spring application to fail to start.
```
// JdbcHttpSessionConfiguration.java
@Autowired
public void setTransactionManager(PlatformTransactionManager transactionManager) {
   this.transactionManager = transactionManager;
}
```

```
Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': 
Unsatisfied dependency expressed through method 'setTransactionManager' parameter 0; 
nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: 
No qualifying bean of type 'org.springframework.transaction.PlatformTransactionManager' available: 
expected single matching bean but found 2
```
@vpavic 's reply was about **TransactionOperations**, not **PlatformTransactionManager**.

I am using spring-session-jdbc-2.7.0.jar.
