### ISSUE TITLE
8.2. Spring Security Concurrent Session Control with Webflux

### ISSUE THREAD

**Issue by henrik-larsson-15-wcar** [spring-projects/spring-session#1612]
Are there any examples on how to use the Spring Security Support in Spring Session with Webflux? There is no `SessionManagementConfigurer` in the Java DSL so how do I limit the number of concurrent sessions for a principal to 1? The default in spring session looks to be that a singel principal can have an unlimited number of concurrent sessions?

**Comment by rwinch** [comment]
Spring Security does not yet have concurrency control for WebFlux. See https://github.com/spring-projects/spring-security/issues/6192
