### ISSUE TITLE
spring-session-sample-boot-findbyusername

### ISSUE THREAD

**Issue by Ethns** [spring-projects/spring-session#1613]
# Issue Description:
encountering "Request method 'POST' not supported" error when terminate user session in  `spring-session-sample-boot-findbyusername` sample application
## Steps to reproduce the issue
1. start-up spring-session-samples/spring-session-sample-boot-findbyusername
Follow below steps displayed on http://localhost:8080/ to delete the previous session
![findbyname](https://user-images.githubusercontent.com/12314312/79039614-d1941b00-7c25-11ea-8d03-6d8a11ae98a3.png)
2. When click the terminate button to delete the session, the an error page comes up:
![terminate](https://user-images.githubusercontent.com/12314312/79039656-2768c300-7c26-11ea-8a80-997fb699f538.png)
![error](https://user-images.githubusercontent.com/12314312/79039591-8f6ad980-7c25-11ea-9a8c-dc389cac97fb.png)

**Comment by rwinch** [comment]
Thanks for the report @Ethns! This is now fixed in master via https://github.com/spring-projects/spring-session/commit/fed318abc76b1992d11746f7fa1c3459eeb31676.
