### ISSUE TITLE
I set the ConfigureRedisAction to NO_OP ，The listener still receives the destroyed message？

### ISSUE THREAD

**Issue by solomonhe** [spring-projects/spring-session#1619]
**Describe the bug**
I set the ConfigureRedisAction to NO_OP ，The listener still receives the destroyed message

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by eleftherias** [comment]
@solomonhe Could you please provide a sample that demonstrates this behaviour?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
