### ISSUE TITLE
Split WebSockets feature from spring-session to relax SpringFramework dependency

### ISSUE THREAD

**Issue by peterksteiner** [spring-projects/spring-session#163]
Spring Session solves a problem for me, but am not ready to upgrade rest of webapp to Spring 4.  Reviewing the code, it appears WebSockets are the driver for Spring 4 dependency. Hacking WebSocket from the project allows one to build, test, and run the sample apps with Spring 3.

Would you consider making refactoring out spring-session-websocket as a child project so apps that have no need for the WebSocket feature could use spring-session with Spring 3?

**Comment by rwinch** [comment]
The dependencies for Spring WebSocket are optional, so they should not impact the version of Spring that is necessary (in fact at its core Spring Session does not require Spring at all).

What specifically are you having trouble with when using Spring Session with Spring 3 (and which exact version are you using)?

**Comment by peterksteiner** [comment]
I've been able to create my own version of your demo apps with Spring 3.2.1.RELEASE. I've posted to https://github.com/peterksteiner/spring-session-demo
Everything works just fine w/o Spring 4. Thanks!

**Comment by rwinch** [comment]
Great glad it is working for you!
