### ISSUE TITLE
Support for overriding session id generation for Session Cookie

### ISSUE THREAD

**Issue by abhishekjoy1** [spring-projects/spring-session#1655]
**Expected Behavior**

I am looking for a provision for overriding session-id generation for the session cookie.

**Current Behavior**

As of now, this session id which is basically a UUID is generated through the framework. Application developers does not have a way to override this session id with their own custom session-id generator.
**Context**

**Comment by eleftherias** [comment]
Thanks for getting in touch @abhishekjoy1.

We already have gh-11 to track this issue.

I'm closing this as a duplicate.
