### ISSUE TITLE
"No-CSRF" sessions?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-session#167]
I'm using Spring Security 4 with its pervasive CSRF protection. While this is a Good Thing for the most part, I am trying to use uniform URIs for both HTML and JSON responses, making non-Web client access a challenge. Would it be feasible to somehow label sessions as "non-Web" to tell Spring Security not to apply CSRF restrictions for that session? (I'm aware that this would also require cooperation from `CsrfFilter` and maybe other places as well, and perhaps this is completely a Spring Security issue and not Session at all?)

**Comment by rwinch** [comment]
This is indeed a Spring Security question. You really need to be careful disabling CSRF if the application is used within a browser. See http://docs.spring.io/spring-security/site/docs/3.2.x/reference/htmlsingle/#when-to-use-csrf-protection

If you still have questions, this is a better question for StackOverflow with the spring-security tag. If you don't get a response within a 3 days feel free to mention me on StackOverflow to get my attention.
