### ISSUE TITLE
spring-session-bom `2020.0.0-SNAPSHOT` refers to milestones

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-session#1685]
The latest [spring-session-bom](https://repo.spring.io/snapshot/org/springframework/session/spring-session-bom/2020.0.0-SNAPSHOT/spring-session-bom-2020.0.0-20200915.060532-123.pom) on repo.spring.io has references to milestone 1 artifacts.

I believe this should be snapshots so that integration tests can be applied on the latest state when using the snapshot.

**Comment by eleftherias** [comment]
Updated in spring-projects/spring-session-bom
