### ISSUE TITLE
Add Mongo SessionRepository w/ support for querying by session attributes

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#17]
> the important part of that was being able to query it - by more than key, query on the value objects, eg items in a basket over $20 or something or other criteria to help convert items in a cart to transactions.

Things we typically look for when getting a new datastore (looks like this is already pretty close):

* [ ] Code (obviously)
* [ ] Unit tests
* [ ] Integration tests (fewer than the unit tests for speed but still ensure things are working)
* [ ] Hello World Sample / Guide for Web Application (i.e. [HttpSession Sample](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/httpsession.html))
* [ ] Sample Tests
* [ ] Optional `@EnableMongoHttpSession` for making things easier
* [ ] Optional spring-session-mongo pom that aggregates the dependencies to make dependency management for users easier

**Comment by jkubrynski** [comment]
I'm currently working on this issue. Hope to finish in few days
