### ISSUE TITLE
Use simple session repository implementations by default

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1711]
As discussed with @rwinch some while ago, Spring Session should use simpler, more performant session repository implementations by default. The `3.0` release as the next major release is a natural place to consider such a change. This was actually the motivation for coming up with `RedisSessionRepository` in `2.2`.

Specifically, at this point this is about `RedisIndexedSessionRepository` vs `RedisSessionRepository`. The _indexed_ variant supports fetching sessions by index (i.e. implements `FindByIndexNameSessionRepository`) as well as session events. These features add quite a bit of complexity implementation wise and benefits (indexes and events) aren't even used by most of the users these day.

While making this change, we should also make sure that it's easy for the users to opt-in to other available session repository implementations.

Related issues:
- #1182

**Comment by dreis2211** [comment]
> are even used by most of the users these day.

@vpavic used or unused? The change wouldn't make much sense imho, if most of the users actually use session events and index based fetching.

Cheers,
Christoph

**Comment by vpavic** [comment]
That _are_ at the beginning of the quote was really supposed to be _aren't_. :slightly_smiling_face:
Thanks @dreis2211, I've updated the original comment.

**Comment by vpavic** [comment]
This was resolved in 8582b97.
