### ISSUE TITLE
Review community extensions section of reference manual

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#1736]
It's likely that the [community extensions](https://docs.spring.io/spring-session/docs/current/reference/html5/#community-extensions) section of reference manual is outdated.

We should:

- check that the listed community modules listed with the current release
- look into whether there are other community modules out there that aren't listed
- consider improving the listing itself (e.g. Spring Boot does it like [this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-starters/README.adoc) and has only a reference to this readme from their reference docs)

**Comment by eleftherias** [comment]
Thanks @vpavic. I updated the table with the correct links to the active projects.
I opted to keep it in the reference docs since I think it makes more sense there than in the readme.
