### ISSUE TITLE
Unsupported CONFIG parameter: notify-keyspace-events with Embedded Redis on Windows

### ISSUE THREAD

**Issue by szabobar** [spring-projects/spring-session#174]
I was cloned the spring-session samples in Win7 - JDK8. If I change 'springSessionVersion' to  '1.0.1.BUILD-SNAPSHOT'  in 'samples/spring-websocket-chat/build.gradle' then, the error also got...

I think this is a blocked issue, because the whole application not works because of it.

**Comment by rwinch** [comment]
Thanks for the report. This is due to the fact that the Windows Version was not updated. Can you help out on https://github.com/kstyrc/embedded-redis/issues/23 to provide feedback on the fix?

**Comment by szabobar** [comment]
Sure,

But, If I use redis server on my win7, the problem was the same, so that code does not work with not embedded redis server.

**Comment by rwinch** [comment]
@szabobar What version of Redis are you using? You need to use at least Redis 2.8.0+ since we rely on [Keyspace Notifications](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration).

Admittedly this is not obvious so we have #115 to make it more apparent.

**Comment by szabobar** [comment]
Your right, if I use the 2.8.17.4 version, work for me: 
https://github.com/MSOpenTech/redis/releases/tag/win-2.8.17.4

Thanks

**Comment by rwinch** [comment]
@szabobar Thanks for the fast response. Do the samples with the embedded Redis work on Windows? If not, we still have an issue and we should probably reopen this.

**Comment by rwinch** [comment]
(reopening for now to ensure this doesn't get lost)

**Comment by brandon-atkinson** [comment]
This also affects users of Amazon's ElastiCache redis, as it doesn't support CONFIG either.
+1 on a fix for this

**Comment by rwinch** [comment]
> This also affects users of Amazon's ElastiCache redis, as it doesn't support CONFIG either.
+1 on a fix for this, even if it's by allowing an option to disable disable keyspace notifications.

This is only to resolve the embedded instances. Please see #124 (now fixed)

**Comment by rwinch** [comment]
Closing this issue. In 1.0.1 have updated the samples to use embedded-redis 0.6 which should work on any OS that supports Redis (i.e. Windows 32 will not work) See #187
