### ISSUE TITLE
spring.session.redis.namespace不生效

### ISSUE THREAD

**Issue by JustCrazyHeart** [spring-projects/spring-session#1740]
配置了spring.session.redis.namespace，但是服务启动并没有加载此项，而且RedisSessionConfiguration也并未加载。
存入reids中的键依旧是spring:session开头。

Via Google Translate:
> Spring.session.redis.namespace is configured, but this item is not loaded when the service starts, and RedisSessionConfiguration is not loaded either.
The key stored in reids is still the beginning of spring:session.

![image](https://user-images.githubusercontent.com/7077925/101145573-f32e9080-3654-11eb-8928-d594bc5f0dff.png)
![image](https://user-images.githubusercontent.com/7077925/101145601-fe81bc00-3654-11eb-8673-8d6f3ad9d784.png)

**Comment by vpavic** [comment]
@JustCrazyHeart Could you share details about how you are configuring Spring Session?

I suspect you're using `@EnableRedisHttpSession` which will result in Spring Boot's auto-configuration backing off. See spring-projects/spring-boot#15757.

**Comment by JustCrazyHeart** [comment]
> @JustCrazyHeart Could you share details about how you are configuring Spring Session?
> 
> I suspect you're using `@EnableRedisHttpSession` which will result in Spring Boot's auto-configuration backing off. See [spring-projects/spring-boot#15757](https://github.com/spring-projects/spring-boot/issues/15757).

使用了`@EnableRedisHttpSession`

![image](https://user-images.githubusercontent.com/7077925/101156564-c46be680-3663-11eb-9f5c-93e0396f9e3c.png)

**Comment by JustCrazyHeart** [comment]
我删除了`@EnableRedisHttpSession`后，还是没有生效，redis中依旧是`spring:session`

![image](https://user-images.githubusercontent.com/7077925/101157007-6a1f5580-3664-11eb-8cf5-d26dfdd53f29.png)

![image](https://user-images.githubusercontent.com/7077925/101157036-773c4480-3664-11eb-81d4-0431fc5b9a0d.png)

**Comment by vpavic** [comment]
Thanks for the update.

From the information you've provided it's hard to figure out why this doesn't work for you. Unfortunately, I cannot reproduce the issue using my own sample. Please provide a minimal sample that we can use to reproduce the problem you're experiencing.

Also note that I've added Google Translate provided translations below your comments. Please try to comment in English in future.

**Comment by JustCrazyHeart** [comment]
> 感谢更新。
> 
> 根据您提供的信息，很难弄清为什么这对您不起作用。不幸的是，我无法使用自己的样本重现该问题。请提供一个最小的样本，我们可以用来重现您遇到的问题。
> 
> 另请注意，我已经在您的评论下方添加了Google翻译提供的翻译。以后请尝试用英语发表评论。

Thank you for your reply，My main class has also been added`@EnableRedisHttpSession`，Today，I deleted the `@EnableRedisHttpSession` and it takes effect. Thank you again for your reply

**Comment by vpavic** [comment]
Glad to hear you managed to get it working.

**Comment by zjg1993** [comment]
加个引号就行了
