### ISSUE TITLE
request for a reactive version of org.springframework.session.FindByIndexNameSessionRepository family

### ISSUE THREAD

**Issue by orcloveasagi** [spring-projects/spring-session#1741]
**Expected Behavior**
Something like org.springframework.session.FindByIndexNameSessionRepository and its subclasses

**Current Behavior**
We cannot access reactive WebSession by username conveniently.

**Context**
When I tried to build a Spring cloud gateway application,which build on webflux, with spring security and spring session, I found it difficult to implement concurrent session controle sinces there's no reactive implementations for the FindByIndexNameSessionRepository. However I can still accomplish my goals through ReactiveSessionRepository in a more cumbersome way. 
And now I'm going to ask you if you need a more convenient way to access reactive WebSession?
If you do I can package something like FindByIndexNameSessionRepository and make a pr.

**Comment by zkning** [comment]
+++

**Comment by chhch** [comment]
Duplicate of #914

**Comment by marcusdacoregio** [comment]
Closing as duplicate of #914
