### ISSUE TITLE
HazelcastIndexedSessionRepository cannot find all user's sessions even though  SPRING_SECURITY_CONTEXT was set

### ISSUE THREAD

**Issue by trim09** [spring-projects/spring-session#1745]
HazelcastIndexedSessionRepository cannot find all user's sessions even though  SPRING_SECURITY_CONTEXT was set on the session. It is because PRINCIPAL_NAME_INDEX_NAME's value was not saved on the modified session.

**To Reproduce**
1) login by calling (I know this is not the safest login ever):
```
var authentication = new UsernamePasswordAuthenticationToken(username, null, Collections.emptyList());
SecurityContextHolder.getContext().setAuthentication(authentication);
//forget to call (HttpServletRequest request).changeSessionId(); that could fix this issue
```
2) try to get all sessions on the next request by calling: 
```
@Autowire
SessionRegistry sessionRegistry;
List<SessionInformation> userSessions = sessionRegistry.getAllSessions(username, false);
```

**Expected behavior**
`userSessions` returned by `getAllSessions` contains 1 session

**Actual behavior**
No user's sessions returned because no `PRINCIPAL_NAME_INDEX_NAME` was set on the session in `HazelcastIndexedSessionRepository`

**Why it does not work?**
Usually, `ChangeSessionIdAuthenticationStrategy` changes the sessionId and it forces saving all session's field.
In this case, `ChangeSessionIdAuthenticationStrategy` is not involved and [this code](https://github.com/spring-projects/spring-session/blob/090a10fb1032d27d1be9fd7a34d99a57efc261ef/spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/HazelcastIndexedSessionRepository.java#L443) does not update `delta` field and therefore `PRINCIPAL_NAME_INDEX_NAME` is not saved.

I think it can be fixed by adding `this.delta.put(PRINCIPAL_NAME_INDEX_NAME, attributeValue);` to line 443 resulting in:
```
		@Override
		public void setAttribute(String attributeName, Object attributeValue) {
			this.delegate.setAttribute(attributeName, attributeValue);
			this.delta.put(attributeName, attributeValue);
			if (SPRING_SECURITY_CONTEXT.equals(attributeName)) {
				Map<String, String> indexes = HazelcastIndexedSessionRepository.this.indexResolver
						.resolveIndexesFor(this);
				String principal = (attributeValue != null) ? indexes.get(PRINCIPAL_NAME_INDEX_NAME) : null;
				this.delegate.setAttribute(PRINCIPAL_NAME_INDEX_NAME, principal);
				this.delta.put(PRINCIPAL_NAME_INDEX_NAME, attributeValue); // <== this is the fix
			}
			flushImmediateIfNecessary();
		}
```

**Comment by eleftherias** [comment]
Thanks for reaching out @trim09.

I have not been able to reproduce this so far. Could you please share a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
