### ISSUE TITLE
With RedisIndexedSessionRepository, when logout ,i invoke the deleteById method， the key of sessions:expires:sessionId is deleted， but the key of sessions:sessionId is not deleted

### ISSUE THREAD

**Issue by zjdym** [spring-projects/spring-session#1746]
**Describe the bug**
With RedisIndexedSessionRepository, when logout ,i invoke the deleteById method， the key of sessions:expires:sessionId is deleted， but the key of sessions:sessionId is not deleted

**To Reproduce**
1: login a user, we can find  the key of sessions:expires:sessionId ，sessions:sessionId，session: expirations:time was  created
2: logout, but only the key of  the key of sessions:expires:sessionId was deleted, whether the key of sessions:sessionId should be deleted  immediately
 
**Expected behavior**
when logout, the key of sessions:expires:sessionId , sessions:sessionId should be deleted

**Sample**
i find  the key of sessions:expires:sessionId is deleted twice ， but not sessions:sessionId was deleted，
the first deletion（RedisIndexedSessionRepository）：
    
	public void deleteById(String sessionId) {
		RedisSession session = getSession(sessionId, true);
		if (session == null) {
			return;
		}

		cleanupPrincipalIndex(session);
		this.expirationPolicy.onDelete(session);

		String expireKey = getExpiredKey(session.getId());
		this.sessionRedisOperations.delete(expireKey);

		session.setMaxInactiveInterval(Duration.ZERO);
		save(session);
	}
        
the second deletion（RedisSessionExpirationPolicy） ：

	void onExpirationUpdated(Long originalExpirationTimeInMilli, Session session) {
		String keyToExpire = "expires:" + session.getId();
		long toExpire = roundUpToNextMinute(expiresInMillis(session));
		if (originalExpirationTimeInMilli != null) {
			long originalRoundedUp = roundUpToNextMinute(originalExpirationTimeInMilli);
			if (toExpire != originalRoundedUp) {
				String expireKey = getExpirationKey(originalRoundedUp);
				this.redis.boundSetOps(expireKey).remove(keyToExpire);
			}
		}

		long sessionExpireInSeconds = session.getMaxInactiveInterval().getSeconds();
		String sessionKey = getSessionKey(keyToExpire);

		if (sessionExpireInSeconds < 0) {
			this.redis.boundValueOps(sessionKey).append("");
			this.redis.boundValueOps(sessionKey).persist();
			this.redis.boundHashOps(getSessionKey(session.getId())).persist();
			return;
		}

		String expireKey = getExpirationKey(toExpire);
		BoundSetOperations<Object, Object> expireOperations = this.redis.boundSetOps(expireKey);
		expireOperations.add(keyToExpire);

		long fiveMinutesAfterExpires = sessionExpireInSeconds + TimeUnit.MINUTES.toSeconds(5);

		expireOperations.expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);
		if (sessionExpireInSeconds == 0) {
                        // _**here the key is sessions:expires:sessionId**_ 
			this.redis.delete(sessionKey);
		}
		else {
			this.redis.boundValueOps(sessionKey).append("");
			this.redis.boundValueOps(sessionKey).expire(sessionExpireInSeconds, TimeUnit.SECONDS);
		}
		this.redis.boundHashOps(getSessionKey(session.getId())).expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);
	}

**Comment by zjdym** [comment]
I wonder if it's a bug or  design it like this

**Comment by eleftherias** [comment]
Thanks for reaching out @zjdym. 
Have you read the [Session Expiration](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisindexedsessionrepository-expiration) section of the reference documentation? 
Does this help answer your question or is it still unclear?

**Comment by zjdym** [comment]
@eleftherias Thanks. I see why
