### ISSUE TITLE
Support transient authentications

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-session#1753]
**Expected Behavior**

Don't create a session when `org.springframework.security.core.Transient` annotation is present on the authentication (like HttpSessionSecurityContextRepository)

**Current Behavior**

Any request passing SessionRepositoryFilter will create a session if not present.

**Context**

We have an application using session based authentication for the user and custom token based for the api. For the api endpoints no sessions should be created.

**Comment by eleftherias** [comment]
Thanks for reaching out @joshiste.

Spring Session does support `org.springframework.security.core.Transient` annotations already, through Spring Security.

It's surprising to me that the `SessionRepositoryFilter` will always create a session in your application.

Could you share a sample that reproduces this behaviour?

**Comment by joshiste** [comment]
I've tried to setup a sample that reproduces the behaviour - turns out that I found a subtle bug in my AuthenticationProvider implementation which returned a non-transient token on success. So everything is working as expected.
