### ISSUE TITLE
Enable setting custom id in RedisSession

### ISSUE THREAD

**Issue by bjevtic** [spring-projects/spring-session#1780]
Hi,
currently, when a RedisSession is created (inside RedisOperationsSessionRepository), its ID is set to a randomly picked UUID. I don't see a way to set a custom session ID afterwards (like we can do in MapSession.setId()), and class itself is package private and final, so it cannot be extended. Is there any way this can be done?

I see issues #11 and #204 are somewhat related to this.

Thanks

**Comment by bjevtic** [comment]
Sorry, I should have been clearer. One case I can think of is integration with existing session management systems, where we already have existing session id which we'd like to use, without resorting to something else. I see that some of the implementations allow setting id, like MapSession and MongoSession, and some don't (RedisSession and possibly Hazelcast and JdbcSession).
I have also found #1545 (much better explained)  and have just upvoted it, so I guess this can be closed as a duplicate.

**Comment by eleftherias** [comment]
Thanks @bjevtic. I will close this as a duplicate.
