### ISSUE TITLE
Unable to build spring-session sample application due to 401 Unauthorized error.

### ISSUE THREAD

**Issue by azrrik** [spring-projects/spring-session#1792]
**Describe the bug**
I'm trying to build the sample application found here:

https://github.com/spring-projects/spring-session/archive/2.4.2.zip

$ ./gradlew :spring-session-sample-boot-redis:bootRun
``
FAILURE: Build failed with an exception.

* Where:
Build file '/home/az/Downloads/spring-session-2.4.2/spring-session-docs/spring-session-docs.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':spring-session-docs'.
> Could not resolve all dependencies for configuration ':spring-session-docs:detachedConfiguration1'.
   > Could not resolve org.junit:junit-bom:5.7.0.
     Required by:
         project :spring-session-docs
      > Could not resolve org.junit:junit-bom:5.7.0.
         > Could not get resource 'https://repo.spring.io/libs-release/org/junit/junit-bom/5.7.0/junit-bom-5.7.0.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-release/org/junit/junit-bom/5.7.0/junit-bom-5.7.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve org.testcontainers:testcontainers-bom:1.15.1.
     Required by:
         project :spring-session-docs
      > Could not resolve org.testcontainers:testcontainers-bom:1.15.1.
         > Could not get resource 'https://repo.spring.io/libs-release/org/testcontainers/testcontainers-bom/1.15.1/testcontainers-bom-1.15.1.pom'.
            > Could not GET 'https://repo.spring.io/libs-release/org/testcontainers/testcontainers-bom/1.15.1/testcontainers-bom-1.15.1.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
``

**To Reproduce**
Download the zip and run the build.

**Expected behavior**
I expect the build to finish without error.

**Comment by eleftherias** [comment]
@azrrik Spring recently changed [the way authentication works](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) with its repositories.

Please use the [latest 2.4.x branch](https://github.com/spring-projects/spring-session/tree/2.4.x) to run the sample. 
We have recently updated all of our branches to work with the changes to the repository authorization.

If you must use the 2.4.2 ZIP, you can try applying the changes in [this commit](https://github.com/spring-projects/spring-session/commit/ba4bb6fcf69b0974558d1eea80e1bd435859d9f3) locally, which may fix the authorization issue.

**Comment by azrrik** [comment]
@eleftherias The build works fine when I clone from the latest 2.4.x branch.  Thanks very much!

The links on this page:

https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html#boot-sample

should be updated as well.
