### ISSUE TITLE
Support for servlet 3.1 API of request.changeSessionId()

### ISSUE THREAD

**Issue by prasenjit-net** [spring-projects/spring-session#180]
Servlet API 3.1 has added one API changeSessionId() to defend against session fixation. Please add that support in here too.

**Comment by cemo** [comment]
see #152

**Comment by rwinch** [comment]
Thanks for the report @prasenjit-net This is indeed a duplicate of #152 Please give the 1.0.1.BUILD-SNAPSHOT a try from https://repo.spring.io/snapshots and let me know if you are still having problems.
