### ISSUE TITLE
Spring Session Redis Customization on Redis Connection Factory

### ISSUE THREAD

**Issue by hanscrg** [spring-projects/spring-session#1806]
**Describe the bug**
To enable Spring Redis Session with Spring Cloud Gateway with AWS Elasticache Redis. we need to customize the Redis Connection Factory to use SSL without TLS cert. However the customized redisConnectionFactory below does not get picked up by Spring Session Redis so all the customizations does not take effective. Spring Session Redis needs to give a way to customize the Redis Connection Factory it used. 

**Code**

@Configuration
public class RedisConfig {
	
	public LettuceConnectionFactory redisConnectionFactory(RedisProperties redisProperties) {
		LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder().useSsl().disablePeerVerification().build();
		RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
		redisStandaloneConfiguration.setHostName(redisProperties.getHost());
		redisStandaloneConfiguration.setPort(redisProperties.getPort());
		redisStandaloneConfiguration.setPassword(redisProperties.getPassword());
		return new LettuceConnectionFactory(redisStandaloneConfiguration, lettuceClientConfiguration);
	}

}

The Redis Spring Boot Configuration:

spring:
  redis:    
    host: ${host}
    port: ${port}
    ssl: true
    password: ${password}
    timeout: 60s      
  session:
    timeout: 7d
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

Enviroment:
Spring Boot: 2.3.3
Spring Cloud: Hoxton.SR7

**Comment by eleftherias** [comment]
@hanscrg It looks like you are missing the `@Bean` annotation on the `LettuceConnectionFactory`.
