### ISSUE TITLE
looking Sample project for "Spring Session - Multiple Sessions"

### ISSUE THREAD

**Issue by sandeepsharda** [spring-projects/spring-session#1814]
**Expected Behavior**

I am looking for a sample project (spring-session-2.0.0.M4\samples\javaconfig\users) of "Spring Session - Multiple Sessions" https://docs.spring.io/spring-session/docs/2.0.0.M4/reference/html5/guides/java-users.html , but the download link is giving an old project which is not building with Gradle.

In the latest Git repo this project is not available so kindly help me out. 

**Current Behavior**
Sample project for "Spring Session - Multiple Sessions" is not present n the latest Git repo branch.

I have a project requirement where I need to enable multiple user session from the same browser, Means in multiple browser tabs the different user can log in.

Looking forward to your sonner support.

Thanks
Sandeep Sharda

**Comment by eleftherias** [comment]
Hi @sandeepsharda, support for managing multiple users' sessions has been removed.
See gh-917 for more details.
