### ISSUE TITLE
SpringHttpSessionConfiguration should set Secure and HttpOnly from sessionCookieConfig

### ISSUE THREAD

**Issue by ikeyat** [spring-projects/spring-session#1844]
**Expected Behavior**

SpringHttpSessionConfiguration creates a DefaultCookieSerializer from sessionCookieConfig that is configured at  `<cookie-config>` in web.xml.
 `<cookie-config>`  has following attributes (see http://java.sun.com/xml/ns/javaee/web-common_3_0.xsd).
 - `<name>`
 - `<domain>`
 - `<path>`
 - `<comment>`
 - `<http-only>`
 - `<secure>`
 - `<max-age>`

`DefaultCookieSerializer` is expected to be configured with all attributes except `<comment>` .

**Current Behavior**

I found following 2 attributes are not configured by default.

 - `<http-only>`
 - `<secure>`

**Context**

I needed to create an instance of `DefaultCookieSerializer` and configure all attributes apart from `<cookie-config>`.
Those 2 attributes are important for building secure application.
I think they should be configured by default to keep application secure.
Most people don't confirm those attributes are actually set into cookie.

On the other hand, `SessionAutoConfiguration` (#1402 ) configures all attributes including `<http-only>` and `<secure>`.
So, Spring Boot users are not affected by this problem.

**Comment by eleftherias** [comment]
Thanks for reaching out @ikeyat.
This behavior is intentional. 
See gh-1253 for more details.
