### ISSUE TITLE
JDBC session with negative timeout should never expire

### ISSUE THREAD

**Issue by Lurkars** [spring-projects/spring-session#1847]
**Describe the bug**
With spring-session-jdbc, cleanUpExpiredSessions() get's called and directly clears previous changed session with MAX_INACTIVE_INTERVAL -1 (also tried -9999 and 0). In SPRING_SESSION table EXPIRY_TIME is always same as LAST_ACCESS_TIME which leads to MAX_INACTIVE_INTERVAL of 0-60 seconds (default interval of cleanUpExpiredSessions cron). I am using MariaDB.

**To Reproduce**
Setup spring boot 2.4.5 application with spring-session-jdbc and following application.properties
```
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=-1
```
create session, wait for call of cleanUpExpiredSessions()

**Expected behavior**
Sessions with MAX_INACTIVE_INTERVAL <= 0 are not cleared kept forever.

**Comment by eleftherias** [comment]
Thanks for bringing this up @Lurkars.

As a workaround you can customize the session deletion query using a `SessionRepositoryCustomizer`
```java
@Bean
public SessionRepositoryCustomizer<JdbcIndexedSessionRepository> sessionRepositoryCustomizerOne() {
	return (sessionRepository) -> sessionRepository.setDeleteSessionsByExpiryTimeQuery(""
					+ "DELETE FROM %TABLE_NAME% "
					+ "WHERE EXPIRY_TIME < ? "
					+ "AND MAX_INACTIVE_INTERVAL >= 0"
			);
}
```
