### ISSUE TITLE
2.5.0 - spring_session_attributes - "ERROR: operator does not exist: character = bytea"

### ISSUE THREAD

**Issue by jhg023** [spring-projects/spring-session#1857]
**Describe the bug**
Upgrading from version `2.4.3` of `spring-session-jdbc` to version `2.5.0` prevents new sessions from being inserted into a PostgreSQL database.

**To Reproduce**
 - Must be using Spring Boot 2.5.0 in your project.
 - The following `@Configuration` must be used in your Spring application (mine uses Kotlin):
```java
/**
 * Adapted from a 'spring-session' [GitHub issue](https://github.com/spring-projects/spring-session/issues/1213#issuecomment-699455928)
 * and a Postgres-specific [GitHub commit](https://github.com/candrews/spring-session/commit/4f38cb8dac5a2c393437f9aca3db03ab1680ae50#diff-e8e52e344ee4f1294748810bc5100cbeR190).
 */
@Configuration
class CustomPostgresSessionInsertConfig @Autowired constructor(
	private val jdbcIndexedSessionRepository: JdbcIndexedSessionRepository
) {
	companion object {
		private const val CREATE_SESSION_ATTRIBUTE_QUERY_ON_CONFLICT =
			"INSERT INTO %TABLE_NAME%_ATTRIBUTES(SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)" +
			"SELECT PRIMARY_ID, ?, ? FROM %TABLE_NAME% WHERE SESSION_ID = ? ON CONFLICT(SESSION_PRIMARY_ID, " +
			"ATTRIBUTE_NAME) DO UPDATE SET ATTRIBUTE_BYTES = EXCLUDED.ATTRIBUTE_BYTES;"
	}

	@PostConstruct
	fun customizedJdbcOperationsSessionRepository() {
		jdbcIndexedSessionRepository.setCreateSessionAttributeQuery(
			StringUtils.replace(
				CREATE_SESSION_ATTRIBUTE_QUERY_ON_CONFLICT,
				"%TABLE_NAME%",
				JdbcIndexedSessionRepository.DEFAULT_TABLE_NAME))
	}
}

```

**Expected behavior**
New sessions should be inserted into the database as they were in version `2.4.3`.

**Comment by jhg023** [comment]
I verified that version `1.4.200` of `h2` works as expected, but version `42.2.20` of `postgresql` does not.

**Comment by jhg023** [comment]
I've also just verified that, if I remove my `CustomPostgresSessionInsertConfig` entirely, then sessions are inserted just fine. That seems to indicate to me that one or more of the schemas updated recently. Is there any documentation on what changed, if anything?

**Comment by eleftherias** [comment]
Thanks for reaching out @jhg023.
I'm sorry to hear you're having trouble upgrading.

There have not been any recent schema updates, you can find all the 2.5.0 changes in the [2.5.0-M1](https://github.com/spring-projects/spring-session/releases/tag/2.5.0-M1), [2.5.0-RC1](https://github.com/spring-projects/spring-session/releases/tag/2.5.0-RC1) and [2.5.0](https://github.com/spring-projects/spring-session/releases/tag/2.5.0) release notes.

If you provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue, I can take a look at it.

**Comment by jhg023** [comment]
@eleftherias Thanks for the response!

It turns out that this may be a non-issue. I originally required this `Configuration` because concurrent requests were being resulting in a constraint violation on duplicate keys.

After removing this from our codebase, the constraint violation hasn't occurred, so it's possible that the underlying issue had been fixed by updating one of our other (many) dependencies.

For anyone that still has this issue, try updating your dependencies to their latest respective versions.

I'll close this issue for now, as I'm not able to reproduce the original bug after having removed the problematic code.
