### ISSUE TITLE
Hazelcast4IndexedSessionRepository.HazelcastSession does not save the PRINCIPAL_NAME_INDEX_NAME attribute

### ISSUE THREAD

**Issue by alienisty** [spring-projects/spring-session#1859]
When the SPRING_SECURITY_CONTEXT attribute is set, the HazelcastSession also sets the PRINCIPAL_NAME_INDEX_NAME attribute, but fails to add it to the delta Map and therefore it doesn't get saved.

**To Reproduce**
Create a new authenticated sesssion while using Hazelcast 4. FindByIndexNameSessionRepository.findByPrincipalName() will not find the session because the attribute is missing.

**Expected behavior**
The attribute is correctly saved and FindByIndexNameSessionRepository.findByPrincipalName() returns the expected session.

The fix is to put the PRINCIPAL_NAME_INDEX_NAME in the delta map:
```java
    @Override
    public void setAttribute(String attributeName, Object attributeValue) {
      this.delegate.setAttribute(attributeName, attributeValue);
      this.delta.put(attributeName, attributeValue);
      if (SPRING_SECURITY_CONTEXT.equals(attributeName)) {
        Map<String, String> indexes = Hazelcast4IndexedSessionRepository.this.indexResolver
          .resolveIndexesFor(this);
        String principal = (attributeValue != null) ? indexes.get(PRINCIPAL_NAME_INDEX_NAME) : null;
        this.delegate.setAttribute(PRINCIPAL_NAME_INDEX_NAME, principal);
        this.delta.put(PRINCIPAL_NAME_INDEX_NAME, principal); // <-- This is the fix
      }
      flushImmediateIfNecessary();
    }
```

**Comment by eleftherias** [comment]
Thanks for reaching out @alienisty. This appears to be a duplicate of #1801.
Could you please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

**Comment by alienisty** [comment]
Looking at #1801, it is exactly the same issue, sorry I didn't find it before creating this one.
I'll see if I can at least help providing a sample minimal project.

**Comment by eleftherias** [comment]
Thanks @alienisty.
It would be very helpful if you could provide a sample.
I will close this in favor of #1801 since you have confirmed it is the same issue.
Feel free to continue the discussion over on that issue.
