### ISSUE TITLE
Dynamic defaultMaxInactiveInterval in spring session

### ISSUE THREAD

**Issue by wapkch** [spring-projects/spring-session#1868]
**Expected Behavior**

If dynamic defaultMaxInactiveInterval session would be supported, it will be very useful in multi-tenancy.
Eg: 
Tenant A with a defaultMaxInactiveInterval as 3600s; 
Tenant B with a defaultMaxInactiveInterval as 7200s

**Current Behavior**

We can only configure defaultMaxInactiveInterval to a fixed value in `RedisIndexedSessionRepository`

**Context**

**Comment by eleftherias** [comment]
Thanks for reaching out @wapkch.

I don't think it makes sense to add this feature, as the `defaultMaxInactiveInterval` is meant to be a default value. 
If it is dynamic then it is no longer a default.

You can customize the interval on a per-session basis using `setMaxInactiveInterval` when you create the session.
