### ISSUE TITLE
MySql5JdbcIndexedSessionRepositoryITests fail on JDK 11.0.11

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-session#1877]
The MySql5JdbcIndexedSessionRepositoryITests fail on JDK 11.0.11 with the cause
```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
```

This is because JDK 11.0.11 disabled TLS 1.0 and 1.1, as documented in their [release notes](https://www.oracle.com/java/technologies/javase/11-0-11-relnotes.html).

This can be fixed by upgrading the MySQL docker image we use in our tests. 
The minimum version needed is 5.7.29.
We will update to the latest version (currently 5.7.34).

**Comment by spring-projects-issues** [comment]
Fixed via 21be7aac9cfabf06c8930cd7704bde6e34e9deeb
