### ISSUE TITLE
Spring Security Remember Me Integration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#189]
https://jira.spring.io/browse/SEC-2939

**Comment by coco1979ka** [comment]
How is the current state for this issue? I think your suggestion in https://jira.spring.io/browse/SEC-2939 will not work, as this is not a real remember me - it only works as long as the browser is opened. If you close and reopen it, the session cookie (similar to JSESSION cookie) is invalid. Is it possible to send the Session Cookie with a fixed expiration time?

**Comment by ptahchiev** [comment]
:+1: on this one

**Comment by rwinch** [comment]
Fixed via #667
