### ISSUE TITLE
IllegalArgumentException running websocket sample

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-session#191]
```
./gradlew :samples:websocket:bootRun
```
fails with an exception caused by:
```
java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.redis.port' in string value "${spring.redis.port}"
```
I'm assuming from the docs that this should run without having to set any properties.

**Comment by rwinch** [comment]
Thanks for the report. This happened in 865e381c7c314c1d8b1968a1d64935c92fd10d87

To resolve the issue we need to ensure `@EnableEmbeddedRedis` is added to a configuration Boot picks up. I have fixed this in master now.
