### ISSUE TITLE
Deserialization failures related to Spring Security

### ISSUE THREAD

**Issue by fbeaufume** [spring-projects/spring-session#1924]
**Describe the bug**

The default serialization mechanism used by Spring Session Redis (i.e. Java serialization) fails when the serialVersionUID of our session data change such as SecurityContextImpl from Spring Security.

**To Reproduce**

1. Successfully run a Spring Boot 2.3 web application with Spring Session Redis and Spring Security. Some sessions get stored in Redis.
2. Stop the application to upgrade to Spring Boot 2.4 (this changes org.springframework.security.core.SpringSecurityCoreVersion.SERIAL_VERSION_UID used as serialVersionUID in org.springframework.security.core.context.SecurityContextImpl)
3. Run the application and use existing sessions stored in Redis. BOOM! See exception sample bellow.

Exception sample:

```
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize;
nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?;
nested exception is java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 530, local class serialVersionUID = 540
```

**Expected behavior**

No such failure and/or clear warnings in the documentation. 

Once we met and understood the issue, we quickly fixed it using a custom serializer. But since it happened on a Spring Boot 2nd digit upgrade (a relatively rare change) it was difficult to anticipate and hurt the application reliability.

**Comment by PhilJay** [comment]
Happened to us after update. 30k users logged out
Whats the best way to prevent this?

**Comment by eleftherias** [comment]
@PhilJay You may find it useful to switch to Jackson serialization to avoid this issue in future version upgrades. See https://github.com/spring-projects/spring-security/issues/3736.

**Comment by benjamin-thomas** [comment]
> You may find it useful to switch to Jackson serialization to avoid this issue in future version upgrades

Hello @eleftherias. I've hit this same annoying issue in my project, using the artifact `spring-session-jdbc` and upgrading to the latest spring-boot version. A surprising default behavior!

Could you provide a little more info on how to proceed? I failed to find any useful documentation or a running example showing how to serialize the session.

Thanks :)
