### ISSUE TITLE
Why ? I can't find the org.springframework.session.redis.embedded.EmbeddedRedisConfiguration class?

### ISSUE THREAD

**Issue by LonggangBai** [spring-projects/spring-session#193]
Dear ALL!
    I gradle the project but I can't the org.springframework.session.redis.embedded.EmbeddedRedisConfiguration class,Please help me ?

**Comment by LonggangBai** [comment]
I find it in samples

**Comment by rwinch** [comment]
I see  you closed this issue already, so you likely figured out the issue. For others finding this issue see  #190
