### ISSUE TITLE
Rename local variable name to enableRedisHttpSessionAnnotation

### ISSUE THREAD

**Issue by dima767** [spring-projects/spring-session#194]
From `enableWebSecurityAnnotation` to `enableRedisHttpSessionAnnotation`. This is most likely a simple "copy-paste" overlook.

https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java#L128

**Comment by rwinch** [comment]
Thanks for the report! This is now fixed in master
