### ISSUE TITLE
Allow springSessionRedisMessageListenerContainer to be switched off if session event publication is unneccassary 

### ISSUE THREAD

**Issue by chinthakadd** [spring-projects/spring-session#1992]
**Expected Behavior**

`springSessionRedisMessageListenerContainer` can be configured to be enabled or disabled depending on developer need. Though this supports HTTP Session Event Publication, it is not a common need for all Redis session implementations. This listener configuration could lead to extrapolated session event listener calls when application is running multiple containers in a high throughput environment. Therefore 

**Current Behavior**

Currently `springSessionRedisMessageListenerContainer` is enabled by default, configured in `RedisHttpSessionConfiguration.java` as a default Bean with any conditional logic. Trying to disable this Listener also was not possible by invoking `stop()` or `destroy()` and noticed that the TaskExecutor is still active and listening to events.

**Context**

We noticed high CPU utilization in our background threads when application is facing high throughput and `springSessionRedisMessageListenerContainer` Task Executor threads showed up in the analysis.

Doing further analysis on this, realized how it could affect entire application performance. Since listener is subscribed to Session Created and Destroyed events on the particular key namespace of Spring Session, session events related to all containers gets published to all containers. This can really tax the network, IO and CPU. If the application is not interested in the session events, can we allow the application disable them? 

Ex: If we create 10 containers and each container is creating 100 Sessions per second and destroy 100 sessions per second, there will be fire 10 * 100 * 2 = 2000 Messages being listened by each container though each container only manages  100 sessions at a time. 

It is great if we can disable it if we are not interested in this session events across containers (if sticky sessions are enabled at the load balancer layer) from the HTTP Sessions in order to reduce CPU/ IO / Network performance.

References related to same issue that I found:

https://www.slideshare.net/RedisLabs/redis-day-tlv-2018-spring-session-redis
Under # 6 - discusses about disabling the Listener, this option is no longer working with Spring Session Data Redis 2.5.2
https://medium.com/@odedia/production-considerations-for-spring-session-redis-in-cloud-native-environments-bd6aee3b7d34
Blog Article on the same.

PS: While attempting workarounds, one option I found is to extend `RedisHttpSessionConfiguration`, override `springSessionRedisMessageListenerContainer()` bean method and return a Null Bean.

**Comment by vpavic** [comment]
@chinthakadd, are you aware that Spring Session offers a simpler alternative to `RedisIndexedSessionRepository` which is [`RedisSessionRepository`](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionRepository.java), that only implements basic `SessionRepository` functionality and doesn't support publishing of session events?

It requires some manual configuration, but there's [a sample available](https://github.com/spring-projects/spring-session/tree/main/spring-session-samples/spring-session-sample-boot-redis-simple) to demonstrate that.

**Comment by chinthakadd** [comment]
@vpavic  Thank you for pointing me to it. It is exactly what I was looking for..

However, when I tried it out and ran the sample from `main` branch.  It provides the following error.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method sessionRepositoryFilterRegistration in org.springframework.boot.autoconfigure.session.SessionRepositoryFilterConfiguration required a bean of type 'org.springframework.session.web.http.SessionRepositoryFilter' that could not be found.
```

It seems like since `sessionRepository` bean is provided by default by the `RedisHttpSessionConfiguration` and the `springSessionRedisMessageListenerContainer` comes also by default without a conditional property, it would become an issue when we try to use the `RedisSessionRepository` instead. Any suggestions to work around this issue?

**Comment by vpavic** [comment]
Not really sure how you're running the sample (or if you made some changes) but it works fine for me. I'm starting it using `./gradlew :spring-session-sample-boot-redis-simple:bootRun`.

**Comment by chinthakadd** [comment]
I ran it differently which was the issue. Running it with the above Gradle Command worked nicely. Thanks for helping out with this @vpavic
