### ISSUE TITLE
Redis Pub/Sub connection failure

### ISSUE THREAD

**Issue by ET02720** [spring-projects/spring-session#1995]
In our project with use spring session (2.6.1), spring boot (2.6.2) and spring data redis (2.6.0).
For network policy purpose, we disabled Key Notifications (providing a bean ConfigureRedisAction.NO_OP).
(Our Redis server is behind Firewall that closes connections after some inactive time to avoid remaining connection)

This behavior introduces following error

```
Connection failure occurred. Restarting subscriptio
n task after 5000 ms
Exception in thread "springSessionRedisMessageListenerContainer-20" java.lang.NullPointerException
        at redis.clients.jedis.BinaryJedisPubSub.psubscribe(BinaryJedisPubSub.java:57)
        at org.springframework.data.redis.connection.jedis.JedisSubscription.doPsubscribe(JedisSubscription.java
:59)
        at org.springframework.data.redis.connection.util.AbstractSubscription.pSubscribe(AbstractSubscription.j
ava:159)
        at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask$PatternSubscri
ptionTask.run(RedisMessageListenerContainer.java:707)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Reading spring session code, I saw that spring session open a pSubscribe command on redis to track Redis keys lifecycle.
This connection is closed by our Firewall so for me the error is normal.

But as we don't want to use Key Notifications is there a way to configure spring session to not perform pSubscribe on Redis Server so this error doesn't append.

Thanks

**Comment by eleftherias** [comment]
Thanks for reaching out @ET02720. Do you have a sample that reproduces this error?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by vpavic** [comment]
@chinthakadd, are you aware that Spring Session offers a simpler alternative to `RedisIndexedSessionRepository` which is [`RedisSessionRepository`](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionRepository.java), that only implements basic `SessionRepository` functionality and doesn't support publishing of session events?

It requires some manual configuration, but there's [a sample available](https://github.com/spring-projects/spring-session/tree/main/spring-session-samples/spring-session-sample-boot-redis-simple) to demonstrate that.

**Comment by ET02720** [comment]
@vpavic I tried to found something like this but didn't succeed. Thanks for the tip. I ll look at the sample.

**Comment by ET02720** [comment]
It did the trick in deed.
Thank you very much.
We can close the issue.

**Comment by sureshne** [comment]
@ET02720 we are also facing same issue, please know how to resolve
