### ISSUE TITLE
How to configure spring-session to support the HeaderHttpSessionStrategy and CookieHttpSessionStrategy in one application?

### ISSUE THREAD

**Issue by jingxiang** [spring-projects/spring-session#205]
scene :
native app ---> H5   or H5---->native app

does spring-session have the plan to include those scene?

**Comment by rwinch** [comment]
The tricky part is determining in a generic way which one should be used. I'd be interested in finding out how you want to determine when each strategy is used.

If you are looking for an example of how to do this, you can take a look at [SmartHttpSessionStrategy](https://github.com/rwinch/spring-state-securing-restful-apis/blob/master/messages-session/src/main/java/session/SmartHttpSessionStrategy.java) From my State of Securing RESTful APIs talk.

**Comment by jingxiang** [comment]
@rwinch Thanks for your response.Your example is very helpfull.

My scene is to keep app session status synchronized with broswer session status,so customer can jump from native app to H5(or pc web pages) easily as they don't need to login again.

For api  i chosed `HeaderHttpSessionStrategy`,  and `CookieHttpSessionStrategy` for  browser.

Is it possible for spring-session to provide a new strategy(or other ways) to merge header `x-auth-token` and cookie `SESSION` that can support multiple terminals session?

**Comment by misawsneto** [comment]
one thing that worked for me was to reimplement the ***HttpSessionStrategy using code from both Cookie and Header implementations.

you can see the concrete implementation of these classes here:

https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/web/http/HeaderHttpSessionStrategy.java
https://raw.githubusercontent.com/spring-projects/spring-session/master/spring-session/src/main/java/org/springframework/session/web/http/CookieHttpSessionStrategy.java

so the `getRequestedSessionId` becomes:

```java
public String getRequestedSessionId(HttpServletRequest request) {
        // header part
        String sessionId = request.getHeader(headerName);
        if(sessionId != null && !sessionId.isEmpty())
            return sessionId;

        // cookie part
        Map<String,String> sessionIds = getSessionIds(request);
        String sessionAlias = getCurrentSessionAlias(request);
        return sessionIds.get(sessionAlias);
    }
```

`onInvalidateSession` becomes:

```java
public void onInvalidateSession(HttpServletRequest request, HttpServletResponse response) {
    // header part
    response.setHeader(headerName, "");

    // cookie part
    Map<String,String> sessionIds = getSessionIds(request);
    String requestedAlias = getCurrentSessionAlias(request);
    sessionIds.remove(requestedAlias);

    Cookie sessionCookie = createSessionCookie(request, sessionIds);
    response.addCookie(sessionCookie);
}
```

`onNewSession` becomes:

```java
public void onNewSession(Session session, HttpServletRequest request, HttpServletResponse response) {
        // header part
        response.setHeader(headerName, session.getId());

        // cookie part
        Set<String> sessionIdsWritten = getSessionIdsWritten(request);
        if(sessionIdsWritten.contains(session.getId())) {
            return;
        }
        sessionIdsWritten.add(session.getId());

        Map<String,String> sessionIds = getSessionIds(request);
        String sessionAlias = getCurrentSessionAlias(request);
        sessionIds.put(sessionAlias, session.getId());
        Cookie sessionCookie = createSessionCookie(request, sessionIds);
        response.addCookie(sessionCookie);
    }
```
I have used this in production for a browser/mobile REST API and suits all my needs.

**Comment by michaelwiles** [comment]
Is it not simpler to build a multi session strategy that just defers to both each time?
