### ISSUE TITLE
Principal synchronisation after session setup?

### ISSUE THREAD

**Issue by uvifian** [spring-projects/spring-session#206]
I was wondering how the principal of a session is being synchronized across nodes. Is this done once when the session is created in the first place or even when the principal is modified later on? Yes, modifying the principal sounds rather odd, we use this to impersonate another user temporarily.

**Comment by rwinch** [comment]
This depends a little on the repository implementation as we want implementations to be better optimized for different situations (similar to how you might use a HashSet vs a TreeSet for a Collection).

The Redis implementation will keep track of the changed attributes for every request. It recognizes a change whenever a session attribute is set. It will NOT recognize setting properties on something in session already. For example, the following will NOT be saved:

```java
MyObject anyValue = request.getSession().getAttribute("any name");
```

To get the value to save, you must set the attribute

```java
request.getSession().setAttribute("any name", anyValue);
```

The value is persisted as soon as the response is committed (i.e. the OutputStream is flushed) AND as soon as the SessionRepositoryFilter is executed. See #198 for details on why that is necessary.

I'm going to close this question as I believe I have covered it. If you have follow up questions, feel free to reopen the issue.
