### ISSUE TITLE
Hazelcast + SessionDestroyedEvent

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-session#208]
I've been working on integrating with Hazelcast and having session expiry/deletion fire SessionDestroyedEvent.

For now all I have had to add is a Hazelcast IMap EntryListener implementation that publishes SessionDestroyedEvents.

I would start work on a PR if this is something you would be interested in adding to the main project. Either in the main code or as a sample?

**Comment by tsachev** [comment]
:+1 for the Hazelcast support will be great to see it in the next version if possible.

**Comment by manderson23** [comment]
I've posted my sample at https://github.com/manderson23/spring-session-hazelcast

**Comment by eladh** [comment]
Great Example , 10x :-)

**Comment by shakuzen** [comment]
:+1:

**Comment by manderson23** [comment]
I guess #274 and #277 cover this.

**Comment by rwinch** [comment]
Good call @manderson23 I will close in favor of those issues
