### ISSUE TITLE
Documentation implies @EnableEmbeddedRedis annotation is supplied by library

### ISSUE THREAD

**Issue by sgrimm-sg** [spring-projects/spring-session#209]
The example code in the Spring Session documentation doesn't compile as presented because neither of the two dependencies the documentation instructs me to include in my pom.xml (spring-session-data-redis and spring-web) provides the EnableEmbeddedRedis annotation. From poking around the example source code and some previously filed issues on Github, that annotation seems to come from a subproject in the samples directory and isn't intended to be used by anything real.

This should at least be mentioned in the text of the documentation, since the implication right now is that the annotation is supplied by Spring Session. The annotation on the next line of code in the basic examples is EnableRedisHttpSession which Spring Session does provide, and the availability of the two annotations isn't differentiated at all in the accompanying text.

This isn't a request to make that annotation generally available; I understand the reasons why it's part of the samples. The issue is that there's no mention that the code snippets in the documentation aren't workable standalone examples. My usual expectation when I read a "getting started" guide is that I can try out the sample code in my own application if I supply the dependencies specified by the instructions, and I spent a good fifteen minutes trying to figure out what extra Spring library I needed to include to get EnableEmbeddedRedis.

**Comment by bladedpenguin** [comment]
I had the same issue.  It would be nice to know what is going on.

**Comment by Endron** [comment]
I too run into this problem.
This guide at no point says how to get the missing dependency: http://docs.spring.io/spring-session/docs/1.0.1.RELEASE/reference/html5/guides/rest.html

**Comment by rwinch** [comment]
This issue is no longer valid in the latest snapshots since we have removed embedded redis. See #248
