### ISSUE TITLE
IndexResolver and ConfigureRedisAction qualify as functional interfaces

### ISSUE THREAD

**Issue by andreistefanwork** [spring-projects/spring-session#2095]
Hi all,

Both `IndexResolver` and `ConfigureRedisAction` qualify as functional interfaces

The proposal is to annotate them with the informative `@FunctionalInterface` annotation

**Comment by andreistefanwork** [comment]
I created a pull request for the proposed changes [PR](https://github.com/spring-projects/spring-session/pull/2097)

**Comment by marcusdacoregio** [comment]
Closed [with comment](https://github.com/spring-projects/spring-session/pull/2097#issuecomment-1703170724)
