### ISSUE TITLE
Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is java.lang.IllegalStateException: Subscription registration timeout exceeded.

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-session#2098]
springboot 2.7.0

upgrade to springboot 2.7.0 Project could not be started

```
Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is java.lang.IllegalStateException: Subscription registration timeout exceeded.
```

https://github.com/spring-projects/spring-boot/issues/31138

**Comment by leshalv** [comment]
After testing, it should be a `redisson` problem, and there is no such problem without integrating `redisson`.

**Comment by aaa2281002** [comment]
Please take a look：https://github.com/spring-projects/spring-session/issues/2452
