### ISSUE TITLE
MongoDB integration tests are failing

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#2118]
Some GitHub Actions runs where this happens:
- https://github.com/spring-projects/spring-session/actions/runs/2836126141
- https://github.com/spring-projects/spring-session/actions/runs/2838269872

The same issue happens for me locally.

**Comment by vpavic** [comment]
This is apparently related to some recent changes in the Spring Framework. If I set the Framework dependency to `6.0.0-M5` then these tests are passing, but with `6.0.0-SNAPSHOT` (which is what [`3.0.x` uses](https://github.com/spring-projects/spring-session/blob/812ac239c047a806afe06aede42f5dea2d5aac4d/gradle/dependency-management.gradle#L6) currently) they're failing.

**Comment by vpavic** [comment]
This is due to https://github.com/spring-projects/spring-security/issues/6613. I'm preparing the PR to adjust usage of Spring Security in various tests within the Spring Session codebase.

**Comment by rwinch** [comment]
Closing in favor of gh-2125
