### ISSUE TITLE
Add an option to expire a session a certain amount of time after creation

### ISSUE THREAD

**Issue by cshannon** [spring-projects/spring-session#212]
It would be really useful to be able to expire a session (plus associated websocket connections) after a session is a certain age, regardless of last access time.  This would be equivalent to a cache "expireAfterWrite" setting.  

The specific use case I have in mind is when using Spring Security I would like to be able to set a maximum time that a Session can be alive before it expires and a user must be re-authorized .  While usually not an issue, sometimes a session can stay open a long time and not expire if a user doesn't close their browser (do to polling channels, etc).

**Comment by vpavic** [comment]
Closing as won't fix as we've had similar requests in the meanwhile - for example, see the discussion on #922.
