### ISSUE TITLE
support self-definition SessionIdGenerator

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-session#2120]
MapSession 
![image](https://user-images.githubusercontent.com/29112991/184321949-f916d3d5-ebdb-4024-ad78-0c0dd6872655.png)

**Comment by imaxun** [comment]
hope support self-determination meeting id strategy

**Comment by imaxun** [comment]
每人维护了么

**Comment by imaxun** [comment]
没人维护了么

**Comment by imaxun** [comment]
why?

**Comment by marcusdacoregio** [comment]
Duplicate of #11
