### ISSUE TITLE
Review OWASP cheat sheets on session management

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#2121]
We should probably review the OWASP cheat sheets on session management in order to see if there are any practices that are beneficial and practical for Spring Session to align with.

Relevant links:
- https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html

**Comment by marcusdacoregio** [comment]
It doesn't seem that there is anything that we could add into Spring Session for now.
