### ISSUE TITLE
 the object can't save into redis if the java class not implements Serializable 

### ISSUE THREAD

**Issue by fglbee** [spring-projects/spring-session#213]
the object can't save into redis if the java class not implements Serializable 
the dwr object is not implements Serializable ,so spring-session and the dwr can't not be used together

**Comment by chrylis** [comment]
Requiring all session attributes to be serializable is nearly universal, and I don't know any session store that will save non-serializable objects.

**Comment by tapanjaggi** [comment]
If you use some serializer like Kryo in you redis template, there is no limitation on attributes to be serializable.

in your config class:
    public RedisTemplate redisTemplate() {
        RedisTemplate redisTemplate = new RedisTemplate();
        redisTemplate.setConnectionFactory(jedisConnectionFactory());
        redisTemplate.setDefaultSerializer(new KryoObjectSerializer());
        return redisTemplate;
    }

public class KryoObjectSerializer implements RedisSerializer<Object> {
	@Override
	public byte[] serialize(Object obj) throws SerializationException {
		byte[] bytes = null;
		try {
			bytes = convertToByteArray(obj);
		} catch (IOException e) {
			throw new SerializationException("failed to serialize", e);
		}
		return bytes;
	}

	@Override
	public Object deserialize(byte[] bytes) throws SerializationException {
		
		Object obj = convertToObject(bytes);
		return obj;
	}

	}

**Comment by sameerjfreaks** [comment]
Hey, is there a way that I can exclude some classes from getting stored in redis
