### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-session#2135]
The documentation links are broken as of Aug 29, 2022.

E.g.: https://docs.spring.io/spring-session/reference/2.7.0/index.html

<img width="522" alt="image" src="https://user-images.githubusercontent.com/685363/187391005-6c82aacc-41a1-403e-912c-cac5b539cdba.png">

The `2.6.x` and the `2.7.x` version folders under https://docs.spring.io/spring-session/docs/ are missing the `reference` folder. The `api` folder is there, though.

**Comment by rwinch** [comment]
There appears to still be an issue with the URL https://docs.spring.io/spring-session/reference/2.7.0/index.html but other URLs are now working (i.e. https://docs.spring.io/spring-session/reference/2.7/index.html) . It appears to be an issue with the the server configuration.

**Comment by marcusdacoregio** [comment]
The URLs mentioned are now working, thanks for the report.
