### ISSUE TITLE
Autowired HttpServletRequest & HttpSession Refer to original request & session

### ISSUE THREAD

**Issue by xfcjscn** [spring-projects/spring-session#214]
Autowired HttpServletRequest & HttpSession refer to native request & session instead of wrappered version. This make the http session can not be used with annotation: Autowired

**Comment by xfcjscn** [comment]
This happens in for rest request to CXF. 
I think this can be closed, it should due to a CXF bug, it didn't update spring's RequestContextHolder(annotation get request from it) after the filter execution(filter wrapped the native reqeust).

**Comment by rwinch** [comment]
Thanks for the follow up. Closing per your request
