### ISSUE TITLE
spring session redis ConfigureRedisAction.NO_OP not working

### ISSUE THREAD

**Issue by ohHyunJae** [spring-projects/spring-session#2178]
according to the document https://docs.spring.io/spring-session/reference/api.html

If you use @EnableRedisHttpSession, managing the SessionMessageListener and enabling the necessary Redis Keyspace events is done automatically. However, in a secured Redis enviornment, the config command is disabled. This means that Spring Session cannot configure Redis Keyspace events for you. To disable the automatic configuration, add ConfigureRedisAction.NO_OP as a bean.

```
implementation 'org.springframework.session:spring-session-data-redis:2.7.0'
implementation 'io.lettuce:lettuce-core:6.2.0.RELEASE'

@Configuration
public class RedisConfig {
    @Bean
    public LettuceConnectionFactory lettuceConnectionFactory() {
        RedisStandaloneConfiguration standaloneConfiguration
                = new RedisStandaloneConfiguration("ip", port);
        standaloneConfiguration.setPassword("password");
        return new LettuceConnectionFactory(standaloneConfiguration);
    }
}

@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 60 * 1)
public class HttpRedisSessionConfig {
    @Bean
    ConfigureRedisAction configureRedisAction() {
        return ConfigureRedisAction.NO_OP;
    }
}

@Component
public class RedisSessionListener {

    @EventListener
    public void onCreate(SessionCreatedEvent event) {
        System.out.println("create!!");
        System.out.println(event);
    }

    @EventListener
    public void onDestroy(SessionDestroyedEvent event) {
        System.out.println("destory!!");
        System.out.println(event);
    }

}
```
but

like the picture below I still receive the expiry event.

enter image de
![스크린샷 2022-10-07 오후 10 06 13](https://user-images.githubusercontent.com/18163630/194755091-e7e1513e-3dd6-4a1c-86c9-aa8c912bf0c5.png)
scription here

and

### It still calls the cleanExpiredSessions(); method periodically.

What should I do?

**Comment by marcusdacoregio** [comment]
Hi, @ohHyunJae. If your Redis instance is configured to emit the events, Spring Session Redis will listen. Configuring `ConfigureRedisAction.NO_OP` only means that Spring Session won't try to configure the Redis instance for you.

> It still calls the cleanExpiredSessions(); method periodically.

You can disabled it by using `@EnableRedisIndexedHttpSession(cleanupCron = Scheduled.CRON_DISABLED)`
