### ISSUE TITLE
Upgrade 'spring - cloud - alibaba met injection problem in the process of' org. Springframework. Session. ReactiveSessionRepository that could not be found '

### ISSUE THREAD

**Issue by luankun88** [spring-projects/spring-session#2196]
**A version number**

org.springframework.boot spring-boot-starter-parent 2.7.1
<spring-cloud.version>2021.0.3</spring-cloud.version>

<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>

<dubbo.version>2.7.18</dubbo.version>

<spring-cloud-starter-oauth2.version>2.1.2.RELEASE</spring-cloud-starter-oauth2.version>
<spring-cloud-starter-security.version>2.1.2.RELEASE</spring-cloud-starter-security.version>

**spring-session version number**
![image](https://user-images.githubusercontent.com/29765300/197320400-93894e20-6218-4a8c-ab7c-b1b3fa7b1e2a.png)

**The error message**

2022-10-22 12:32:05.175 ERROR 17736 --- [ main] o.s.b.d.LoggingFailureAnalysisReporter :

APPLICATION FAILED TO START

Description:

Parameter 0 of method webSessionManager in org.springframework.session.config.annotation.web.server.SpringWebSessionConfiguration required a bean of type 'org.springframework.session.ReactiveSessionRepository' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.session.ReactiveSessionRepository' in your configuration.

**Comment by marcusdacoregio** [comment]
Hi @luankun88, thanks for the report.

Can you provide a minimal, reproducible sample so it is easier to have the same behavior when testing on our side?

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
