### ISSUE TITLE
Netty Integration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#22]

**Comment by truemany** [comment]
It means that spring session works well with netty?

**Comment by rwinch** [comment]
@truemany It means we want to provide seamless integration with Netty, but do not yet have it (this is stil sopen)

**Comment by vpavic** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.
