### ISSUE TITLE
In 3.0.0 HeaderHttpSessionIdResolver resolveSessionIds method have System.out.println

### ISSUE THREAD

**Issue by khiker007** [spring-projects/spring-session#2215]
In spring-session-core:3.0.0,HeaderHttpSessionIdResolver resolveSessionIds method have System.out.println,suggest remove it

**Comment by khiker007** [comment]
https://github.com/spring-projects/spring-session/blob/df3f9a386ec585557a9e1a7cd7ee65dd5c9eb80e/spring-session-core/src/main/java/org/springframework/session/web/http/HeaderHttpSessionIdResolver.java#L101

**Comment by marcusdacoregio** [comment]
Before the patch release is out, you can configure a copy of `HeaderHttpSessionIdResolver` that does not contain the print line:

```java
@Bean
public HttpSessionIdResolver httpSessionIdResolver() {
	return new MyHeaderHttpSessionIdResolver("my-header");
}

class MyHeaderHttpSessionIdResolver implements HttpSessionIdResolver {

	// ...

	@Override
	public List<String> resolveSessionIds(HttpServletRequest request) {
		String headerValue = request.getHeader(this.headerName);
		return (headerValue != null) ? Collections.singletonList(headerValue) : Collections.emptyList();
	}

        // ...

}
```
