### ISSUE TITLE
Compile sources with '-parameters' to retain method parameter names

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-session#2219]
Warning show up when upgrade to spring boot 3.0
```
o.s.c.LocalVariableTableParameterNameDiscoverer WARN Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration
```

**Comment by quaff** [comment]
Superseded  by https://github.com/spring-projects/spring-session/pull/2252

**Comment by marcusdacoregio** [comment]
Hi @quaff,

I am not seeing this warning, can you help me reproduce it?

In addition to that, if you are using IntelliJ IDEA, can you check under Settings > Build, Execution, Deployment > Compiler > Java Compiler, if you are not using `-debug` as compilation options?

**Comment by quaff** [comment]
> Hi @quaff,
> 
> I am not seeing this warning, can you help me reproduce it?
> 
> In addition to that, if you are using IntelliJ IDEA, can you check under Settings > Build, Execution, Deployment > Compiler > Java Compiler, if you are not using `-debug` as compilation options?

It's recommended to use `-parameters` for reflection, my own code always complied with parameters, the warning reported by spring is come from 3rd party jars such as spring-session, it should be fixed at their side.

**Comment by quaff** [comment]
I didn't notice this warning recently, It probably fixed by spring-framework.
