### ISSUE TITLE
Potential Security Issue with multiple Context Paths within the same application

### ISSUE THREAD

**Issue by benneq** [spring-projects/spring-session#222]
I have a Spring application with Spring Session 1.0.1.RELEASE.
My Spring app uses multiple context-path, each with own users.

Long story short:

I open `/foo/test` , it asks for authentication , after that I get a Session with `Path=/foo/`.
When I open `/bar/test` , it asks for authentication , and then I get a second cookie with `Path=/bar/`.
That's fine and works correctly.

But of course I'm a malicious user. So I took the Cookie with `Path=/bar/` and change that to `Path=/baz/` (using `EditThisCookie` app in Chrome).
Now I call `/baz/test` and I'm logged in!

This of course happens, because it's all within the same application, and Spring Session just sees that it's a valid session id.
Though I suggest, to also validate the `contextPath`.

Or at least some method I can override to enforce this validation myself.

Thank you.

**Comment by benneq** [comment]
I now solved it this way:

```
MapSessionRepository sessionRepository = new MapSessionRepository() {
	@Override
	public void save(ExpiringSession session) {
		session.setAttribute("contextPath", CURRENT_CONTEXT_PATH);
		super.save(session);
	}
	@Override
	public ExpiringSession getSession(String id) {
		ExpiringSession session = super.getSession(id);
		if(Optional.ofNullable(session).map(s -> s.getAttribute("contextPath")).filter(val -> val.equals(CURRENT_CONTEXT_PATH)).isPresent()) {
			return session;
		}
		delete(id);
		return null;
	}
};
```

**Comment by rwinch** [comment]
Thanks for the report!

It looks like you are using `MapSessionRepository`? If so, each application that wants its own namespace can provide its own `Map` instance so the session keys are distinct.

If you are speaking about using Redis, then I do see an issue here. Although not obvious from searching through issues, I think this is related if not a duplicate of #166. If we made it possible to ensure that the application looked up the session keys in isolation, then this would be resolved with no problem.

Thoughts?

**Comment by benneq** [comment]
The kind of repository shouldn't matter in this case.

I have an application at the root of Tomcat. This application has by default the "/" contextPath.
But it's a multitenancy application, though I have injected a filter, that modifies the contextPath for each tenant.
Example: GET /foo/bar will become GET /bar with contextPath /foo.

This way each tenant can have a completely own database with own user. No data at all is shared.

Now the problem is, that Spring Session will just see each user as a user of the application with no respect to the contextPath.

Of course this in a edge case, and I could also have used Subdomains instead of URL Path, e.g. foo.mydomain.org/bar instead of mydomain.org/foo/bar.

Though it seems like it may be a duplicate of #166 . I basically just need some way to provide an additional session identifier, that (in my case) isn't part of the cookie, but will just come from within the backend.

**Comment by rwinch** [comment]
Thanks for your reply. It sounds to me as though you have two options if you want to support multi tenancy:

* Change the datastore being used per client
* Change your authorization logic to ensure that the tenant that is authenticated has access

Neither of these sound like a Spring Session issue to me.

**Comment by rwinch** [comment]
I'm closing this as invalid. If you disagree, please make a case for why this should be in Spring Session and the above solutions will not work for you.

**Comment by juzerali** [comment]
It is not always easy to change the datastore being used per client. Mainly due to infrastructural overheads. We have a 5 instances redis cluster deployed on production and we have several applications using them. In a clustered environment, redis does not support separate datastores or databases. Only option remains is to deploy a redis cluster for every application that uses `spring-session` which is an overkill. This problem could have been best solved if session prefix for each application was configurable.

**Comment by rwinch** [comment]
@juzerali Thanks for your feedback. You can now isolate the session per application. See [@EnableRedisHttpSession.redisNamespace](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-config)

**Comment by juzerali** [comment]
@rwinch I realised that after making the above comment. Thanks, spring rocks :+1:
