### ISSUE TITLE
spring-session 3.0.1 is not available in maven central 

### ISSUE THREAD

**Issue by TolstovM** [spring-projects/spring-session#2224]
**spring-session 3.0.1 is not available in maven central **
Please release it.

![image](https://user-images.githubusercontent.com/44347121/213187870-97f97d34-98f8-40f6-b238-eb51a1337255.png)

**Comment by DidierLoiseau** [comment]
3.0.1 is due in March 🤔

https://github.com/spring-projects/spring-session/milestone/130
https://calendar.spring.io/

**Comment by TolstovM** [comment]
Thank for your answer!

Is there any chances to release it earlier?
Because it's impossible to use it production, because of this issue https://github.com/spring-projects/spring-session/issues/2215
It creates too much logs...

**Comment by marcusdacoregio** [comment]
Hi @TolstovM, thanks for the report.

It didn't get released earlier but I'll see to release it the next week. I'll keep you posted here.

**Comment by marcusdacoregio** [comment]
Hello folks, we will stick to the schedule and release 3.0.1 in March since the workaround for #2215 is pretty simple. Please refer to this comment for a solution https://github.com/spring-projects/spring-session/issues/2215#issuecomment-1398312221
