### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [spring-projects/spring-session#2231]
## Description

In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by marcusdacoregio** [comment]
Thanks a lot, @jongwooo, there is another PR for fixing this, so I'll close this as a duplicate of #2226.
