### ISSUE TITLE
required a bean of type 'org.springframework.session.FindByIndexNameSessionRepository' that could not be found

### ISSUE THREAD

**Issue by royalzzz** [spring-projects/spring-session#2235]
**Describe the bug**
Recently, our team is considering spring's upgrade and migration plan. We have adopted the latest version of the Spring project to better adapt to the changes in the spring boot 3.0 version. However, when configuring Spring Concurrent according to the document [Spring Security Concurrent Session Control](https://docs.spring.io/spring-session/reference/spring-security.html#spring-security-concurrent-sessions), we encountered an unexpected problem. `FindByIndexNameSessionRepository` seems to be unable to inject normally, which is not a problem in the 2. x version. In addition, I provided some samples later to reproduce this problem.

The following is the version of my package dependency management.

```xml
<properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <spring-cloud.version>2022.0.1</spring-cloud.version>
    <spring-boot.version>3.0.2</spring-boot.version>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>${spring-cloud.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>${spring-boot.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-bom</artifactId>
            <version>${spring-cloud.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.24</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

The following is the program running error prompt.

```
required a bean of type 'org.springframework.session.FindByIndexNameSessionRepository' that could not be found.
```

**To Reproduce**
According to the steps of the web page [Spring Security Concurrent Session Control](https://docs.spring.io/spring-session/reference/spring-security.html#spring-security-concurrent-sessions)

#
**Sample**

Here is a sample project link to my GitHub repository. [concurrent-session-sample](https://github.com/royalzzz/concurrent-session-sample).

**Comment by royalzzz** [comment]
Did I miss any steps or configurations？

**Comment by marcusdacoregio** [comment]
Hi @royalzzz, thanks for the report.

I think you need `@EnableRedisIndexedHttpSession` instead of `@EnableRedisHttpSession`?

**Comment by royalzzz** [comment]
ohhhhhh, it works!  Thanks! 🙂 I can't see any guide about `@EnableRedisIndexedHttpSession` in the official document.

**Comment by pulse00** [comment]
@marcusdacoregio we faced the same issue. Do you have any background information on this change? I could not find anything in release notes. For us, this change brings some problems too, because we would like to configure the session timout via property files.

But it seems that now since you need to use `EnableRedisIndexedHttpSession` in order to get a `RedisIndexedSessionRepository` bean, you cannot use `spring.session.timeout` property anymore, but must hardcode `maxInactiveIntervalInSeconds` on the `EnableRedisIndexedHttpSession` annotation.

**Comment by marcusdacoregio** [comment]
Hi, @pulse00. If you add the annotation you are in charge of configuring the beans yourself, see [the documentation on Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.spring-session:~:text=You%20can%20take%20control,previously%20described%20configuration%20properties.).
