### ISSUE TITLE
`ConcurrentSessionControlAuthenticationStrategy.setExceptionIfMaximumExceeded(false)` not work with session stored in redis

### ISSUE THREAD

**Issue by leozhao0709** [spring-projects/spring-session#2253]
I am using spring security, spring session data redis. I've setup the security authentication strategy as follows. 

When I setup the `ConcurrentSessionControlAuthenticationStrategy.setExceptionIfMaximumExceeded(true)`, it works as expected and throws exception correctly. 

But when I setup it to false, then the expected behavior should logout the previous signed in user, but seems it's not. 

```
@Configuration
@EnableRedisIndexedHttpSession
class SessionConfig(
    private val sessionRepo: FindByIndexNameSessionRepository<out Session>
) {
    @Bean
    fun sessionRegistry(): SessionRegistry {
        return SpringSessionBackedSessionRegistry(sessionRepo)
    }

    @Bean
    fun httpSessionEventPublish(): HttpSessionEventPublisher {
        return HttpSessionEventPublisher()
    }

    @Bean
    fun concurrentSessionControlAuthenticationStrategy(sessionRegistry: SessionRegistry): ConcurrentSessionControlAuthenticationStrategy {
        val sessionStrategy = ConcurrentSessionControlAuthenticationStrategy(sessionRegistry)
        sessionStrategy.setMaximumSessions(1)
        sessionStrategy.setExceptionIfMaximumExceeded(false)
        return sessionStrategy
    }
}
```

I've debugged a little bit, I saw these code in [here](https://github.com/spring-projects/spring-session/blob/main/spring-session-core/src/main/java/org/springframework/session/security/SpringSessionBackedSessionInformation.java#L75-L90)

```
@Override
public void expireNow() {
        if (logger.isDebugEnabled()) {
	        logger.debug("Expiring session " + getSessionId() + " for user '" + getPrincipal()
			        + "', presumably because maximum allowed concurrent " + "sessions was exceeded");
        }
        super.expireNow();
        S session = this.sessionRepository.findById(getSessionId());
        if (session != null) {
	        session.setAttribute(EXPIRED_ATTR, Boolean.TRUE);
	        this.sessionRepository.save(session);
        }
        else {
	        logger.info("Could not find Session with id " + getSessionId() + " to mark as expired");
        }
}
```

Seems when SpringSessionBackedSessionInformation calling expired now, it's just setting a new Attribute to mark the session as expired and then save back to the redis? But the session is still persisted, previous user session is not logged out.

BTW, I am using spring boot 3.

**Comment by turboezh** [comment]
I think this is by design. Concurrently expired session are just marked expired, but as soon as a user would use this session, he will fatefully get logged out.

Look at this filter: https://github.com/spring-projects/spring-security/blob/8c17b978c881fb0df3961cbc7f4a01c6f97deede/web/src/main/java/org/springframework/security/web/session/ConcurrentSessionFilter.java

**Comment by marcusdacoregio** [comment]
Hi @leozhao0709, thanks for the report.

> But the session is still persisted, previous user session is not logged out.

What do you mean about the session is not logged out? An invalid session would still be persisted.
Do you have a minimal, reproducible sample so we can see exactly what is happening and what would be the expected behavior?

**Comment by leozhao0709** [comment]
Hey @marcusdacoregio , thanks for replying. And thanks @turboezh  , you are saving my life.

My bad, seems ConcurrentSessionControlAuthenticationStrategy need to work with `ConcurrentSessionFilter` together. After I add `ConcurrentSessionFilter` at config, then everything works as expected.

Thanks again for all your help!
