### ISSUE TITLE
multi redis JedisConnectionFactory

### ISSUE THREAD

**Issue by flyzb618** [spring-projects/spring-session#226]
my app want to use multi redis JedisConnectionFactory . one is for orm cache , the other is for spring-session.  But now JedisConnectionFactory bean can only use one . Who can help me?

**Comment by rwinch** [comment]
The simplest solution is to add the `@Primary` annotation to the one for Spring Session. Does this work for you?

**Comment by flyzb618** [comment]
thanks rwinch, It works fine.  Because the session redis server is shared for all app, but every app has its own redis cache server.
