### ISSUE TITLE
obtained session instance is unusable after  HttpServletRequest#changeSessionId() is called.

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-session#227]
When `spring-session` is used and `HttpServletRequest#changeSessionId()` is called previously obtained HTTP session instance is no longer usable.
For example following code works fine on tomcat, jetty and undertow, but doesn't when `spring-session` is used
```java
HttpSession session = req.getSession();
req.changeSessionId();
session.setAttribute("attr", "value");

// ...

// expect attrValue to be "value" 
Object attrValue = req.getSession().getAttribute("attr");
```

**Comment by rwinch** [comment]
Thanks for the report! This was indeed an issue. I have fixed this in master and it will be available in the 1.0.2 release.

While I did test this myself, I'd appreciate you trying out the latest SNAPSHOT and ensuring that it resolved your issue. You can obtain the spring-session-1.0.2.BUILD-SNAPSHOT.jar from our maven repository:

```xml
<repository>
    <id>spring-snapshot</id>
    <url>https://repo.spring.io/libs-snapshot</url>
</repository>
```
