### ISSUE TITLE
Is it possible/safe to have the current Session as a request attribute?

### ISSUE THREAD

**Issue by tsachev** [spring-projects/spring-session#228]
As discussed here http://stackoverflow.com/a/29640179/741765 currently there is no easy way to get the current active session instance as `Session`.

But we have code that expects `Session` rather than `HttpSession`. Usually we can use `SessionRepository`, but not for the currently active session, because if this code makes changes to the session attributes they will not be visible later in the view layer.

One way to  workaround this is to create an implementation of the `Session` interface using for example `RequestContextHolder` and `RequestAttributes` which calls the `HttpSession`, which in case of `spring-session` will be a wrapped `Session`.

But if it is safe to export the wrapped instance as request attribute - I would love see this new feature in `spring-session`.
AFAIK `spring-session` already exports several things as request attributes - `sessionRepository` and  `httpSessionManager`.

**Comment by rwinch** [comment]
@tsachev Thanks for the feedback. I think we are going to solve this by providing a SessionContextHolder.getSession() method. See #249

**Comment by rwinch** [comment]
I'm going to close this in favor of #249 If you don't think this will work, please feel free to reopen.
