### ISSUE TITLE
Allow customization of sessionId, e.g. hazelcast-session

### ISSUE THREAD

**Issue by trydofor** [spring-projects/spring-session#2283]
**Expected Behavior**

Make it possible to customize the sessionId instead of the UUID.

**Current Behavior**

hazelcast-session, for example, use UUID as sessionId, cannot override or customize.

① let `final class HazelcastSession` to `public`
https://github.com/spring-projects/spring-session/blob/3ead79340b03e45a387f25a969882c559d94fea2/spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/HazelcastIndexedSessionRepository.java#L358

② extract `MapSession cached = new MapSession();` to method can be override
https://github.com/spring-projects/spring-session/blob/3ead79340b03e45a387f25a969882c559d94fea2/spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/HazelcastIndexedSessionRepository.java#L247-L253

**Comment by trydofor** [comment]
Provide Session Id Generation Strategy #2251

**Comment by quaff** [comment]
I think it's duplication of https://github.com/spring-projects/spring-session/issues/2258

**Comment by marcusdacoregio** [comment]
Hi @trydofor, thanks for the report.

This is a duplicate of #11, we are aiming to get this feature for 3.1. Please subscribe to that issue for any updates.
