### ISSUE TITLE
use spring-session in spring controller

### ISSUE THREAD

**Issue by agao1985** [spring-projects/spring-session#230]
hi ,can we use it in controller directly when controller's scope is session
@Controller
@RequestMapping("/test")
@("session")
public class Test{
private int counter;

    @RequestMapping(value = "/increase", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody 
    public Model increaseNum(HttpServletRequest req, Model m) {
        try {
            counter++;
            m.addAttribute("counter", counter);
        }  catch (Exception e) {
  
        }
        return m;
    }
}
or  i have to implement Serializable interface.

**Comment by rwinch** [comment]
I don't understand your question. Can you please elaborate?

**Comment by rwinch** [comment]
Closing due to lack of information and response. Please reopen if you can provide more details.
