### ISSUE TITLE
easier way to set maxInactiveIntervalInSeconds for anonymous users

### ISSUE THREAD

**Issue by gregjotau** [spring-projects/spring-session#2302]
Hi,

I think that usually you want the time before expiry of a session will be shorter for anonymous users than logged in/authenticated. 

Would it make sense to add a maxInactiveIntervalInSeconds for anonymous users? 

Also an easy way to not store Spring session rows for anonymous users would be great (but maybe that lies in spring security logic). 

Thanks for your awesome work 🤓

**Comment by marcusdacoregio** [comment]
I believe so, I also didn't have the time to test it out. If you are able to make it work nicely please share it here so others can know that the alternative works.

Happy coding :)
