### ISSUE TITLE
Add @EnableSpringHttpSession

### ISSUE THREAD

**Issue by marceloverdijk** [spring-projects/spring-session#231]
I'm wondering why there is no simple @EnableHttpSession.

This would simply look for a (custom) configured SessionRepository @Bean and register the SessionRepositoryFilter automatically.

Any thoughts?

**Comment by rwinch** [comment]
Thanks for the feedback. 

I have been thinking we needed something like this also. I think it will be a natural result of supporting other stores (i.e. #148) but it is probably best to have this explicitly listed.

Thanks again!

**Comment by marceloverdijk** [comment]
Nice!
