### ISSUE TITLE
Samples should use developer support for Testcontainers

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-session#2316]
This feature was added in Spring Boot 3.1.0 and gives the developer the possibility to use the same Testcontainers setup for development
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.testcontainers.at-development-time

**Comment by quaff** [comment]
See https://github.com/spring-projects/spring-session/pull/2395

**Comment by marcusdacoregio** [comment]
Closing as fixed via https://github.com/spring-projects/spring-session/pull/2395
