### ISSUE TITLE
how to run EmbededServer on windows?

### ISSUE THREAD

**Issue by uyifan** [spring-projects/spring-session#232]
I saw the jar Embeded-redis-0.6 include redis of linux and max version. when i run the sample on windows.  there are errors happened:

Error creating bean with name 'redisServer' defined in class path resource [org/springframework/session/redis/embedded/EmbeddedRedisConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalAccessError: tried to access method redis.embedded.AbstractRedisInstance.<init>(I)V from class org.springframework.session.redis.embedded.EmbeddedRedisConfiguration$RedisServerBean

How can I solve it

**Comment by rwinch** [comment]
Thanks for the report. Unfortunately embedded redis does not work on Windows. Please see #121. In short, we are removing embedded redis from our samples and requiring running redis externally.
