### ISSUE TITLE
How to use Jedis client in Spring Session Redis

### ISSUE THREAD

**Issue by hk250097** [spring-projects/spring-session#2338]
**Expected Behavior**

How to use Jedis client in Spring Session Redis Is there a way to use Jedis instead of Lettuce in spring session. It seems like spring-session-data uses Lettuce by default. Is there a way to override them?

**Current Behavior**

It seems like spring-session-data uses Lettuce by default.

**Context**

Is Lettuce preferred or the Jedis ?

**Comment by marcusdacoregio** [comment]
Hi @hk250097, Spring Session uses Spring Data Redis, therefore you can follow its documentation to configure [the Jedis Connector](https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#redis:connectors:jedis). Spring Boot also [automatically configures the connector for you](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql.redis) depending on the classpath dependencies.

**Comment by hk250097** [comment]
@marcusdacoregio It seems like spring session by default uses Lettuce Connector as per the issue given in the below link 
https://github.com/spring-projects/spring-session/issues/789
As in the spring session, its all abstract as in internally the spring-session takes care of putting and getting the session records in redis.
Would like to understand if we could override by following [the Jedis Connector](https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#redis:connectors:jedis) ..does the spring-session internally uses jedis connector instead of lettuce which is default.

**Comment by marcusdacoregio** [comment]
Spring Session uses the connector that is configured for Spring Data Redis.
