### ISSUE TITLE
Searching for `springSessionRedisTaskExecutor` or `springSessionRedisSubscriptionExecutor` produces zero results

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-session#2349]
I was trying to find the documentation for configuring Spring Session Redis's task executors. Knowing the bean names involved, I tried searching https://docs.spring.io/spring-session/reference/3.2/ for `springSessionRedisTaskExecutor` and `springSessionRedisSubscriptionExecutor`. Both terms produces zero results. In the end, I found the documentation by [searching on GitHub](https://github.com/search?q=repo%3Aspring-projects%2Fspring-session%20springSessionRedisTaskExecutor&type=code). That led me to [api.adoc](https://github.com/spring-projects/spring-session/blob/cb6f21968d94c10ac4d5a9443ea898aa586ec047/spring-session-docs/modules/ROOT/pages/api.adoc#L264). From there I could reverse engineer [the location in the docs](https://docs.spring.io/spring-session/reference/3.2/api.html#_redis_taskexecutor).

**Comment by marcusdacoregio** [comment]
Hi @wilkinsona, there was an issue with the indexing of Spring Session that is fixed and it is now searching for the latest snapshot.

**Comment by wilkinsona** [comment]
Thanks, @marcusdacoregio. Is the re-indexing a side-effect of that UI upgrade?

**Comment by marcusdacoregio** [comment]
I don't think it is.
