### ISSUE TITLE
How to customize spring session using spring cache

### ISSUE THREAD

**Issue by uyifan** [spring-projects/spring-session#237]
Spring session uses spring data redis. I found spring data redis has implemented spring cache abstraction. Then, who can tell me  how to customize it?

**Comment by rwinch** [comment]
Can you please elaborate? I'm not sure I understand your question.

**Comment by uyifan** [comment]
Spring session save session in redis，is there some ways to get  session at local cache，and when session don‘t exist in local cache，then get session from redis. Used in distributed system.

**Comment by rwinch** [comment]
Honestly I haven't looked into how you would do this w/out writing your own implementation of SessionRepository. Perhaps @snicoll can provide a pointer

**Comment by snicoll** [comment]
I don't understand the question either and I think there is a misunderstanding of what the cache abstraction could do for you @uyifan.

If you use Spring Session with Redis, I believe you get the feature that you are describing out-of-the-box (i.e. no need to play with the cache abstraction or anything else).

@rwinch maybe showing an example of distributed sessions with spring session and redis would help?

**Comment by rwinch** [comment]
@uyifan  Does this help?

**Comment by rwinch** [comment]
Closing due to no follow up. Please reopen and clarify the problem if you are still having issues.
