### ISSUE TITLE
Session Registry and  Concurrency Control

### ISSUE THREAD

**Issue by coco1979ka** [spring-projects/spring-session#238]
How does the original SessionRegistry in a Spring Boot application fits together with spring-session. My HttpSecurity config looks like this:

    http.
      (...)
        .and()
                .sessionManagement()
                .maximumSessions(1)
                .expiredUrl("/expired")
                .maxSessionsPreventsLogin(true)
                .sessionRegistry(sessionRegistry())
   
I'm using spring-session with Redis as a backend by using `@EnableRedisHttpSession`. If I logout from the application, the sessions are still valid in the sessionRegistry, which means I cannot login again. Should I disable the session management in my http config? Is there a replacement with spring-session?

**Comment by coco1979ka** [comment]
I think I found a solution:
    
    public class SpringSessionRegistry implements SessionRegistry, ApplicationListener<SessionDestroyedEvent> {

        private SessionRegistry delegateSessionRegistry;

        public SpringSessionRegistry() {
             delegateSessionRegistry = new SessionRegistryImpl();
        }

        @Override
        public void onApplicationEvent(SessionDestroyedEvent event) {
            String sessionId = event.getSessionId();
            removeSessionInformation(sessionId);
        }

        @Override
        public List<Object> getAllPrincipals() {
            return delegateSessionRegistry.getAllPrincipals();
        }
        // delegate all methods
    }

This could be included as a replacement for the SessionRegistryImpl of Spring Security.

**Comment by Mati20041** [comment]
Does SessionDestroyedEvent appears on every servers that share Spring Sessions on same Redis?

**Comment by rwinch** [comment]
@Mati20041 Yes. It is fired based upon Redis keyspace notification. See [RedisOperationsSessionRepository - Session Expiration](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration) for details.

**Comment by Mati20041** [comment]
@coco1979ka Sounds like something I was looking for, thanks :)

**Comment by rwinch** [comment]
@coco1979ka 

> I think I found a solution:

Thanks for providing the workaround. This is pretty clever. I wonder if just translating between the two events would work. For example something like this:

```java
public class SpringSessionRegistry implements SessionRegistry, ApplicationListener<org.springframework.session.events.SessionDestroyedEvent> {
    ApplicationEventPublisher publisher;

    @Override
    public void onApplicationEvent(org.springframework.session.events.SessionDestroyedEvent event) {
        publisher.publish(new org.springframework.security.core.session.SessionDestroyedEvent(..));
    }
```

> Btw: It should be mentioned explicitly in documentation that spring session comes with its own session destroyed event.

See [RedisOperationsSessionRepository - Session Expiration](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration)

> This could be included as a replacement for the SessionRegistryImpl of Spring Security.

We plan to provide proper integration with Spring Security's concurrency control which would simply invalidate the user's session immediately (i.e. by looking up the session and destroying it). This would avoid the need to check to see if the session was "marked as destroyed". See #65

**Comment by bmorris591** [comment]
I have had this issue and solved in using a combination of my utility class mentioned in #255.

I have created a very simple `SessionRegistry` that only provides support for the

```java
getAllSessions(final Object principal, final boolean includeExpiredSessions)
```

method. This seems to be the only method used by the `ConcurrentSessionControlAuthenticationStrategy`.

It is neccessary **not** to store the session details in a `Map` as the very point of putting sessions in Redis is to allow distributed applications. If the sessions are then stored in a `Map` in each application, the user can the allowed number of sessions on _each server_.

I would suggest using the `getAllSessionIds` method requested in #255 and implementing a  `SessionRegistry` backed by whatever store Spring Session is using

**Comment by rwinch** [comment]
Closing as duplicate of #64 Please reopen if you disagree

**Comment by coco1979ka** [comment]
Cannot reopen this... But it seems to me, that it is not a duplicate of #64 
@rwinch The conversion of thrown events is also a good option, to get notified, when a session is destroyed.

**Comment by rwinch** [comment]
@coco1979ka You are right that it is not a duplicate of #64 (that was a typo on my part). It should be marked as a duplicate of #65. Can you confirm?

Also of importance is that the latest SNAPSHOT of Spring Session supports HttpSessionListener. This means Spring Security's standard concurrency support should work fine. See docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#httpsession-httpsessionlistener
