### ISSUE TITLE
Shameful ask for help: SessionRegistry

### ISSUE THREAD

**Issue by colin-riddell** [spring-projects/spring-session#2383]
Just wanted to get some eyes on a (hopefully) simple question I have about how to inject the auto-configured `SessionRegistry` with Spring Boot :

https://stackoverflow.com/questions/76702873/unable-to-inject-sessionregistry-with-spring-boot-3-1-1-and-spring-session-redis

Sorry! 😇 

TIA 😁

**Comment by marcusdacoregio** [comment]
Hi @colin-riddell, please refer to https://docs.spring.io/spring-session/reference/spring-security.html#spring-security-concurrent-sessions
