### ISSUE TITLE
Rename SessionIdGenerationStrategy to SessionIdGenerator

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-session#2391]
We should change the name of the interface `SessionIdGenerationStrategy` to `SessionIdGenerator` for a couple of reasons:
- There is no need for the Strategy suffix
- The name is not too clear, `SessionIdGenerator` gives a better idea of what it is for
- Tomcat has a `SessionIdGenerator` and WebFlux uses `IdGenerator`, so we would not deviate too much

**Comment by rishiraj88** [comment]
Nice points by @marcusdacoregio .
