### ISSUE TITLE
Add new default session ID generator strategy: minimum 32-byte random (base64url encoded), deprecate current UUID default strategy

### ISSUE THREAD

**Issue by jcranfordupgrade** [spring-projects/spring-session#2398]
**Expected Behavior**

Default session ID generator => minimum 32-bytes random, 43-char base64url-encoded => 128-bit entropy

**Current Behavior**

Default session ID generator => UUID Type-4 => 16-bytes random (6-7 bits reserved) => 60.5-bit or 61-bit entropy

**Context**

There are multiple closed issues for requesting override of session ID generator to:
1. Increase randomness to 256-bit for entropy 128-bit (i.e. to meet FIPS 140, ANSI, OWASP, etc entropy recommendations)
2. Append application-aware data to session IDs

Most of the requests are to 1) Increase entropy. Spring Session 3.2 has an option to override the default session ID generator strategy. Most developers including me will need to replace it with a minimum 32-bytes random (43-char base64url-encoded) value.

Now that there is a way to override the default session ID generator strategy, add a new default into Spring Session to replace the current default based on Java's built-in UUID Type 4. That will mitigate the need for many developers to do that themselves.

**Comment by jcranfordupgrade** [comment]
I requested this via https://stackoverflow.com/questions/76868764/enhancement-request-add-base64-session-id-generator-deprecate-uuidsessionidgen. I didn't get a response there for 7 days, so I am opening it here as a GitHub issue.

**Comment by jcranfordupgrade** [comment]
Can you clarify what are the backward compatibility requirements for session IDs?

The only thing I can think of is maybe the UUID length of 36-chars (32-char hex + 4 dashes). For example, a custom SessionStore backed by a SQL CHAR(36) column for IDs would work for UUIDs, but not 32-byte/43-char base64url-encoding.

If that is the issue, I suggest a compromise of random 27-bytes/36-char base64url-encoding. That will take exactly the same number of characters as UUID, but increase the randomness from 16-bytes to 27-bytes by using a more efficient base64url encoding instead of hex encoding.
- 27-bytes random => 216-bits => 113-bits entropy

113-bits of entropy is sufficient to meet both of the current OWASP and FIPS 140 entropy recommendations.
- OWASP => 64-bit entropy
- NIST FIPS 140 => 112-bits entropy (sufficient for now through 2029, before the increase to 128-bit in 2030)

If anyone needs to increase it to 32-bytes/43-char base64url-encoded for ANSI entropy compliant, an configuration property could be used to override the size in bytes.

**Comment by jcranfordupgrade** [comment]
If backwards compatibility is still an issue, another compromise could be to add it but don't enable it by default. Two configuration properties in that case:
1. spring.session.id-generator.provider=uuid (e.g. uuid is default, base64url is optional)
2. spring.session.id.generator.base64url.num-bytes=27 (e.g. default 27 means 36-char for uuid size backwards compatibility)

Having it available and maintained by Spring Security would benefit a lot of developers.

Also, the base64url id generator could be made the default in Spring Session 4.0, when a potential breaking change is more acceptable. Spring Session developers could gather feedback about the base64url id generator during 3.x minor releases and patches, before making it the new default id generator in 4.0 with higher default num-bytes=32.

**Comment by marcusdacoregio** [comment]
I don't think we want to change the default implementation of `SessionIdGenerator`, at least not if Java's UUID still follows [OWASP guidelines](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-id-properties). In addition to that, `UUID` is probably enough for most use-cases and the users have now the ability to override it if needed.

I'll close this as declined for now but if we receive more feedback from the community we can consider reopening it.
