### ISSUE TITLE
Commit session called twice for Async requests

### ISSUE THREAD

**Issue by ctatineni** [spring-projects/spring-session#240]
Hello,

  I am using Servlet 3 Async features using spring WebAsyncTask to build an rest api, looks like during the response commit method is called twice and as they are two different threads.

**Comment by ctatineni** [comment]
just to add this is only happening if i use tomcat.

**Comment by rwinch** [comment]
Thanks for the report. I'm not sure there is anything we can do about it being invoked twice. Is this actually causing a problem of some sort? The redis implementation only persists attributes that have been changed, so there should only be a single write to the database (assuming no attributes have changed)

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
