### ISSUE TITLE
Invalid JavaBean property 'httpSessionStrategy' being accessed in SessionRepositoryFilter

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-session#242]
I get the following warning in my logs
```
Invalid JavaBean property 'httpSessionStrategy' being accessed!
Ambiguous write methods found next to actually used
[public void org.springframework.session.web.http.SessionRepositoryFilter.setHttpSessionStrategy(org.springframework.session.web.http.HttpSessionStrategy)]:
[public void org.springframework.session.web.http.SessionRepositoryFilter.setHttpSessionStrategy(org.springframework.session.web.http.MultiHttpSessionStrategy)]
```
I understand that this isn't necessarily an issue as it is obviously resolving to the correct setter. But should the setter for MultiHttpSessionStrategy be renamed to avoid the ambiguity?

**Comment by rwinch** [comment]
@manderson23 Thanks for the feedback. We cannot really change the method signature for passivity reasons. Just out of curiosity how do you get this error / warning?

**Comment by manderson23** [comment]
I'm using XML configuration for Spring Security and I'm setting a custom strategy that supports setting the max cookie age.
```
<beans:bean id="sessionRepositoryFilter"
              class="org.springframework.session.web.http.SessionRepositoryFilter">
    <beans:constructor-arg ref="sessionRepository"/>
    <beans:property name="httpSessionStrategy">
      <beans:bean class="com.mypackage.springframework.session.CookieWithMaxAgeHttpSessionStrategy">
        <beans:property name="cookieName" value="JSESSIONID" />
        <beans:property name="maxAge" value="300" />
      </beans:bean>
    </beans:property>
  </beans:bean>
```

**Comment by rwinch** [comment]
Just to follow up, I don't think there is anything we can do at this point since we need to remain passive. Since this is not actually causing a problem at this point, I'm going to close this as won't fix. If someone has a specific error this is causing feel free to reopen the issue.
