### ISSUE TITLE
springSessionRedisMessageListenerContainer

### ISSUE THREAD

**Issue by aaa2281002** [spring-projects/spring-session#2452]
hello!
My error message，bean springSessionRedisMessageListenerContainer， Dynamically switching Redis sources，Exception occurred，
Abnormal information is as follows：
2023-08-21 14:19:27.269  WARN 19480 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is java.lang.IllegalStateException: Subscription registration timeout exceeded.
My version 2.6.6 Upgrade to 2.7.14 Problems that arise
Which big shot has encountered a similar problem. Thank you for your timely feedback. thanks

Example link here:
https://github.com/aaa2281002/redis-demo.git

**Comment by aaa2281002** [comment]
Didn't anyone solve the problem? Community death?

**Comment by marcusdacoregio** [comment]
As I [mentioned in my other comment](https://github.com/spring-projects/spring-session/issues/2452#issuecomment-1755450856), it would be great if you could provide the whole infrastructure to be able to run your application, it can be either a Docker Compose file or you can adapt your app to use Testcontainers

**Comment by aaa2281002** [comment]
> 嗨， .
> 
> 您能提供一个可运行的样本吗？理想情况下，它将使用 Testcontainers 或 Docker Compose 之类的东西来运行所需的基础设施。

Hi, 
Example link here:
https://github.com/aaa2281002/redis-demo.git

**Comment by aaa2281002** [comment]
> Hi, @aaa2281002.
> 
> Can you please provide a runnable sample? Ideally, it would use something like Testcontainers or Docker Compose to run the required infrastructure.

Hi,
Example link here:
https://github.com/aaa2281002/redis-demo.git

**Comment by marcusdacoregio** [comment]
Hi, @aaa2281002. You haven't changed anything in your sample for it to be reproducible. I'll close this for now, if you provide a runnable sample with all the dependencies on it, we can reopen it.

**Comment by AmanMoglix** [comment]
need to update the redisson-spring-boot-starter -3.17.3
sping-boot- 2.7.12

it will work

package com.moglix.reward.config;

import com.moglix.reward.factory.CoinTransactionFactory;
import com.moglix.reward.redis.RedisKeyExpirationListener;
import com.moglix.reward.online.repo.UserCoinHistoryRepository;
import org.redisson.api.RedissonClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.listener.PatternTopic;
import org.springframework.data.redis.listener.RedisMessageListenerContainer;
import org.springframework.data.redis.listener.adapter.MessageListenerAdapter;
import org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer;
import org.springframework.data.redis.serializer.StringRedisSerializer;
import redis.clients.jedis.Jedis;

@Configuration
public class RedisConfig {

    @Autowired
    private ApplicationConfig applicationConfig;
    @Autowired
    @Lazy
    private UserCoinHistoryRepository userCoinHistoryRepository;
    @Autowired
    @Lazy
    private CoinTransactionFactory coinTransactionFactory;
    @Autowired
    private RedissonClient redissonClient;
    @Autowired
    @Lazy
    private RedisTemplate < String, Object > redisTemplate;

    @Bean
    public RedisTemplate<String, Object> redisTemplateJedis(RedisConnectionFactory cf) {
        RedisTemplate<String, Object> redisTemplateJedis = new RedisTemplate<String, Object>();
        redisTemplateJedis.setConnectionFactory(cf);
        redisTemplateJedis.setKeySerializer(new StringRedisSerializer());
        redisTemplateJedis.setValueSerializer(new StringRedisSerializer());
        redisTemplateJedis.setHashValueSerializer(new Jackson2JsonRedisSerializer<>(Object.class));
        return redisTemplateJedis;
    }


    @Bean
    public MessageListenerAdapter messageListenerAdapter() {
        return new MessageListenerAdapter(new RedisKeyExpirationListener(userCoinHistoryRepository,coinTransactionFactory,redissonClient,redisTemplate));
    }

    /**
     * Configures a RedisMessageListenerContainer bean that sets up a Redis message listener.
     * This container listens for keyspace notifications on all keys that match the pattern "__key*__:*".
     *
     * @param connectionFactory the factory to establish Redis connections
     * @param messageListenerAdapter the adapter that handles the messages received
     * @return the configured RedisMessageListenerContainer
     */
    @Bean
    public RedisMessageListenerContainer redisMessageListenerContainer(RedisConnectionFactory connectionFactory,
                                                                       MessageListenerAdapter messageListenerAdapter) {
        RedisMessageListenerContainer container = new RedisMessageListenerContainer();
        container.setConnectionFactory(connectionFactory);
        container.addMessageListener(messageListenerAdapter, new PatternTopic("__key*__:*"));
        return container;
    }
    @Bean
    public Jedis jedisClient() {
        return new Jedis(applicationConfig.getRedisServer(),applicationConfig.getRedisPort());
    }
}
