### ISSUE TITLE
Is it more reasonable to add parameter passing here? for example

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-session#2458]
![image](https://github.com/spring-projects/spring-session/assets/29112991/ff145baa-acf7-4e6e-a324-b5b672b5a361)
![image](https://github.com/spring-projects/spring-session/assets/29112991/60e313be-5656-453d-a605-b8795405292d)

**Comment by marcusdacoregio** [comment]
Hi, @imaxun. It depends, for new sessions there is no reason. But to generate a new ID for an existing session it can make sense.

However, I do not remember seeing any use case where the generated ID depends on the session properties.
