### ISSUE TITLE
Create Grails 3 Sample and Guide

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#246]
Related to #245

https://github.com/rwinch/spring-session/tree/gh-245

**Comment by rwinch** [comment]
@bobbywarner or @erichelgeson Given your involvement in the original issue... Any chance you would be interested in creating a minimal Grails 3.1.1 / Spring Session sample, tests, and a guide? It would be similar to [Spring Session - HttpSession (Quick Start)](http://docs.spring.io/spring-session/docs/1.0.2.RELEASE/reference/html5/guides/httpsession.html) but a grails version. I'm thinking if one of you contributed the sample it would be a lot more "groovy" than if I did it. Thanks for your consideration!

**Comment by rwinch** [comment]
@bobbywarner or @erichelgeson - Even if you were only able to contribute the Grails 3 / Spring Session sample code that would be extremely valuable. I could provide all the additional pieces.

**Comment by bobbywarner** [comment]
@rwinch Sure, we can definitely create a sample.  Not sure if we'll get to it this week or not, but we will soon! (cc @erichelgeson)

**Comment by rwinch** [comment]
@bobbywarner That sounds great! Thank you very much :) 

As I alluded to...I'm perfectly fine with this issue being broken up into multiple issues (i.e. first create a sample, then test, then a guide, etc) if that can help make progress

cc @erichelgeson

**Comment by erichelgeson** [comment]
@rwinch Finally found a few min to create a minimal grails 3 app. With Grails 3.1.4, Spring-session 1.1.1 and Spring Security Core plugin 3.0.4 it all is very straight forward now https://github.com/erichelgeson/grails3-redis-session (see the 3 individual commits)

The guidance is now pretty much "add it to your build.gradle and it works!" which is great! - Do we still want a quickstart guide? (we can it's just it'll be pretty light)

I'll open a PR for this code to `samples/` shortly.

**Comment by rwinch** [comment]
@erichelgeson Thanks for the response! Yes we would still like to add this even though it is very simple (it is just as simple with Boot and we demo that too). Part of the instructions will be demonstrating updating the dependencies / version that should be used.
