### ISSUE TITLE
Rectify Hazelcast documentation

### ISSUE THREAD

**Issue by SHISIA** [spring-projects/spring-session#2461]
### **Expected Behavior**

The **HazelcastHttpSessionConfig** class should be enabled/uncommented as seen [here](https://docs.spring.io/spring-session/reference/http-session.html#httpsession-hazelcast).
The Code 
`// @EnableHazelcastHttpSession `
`// @Configuration`
`// public class HazelcastHttpSessionConfig {`
`//`
`// @Bean`
`// public HazelcastInstance hazelcastInstance() {`
`// Config config = new Config();`
`// AttributeConfig attributeConfig = new AttributeConfig()
`
`// .setName(HazelcastIndexedSessionRepository.PRINCIPAL_NAME_ATTRIBUTE)
`
`// .setExtractorClassName(PrincipalNameExtractor.class.getName());
`
`// config.getMapConfig(HazelcastIndexedSessionRepository.DEFAULT_SESSION_MAP_NAME) `
`// .addAttributeConfig(attributeConfig).addIndexConfig(
`
`// new IndexConfig(IndexType.HASH,
`
`// HazelcastIndexedSessionRepository.PRINCIPAL_NAME_ATTRIBUTE));
`
`// SerializerConfig serializerConfig = new SerializerConfig();
`
`// serializerConfig.setImplementation(new
`
`// HazelcastSessionSerializer()).setTypeClass(MapSession.class);
`
`// config.getSerializationConfig().addSerializerConfig(serializerConfig); `
`// return Hazelcast.newHazelcastInstance(config); `
`// }`
`//`
`// }`

### **Current Behavior**

The HazelcastHttpSessionConfig class configuration code is commented out

### **Context**
The explanation/description is still provided pointing to the same commented code.
It is hard to tell whether the code is correct for use or was intended to be removed
The workaround should be:
- Uncomment the configuration class 
- Change the code, if it was intended for removal, and replace it with a working configuration

**Comment by marcusdacoregio** [comment]
Thanks, @SHISIA. This is now fixed.

**Comment by SHISIA** [comment]
You're welcome ,@marcusdacoregio
