### ISSUE TITLE
NoSuchMethodError: redis.clients.jedis.JedisShardInfo.setTimeout(I)V

### ISSUE THREAD

**Issue by flyspider** [spring-projects/spring-session#252]
Using 1.0.1.RELEASE with jedis version upper than 2.6.2, when init app context, throws:
 XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.data.redis.connection.jedis.JedisConnectionFactory#0' defined in class path resource [spring/mvc-session-config.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: redis.clients.jedis.JedisShardInfo.setTimeout(I)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)

**Comment by rwinch** [comment]
This is more of a Spring Data Redis issue. It seems there a few issues logged for updating the version of Jedis (i.e. [DATAREDIS-71](https://jira.spring.io/browse/DATAREDIS-71) [DATAREDIS-395](https://jira.spring.io/browse/DATAREDIS-395)). Perhaps @christophstrobl can comment on this specific issue?

**Comment by christophstrobl** [comment]
Jedis 2.7.x changed the name of `setTimeout`. The [Evans](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Evans) release(s) stick to jedis 2.6.x and therefore won't work. [DATAREDIS-374](https://jira.spring.io/browse/DATAREDIS-374) fixed the issue for [Fowler](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Fowler) aka `spring-data-redis:1.5.0.RELEASE`.

**Comment by flyspider** [comment]
Oh...Thanks !

**Comment by rwinch** [comment]
Thanks @christophstrobl! I'm closing this since it appears to be already addressed in Spring Data Redis
