### ISSUE TITLE
Provide a method to retrieve all session ids from the repo.

### ISSUE THREAD

**Issue by bmorris591** [spring-projects/spring-session#255]
Currently I use a utility class with the following code:

```java
private final RedisOperations<String, ? extends S> redisOperations;
private final SessionRepository<? extends S> sessionRepository;

@Autowired
public DefaultRedisSessionUtil(
  final RedisOperations<String, ? extends S> redisOperations,
  final SessionRepository<? extends S> sessionRepository) {
    this.redisOperations = redisOperations;
    this.sessionRepository = sessionRepository;
}

@Override
public Stream<String> getAllSessionIds() {
    final Set<String> keys = redisOperations.keys(REDIS_SESSION_PREFIX + "*");
    log.trace("Got all session ids {}", keys);
    return keys.stream()
      .map(key -> key.replace(REDIS_SESSION_PREFIX, ""));
}
```

This allows me to get all the session ids stored in the Redis database - while this works, the `REDIS_SESSION_PREFIX` constant not `public` in `RedisOperationsSessionRepository` making this code more fragile than I would like.

But even if this were public, this code is tightly coupled to the Redis backend for session storage, so switching to another backend would obviously require changing the code.

It would be good to add an optional operation on `SessionRepository` that returns all session ids, this could be implemented for repositories that supported it.

I realise I could add event listeners and keep an in-memory store of sessions as they are created/destroyed but that doesn't seem like a particularly clean solution.

**Comment by rwinch** [comment]
@bmorris591 Thanks for the report. We would not be able to add a new method to an existing interface as this would break passivity.

Returning all of the ids (without paging) is likely a bad idea in large systems. Is there a reason you want to find all session ids? Perhaps if I understood the underlying goal then we could provide something a little more robust.

**Comment by bmorris591** [comment]
I suppose the new `default` method can be leveraged to avoid that - but I'm not sure if this project needs to support older versions of Java.

One use case was to implement a `SessionRegistry` for the `ConcurrentSessionControlAuthenticationStrategy` because the `Map` based implementation does not work in a distributed setup.

Another use case to the need to kick certain users out from a background process, so the sessions needed to be search for certain properties and invalidated.

Before using spring-session we used a `SessionListener` and a `Map` to dynamically keep track of whatever was required - but with a distributed application this approach stops being possible.

One could set up other Redis entries, much like you do for expiring sessions, but the Redis persistence API does not provide access to the techniques used for creating the keys that are stored in the database so this seems to be fragile.

Could perhaps the session ids be _streamed_ from Redis somehow?

**Comment by rwinch** [comment]
> I suppose the new default method can be leveraged to avoid that - but I'm not sure if this project needs to support older versions of Java.

Thanks for the suggestion. Unfortunately, we need to support older versions of Java

> One use case was to implement a SessionRegistry for the ConcurrentSessionControlAuthenticationStrategy because the Map based implementation does not work in a distributed setup.

We will support looking up the session by username in an upcoming release. This will eliminate this need.

> Another use case is the need to kick certain users out from a background process, so the sessions needed to be searched for certain properties and invalidated.

Searching over all the sessions in memory (even if loaded in pages) does not really seem scalable to me. What properties do you need to search by?

> One could set up other Redis entries, much like you do for expiring sessions, but the Redis persistence API does not provide access to the techniques used for creating the keys that are stored in the database so this seems to be fragile.

Depending on how many properties you need to search by, it may make sense to use a different data store.

**Comment by bmorris591** [comment]
Adding support for searching by username would certainly be very helpful -  I imagine this is a fairly common use case.

We also search by one other session attribute - it's a business identifier that groups certain users (kind of). So if a backend event happens then sessions belonging to relevant users need to be updated or invalidated depending on the event.

If we can query the repo by username then we can fairly easily add grouping keys into Redis for the other use case.

We're still experimenting with Spring Session, so you might well be right on the different datastore front, but it works with Redis out of the box so we thought we would try that first.

**Comment by rwinch** [comment]
@bmorris591 Thanks for the response. The reason I ask is because we are looking into adding Gemfire support too. Likely we could support querying by any attribute in that case. See #148

**Comment by rwinch** [comment]
Closing in favor of the searching by user attributes features since finding all session ids is not scalable.
