### ISSUE TITLE
Apache mod_jk with Spring-session

### ISSUE THREAD

**Issue by eladh** [spring-projects/spring-session#256]
Hello :-) 

First , thanks for this great project.

We having some issues with our Apache mod_jk balancing : 
setting a cluster of 2 servers : 

- Each server is  a Spring boot with Embedded tomcat container .
- Sticky session configuration 
 
For some reason when setting up the Spring session the client request are sent randomly to the cluster members.

Also we needed to create PearlHttpSessionStrategy to get the spring session id.

we set the JvmRoute properly and the mod_jk also configured as needed.
when switching back from spring session things get to normal again.

AFAIK - the apache balancing is based on the jvm route appended to the the JSESSIONID and in this case there is no such information for the apache balancer 

the strange think here is that we only see SESSION = XXXX in the client browser cookie  resources.
when switching back we see the original JSESSIONID = XXXX.

Thanks in advance,
elad.

```
 # USERTEST Node 1
worker.pearlusertest1.port=8009
worker.pearlusertest1.host=pearlapput1
worker.pearlusertest1.type=ajp13
worker.pearlusertest1.socket_keepalive=true
worker.pearlusertest1.lbfactor=1
worker.pearlusertest1.connection_pool_size=50
worker.pearlusertest1.connect_timeout=5000
worker.pearlusertest1.prepost_timeout=5000

 # USERTEST Node 2
worker.pearlusertest2.port=8009
worker.pearlusertest2.host=pearlapput2
worker.pearlusertest2.type=ajp13
worker.pearlusertest2.socket_keepalive=true
worker.pearlusertest2.lbfactor=1
worker.pearlusertest2.connection_pool_size=50
worker.pearlusertest2.connect_timeout=5000
worker.pearlusertest2.prepost_timeout=5000


# Load-balancing behaviour
worker.pearlusertestlb.type=lb
worker.pearlusertestlb.balance_workers=pearlusertest1,pearlusertest2
worker.pearlusertestlb.sticky_session=1
```

```
@Bean
	public FilterRegistrationBean webSessionsFilter() {
		Map<String, ExpiringSession> sessions;

		if (env.acceptsProfiles(Profiles.SPRING_PROFILE_HAZELCAST)) {
			sessions = hazelcastConfiguration.getHazelcastInstance().getMap(SpringSessionHazelcastConfig.SPRING_SESSIONS);
		} else {
			sessions = Maps.newConcurrentMap();
		}

		SessionRepository<ExpiringSession> sessionRepository = new MapSessionRepository(sessions);
		((MapSessionRepository) sessionRepository).setDefaultMaxInactiveInterval(SESSION_TIMEOUT);
		SessionRepositoryFilter filter = new SessionRepositoryFilter<ExpiringSession>(sessionRepository);
		filter.setHttpSessionStrategy(pearlHttpSessionStrategy);

		FilterRegistrationBean filterRegBean = new FilterRegistrationBean();
		filterRegBean.setFilter(filter);
		filterRegBean.setUrlPatterns(Lists.newArrayList("/*"));
		filterRegBean.setAsyncSupported(true);
		filterRegBean.setOrder(0);
		return filterRegBean;
	}

```

```
@Service
@Provider
public class PearlHttpSessionStrategy implements MultiHttpSessionStrategy,ContainerResponseFilter {

    private final MultiHttpSessionStrategy delegate;

    public PearlHttpSessionStrategy() {
        delegate = new CookieHttpSessionStrategy();
    }

    @Override
    public String getRequestedSessionId(HttpServletRequest request) {
        return delegate.getRequestedSessionId(request);
    }

    @Override
    public void onNewSession(Session session, HttpServletRequest request, HttpServletResponse response) {
        delegate.onNewSession(session ,request ,response);
    }

    @Override
    public void onInvalidateSession(HttpServletRequest request, HttpServletResponse response) {
        delegate.onInvalidateSession(request ,response);
    }

    @Override
    public HttpServletRequest wrapRequest(HttpServletRequest request, HttpServletResponse response) {
        HttpServletRequest wrappedRequest = delegate.wrapRequest(request ,response);
        SpringSessionRequestHolder.setRequestAttributes(wrappedRequest.getSession().getId());
        RequestContextHolder.setRequestAttributes(new ServletRequestAttributes(wrappedRequest));
        return wrappedRequest;
    }

    @Override
    public HttpServletResponse wrapResponse(HttpServletRequest request, HttpServletResponse response) {
        return delegate.wrapResponse(request ,response);
    }

    @Override
    public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext containerResponseContext) throws IOException {
        SpringSessionRequestHolder.resetRequestAttributes();
    }
}
```

**Comment by rwinch** [comment]
> For some reason when setting up the Spring session the client request are sent randomly to the cluster members.

There currently is no support for sticky sessions (see #6). Is there a reason you need sticky sessions? If you are using a distributed data store, then there is no real advantage to sticky sessions unless you are using a local cache too (which we don't yet provide). Generally, I would expect that Spring Session is plenty fast and sticky session is not necessary.

> Also we needed to create PearlHttpSessionStrategy to get the spring session id.

Can you elaborate on why you need this?

> the strange think here is that we only see SESSION = XXXX in the client browser cookie resources.

By default Spring Session uses a cookie named SESSION. You can override this behavior by configuring a `CookieHttpSessionStrategy` with a different cookie name. For example:

```java
CookieHttpSessionStrategy strategy = new CookieHttpSessionStrategy();
strategy.setCookieName("JSESSIONID");
SessionRepositoryFilter filter = new SessionRepositoryFilter<ExpiringSession>(sessionRepository);
filter.setHttpSessionStrategy(strategy);
```

**Comment by eladh** [comment]
thanks @rwinch  :-)

1. Is there a reason you need sticky sessions? - in a case of a fully synced and replicated Hazelcast Map 
its should be fine - but as i saw in other issue spring session is lazy updating the session and we saw under test load that the map is not synced all the time and from time to time we getting NPE.

2. about the PearlHttpSessionStrategy  - we needed the custom implemention to update the SpringSessionRequestHolder ThreadLocal , is there any other way to do so ?


3. about setting the cookie name ? I'm must say i really confused here :
we got Spring boot with embedded tomcat and setup a spring security for the AAA policy
we didn't used any spring http.sessionManagement().sessionCreationPolicy(....)
for a load balancer  we use the apache mod_jk and the session sticky should be obtained by :
JSESSIONID=XXXXXX.[JvmRouteId] 
not using Spring session i got the cookie setup properly , is there any way to do so with spring boot  ? 
i just need to rename the cookie with : trategy.setCookieName("JSESSIONID"); ??


10x ,
elad.

**Comment by rwinch** [comment]
Thanks for your response.

> i saw in other issue spring session is lazy updating the session 

The session should be updated any time the request is committed and any time the `SessionRepositoryFilter` finishes. This problem only occurs when users are trying to use the `SessionRepository` to directly obtain a `Session` before the request is committed or the filter completes.

> and we saw under test load that the map is not synced all the time and from time to time we getting NPE.

Can you create a bug for this? I'm thinking this should not be happening.

> we needed the custom implemention to update the SpringSessionRequestHolder ThreadLocal , is there any other way to do so ?

We don't have a `SpringSessionRequestHolder` at this time so I'm not sure what you are referring to. I'm wondering if #249 would resolve your issue. If you are using Spring's `RequestContextHolder` it should have the correct `RequestContext` populated once you are using Spring MVC. If you need to use it prior, then you will want to setup a `RequestContextFilter` that is ordered after `SessionRepositoryFilter` and before your Filter. See for a discussion around this #2637

>  is there any way to do so with spring boot ?
i just need to rename the cookie with : trategy.setCookieName("JSESSIONID"); ??

Based on your code, you need to update your configuration to something like this:

```java
@Bean
public FilterRegistrationBean webSessionsFilter() {
    ...
   CookieHttpSessionStrategy strategy = new CookieHttpSessionStrategy();
   strategy.setCookieName("JSESSIONID");
   SessionRepositoryFilter filter = new SessionRepositoryFilter<ExpiringSession>(sessionRepository);
   filter.setHttpSessionStrategy(strategy);
   ...
}
```

Alternatively, if you still need `PearlHttpSessionStrategy` you can update the constructor:

```java
public PearlHttpSessionStrategy() {
    CookieHttpSessionStrategy delegate = new CookieHttpSessionStrategy();
    delegate.setCookieName("SESSION");
    this.delegate = delegate;
}
```

**Comment by eladh** [comment]
Hi .

after further investigation we must have sticky session for the time being , the reason or the fault is in out client size - there are some ajax requests that not written well with promises or chain of requests .
From tomcat docs : tomcat rewrites the session id to ensure that the next request will remain sticky (and not fall back to go to random nodes)

and before spring session we got  = JSESSIONID=XXXXXX.[JvmRouteId] 

10x
elad.

**Comment by rwinch** [comment]
Regardless of which JVM it hits, the data is always looked up in the same data store (i.e. Redis). This means there should be no need for sticky sessions since they are in a central data store.  Are you encountering a specific issue?

> From tomcat docs : tomcat rewrites the session id to ensure that the next request will remain sticky (and not fall back to go to random nodes)

Spring Session overrides the `HttpSession` implementation so any documentation regarding Tomcat and sessions is no longer valid.

> and before spring session we got = JSESSIONID=XXXXXX.[JvmRouteId]

Yes Spring Session overrides how the session is created and managed.

**Comment by ggtucker** [comment]
Sticky sessions may not seem necessary when using a centralized session store, but they can be quite beneficial in terms of having consistent logging for sessions (so one doesn't have to check several different servers to find logs about 1 session).

Right now subclasses of RedisOperationsSessionRepository don't have an easy way to set a custom session ID on a RedisSession when overriding the #createSession() method. Providing a constructor as simple as

    RedisSession(String id) {
    	this();
    	cached.setId(id);
    }

would make it possible for developers, if only as a temporary fix, to inject their own session ID with a jvmRoute.

**Comment by rwinch** [comment]
I'm closing this in favor of #256

**Comment by rwinch** [comment]
@ggtucker I updated #256 to ensure that we support adding a JVM route to the suffix of the cookie value to ease looking at logs (as you mentioned).
