### ISSUE TITLE
Document that a custom CookieSerializer might break Remember Me

### ISSUE THREAD

**Issue by OneGeek** [spring-projects/spring-session#2567]
I think that the docs update made for https://github.com/spring-projects/spring-session/issues/1157 does not actually solve the problem because although `SpringSessionRememberMeServices` does call `request.setAttribute(REMEMBER_ME_LOGIN_ATTR, true);` it doesn't ensure `cookieSerializer.setRememberMeRequestAttribute(REMEMBER_ME_LOGIN_ATTR);` gets called, which is necessary for `DefaultCookieSerializer` to know to check if the attribute is actually set on the request. 

So the example present [docs for customizing the session cookie](https://docs.spring.io/spring-session/reference/guides/java-custom-cookie.html) will break remember me, and nothing elsewhere in the documentation accounts for this.

**Comment by marcusdacoregio** [comment]
Hi, @OneGeek. Thanks for the report.

Nice catch, I think that in addition to improving the documentation it would be worth adding a warning log if they are using `SpringSessionRememberMeServices` and their `DefaultCookieSerializer` does not have the `rememberMeRequestAttribute` set.

It is important to remember folks that if you let Spring Session create the cookie serializer for you it already takes care of [setting the `rememberMeRequestAttribute`](https://github.com/spring-projects/spring-session/blob/main/spring-session-core/src/main/java/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.java#L182-L184).
