### ISSUE TITLE
Add SessionExpiredEvent and SessionDeletedEvent

### ISSUE THREAD

**Issue by manderson23** [spring-projects/spring-session#257]
I have a use case where I need to audit log in reaction to login/logout/session timeout etc.

Currently you do not know whether SessionDestroyedEvent was caused by a delete or expiry. Would you be open to extending SessionDestroyedEvent to support this? Two options I can think of are

1. Add a Cause enum to SessionDestroyedEvent with values DELETE/EXPIRED
2. Add SessionExpiredEvent that extends SessionDestroyedEvent

I'm implementing this myself for now and I'm happy to do so going forward but through I would raise it in case it was viewed as a useful feature to go into the library itself.

**Comment by rwinch** [comment]
We would love to see a PR that provides this functionality! I think that option 2 sounds the best to me. If you can get a PR that does this, we will could include it in 1.1 (which I just started work on).

**Comment by manderson23** [comment]
Option 2 is what I am currently implementing. I'll look at creating a PR.

**Comment by manderson23** [comment]
@rwinch Do you need Redis running locally for the `./gradlew check` integration tests to pass?

**Comment by rwinch** [comment]
Yes you do
