### ISSUE TITLE
Is it possible change the access level of RedisSession in class RedisIndexedSessionRepository to public

### ISSUE THREAD

**Issue by herodotus-cloud** [spring-projects/spring-session#2586]
I want to use Spring Session in the Spring Security and Spring Authorization Server environments. Currently, I achieve this by configuring the following beans

```java
@Bean
@ConditionalOnMissingBean
public <S extends Session> SessionRegistry sessionRegistry(FindByIndexNameSessionRepository<S> sessionRepository) {
	SpringSessionBackedSessionRegistry<S> springSessionBackedSessionRegistry = new SpringSessionBackedSessionRegistry<>(sessionRepository);
	log.trace("[Herodotus] |- Bean [Spring Session Backed Session Registry] Auto Configure.");
	return springSessionBackedSessionRegistry;
}
```

**This code can make Spring Security run normally without any issues.**

My problem is that the above code has some flaws, which are in the idea, as shown in the following figure, Prompt error "No beans of 'FindByIndexNameSessionRepository' type found"

![image](https://github.com/spring-projects/spring-session/assets/11025512/8404a3df-11af-45cf-8214-b80e8f45f74e)

- From the perspective of class inheritance, there is no problem with this approach now, and the code can also run normally.
- However, from the configuration perspective of Spring beans, there is indeed a small issue, as only RedisIndexedSessionRepository (in `org.springframework.session.data.redis.config.annotation.web.http.RedisIndexedHttpSessionConfiguration`) beans were injected into the Spring session without FindByIndexNameSessionRepository beans, so the IDE prompts that FindByIndexNameSessionRepository beans cannot be found, which is also correct.

if change the access level of RedisSession in class RedisIndexedSessionRepository to public,  can turn the code into the following way

```java
@Bean
@ConditionalOnMissingBean
public SessionRegistry sessionRegistry(RedisIndexedSessionRepository sessionRepository) {
	SpringSessionBackedSessionRegistry<RedisIndexedSessionRepository.RedisSession> springSessionBackedSessionRegistry = new SpringSessionBackedSessionRegistry<>(sessionRepository);
	log.trace("[Herodotus] |- Bean [Spring Session Backed Session Registry] Auto Configure.");
	return springSessionBackedSessionRegistry;
}
```

This seems more reasonable, and there will be no error prompts in the IDE.

However, RedisSession is currently inaccessible in RedisIndexedSessionRepository, so it cannot be configured using the above code.

**Comment by marcusdacoregio** [comment]
Hi, @herodotus-cloud. This is a duplicate of https://github.com/spring-projects/spring-session/issues/2258.

Since there isn't a bug with your approach, I'll close this to keep the discussion on the other issue.
