### ISSUE TITLE
Missing persisted `OAuth2AuthorizedClient` in sessions

### ISSUE THREAD

**Issue by Haarolean** [spring-projects/spring-session#2610]
Hi,

I encountered an issue while using `spring-session-data-redis` to persist sessions in a Spring app that utilizes OAuth clients. The problem stems from the default implementation of `OAuth2AuthorizedClientService`, which is `InMemoryOAuth2AuthorizedClientService`. As a result, instances of `OAuth2AuthorizedClient` are not persisted, requiring users to re-authenticate in order to obtain an `OAuth2AuthorizedClient` instance.

Currently, the only alternative implementation available is `JdbcOAuth2AuthorizedClientService`. I believe it sounds justified to have an implementation tailored for each spring-session module. Specifically, in my use case, I use Redis and propose that we store the OAuth2AuthorizedClient instance as a session attribute in Redis.

I'm down to raise a PR for a Redis implementation if we agree that the suggestion is good. Please let me know your thoughts.

**Comment by marcusdacoregio** [comment]
Hi, @Haarolean.

The `OAuth2AuthorizedClientService` is from Spring Security, therefore you would need to open an issue on its [issue tracker](https://github.com/spring-projects/spring-security/issues). Spring Session is only related to the clustered-sessions support and wouldn't have an implementation based on something that specific.

**Comment by Haarolean** [comment]
@marcusdacoregio thank you for a swift reply. However, I'm not sure that relates to spring-security. As we're (in spring-session-data-redis, not spring-security) altering the session storage mechanism, this seems to be an issue with spring-session, as without it everything would work fine as everything would be stored in memory.

**Comment by marcusdacoregio** [comment]
I don't think I follow. If you are using Spring Session Redis then your session will be stored in a Redis instance transparently to the application. Maybe you are confused between `OAuth2AuthorizedClientService` and `OAuth2AuthorizedClientRepository`, where the latter has the `HttpSessionOAuth2AuthorizedClientRepository` implementation.

**Comment by Haarolean** [comment]
Yes, indeed, there's an implementation of `OAuth2AuthorizedClientRepository`, but there's no implementation of the `OAuth2AuthorizedClientService` which will let us use the `HttpSessionOAuth2AuthorizedClientRepository` as underlying storage mechanism. So, with spring-session-redis (or any other package) we have broken `OAuth2AuthorizedClient` storage mechanism out of the box.

**Comment by marcusdacoregio** [comment]
It is not intended to store authorized clients in the session after the user has logged in. The reason they are stored there at all is for anonymous users who would otherwise clutter up the database with junk records. Once a user is logged in, their authorized client should be stored in a database where it can be managed and revoked if a leak occurs. If you still want to use sessions you can do:

```java
@Bean
public OAuth2AuthorizedClientRepository authorizedClientRepository() {
    return new HttpSessionOAuth2AuthorizedClientRepository();
}
```
