### ISSUE TITLE
Provide a way to retrieve user's last N sessions.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-session#264]
It would be a nice feature to be able to show a list of user's last N sessions - where one logged in from, was it mobile, which browser, the date, etc.

**Comment by rwinch** [comment]
Thanks for bringing up this idea!

My initial thoughts are this appears to be more of an auditing solution that you are looking for. I'm not sure this is something we would add to Spring Session itself.  This isn't to say that it wouldn't be valuable, but just that at the moment I don't think this fits in with Spring Session.

To explore this some...How would you see this implemented in a key value store like Redis? Remember we need to ensure that the session is deleted at some point. This is currently done by adding an expiration to the session entry. That means we would not know how long the user might take before logging in again.

**Comment by martin-g** [comment]
I agree that the requested functionality doesn't fit with "session store".

**Comment by ptahchiev** [comment]
Absolutely valid concerns. One point would be to provide some sort of session invalidation strategy and allow the user to define their own - I myself would probably run a cronjob to delete the session history older than some period. So if a user logs out the session is preserved in redis, but flagged as disabled so the user cannot use it again.

**Comment by rwinch** [comment]
@ptahchiev I have considered allowing an expiration policy for the Redis implementation. However, the primary reason would be so that users could avoid managing anything related to session expiration events. You might be able to leverage something like that.

**Comment by vpavic** [comment]
For the reasons outlined in discussion above (not being a core session repository concern, hard to implement on many data stores), I'm closing this as won't fix.
