### ISSUE TITLE
when provide a way  that uses a url params to obtain the session from.

### ISSUE THREAD

**Issue by yysct2005** [spring-projects/spring-session#265]
for example，
http://localhost/?jsessionid=xxxxx

**Comment by rwinch** [comment]
Can I ask why you want to do this?

In general, allowing the session id or any sensitive data within a URL is bad. From the [HTTP specification](http://www.w3.org/Protocols/rfc2616/rfc2616-sec15.html#sec15.1.3):

> Authors of services which use the HTTP protocol SHOULD NOT use GET based forms for the submission of sensitive data, because this will cause this data to be encoded in the Request-URI. Many existing servers, proxies, and user agents will log the request URI in some place where it might be visible to third parties. Servers can use POST-based form submission instead

Allowing the session id in the URL can also make [session fixation attacks](https://www.owasp.org/index.php/Session_fixation) easier.

**Comment by yysct2005** [comment]
thank you first,rwinch!
some the old system integration that used token to obtain the session.
another，if it use https,not http.
thx!

**Comment by rwinch** [comment]
HTTPS will protect you some, but you still should not include sensitive data in query strings. Please read the references I provided. Generally including sensitive data in query strings (including over HTTPS) is insecure. For this reason, we cannot include something like this in Spring Session itself.

If you feel the need to do this, then you can always provide your own `MultiHttpSessionStrategy` that obtains the session id from the parameters. For example:

```java
public class InsecureHttpParamHttpSessionStrategy implements MultiHttpSessionStrategy {

	public String getRequestedSessionId(HttpServletRequest request) { 
		return request.getParameter("session"); 
	}

	public void onNewSession(Session session, HttpServletRequest request, 
		HttpServletResponse response) {
	}

	public void onInvalidateSession(HttpServletRequest request,
		HttpServletResponse response) {
	}

        public HttpServletRequest wrapRequest(HttpServletRequest request, 
		HttpServletResponse response) { 
		return request;
	}

	public HttpServletResponse wrapResponse(HttpServletRequest request, 
		HttpServletResponse response) {
		return new InsecureResposneWrapper(response, request);
	}

	class InsecureResposneWrapper extends HttpServletResponseWrapper {
		private final HttpServletRequest request;

		public InsecureResposneWrapper(HttpServletResponse response, HttpServletRequest request) {
			super(response);
			this.request = request;
		}

		@Override
		public String encodeRedirectURL(String url) {
			url = super.encodeRedirectURL(url);
                        // update to handle if ? exists already, session id is null, etc
			return url + "?session=" + getRequestedSessionId(request);
		}

		@Override
		public String encodeURL(String url) {
			url = super.encodeRedirectURL(url);
                        // update to handle if ? exists already, session id is null, etc
			return url + "?session=" + getRequestedSessionId(request);
		}
	}
}
```

If you expose that as a Bean Spring Session will use it in place of the existing strategy.

**Comment by yysct2005** [comment]
OK，Thank you very much！Rwinch。
