### ISSUE TITLE
Provide findByIndexNameAndIndexValue hooks with Spring Security

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#266]
Update Spring Session to automatically index the username of SecurityContext

**Comment by ractive** [comment]
Reconsider following a more generic approach to handle session metadata as described in #223.

**Comment by ractive** [comment]
You may also want to consider listening to `AuthenticationSuccessEvent`s and `InteractiveAuthenticationSuccessEvent`s events to set the username to the session. This is probably less intrusive then creating an own `AuthenticationSuccessHandler`.

We're doing something like:

```java
public class SessionMetadataSettingAuthenticationEventListener implements ApplicationListener<AbstractAuthenticationEvent> {
	@Override
	public void onApplicationEvent(AbstractAuthenticationEvent event) {
		if (event instanceof AuthenticationSuccessEvent || event instanceof InteractiveAuthenticationSuccessEvent) {
			ServletRequestAttributes sra = (ServletRequestAttributes)RequestContextHolder.getRequestAttributes();
			HttpSession session = sra.getRequest().getSession(false);
			if (session != null) {
				session.setAttribute(Session.PRINCIPAL_NAME_ATTRIBUTE_NAME, event.getAuthentication().getName());
				...
			}
		}
	}
}
```

**Comment by rwinch** [comment]
@ractive Thanks for the suggestion about using a `ApplicationListener `. This is a good idea, but will likely need to supplement the `AuthenticationSuccessHandler ` approach since the events are sent asynchronously and the meta information may need to be available immediately.

**Comment by ractive** [comment]
Spring events are sent synchronously if no special `ApplicationEventMulticaster` is configured (if this default behaviour has not been changed in recent Spring versions).

**Comment by rwinch** [comment]
@ractive Correct. In my experience many people configure a custom `ApplicationEventMulticaster`.

**Comment by rwinch** [comment]
Pushing back till #301 is resolved
