### ISSUE TITLE
Unable to Inject Jedis connector in spring session

### ISSUE THREAD

**Issue by hk250097** [spring-projects/spring-session#2694]
**Describe the bug**
I am unable to Autowire redisTemplate with JedisConnectionFactory.

**To Reproduce**
I am using the dependency
```
<spring.boot.version>2.1.7.RELEASE</spring.boot.version>

<dependency>
                <groupId>org.springframework.session</groupId>
                <artifactId>spring-session-bom</artifactId>
                <version>2021.1.1</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
<dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
</dependency>
<dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.lettuce</groupId>
                    <artifactId>lettuce-core</artifactId>
                </exclusion>
            </exclusions>
</dependency>
```

The redisConfig class is as below
```
@Configuration
@EnableRedisHttpSession
public class RedisConfiguration {

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        return new JedisConnectionFactory();
    }

    @Bean(name = "redisTemplate")
    RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<Object, Object> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory);
        return template;
    }
}
```
The application property has
```
spring.session.redis.cleanup-cron=0 0/30 * * * *
spring.session.store-type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=pwd
```
**Expected behavior**
JedisConnectionFactory to be injected instead of Lettuce.
But i get error as

Error creating bean with name 'redisConnectionFactory' defined in class path resource [com/ncr/olb/redis/RedisConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.redis.connection.RedisConnectionFactory]: Factory method 'redisConnectionFactory' threw exception; nested exception is java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: redis/clients/jedis/Tuple
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by marcusdacoregio** [comment]
Hi, @hk250097. This does not seem to be a problem with Spring Session, based on your stack trace your project is missing some Jedis classes. Make sure that you are using the proper dependency versions. Take a look at [Spring Data Redis documentation](https://docs.spring.io/spring-data/redis/reference/redis/drivers.html#redis:connectors:jedis) for more details on how to set it up.
