### ISSUE TITLE
Provision to encode websession similar to httpsession with base64

### ISSUE THREAD

**Issue by nmsundar-coder** [spring-projects/spring-session#2704]
**Expected Behavior**

Need a configuration to enable / disable base64 encoding for cookie value in websession. 

**Current Behavior**

Currently websession does not support encoding and set the cookie value directly whatever been set

Have used below code in httpsession to enable / disable base64 encoding for cookie value 

        ```
        DefaultCookieSerializer serializer = new DefaultCookieSerializer();
        serializer.setUseBase64Encoding(true);
        return serializer;
        ```

**Comment by marcusdacoregio** [comment]
Hi, @nmsundar-coder. Spring Session uses the `WebSessionIdResolver` to read/write the session id from the web exchange. If you need a Base64 encoding, you can provide your own implementation or maybe use `CookieWebSessionIdResolver#addCookieInitializer` to customize the resolved cookie.
