### ISSUE TITLE
ClassCastException calling SpringSessionWebSessionStore.updateLastAccessTime(WebSession) with Spring Security 6.2 and OAuth2 login enabled

### ISSUE THREAD

**Issue by MatthiasZerau** [spring-projects/spring-session#2716]
I'm running a reactive Spring Boot 3.2.1/Spring Security 6.2.1 application with OAuth2 login enabled:
```
@Configuration
@EnableWebFluxSecurity
public class SecurityConfig {
  @Bean
  SecurityWebFilterChain securityWebFilterChain(final ServerHttpSecurity httpSecurity){
    return httpSecurity.oauth2Login(Customizer.withDefaults()).build();
  }
}
```
<sup>(simplfied)</sup>

The Spring Boot application uses Spring Session to persist web-sessions:
```
@Configuration
@EnableSpringWebSession
public class SessionConfig {
  @Bean
  WebSessionStore webSessionStore(final WebSessionManager aWebSessionManager) {
    return ((DefaultWebSessionManager) aWebSessionManager).getSessionStore();
  }
}
```

Further, there's  a `WebFilter` which (among other things) touches the session as follows:
```
@Component
public class SessionHandlingFilter implements WebFilter {
  private final WebSessionStore webSessionStore;

  SessionHandlingFilter(final WebSessionStore webSessionStore) {
    this.webSessionStore = webSessionStore;
  }

  @Override
  public Mono<Void> filter(final ServerWebExchange exchange, final WebFilterChain chain) {
    return exchange.getSession().flatMap(webSessionStore::updateLastAccessTime).then(chain.filter(exchange));
  }
}
```
The call to `WebSessionStore.updateLastAccessTime` fails with following exception:
```
2024-01-08 16:28:29,121 [reactor-tcp-epoll-5] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [ce08567]  500 Server Error for HTTP GET "/backend"
java.lang.ClassCastException: class org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2LoginSpec$OidcSessionRegistryWebFilter$OidcSessionRegistryServerWebExchange$OidcSessionRegistryWebSession cannot be cast to class org.springframework.session.web.server.session.SpringSessionWebSessionStore$SpringSessionWebSession (org.springframework.security.config.web.server.ServerHttpSecurity$OAuth2LoginSpec$OidcSessionRegistryWebFilter$OidcSessionRegistryServerWebExchange$OidcSessionRegistryWebSession and org.springframework.session.web.server.session.SpringSessionWebSessionStore$SpringSessionWebSession are in unnamed module of loader 'app')
	at org.springframework.session.web.server.session.SpringSessionWebSessionStore.updateLastAccessTime(SpringSessionWebSessionStore.java:87) ~[spring-session-core-3.2.1.jar:3.2.1]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ com.mycompany.myservice.session.SessionHandlingFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ com.mycompany.myservice.savedrequest.RestoreSavedRequestFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OidcSessionRegistryAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OidcSessionRegistryWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerWebExchangeContextFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ com.mycompany.myservice.logging.LogRequestWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/backend" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.session.web.server.session.SpringSessionWebSessionStore.updateLastAccessTime(SpringSessionWebSessionStore.java:87) ~[spring-session-core-3.2.1.jar:3.2.1]
		at com.mycompany.myservice.session.SessionHandlingFilter.lambda$filter$1(SessionHandlingFilter.java:62) ~[main/:?]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) [reactor-core-3.6.1.jar:3.6.1]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) [reactor-core-3.6.1.jar:3.6.1]
```

This used to work with Spring Boot 3.1/Spring Security 6.1.

My understanding of the issue is that with Spring Security 6.2 and OAuth2 login enabled, a filter called `OidcSessionRegistryWebFilter` is activated, which in turn decorates the `ServerWebExchange` with `OidcSessionRegistryServerWebExchange` which in turn always returns a `OidcSessionRegistryWebSession` in `getSession()` to the application. Consequently the cast to `SpringSessionWebSession` in `org.springframework.session.web.server.session.SpringSessionWebSessionStore.updateLastAccessTime(WebSession)` fails.

**Expected behavior**
A call from the application to `WebSessionStore.updateLastAccessTime(WebSession)` works even when OAuth2 login is enabled.

**Workaround**
As a workaround I'm unwrapping the origin `ServerWebExchange` from OidcSessionRegistryServerWebExchange in order to access the session of the type as expected in SpringSessionWebSessionStore.

**Comment by marcusdacoregio** [comment]
Hi, @MatthiasZerau. Thanks for the report.

What is the reason that you are updating the last access time for the web session manually? I wonder why you didn't let the `WebSessionManager` deal with that.

Have you tried to place your filter before the `OidcSessionRegistryWebFilter`? Something like `http.addFilterBefore(myFilter, SecurityWebFiltersOrder.HTTP_HEADERS_WRITER);`. Note that your `WebFilter` is annotated with `@Component`, therefore Spring Boot will register it automatically in the filter chain, I do not recall correctly the ordering that it will apply.

**Comment by MatthiasZerau** [comment]
Hi @marcusdacoregio, thank you for looking into this issue.

> What is the reason that you are updating the last access time for the web session manually?

The reason is that the session is only touched conditionally i.e. some requests must not prolong the session lifetime. My given example above did not showed that as I simplified the code.

> Have you tried to place your filter before the OidcSessionRegistryWebFilter?

Thank you for that hint, didn't thought about this yet. `OidcSessionRegistryWebFilter` is part of the SecurityWebFilterChain which has the default order of -100 (c.f. [here](https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java#L47). So annotating my web filter with `@Ordered(-101)` worked.

I'm fine with that and from my end the ticket can be closed.
