### ISSUE TITLE
Add ExpiringSession.setLastAccessedTime(long)

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#272]
It is quite surprising that `SessionRepository.getSession(String)` updates the state of the `Session`. It also complicates administration of `ExpiringSession`. For example, if we need to access `ExpiringSession` to simply view it then it should not have the last accessed time modified.

This means that `SessionRepositoryFilter` will also need to update the last accessed time.

Anyone that implements `ExpiringSession` will need to add the new method.

**Comment by rwinch** [comment]
+1 from @danhyun via Twitter https://twitter.com/lspacewalker/status/634030777815187456

**Comment by jtmelton** [comment]
+1 - current functionality is "surprising" as you said. This should clarify the intent.

**Comment by bcecchinato** [comment]
+1 for the same reasons than quoted ;)

**Comment by ptahchiev** [comment]
+1
