### ISSUE TITLE
Allow to configure start/stop behaviour of cron job inside JdbcIndexedSessionRepository

### ISSUE THREAD

**Issue by nils-christian** [spring-projects/spring-session#2768]
Hi,

In our application we have different start and shutdown phases so we usually control at which point components are started and stopped. It would be nice if we could somehow configure this for the cron job inside _JdbcIndexedSessionRepository_ as well.

**Expected Behavior**

The _JdbcIndexedSessionRepository_ should have a configuration property to disable auto-start of the cron-job. The repository should also have an explicit method for the shutdown.

**Current Behavior**

The cron job is started inside the _afterPropertiesSet_ method and the tash scheduler is stopped in the _destroy_ method.

**Comment by marcusdacoregio** [comment]
Hi, @nils-christian. The job inside the `JdbcIndexedSessionRepository` is simple and only intended for basic usage of that implementation. If you need anything more robust that achieves your business needs, you should implement your own strategy to cleanup the session and disable the execution of the default task.

To disable the task you can do `@EnableJdbcHttpSession(cleanupCron = Scheduled.CRON_DISABLED)`.
