### ISSUE TITLE
Allow override default RedisSerializer

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#283]
When using `@EnableRedisHttpSession` you can now override the default `RedisSerializer` by specifying a bean with the name of `defaultRedisSerializer`.

**Comment by fehmicansaglam** [comment]
@rwinch I am trying to use Jackson2JsonRedisSerializer but I could not make it work. Is this feature already released or should I wait for the next release?

**Comment by pcornelissen** [comment]
You need the brixton build-snapshot

**Comment by fehmicansaglam** [comment]
Thanks. Is there a roadmap for the next stable release?

**Comment by rwinch** [comment]
@fehmicansaglam From a Spring Session perspective you should only need 1.1.0.M1. Can you provide more details on how this is not working?

**Comment by fehmicansaglam** [comment]
Milestone works but it was not clear that this feature was not supported in
the stable release.
On Thu, 4 Feb 2016 at 18:54, Rob Winch <notifications@github.com> wrote:

> @fehmicansaglam <https://github.com/fehmicansaglam> From a Spring Session
> perspective you should only need 1.1.0.M1. Can you provide more details on
> how this is not working?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-projects/spring-session/issues/283#issuecomment-179943106>
> .
>
-- 
--
Fehmi Can Saglam

**Comment by rwinch** [comment]
@fehmicansaglam Glad to hear it works in 1.1.0.M1.

This issue has 1.1.0.M1 as the selected milestone. Can you clarify why it wasn't clear you needed 1.1.0.M1 (perhaps something else made this misleading)?

**Comment by fehmicansaglam** [comment]
I am not sure. It was possibly my bad.

**Comment by rwinch** [comment]
@fehmicansaglam Thanks for the fast response. Not a problem it happens. I just wanted to make sure that there wasn't something we could do to make this more clear. Thanks again for your feedback!
