### ISSUE TITLE
Session over DB and timeout

### ISSUE THREAD

**Issue by javenosa** [spring-projects/spring-session#285]
Hello,

I recently implement the session over db (postgresql), everything ok about this. But I cannot configure the timeout of the cookie in any way.

Like this over the web.xml:

    <session-config>
        <session-timeout>1</session-timeout>
        <cookie-config>
            <name>SESSION</name>
            <http-only>true</http-only>
        </cookie-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>

Or even in my success handler:

    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response, Authentication authentication) throws IOException {
        handle(request, response, authentication);
        HttpSession session = request.getSession(false);

        if (session != null) {
            session.setMaxInactiveInterval(60 * 1);
        }
        clearAuthenticationAttributes(request);
    }

On the session service:

    @Override
    public ExpiringSession createSession() {
        ExpiringSession result = new MapSession();     
        
        result.setMaxInactiveIntervalInSeconds(60);
        
        return result;
    }

There is a way to configure this? 
I think result.setMaxInactiveIntervalInSeconds(60); is the correct way, but it doesn't work. 

Thanks.

PD: This is the sample app with the Session implementation over database which I use to make my own implementation.
https://github.com/Mati20041/spring-session-jpa-repository

**Comment by rwinch** [comment]
Configuring the cookie expiration is not currently supported. See #106 

Keep in mind configuring the cookie expiration is different than configuring the expiration of the session itself. The reason for this distinction is due to the fact that in order to be secure most implementations will want to set the cookie as a browser session. A browser session means that the cookie will be deleted as soon as the browser is closed. To do this the HTTP specification requires the cookie be set with an expiration time of 0.

The expiration of the session is handled by the SessionRepository itself. If the session is expired, it should return null. Keep in mind that simply setting the session expiration does not ensure it gets removed from the database. This is the responsibility of the SessionRepository implementation. For example, the Redis implementation uses Redis' built in expiration support. For your database, you could write a background task that deletes all sessions that have expired.

**Comment by rwinch** [comment]
I am closing this as a duplicate. If you have any additional concerns, please feel free to re open the issue.

**Comment by javenosa** [comment]
rwinch, first of all, thanks for your time and effort.

Here my questions:

The default session timeout is 30 minutes right?
Do you know the estimated date to implement this functionality?
There is a sample code about removing expired sessions? (Do you say something about Redis, but I don't know if this implementation will have the same logic as session database)

About spring session in general:

I already did implement the database session, so when I enter to the site (even if I not logged in) I see the "SESSION" cookie. If I put my credentials and log into, the "SESSION" already stills with another ID.
With this is enough to work on clustered environment, right?

Please answer all the questions it will help me alot.
Thanks!!

**Comment by rwinch** [comment]
> The default session timeout is 30 minutes right?

This is implementation specific. The default Redis session timeout is 30 minutes.

> Do you know the estimated date to implement this functionality?

We plan to implement this for the next milestone of Spring Session which is currently scheduled for Oct 8. Keep in mind that this is not a guaranteed date and that it is a milestone which means it is not generally considered best to use in production.

> There is a sample code about removing expired sessions? (Do you say something about Redis, but I don't know if this implementation will have the same logic as session database)

This will be highly implementation specific. You can find the Redis implementaiton within [RedisSessionExpirationPolicy](https://github.com/spring-projects/spring-session/blob/1.0.2.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/RedisSessionExpirationPolicy.java#L102).

> With this is enough to work on clustered environment, right?

This will be enough to work within a clustered environment. Do keep in mind you will want to delete expired sessions (as already mentioned). Also keep in mind that anytime a user requests an HttpSession the repository will be invoked. This means you will want to ensure this performs well.

**Comment by javenosa** [comment]
rwinch:

My question was:
The default session timeout is 30 minutes right?
You answer:
This is implementation specific. The default Redis session timeout is 30 minutes.

When you say "This is implementation specific" I don't understand very well, because the init of this issue is about the session timeout.
As you say on your first comment:
Configuring the cookie expiration is not currently supported. See #106

So, how can I configure this in my own implementation if this is not supported?

Sorry if I don't understand well, but I get confused about this.
Thanks!

**Comment by martin-g** [comment]
I think what @rwinch says is that Redis' default is 30 mins, but other backend may have completely different timeout.
So you can change Redis timeout to something else but for now there is no way to setup the expiration time for the cookie.

**Comment by rwinch** [comment]
Thank you @martin-g [your response](https://github.com/spring-projects/spring-session/issues/285#issuecomment-138705875) is right on

**Comment by javenosa** [comment]
Thanks for your time guys.
