### ISSUE TITLE
Request Mappings starting with "/api/v1/" invalidate sessions with @EnableRedisHttpSession

### ISSUE THREAD

**Issue by twjordan** [spring-projects/spring-session#286]
Perhaps this is documented somewhere, but I can't find it. 

When I add @EnableRedisHttpSession to a stock spring-boot project with Spring Session and Spring Security, I can no longer visit endpoints mapped to "/api/v1/*" somehow my session is disappearing.  Endpoints with "/api/v2/" or other variations work.

I have cloned the spring-boot sample for web security, added the annotation and two endpoints "/api/v1/foo" and "/api/v3/foo"  You should be able to replicate the issue by logging in, visiting the v3 endpoint (which should work) and then the v1 endpoint, which will return you to login.  

Here is my clone: https://github.com/twjordan/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-web-secure

**Comment by twjordan** [comment]
Well,  I beat my head against the wall for a while and I think the problem here, and I'm embarrassed to say, is errant JSESSIONID cookies lying around associated with the /api/v1/path on localhost.

**Comment by rwinch** [comment]
@twjordan I tried out the sample you posted and it works. It sounds to me like you may be on the right track with having multiple cookies. See #275

It might be valuable for your to show what your HTTP request and response looks like for /api/v3/foo. Alternatively, you might also try using an incognito window or try clearing your cookies out.

**Comment by twjordan** [comment]
It was definitely my cookies.  Shameful!  It seems that the postman client for chrome must cache cookies separately from the browser, so even thought I was clearing them via chrome, they were sticking around, the test app I made didn't work because the paths and domain (localhost!) were the same. Oh well. 

Issue #275 seems like it would prevent this frustration in the future.  Thanks!

**Comment by rwinch** [comment]
@twjordan Thanks for the quick follow up. Your feedback is greatly appreciated.

PS: FWIW... #275 has got me multiple times.
