### ISSUE TITLE
Possibility to apply the `SessionRepositoryFilter` conditionally.

### ISSUE THREAD

**Issue by yuezk** [spring-projects/spring-session#2942]
**Expected Behavior**

The `SessionRepositoryFilter` can be applied conditionally.

**Current Behavior**

The `SessionRepositoryFilter` **cannot** be applied conditionally.

**Context**

We are working on a legacy giant project and we want to migrate to Spring Session progressively. Currently, it seems like the `SessionRepositoryFilter` is applied to all requests once set up. However, we only want to apply the filter to some requests, for example, requests that have a specific header or requests that have a specific path.

I looked into the source code of `SessionRepositoryFilter` and it seems like there is no way to achieve this. I am wondering if there is a way to achieve this with the current Spring Session implementation.

If not possible, shall we consider introducing such a mechanism to the Spring Session? For example:

* Support accepting a customized `SessionRepositoryFilter` bean, instead of creating a new one in [SpringHttpSessionConfiguration.java](https://github.com/spring-projects/spring-session/blob/7474bbbc84cde58f5c07c77251854d7a62adbc3c/spring-session-core/src/main/java/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.java#L120-L125)
* Support passing a condition bean to the `SessionRepositoryFilter` bean, so that the filter can be applied conditionally.
* Or any other better ideas?

Thanks in advance!

**Comment by yuezk** [comment]
The current solution is to define our own SessionRepositoryFilter, which extends the default `SessionRepositoryFilter` and add condition check in the `doFilterInternal` method.

The the Spring configuration class, implement the `BeanDefinitionRegistryPostProcessor` and remove the `springSessionRepositoryFilter` bean definition and add a new bean definition using our own SessionRepositoryFilter.

```java
@Configuration(proxyBeanMethods = false)
@EnableRedisIndexedHttpSession
public class SpringSessionConfig implements BeanDefinitionRegistryPostProcessor {
    @Bean
    public LettuceConnectionFactory connectionFactory() {
        return new LettuceConnectionFactory();
    }

    @Override
    public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry) throws BeansException {
        registry.removeBeanDefinition("springSessionRepositoryFilter");

        BeanDefinition definition = BeanDefinitionBuilder.genericBeanDefinition(ConditionalSessionRepositoryFilter.class)
                .addConstructorArgReference("sessionRepository")
                .getBeanDefinition();

        registry.registerBeanDefinition("springSessionRepositoryFilter", definition);
    }
}
```

**Comment by marcusdacoregio** [comment]
Thanks for the report @yuezk. I agree that there should be an easier way to define my own `SessionRepositoryFilter`. Let's use this ticket to investigate if there is a better way to structure our configuration classes so we can have a better reuse if we want to customize some components that it creates.
