### ISSUE TITLE
AsyncContext with Spring Session

### ISSUE THREAD

**Issue by grayros** [spring-projects/spring-session#295]
<code>
HttpSession session = request.getSession(false) ;//not null
</code>
But when
<code>
request = (HttpServletRequest)(request.startAsync().getRequest());
</code>
session is null.
Just this problem we found.It didn't come up before replacing HttpSession.

**Comment by grayros** [comment]
Maybe Spring Session can not be the same with Httpsession

**Comment by rwinch** [comment]
@grayros I'm not sure why you closed this. Did you get your issue figure out? I just want to make sure things are alright.
