### ISSUE TITLE
Make the cookiePath on CookieHttpSessionStrategy configurable

### ISSUE THREAD

**Issue by lbornov2** [spring-projects/spring-session#296]
There are cases when a user may want to explicitly set the cookiePath on the SESSION cookie generated by CookieHttpSessionStrategy.  

A typical example is when N applications are deployed on the same application server. In this case, the cookie path must be "/" in order for all applications to be able to read the SESSION cookie.  However, the default is "/" + request.getContextPath()

**Comment by manderson23** [comment]
Duplicate of #155 ?

**Comment by lbornov2** [comment]
@manderson23 certainly seems like it.  This is, in fact, a duplicate.

**Comment by rwinch** [comment]
Closing as duplicate of #155 as indicated above
