### ISSUE TITLE
How Spring Session Cross Multiply Domain like a.apple.com and b.apple.com ? 

### ISSUE THREAD

**Issue by dxywx** [spring-projects/spring-session#297]
The SESSION cookie's domain is “a.apple.com” , so “b.apple.com” can't get the same Session ,So maybe the cookie's can be set to ".apple.com" , and the session can cross domain more easier.

**Comment by rwinch** [comment]
Thanks for the great request! I'm trying to aggregate all the feature requests for cookies, so we can solve this problem more holistically. Therefore, I'm closing this in favor of #299 which takes this feature into account.

**Comment by rwinch** [comment]
This is now resolved via #299 See http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html for details.

**Comment by dxywx** [comment]
It's really helpful for me ! Thanks !

**Comment by icloudkit** [comment]
Why is invalid under IE8 and chrome-45.0.2454.101?
