### ISSUE TITLE
Update reference site link

### ISSUE THREAD

**Issue by azurealstn** [spring-projects/spring-session#2978]
![image](https://github.com/spring-projects/spring-session/assets/55525868/494e7001-1c31-4aa7-91b3-e0cc68225614)

https://docs.spring.io/spring-session/reference/current/index.html goes to a 404 page

Use https://docs.spring.io/spring-session/reference/index.html instead which is the current documentation site.

I don't know which file the path to the image is in. 😢 So, I registered an issue instead of a pull request.

**Comment by marcusdacoregio** [comment]
Thanks @azurealstn, the link is now fixed. The current version is now incorrectly pointing to `2021.2.3`, but that is going to be fixed as well.
