### ISSUE TITLE
Allow Custom Cookie Creation

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#299]
This issue is an aggregate of all the requests for customizing a Cookie

* Custom Cookie Path #155
* Provide Cookie Domain #141 #302
* Allow looking up parent domain rather than hard coding, dynamically find the parent domain. #297
* Allow configuring cookie expiration #106 
* Allow configuring cookie name
* HttpOnly #302
* Support JVM Route suffix for making easier to sift through logs #256

**Comment by rwinch** [comment]
Please see http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/custom-cookie.html

**Comment by cbeattie-miovision** [comment]
:+1:
