### ISSUE TITLE
Spring Session Redis Index Key not deleted when session expired

### ISSUE THREAD

**Issue by Bigcream** [spring-projects/spring-session#3004]
**Describe the bug**
"spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:springbootuser"
not deleted in redis when session expired ( didn't have any session key exist)
Although I was config this `redis-cli config set notify-keyspace-events Egx` in my redis (running in docker) and I also having entries starting with `Publishing SessionDestroyedEvent for session` logged
I'm using Sping boot 2.5.12 and Spring session redis 2.7.4

**Expected behavior**
(spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:springbootuser)

Key clear when don't have any session key available in my redis.

**Comment by marcusdacoregio** [comment]
Closing as duplicate. Please see https://github.com/spring-projects/spring-session/pull/2869#issuecomment-2155232872
