### ISSUE TITLE
EnableRedissonHttpSession Deprecated

### ISSUE THREAD

**Issue by knight-xiaolu2023** [spring-projects/spring-session#3040]
hello,
![image](https://github.com/spring-projects/spring-session/assets/131353676/f4e30c2e-6264-4c93-bc40-76aed783d047)

After this annotation was deprecated, are there any alternative solutions? I notice that the official website is still using it.

**Comment by marcusdacoregio** [comment]
Hi @knight-xiaolu2023, `@EnableRedissonHttpSession` is not from Spring Session. However, I found the documentation where they guide users how to use it, please refer to https://github.com/redisson/redisson/wiki/14.-Integration-with-frameworks/#147-spring-session
