### ISSUE TITLE
add shiro and spring session integration

### ISSUE THREAD

**Issue by martinou** [spring-projects/spring-session#310]
add shiro and spring session integration

**Comment by martin-g** [comment]
Apache Shiro is not maintained.
I think it is not good idea to add support for it right now

**Comment by martinou** [comment]
thanks you

**Comment by chrylis** [comment]
Not maintained? I suspect Les would be surprised to hear that.

**Comment by martin-g** [comment]
@chrylis Please check the project's SVN history, the activity in JIRA and mailing lists. For me, and not only for me, Apache Shiro is in very bad state at the moment.
