### ISSUE TITLE
Azure Redis Cache - keep getting: readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-session#3112]
I can connect using the redis cli, but not through Spring Boot Webflux, I keep getting readAddress(..) failed: Connection reset by peer

So, i figured this was a spring issue, using lettuce. 

Here is my code:

```
@Bean
    @Primary
    fun reactiveRedisConnectionFactory(): ReactiveRedisConnectionFactory {

        // Configure Redis standalone configuration
        val config = RedisStandaloneConfiguration()
        config.hostName = redisHostName
        config.port = redisPort
        config.setPassword(redisPassword) // Use the token as password

        // Create socket options
        val socketOptions = SocketOptions.builder()
            .keepAlive(true)
            .build()

        // Create client options
        val clientOptions = ClientOptions.builder()
            .socketOptions(socketOptions)
            .build()

        // Create Lettuce client configuration with authentication details
        val clientConfig = LettucePoolingClientConfiguration.builder()
            .commandTimeout(Duration.ofSeconds(60))
            .clientResources(DefaultClientResources.create())
            .clientOptions(clientOptions)
            .poolConfig(buildLettucePoolConfig())
            .useSsl()
            .build()

        // Create Lettuce connection factory
        return LettuceConnectionFactory(config, clientConfig).apply {
            afterPropertiesSet()
        }
    }

    protected fun buildLettucePoolConfig(): GenericObjectPoolConfig<Any> {
        val poolConfig = GenericObjectPoolConfig<Any>()
        poolConfig.maxTotal = 100
        poolConfig.maxIdle = 50
        poolConfig.minIdle = 50
        poolConfig.setMaxWait(Duration.ofMillis(60000))
        poolConfig.timeBetweenEvictionRuns = Duration.ofMillis(60000)
        poolConfig.minEvictableIdleDuration = Duration.ofMillis(60000)
        return poolConfig
    }
}

spring.data.redis.host=hostname.redis.cache.windows.net
spring.data.redis.password=access-key
spring.data.redis.port=6380
```

And the error chain I keep getting, after about 10 seconds:

`org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis Caused by: org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to hostname.redis.cache.windows.net/:6380 Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer`

Would be grateful for nay help and support

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by marcusdacoregio** [comment]
Hi @dreamstar-enterprises, thanks for the report.

I don't see Spring Session involved in your configuration. In addition to that, Spring Session uses Spring Data Redis to manage the connections with Redis, you should open this issue [on their issue tracker](https://github.com/spring-projects/spring-data-redis/issues).

**Comment by dreamstar-enterprises** [comment]
Hi Marcus, 
My BFF code can be found here:
https://github.com/dreamstar-enterprises/docs/tree/master/Spring%20BFF/bff
but I was able to resolve it, though I still often get timeout or connection issues with Azure Redis Cache

Many thanks
