### ISSUE TITLE
Single session in CookieHttpSessionStrategy assumed to be DEFAULT_ALIAS

### ISSUE THREAD

**Issue by RobRendell** [spring-projects/spring-session#321]
The cookie-writing code in org.springframework.session.web.http.CookieHttpSessionStrategy#createSessionCookie does not save the session alias if there is only a single session:

		if(sessionIds.size() == 1) {
			String cookieValue = sessionIds.values().iterator().next();
			sessionCookie.setValue(cookieValue);
			return sessionCookie;
		}

The cookie-loading code in org.springframework.session.web.http.CookieHttpSessionStrategy#getSessionIds assumes that a single sessionId must be associated with DEFAULT_ALIAS:

		if(tokens.countTokens() == 1) {
			result.put(DEFAULT_ALIAS, tokens.nextToken());
			return result;
		}

This means that if the first request to the server has an explicit session alias, the session that is created is not associated with that alias, and the second request with that same alias will be allocated a fresh session.

The test in `createSessionCookie` should test that the alias associated with the single session is in fact DEFAULT_ALIAS before using the "compact" alias-free version of the cookie.

**Comment by rwinch** [comment]
Thanks for the report!

This issue is now fixed in master and will be part of 1.3 RC1

**Comment by martin-g** [comment]
s/1.3 RC1/1.1.0 RC1/ ?

**Comment by rwinch** [comment]
@martin-g 
Yes you are right. Sorry about that...I've been working on too many projects and got versions mixed up.
