### ISSUE TITLE
ExpiringSession.setAttribute(name,object) not working as I assume it should 

### ISSUE THREAD

**Issue by tschiman** [spring-projects/spring-session#322]
I'm using the M1 build in my project right now to get the find sessions by username functionality. What I wanted to do was to grab any session related to a user that had just had their permissions updated and modify their "SPRING_SECURITY_CONTECT" attribute. 

This is what I'm trying to do:

    @Autowired
    private FindByPrincipalNameSessionRepository<? extends ExpiringSession> sessions;

    @Autowired
    private SessionRepository<ExpiringSession> sessionRepository;
    ...

    for (String key : sessions.findByPrincipalName(auth.getName()).keySet()) {

        ExpiringSession session = sessions.getSession(key);
        session.setAttribute("SPRING_SECURITY_CONTEXT", newAuth);
        sessionRepository.save(session);
    }

When setAttribute is called on the session, it's value does not change. 

 Can I do what I want to here? Am I making some kind of fatal flaw in thinking I can or even should do something like this?

**Comment by rwinch** [comment]
@tschiman As far as I can tell this should work just fine. Remember that updating the session will only update a currently logged in user and not any new log in attempts.

Any chance you can throw together a sample to reproduce this?

**Comment by tschiman** [comment]
I will try to put that together. I will upload it to my github account when I get it finished and post back here.

In the meantime I have worked around this using filters to update the session when that user logs in. See: http://stackoverflow.com/questions/33990260/spring-session-redis-and-spring-security-how-to-update-user-session

I would like to just be able to do it like I had it here, this would be super clean.

**Comment by rwinch** [comment]
I'm closing this issue due to lack of feedback. Please reopen if you are able to provide something to reproduce the problem
