### ISSUE TITLE
Session last accessed time not updated in SessionRepositoryMessageInterceptor

### ISSUE THREAD

**Issue by bmorris591** [spring-projects/spring-session#325]
After implementing #272, `org.springframework.session.web.socket.server.SessionRepositoryMessageInterceptor` was not updated.

This means that the following code:

```java
String sessionId = sessionHeaders == null ? null : (String) sessionHeaders.get(SPRING_SESSION_ID_ATTR_NAME);
if (sessionId != null) {
    S session = sessionRepository.getSession(sessionId);
    if (session != null) {
        // update the last accessed time
	sessionRepository.save(session);
    }
}
```

No longer has the desired effect.  This means that a session expires after a certain period of only WebSocket activity - exactly the behaviour Spring Session was designed to prevent.

**Comment by rwinch** [comment]
Thanks for the report @bmorris591! 

You are right this is a problem in 1.1.0.M1. I have fixed this in master.

Thanks again for taking time to make Spring Session better :)
