### ISSUE TITLE
SessionRepositoryFilter in combination with HandlerInterceptor

### ISSUE THREAD

**Issue by kianris** [spring-projects/spring-session#327]
I'm using `SessionRepositoryFilter`, that wraps the request and response objects, which works for subsequent filters as the session is already created. However, I also have a `HandlerIntercepter` that does some checks on the session, which runs before any of the filters. The request hasn't been wrapped at this point and ends up creating two session cookies and breaking login.

Since `HandlerInterceptor` seems to be recommended over filters for this kind of check, is this behaviour supported in spring-session or should I be rewriting the interceptor as another filter?

**Comment by rwinch** [comment]
A `HandlerInterceptor` will use the `HttpServletRequest` that is passed into the `DispatcherServlet`. The `HttpServletReqeust` that is passed into the `DispatcherServlet` will be the value that is wrapped by the `SessionRepositoryFilter` so it should work without any changes so long as the `SessionRepositoryFilter` is being invoked for that request.

Do you have a concrete example of a `HandlerInterceptor` creating a second session that you could provide?

**Comment by kianris** [comment]
Thanks for responding quickly. I think the problem was simply that the filter was mapped by servlet name instead of URL pattern and running too late, not a problem with spring-session. Will close this issue.

**Comment by rwinch** [comment]
Thanks for the fast follow up @kianris! I'm glad you got this working :)
