### ISSUE TITLE
Resource server occasionally fails to retrieve logged in user

### ISSUE THREAD

**Issue by rrajarethnam** [spring-projects/spring-session#328]
I am using the Microservices architecture as described in https://spring.io/blog/2015/01/28/the-api-gateway-pattern-angular-js-and-spring-security-part-iv . But sometimes, I find that although the user is logged in at the gateway, the Principal User comes in as null at the resource server. This happens very rarely, but is still an annoyance for the users and very difficult for me to debug. Could this be related to this issue: https://github.com/spring-projects/spring-session/issues/250? I don't use/store anything in the session except to note logged in state. Note that I am using a load balanced configuration with 2 nodes. Each node contains gateway and resource servers, while there is a single redis instance on a separate server as session store for these 2 nodes.

**Comment by rrajarethnam** [comment]
This was occurring due to the client passing the Authorization header with every request - even for those with expired tokens. Since the Authorization header is present in the request, the gateway passes it to the service. Now the service tries to retrieve the session using the expired token. This fails and the Principal is returned as null. Now the client is fixed and this error does not occur anymore.

**Comment by rwinch** [comment]
@rrajarethnam Thanks for following up! I'm glad you figured this out :)
