### ISSUE TITLE
Spring Redis Http Session Authenticate and Route in Same Request

### ISSUE THREAD

**Issue by justiniantaylor** [spring-projects/spring-session#334]
Hi

I have created a question on stackoverflow on this, but thought I might get an and answer from the legend Mr Winch on here. I am really battling and really tried hard getting to the bottom of this but have admitted I need a higher power on this one.

My question on stackoverflow:
https://stackoverflow.com/questions/34751700/spring-zuul-api-gateway-with-spring-session-redis-authenticate-and-route-in-sa

Essentially I am trying to get Zuul to authenticate and route in the same request to my resource server by adding the following header:
RestTemplate template = new RestTemplate();
String plainCreds = "user:password";
byte[] plainCredsBytes = plainCreds.getBytes();
byte[] base64CredsBytes = Base64.getEncoder().encode(plainCredsBytes);
String base64Creds = new String(base64CredsBytes);

HttpHeaders headers = new HttpHeaders();
headers.add("Authorization", "Basic " + base64Creds);
response = template.exchange(...

The problem is that I can see that my user is authenticated in the gateway, however when the request is routed via zuul to my resource server it cannot get the session from redis, it seems to only commit after the request has completed. So on the 403 I get back on my call, if I take the session id and retry my call it works. Is there anyway I can get this to happen in the same request to reduce the back and forth of my api users?

Thanks kindly
Justin

**Comment by rwinch** [comment]
Thanks for the report! Seems this is a duplicate of https://github.com/spring-projects/spring-session/issues/250

**Comment by justiniantaylor** [comment]
Hi Mr Winch!

Been reading a lot of your stuff lately, thank you for your awesome work!

Yes I have read that issue about 50 times and it is similar! But I was hoping that as this is such a common scenario (ie external apps calling your spring microservices via your gateway) was really hoping you might be able to give me a workaround of sorts.

Essentially I was trying to get to a point where I could issue a "loose" api key (basic or hmac) that mobile sdks could use to call and authenticate in one call to my service. Any hints or absolutely anything would be appreciated.

I have gone down the oauth2 route and I really dont want to go there, very overkill and complicated for something you have managed to make so effortless in the spring session option.

Any help is much appreciated! Thanks!

**Comment by rwinch** [comment]
You could create a SessionRepository implementation that automatically saves as soon as any attributes are set, the session is created, etc. A rough sketch can be found below:

```java
public class EagerSessionRepository implements SessionRepository {
    private SessionRepository delegateRepo;

    public EagerSession createSession() {
        ExpiringSession session = delegateRepo.createSession();
        delegateRepo.save(session);
        return new EagerSession(session);
    }

    ...

    class EagerSession implements ExpiringSession {
        private ExpiringSession delegate;

        public void setAttribute(String attrName, Object attrValue) {
            delegate.setAttribute(attrName, attrValue);
            delegateRepo.save(delegate);
        }

        ...
    }
}
```

**Comment by justiniantaylor** [comment]
Wow you never disappoint, you are a king thanks very much will give it a shot.

**Comment by justiniantaylor** [comment]
Um no actually I dont really follow sorry, could you please give a little more context how I could implement this I am a bit lost? How would I go about replacing the existing Session Repository with this implementation?

Please excuse my outright naivety!

**Comment by justiniantaylor** [comment]
Hi Rob.

Sorry to give more context from my side, the reason I am probably confused is that due to me using redis, I am obviously using RedisOperationsSessionRepository, so I was thinking of extending this , but on createSession this class returns RedisSession which is a final class so I cannot extend it.

So what I did as a test is I copied the source for RedisOperationsSessionRepository and changed the createSession() method to:
    public RedisSession createSession() {
    		RedisSession redisSession = new RedisSession();
    		if(defaultMaxInactiveInterval != null) {
    			redisSession.setMaxInactiveIntervalInSeconds(defaultMaxInactiveInterval);
   		}
   		**save(redisSession);**
   		return redisSession;
    }

And then in the RedisSession class changed this method:
public void setAttribute(String attributeName, Object attributeValue) {
			cached.setAttribute(attributeName, attributeValue);
			delta.put(getSessionAttrNameKey(attributeName), attributeValue);
			**save(this);**
		}

And then to get my app to use the new session repository:
 @Primary
    @Bean
    public EagerRedisOperationsSessionRepository sessionRepository(RedisTemplate<String, ExpiringSession> sessionRedisTemplate) {
        **EagerRedisOperationsSessionRepository sessionRepository = new EagerRedisOperationsSessionRepository(sessionRedisTemplate);**
        sessionRepository.setDefaultMaxInactiveInterval(maxInactiveIntervalInSeconds);
    return sessionRepository;
    }

But it doesnt appeared to have worked, still getting the same behaviour. Can you see anything that I may have overlooked?

Thanking you in advance.

**Comment by rwinch** [comment]
@justiniantaylor I updated the description above. Please see if that helps.

**Comment by justiniantaylor** [comment]
Ok, I have done some debugging with some filters and ZuulFilters (pre and post). I can see its saving the spring security context before it routes to the resource in my logs:
EagerRedisOperationsSessionRepository$RedisSession:405 setAttribute] - SAVING ATTR: SPRING_SECURITY_CONTEXT VALUE: ..

However when zuul  routes to the resource it is not adding the authenticated session id to the reverse proxy request to the resource application because in the logs I see:
HttpSessionSecurityContextRepository:159 readSecurityContextFromSession] - No HttpSession currently exists

So I actually am starting to think this is not a spring session problem, but a problem with the way Zuul routes a request to a resource after its been authenticated in the same request?

**Comment by rwinch** [comment]
@justiniantaylor Sorry I just now saw that you had additional replies. You may need to explicitly ensure that Zuul adds the session. I'm not familiar with what integrations it has at the moment.

**Comment by justiniantaylor** [comment]
Great thank you very much for your response. I will try dig around to see if there is something I can do to explicitly set the newly authenticated session into the route. I will log into spring cloud if I dont come right. Thank you so much for taking the time to answer.

**Comment by justiniantaylor** [comment]
Hi Rob

I have managed to get this working, its a bit of a two part solution, I needed to eagerly save the redis session as discussed in this issue and then also needed to create a zuul pre filter to inject the new authenticated session cookie in the addZuulRequestHeader. Please see below for part two of getting around the issue.

[#13] (https://github.com/spring-projects/spring-cloud/issues/13)

Just for the record I couldnt quite get your suggestion to work so I had to take the source for RedisOperationsSessionRepository and write a EagerRedisOperationsSessionRepository. The two methods I had to change were as per your solution:

    public RedisSession createSession() {
		RedisSession redisSession = new RedisSession();
		if(defaultMaxInactiveInterval != null) {
			redisSession.setMaxInactiveIntervalInSeconds(defaultMaxInactiveInterval);
		}
		save(redisSession);
		return redisSession;
	}

and then in the inner class RedisSession:

    public void setAttribute(String attributeName, Object attributeValue) {
			cached.setAttribute(attributeName, attributeValue);
			delta.put(getSessionAttrNameKey(attributeName), attributeValue);
			save(this);
		}

i hope this helps if you ever decide to include it somehow.

Thanks again for your help, super stoked the last minor issue on my full solution is working like a dream now. And spring session makes life so simple but effective to use!!

**Comment by dhiraj65** [comment]
Hi Winch,
I am facing problem when i trying to access another REST API(registered in ZUUL route) from zuul pre-filter, the call is becoming recursive i.e its running my pre-filter code again and again. My Usecase is as follows-

1) In Zuul Prefilter run() method, i am validating the Token passed in the header.
2) After validating the token, i am calling one rest service(User Location Service) to fetch the user details. My User Location Service is itself registered in ZUUL as below
user-location-service:
     path: /userLocationService/**
     url: http://localhost:9002

The problem is JWT token validation code is running again and again, Can you please suggest some solution where i can apply the call Userlocation service? so that the Prefilter code should not run again and again.

Thanks,
Dhiraj
