### ISSUE TITLE
Is there a way get the latest snapshot from Maven

### ISSUE THREAD

**Issue by littlejedi** [spring-projects/spring-session#335]
Hi guys,
I kinda need this commit:

https://github.com/spring-projects/spring-session/commit/e766ad774d3ea1497dbabdbc008f4083213f5983

Is there a way to get the latest snapshot in Maven?

Thank you!

**Comment by shakuzen** [comment]
Sure. It is mentioned in the guides in [the documentation](http://docs.spring.io/spring-session/docs/1.1.0.BUILD-SNAPSHOT/reference/html5/). For example, the [HttpSession Guide](http://docs.spring.io/spring-session/docs/1.1.0.BUILD-SNAPSHOT/reference/html5/guides/httpsession.html#updating-dependencies) mentions to add the Spring snapshot repository like follows (for Maven):

```xml
<repositories>
        <!-- ... -->
        <repository>
                <id>spring-snapshot</id>
                <url>https://repo.spring.io/libs-snapshot</url>
        </repository>
</repositories>
```

Then you can add the latest SNAPSHOT version of whichever Spring Session dependency you are using.

**Comment by rwinch** [comment]
Thanks for helping out with a very quick answer @shakuzen!

**Comment by littlejedi** [comment]
Thanks guys
