### ISSUE TITLE
when 1.1.0-RELEASE will be published?

### ISSUE THREAD

**Issue by caspar-cao** [spring-projects/spring-session#336]
It seems like that the 1.1.0-M version has been published, and the "#299 - Customize Cookie Creation" functionality has been added, so i want to know whether it's ready for production environment? or i have to wait for the 1.1.0-RELEASE ? if so , when ? Thank you very much.

**Comment by rwinch** [comment]
@caspar-cao I tend to be rather conservative on waiting until a GA is out. However, if you are less conservative you are free to use the milestone. It is worth noting that some of the APIs (i.e. around finding user's by username) are going to be redone to a large degree. I plan on doing a GA in late Feb early march.

**Comment by rwinch** [comment]
I believe this is now answered, so I'm resolving as no additional feedback. Please feel free to re-open if you have follow up questions.
