### ISSUE TITLE
Integration with spring-security-messaging

### ISSUE THREAD

**Issue by bmorris591** [spring-projects/spring-session#340]
Currently, in order to utilise spring-session, `AbstractSessionWebSocketMessageBrokerConfigurer<>` is provided.

Currently, in order to utilise spring-security-messaging, `AbstractSecurityWebSocketMessageBrokerConfigurer` is provided.

This issue is, I need both to unify my http session across HTTP and WebSocket interactions _and_ secure my application.

Currently I have to `extends` one of the above classes and then manually merge in the other to achieve both.

I suppose that creating `AbstractSecuritySessionWebSocketMessageBrokerConfigurer<>`, for example, is just asking for an exponentiation of configuration classes as more are more combinations are required.

But there does need to be a way to use these two libraries together without pasting swathes of code into a third location.

**Comment by mschipperheyn** [comment]
Any word on this?

**Comment by rwinch** [comment]
Thanks for the report. This is an issue and reflected in #98. The only alternative is to configure the adapter yourself.
