### ISSUE TITLE
Add spring-shell to spring-session-gemfire

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#345]
Once https://github.com/spring-io/platform/issues/313 is resolved we need to add spring-shell back to spring-session-gemfire

Relates to https://github.com/spring-projects/spring-session/issues/344

**Comment by jxblum** [comment]
After discussion with both @rwinch and @wilkinsona, this is no longer required.  We can close this issue.

**Comment by rwinch** [comment]
@jxblum Thanks! Closed as invalid
