### ISSUE TITLE
Add generic GemFire findByINdexNameAndIndexValue support

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session#353]
This issue is setup to track the development effort involved in enabling the GemFireOperationsSessionRepository implementation to find (lookup) Sessions by any arbitrary Session attribute name/value pair.

Commit [ad09b49](https://github.com/spring-projects/spring-session/commit/ad09b498a3716a9571853057f562d3ed4caf4f0b) changed the *FindByPrincipalNameSessionRepository* interface to *FindByIndexNameSessionRepository*, thereby allowing *Spring Session* users to lookup any Session or Sessions by any of the Session's attributes.

**Comment by rwinch** [comment]
@jxblum Thanks for the submission. We will wait until the docs are updated (as you suggested offline).

**Comment by jxblum** [comment]
@rwinch All development work (implementation, testing and documentation) complete.  The PR gh-353 branch has been rebased with the latest changes on master and is up-to-date.
