### ISSUE TITLE
How to use @EnableRedisHttpSession and @EnableOAuth2Client same time

### ISSUE THREAD

**Issue by maxiplay** [spring-projects/spring-session#357]
https://github.com/spring-projects/spring-security-oauth/issues/689

**Comment by rwinch** [comment]
Thanks for the report! Currently this is not possible since Spring Security OAuth uses scoped proxies. There is an issue for this #52 that needs resolved.

Ultimately, I suspect this is an issue with Spring Security OAuth's or Spring Framework's scoped proxy serialization mechanism.

**Comment by maxiplay** [comment]
Thanks for reply

**Comment by rwinch** [comment]
Related to #395
