### ISSUE TITLE
HazelcastClientRepositoryITests should shutdown single instance not all

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#358]
We should close a [single Hazelcast instance rather than all of them](https://github.com/spring-projects/spring-session/blob/7c53558454a160e0443d73366ecc9e0d32211c3f/spring-session/src/integration-test/java/org/springframework/session/hazelcast/HazelcastClientRepositoryITests.java#L55-L58)

**Comment by artembilan** [comment]
I'd be glad to contribute @rwinch :smile: .

Will consider to PR this evening or tomorrow's morning.

**Comment by rwinch** [comment]
@artembilan Thank you so much!
