### ISSUE TITLE
Spring Session Couchbase Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#363]
This feature is well under way at https://github.com/ldoguin/spring-session-couchbase/issues/1

Things we typically look for when getting a new datastore (looks like this is already pretty close):
- [ ] Code (obviously)
- [ ] Unit tests
- [ ] Integration tests (fewer than the unit tests for speed but still ensure things are working)
- [ ] Hello World Sample / Guide for Web Application (i.e. [HttpSession Sample](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/httpsession.html))
- [ ] Sample Tests
- [ ] Optional `@EnableCouchbaseHttpSession` for making things easier
- [ ] Optional spring-session-couchbase pom that aggregates the dependencies to make dependency management for users easier

**Comment by mkopylec** [comment]
Hi there, I've already created such an implementation: https://github.com/mkopylec/session-couchbase-spring-boot-starter

It is already mentioned here: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters

**Comment by rwinch** [comment]
Thank you @mkopylec Would you be interested in submitting a PR?

**Comment by mkopylec** [comment]
sure

**Comment by mkopylec** [comment]
There is also a support for session namespaces in the project.
Maybe it will be good idea to generify it and move it to the spring session core project?
With the namespaces support we can gain some performance improvements in large distributed systems, because there is no need to retreiving whole session data in every session request.

**Comment by rwinch** [comment]
@mkopylec Sorry for the delayed response. Maybe you can elaborate on what you mean here?

As I understand your suggestion, I don't think this makes sense as how things are namespaced is very store specific. For example, Redis will place them in different keys and JDBC might place them in different tables or add a qualifier column, etc.

**Comment by mkopylec** [comment]
Maybe you're right.
I just thought to maybe add some method to `ExpiringSession` like `setNamespaceAttribute(...)` etc.

Never mind.
I will soon submit a PR.

**Comment by mkopylec** [comment]
I have created a PR for Couchbase support:
https://github.com/spring-projects/spring-session/pull/468

**Comment by rwinch** [comment]
Awesome! Thanks @mkopylec I will review this tomorrow.

**Comment by cambierr** [comment]
any news on spring session couchbase ?

**Comment by crisarmen** [comment]
Hi @mkopylec, thanks for your work in this direction!

Will it be possible to use spring session couchbase also not in spring-boot, but for example directly in tomcat?

Thanks.

**Comment by mkopylec** [comment]
Hi @crisarmen it will be possible if the https://github.com/spring-projects/spring-session/pull/477 will be merged and released.

**Comment by crisarmen** [comment]
Thanks @mkopylec!

**Comment by cambierr** [comment]
Just in case, I wrote this: https://github.com/cambierr/spring-session-couchbase
It's not super complete bus it does the job while waiting for official merge of @mkopylec's work

**Comment by vpavic** [comment]
Closing as explained in [#477 (comment)](https://github.com/spring-projects/spring-session/pull/477#issuecomment-298104321).
