### ISSUE TITLE
Spring Session Relational Database Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#364]
It would be great to have Spring Session support with relational databases.

Most likely session attributes would be saved as serializable blobs since session attributes are unlikely to provide JPA mappings related to the session. For this reason, it may make sense to use straight JDBC rather than JPA. This part is up for discussion.

What we would typically look for:

* [ ] Code (obviously)
* [ ] Unit tests
* [ ] Integration tests (fewer than the unit tests for speed but still ensure things are working)
* [ ] Hello World Sample / Guide for Web Application (i.e. [HttpSession Sample](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/httpsession.html))
* [ ] Sample Tests
* [ ] Optional `@EnableJdbcHttpSession` for making things easier
* [ ] Optional spring-session-jdbc pom that aggregates the dependencies to make dependency management for users easier

**Comment by vpavic** [comment]
@rwinch this is a really great proposal! :+1:

Having support for relational database as session store would surely aid more widespread adoption of Spring Session, especially in conservative environments which heavily rely on a RDBMS.

I'm willing to work on a PR to provide this functionality. Are there any specific milestones/timelines for this feature?

**Comment by chrylis** [comment]
Is there a particular reason to focus this on JPA instead of the (usual) underlying JDBC, since the session will end up as a blob anyhow? The only advantage that comes to mind is supporting nontraditional JPA providers (e.g., BigTable), and the management and performance overhead of JPA would be noticeable.

**Comment by rwinch** [comment]
@vpavic That is great news!

> I'm willing to work on a PR to provide this functionality. Are there any specific milestones/timelines for this feature?

Given this would be contributed by the community (sounds like you) it will make it in when you get it done. I've updated the comment to include things that we would look for for this to be considered done. Of course if you only have time for one item, we can always divide the work up :)

**Comment by rwinch** [comment]
@chrylis Thank you for your feedback!

> Is there a particular reason to focus this on JPA instead of the (usual) underlying JDBC, since the session will end up as a blob anyhow

This is a good point! I updated the description 

cc @vpavic

**Comment by vpavic** [comment]
@rwinch I agree with @chrylis's suggestion that the implementation should be based on ```spring-jdbc``` instead of ```spring-data-jpa```. Why force users into JPA if they don't use/want it? That could present a deal breaker for some.

Spring Security's ```JdbcDaoImpl``` and Spring Integration's ```JdbcMessageStore``` are some examples of the approach we should also take here.

**Comment by cemo** [comment]
+1 for JdbcTemplate

**Comment by rwinch** [comment]
@cemo Thanks for pointing out the duplicate! I closed the other issue since this issue seems to have gained traction of a PR from @vpavic
