### ISSUE TITLE
Spring Session Apache Geode Support

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session#365]
This issue was setup to track the development of _Apache Geode_ support in _Spring Session_.  This development effort is very similar to the work involved in supporting _Pivotal GemFire_, and much of the existing functionality, if not all, can be reused.

In a nutshell, the work involved should be as simple as switching the **artifact** from `org.spirngframework.data:spring-data-gemfire` to `org.springframework.data:spring-data-geode` and the **version** from `1.9.0.RELEASE` to `1.0.0.INCUBATING-RELEASE`.

Note: _Apache Geode_ support will be added to _Spring Session_ as a separate module (i.e. `spring-session-data-geode`) to preserve both _Pivotal GemFire_ support along with _Apache Geode_ support, simultaneously.  A developer/user only need include the right module (either `spring-session-data-gemfire` or `spring-session-data-geode`) dependency to add the data store of their choice to back the HTTP Session using _Spring Session_.

**Comment by jxblum** [comment]
Closing this issue in favor of #366.

**Comment by jxblum** [comment]
Unfortunately, due to technical limitations (divergence) imposed on _Pivotal GemFire_ and introduced by _Apache Geode_, it is NO longer possible to support both _Pivotal GemFire_ and _Apache Geode_ in _Spring Session_.

This PR will have to wait indefinitely, or at least until _Pivotal GemFire_ 9 is available, and available for _Spring Data GemFire_ to consume and be rebased upon.

In a nutshell, this problem has everything to due with [GEODE-37](https://issues.apache.org/jira/browse/GEODE-37), the package rename from `com.gemstone.gemfire` to `org.apache.geode` for all classes, components and DB objects of GemFire.  And because key components (e.g. [GemFireHttpSessionConfiguration](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/data/gemfire/config/annotation/web/http/GemFireHttpSessionConfiguration.java#L21-L28) and [AbstractGemFireOperationsSessionRepository](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/data/gemfire/AbstractGemFireOperationsSessionRepository.java#L36-L43)) in _Spring Session's_ GemFire support uses GemFire classes for the implementation, it make it virtually *impossible* to swap _Pivotal GemFire_ for _Apache Geode_, or vice versa.

**Comment by jxblum** [comment]
As of this moment, _Pivotal GemFire_ **9.0.1** is available now!

_Pivotal GemFire_ 9.0 was based on Apache Geode 1.0.0-incubating.  Apache Geode has now become a TLP in ASF.  And since Spring Session is moving to Java 8, _Spring Framework_ 5, _Spring Boot_ 2, _Spring IO Platform_ Cairo and _Spring Data_ Kay, which aligns all dependencies involved, it is now possible to include support for _Spring Data Geode/Apache Geode_ in _Spring Session_.

The only requirement is for _Spring IO Platform_ to include support for _Spring Data Geode/Apache Geode_ so the the `springIoCheck` passes.

**Comment by jxblum** [comment]
This PR is not waiting on the _Spring IO Platform_ to add support for _Spring Data Geode_ with _Apache Geode_, which is being tracked in Platform PR [#513](https://github.com/spring-io/platform/pull/513).

**Comment by vpavic** [comment]
Closing due to reasons explained in #768.
