### ISSUE TITLE
Spring Boot - Redis persistence token

### ISSUE THREAD

**Issue by gabber3000** [spring-projects/spring-session#368]
I have a project that uses this scheme:

Spring Boot
Spring Security
Redis
Everything works fine except the session time. I want to keep the token in Redis permanent. The token must have no expiration how should I do? This and configuration of my HttpSessionConfig:

```
@Configuration
@EnableRedisHttpSession
public class HttpSessionConfig {

    @Bean
    public HttpSessionEventPublisher httpSessionEventPublisher() {
            return new HttpSessionEventPublisher();
    }   
}
```
http://i.stack.imgur.com/D2v1L.jpg

**Comment by rwinch** [comment]
It does not appear that this is supported at the moment. I created #369 to address this. For now, you can work around this using:

```java
@EnableRedisHttpSession(maxInactiveIntervalInSeconds=Integer.MAX_VALUE)
...
```

This will make the Redis sessions expire in 68 years.

I'm closing this as resolved, but please let me know if you have additional questions.

**Comment by gabber3000** [comment]
Optimal solution. Thank you

**Comment by rwinch** [comment]
@gabber3000 Thanks for the fast response!
