### ISSUE TITLE
Extract IndexResolver

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#376]
As pointed out in #372 there is currently quite a bit of duplication of logic for `PrincipalNameResolver`. It would be good to extract this logic out in a way that works for any index name and value. However, we should wait and see what shapes up in Spring Data as it may provide a convenient mechanism for this via [Redis Index](https://github.com/spring-projects/spring-data-redis/pull/156/files#diff-d2c04ffe360655561105d34b8ba1d122R31) (I'm in discussion to see if this makes sense to make indexing available in Spring Data Commons

**Comment by rwinch** [comment]
@vpavic Has said he would consider submitting a PR once we know how Spring Data shapes up. https://github.com/spring-projects/spring-session/pull/372#issuecomment-187376689

**Comment by vpavic** [comment]
@rwinch Could this improvement be given a second look now?

**Comment by rwinch** [comment]
@vpavic I think that we can extract this logic out. We would want to ensure that we can extract a generic value to be indexed and not just the principal.

**Comment by vpavic** [comment]
Closing in favor of PR #557.
