### ISSUE TITLE
Make SessionRepository implementations cluster safe

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#380]
```RedisOperationsSessionRepository``` and ```JdbcOperationsSessionRepository``` (provided by #379) both use methods annotated with ```@Scheduled``` for cleanup of expired sessions.

This approach is actually not cluster-safe since there are no guarantees that cleanup methods won't be executed concurrently when application is run in configuration with multiple active instances.

Basic locking should be provided, preferably using the underlying technology which backs the ```SessionRepository``` itself since it is also a shared resource in such configrations. Also locking mechanism should be possible to customize, in scenarios where users already have something like Zookeeper in their stack and would like to reuse it.

**Comment by rwinch** [comment]
@vpavic Thanks for the report. Are you experiencing specific problems with the tasks running at once? this shouldn't be much different than if two requests come in to delete a session.

**Comment by vpavic** [comment]
@rwinch, no, I didn't experience specific problems. This is an observation I had analyzing ```RedisOperationsSessionRepository``` and working on #379, and considered it worth reporting and looking into since Clustered Sessions are one of the main features of this project.

My main concern was that this could, depending on the implementation of the ```SessionRepository```, lead to duplicate ```SessionExpiredEvent```s.

**Comment by rwinch** [comment]
@vpavic We should be fine. The way expiration event is fired is from Redis itself (the background task just performs a touch which will force the expires rather than having it happen non-deterministically). This is necessary to ensure every node receives the event.

I'm going to close this until we actually see some sort of issue with it.

**Comment by mp911de** [comment]
One thought about Redis and clustering: Redis Cluster keyspace events are node-local and not propagated to the whole cluster. That's an issue with Spring Data Redis and the backing clients which may cause missing application notifications. Just wanted to drop you a line to keep it in mind.
