### ISSUE TITLE
EnableRedisHttpSession redisNamespace should support SpEL

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#381]

**Comment by eddumelendez** [comment]
@rwinch I have created a PR for this. I think that should be more generic now since `spring-session` support JDBC, Mongo. Can you confirm this? then I can add the other ones. Thanks

**Comment by rwinch** [comment]
@eddumelendez Thanks for the PR! If you are interested in submitting it, please create additional PRs for the other databases that are supported too. Thanks again!

**Comment by eddumelendez** [comment]
@rwinch #512 and #513 were submitted
