### ISSUE TITLE
logout causing NPE

### ISSUE THREAD

**Issue by sreekanthsnair** [spring-projects/spring-session#392]
Was testing the latest release 1.1.0.RELEASE, I was trying to logout, it throws the following exception. And also i have noticed that upon logout there is another cookie called JSESSIONID getting created.

```
Exception handling request to /myapp/logout: java.lang.NullPointerException
	at java.util.StringTokenizer.<init>(StringTokenizer.java:199)
	at java.util.StringTokenizer.<init>(StringTokenizer.java:221)
	at org.springframework.session.web.http.CookieHttpSessionStrategy.getSessionIds(CookieHttpSessionStrategy.java:308)
	at org.springframework.session.web.http.CookieHttpSessionStrategy.onInvalidateSession(CookieHttpSessionStrategy.java:260)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:190)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:170)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:128)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:65)
```

Environment : Ubuntu 14.04, Wildfly 9.0.2.Final, Chrome/Firefox

**Comment by rwinch** [comment]
@sreekanthsnair Thanks for the report. Does this still happen if you clear out your cookies before authenticating?

**Comment by sreekanthsnair** [comment]
@rwinch Yes it is, i have cleared all the cookie then i have logged in then while tried to logout its giving NPE. I was using 1.0.2.RELEASE and was overriding **CookieHttpSessionStrategy** to solve setting custom cookie path  as per your input and i have experience the same NPE but i thought it may be due to the change i've made so i have fixed in **getSessionIds** method as follows
```
String sessionCookieValue = session == null ? "" : StringUtils.defaultIfBlank(session.getValue(), "");
```
Since setting custom cookie path is fixed in latest release, i have removed my custom **CookieHttpSessionStrategy** implementation and used the config as follows

```
@Configuration
@EnableRedisHttpSession
public class RedisHttpSessionConfiguration {

    @Bean
    public CookieSerializer cookieSerializer() {
        final DefaultCookieSerializer serializer = new DefaultCookieSerializer();
        serializer.setCookieName("JSESSIONID");
        serializer.setCookiePath("/");
        serializer.setDomainNamePattern("^.+?\\.(\\w+\\.[a-z]+)$");
        return serializer;
    }
}
```
But this config didn't work for me since was not able to do SSO, at the same time i was facing the NPE while logout. Then i have add **CookieHttpSessionStrategy** bean definition back to my config as follows 

```
 @Bean
    public CookieHttpSessionStrategy cookieHttpSessionStrategy(CookieSerializer cookieSerializer) {
        final CookieHttpSessionStrategy cookieHttpSession = new CookieHttpSessionStrategy();
        cookieHttpSession.setCookieSerializer(cookieSerializer);
        return cookieHttpSession;
    }
```

After this change, SSO started working but facing the same NPE on logout, that leads me to file this issue. Later i have added custom implementation for **CookieHttpSessionStrategy** and override **getSessionIds** method to solve the NPE as follows.
```
String sessionCookieValue = StringUtils.defaultIfBlank(cookieValues.isEmpty() ? "" : cookieValues.iterator().next(),
                "");
```
the problem was ```cookieValues.iterator().next()``` was returning null on logout.

**Comment by tsachev** [comment]
It seems that following line can return `null`.
https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/web/http/DefaultCookieSerializer.java#L61

**Comment by sreekanthsnair** [comment]
@tsachev  no i'm not clearing any cookie before logout, but before login i did clear.

**Comment by rwinch** [comment]
@tsachev Thanks for the help!

@sreekanthsnair Thanks for the details on the issue :) I put together a branch that I believe should resolve your issue. Can you check to see if this fixes your issue?

https://github.com/rwinch/spring-session/tree/gh-392

You should be able to produce a jar by invoking

    $ cd <clone-dir>/spring-session
    $ ./gradlew package

The jar will be available at 

   <clone-dir>/spring-session/build/libs/spring-session-1.2.0.BUILD-SNAPSHOT.jar

Once you have verified it works, I will push to master and backport it to 1.1.x branch.

**Comment by sreekanthsnair** [comment]
@rwinch  sorry for the late reply, i have tested and its working fine now... When shall we expect 1.2.0 release ?

**Comment by rwinch** [comment]
@sreekanthsnair I don't expect to have a 1.2 GA for about a month. However, this issue was also back ported to 1.1.1 via #412 (GitHub issues only allows a single Milestone to be selected). I expect we will try and get a 1.1.1 out in the next week.

**Comment by sreekanthsnair** [comment]
@rwinch thanks :+1:

**Comment by rwinch** [comment]
@sreekanthsnair I just wanted to let you know that 1.1.1 is out with this fix. Thanks again for reporting it :)

**Comment by sreekanthsnair** [comment]
@rwinch thanks :+1:  :-)
