### ISSUE TITLE
Add Travis CI build

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#394]
Since the project is pretty active in terms of community contributions, it might be worth to consider adding Travis CI build to validate changes.

**Comment by rwinch** [comment]
@vpavic Thanks for the suggestion! Any chance you would like to send a PR?

**Comment by vpavic** [comment]
I'd like to help but I can't give you any concrete timeline ATM.
I'll look at it after we clear the #393. They're somewhat related anyway.

**Comment by rwinch** [comment]
@vpavic No problem on the timeline. If you (or anyone else) gets a chance ping this issue first (to make sure others aren't working on it) and then send a PR :)
