### ISSUE TITLE
Update security context for all of a user's sessions?

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-session#398]
I'm implementing subscription plans, where a user can upgrade/downgrade, and the plan change (stored in the Spring Security Authentication) is immediately reflected. The ordinary way to handle this would be to construct a new `Authentication` with the new plan and set it in the security context. However, this will only update the session through which the user performed the change.

I understand that in 1.1 I can `findByIndexNameAndIndexValue` to retrieve the user's sessions, but how would I then go about changing the Spring Security setting and ensuring an update? Do I retrieve `SPRING_SECURITY_CONTEXT`, manipulate it, and save it back into the session? Do I then need to save the session back into the repository?

**Comment by rwinch** [comment]
Thanks for the question.

> Do I retrieve SPRING_SECURITY_CONTEXT, manipulate it, and save it back into the session? 

Yes

> Do I then need to save the session back into the repository?

Yes

I'm not sure I understand the question, because it seems like you already know the answer. I'm closing this, but if you feel like this is unanswered, please reopen and clarify what you are looking for.

**Comment by chrylis** [comment]
I wasn't sure that I knew the answer. I think that it would be helpful to note in the docs for `SessionRepository` that, in the general case, out-of-band manipulation of sessions requires (1) saving a top-level session attribute so that the session knows to include the attribute in the delta and (2) explicitly re-saving the session back into the repository.

**Comment by rwinch** [comment]
@chrylis 

I might be missing your point. I thought this was covered in the [javadoc](http://docs.spring.io/spring-session/docs/current/api/org/springframework/session/SessionRepository.html#save-S-):

> Ensures the Session created by createSession() is saved.
> Some implementations may choose to save as the Session is updated by returning a Session that immediately persists any changes. In this case, this method may not actually do anything.

Perhaps you missed this or it wasn't what you had in mind? If you have some documentation clarifications, I'd encourage you to send a PR :)

**Comment by chrylis** [comment]
I'll try to think how to express it; I was thinking in terms of the reference, not the Javadoc.

**Comment by cemo** [comment]
@rwinch I had same requirements as @chrylis stated. I had to upgrade users plan in case a successful transaction. This was easy because action is taken by user immediately. But downgrading is not easy. Because this process is triggered by cron style applications usually. The problem is that user might be logged as well and race condition can be occur. 

In order to deal with this problem we forced user to reload its own data. We added another db column which is reflecting a dirty principal is available. We did not use session variables for this information because it should not be override by mistake by another request.

What is the Spring Session way to deal with this problem? This is the last thing to remove my whole code to move over Spring Session JDBC Session.

**Comment by rwinch** [comment]
@cemo So what is the race condition that may occur? 

If you are using Redis, only session attributes that are changed will be written. This means that the only chance for a race condition is if you are changing the same session attribute on the same session instance at the same time.

In the JDBC version all the session attributes are written as a blob. This means if any session attributes change there is a chance of a race condition. Note that the last modified attribute is separate and will not cause a race condition with session attributes.

**Comment by cemo** [comment]
I would like to use JDBC based implementation. 

My scenario and causing a race condition: 

1. User is online and has an active request. 
2. Spring Security Context is fetched at beginning of request from session. 
3. At the same time of middle of the request timeline, a cron job downgrades user's subscription. This cron job fetches user session and updates session for necessary roles to reflect downgrade.
4. User request finishes and persists after cron job's persist.   

In this case I am losing the information of downgrading in security context. Hope that I am clear enough. What is the best practice to deal with this problem?

**Comment by rwinch** [comment]
@cemo  I'm wondering if in practice we are going to need to change the JDBC implementation to write attributes independently so we can only write attributes that have changed. Can you create a new ticket?
