### ISSUE TITLE
Add HttpSessionListener Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#4]
Consider adding HttpSessionListener Support.

Depending on the implementation this may be impossible to reliably support. For example, while we can receive expiration notifications from Redis, there are no guarantees on when the expiration event will be sent.

Depends On #45

**Comment by aravindanr** [comment]
@rwinch Any plans to support this for MapSession. Currently, I am using MapSession with Spring Security. Since the Session events are not published, the Spring Security Session Management does not work correctly. Destroyed sessions do not get removed from SessionRegistry. To fix this, i am manually publishing the event in a LogoutHandler.

For my use case, if at least MapSession publishes appropriate events, it would be beneficial.

**Comment by gdelprete** [comment]
If ``HttpSessionListener`` support cannot be implemented could you consider at least firing Spring Security's ``HttpSessionCreatedEven``t and ``HttpSessionDestroyedEvent`` ? Those are helpful to build an in-memory list of HttpSession objects by session id, which I'd like to use in a custom implementation of Spring Security session management own ``ConcurrentSessionControlAuthenticationStrategy`` that invalidates sessions on the spot.

Without those two, I can retrieve Spring Session's ``Session`` or ``ExpiringSession`` objects (wiring ``SessionRepository`` in) but then I can;t invalidate the session as those objects do not have a invalidate() method.

**Comment by making** [comment]
:+1: 

Unless `HttpSessionListener` and `HttpSessionAttributeListener` is supported, documenting alternative solutions is helpful and required.

`org.springframework.context.ApplicationListener` for `org.springframework.session.events.SessionDestroyedEvent` is alternative of `javax.servlet.http.HttpSessionListener#sessionDestroyed`?

**Comment by making** [comment]
`javax.servlet.http.HttpSessionBindingListener` dose not seem to work.
So `org.springframework.web.context.request.DestructionCallbackBindingListener` doesn't work.
This means `@PreDestroy` annotated session scoped bean doesn't work, right?

**Comment by paskos** [comment]
:+1: 
We don't have requirement for clustering and use `MapSessionRepository` as bridge between `HttpSession`and `WebSocketSession`and we'd like to have metrics on active sessions but `HttpSessionListener`is not supported.

**Comment by rwinch** [comment]
@paskos  NOTE: You can get active sessions by querying Redis instead

**Comment by paskos** [comment]
We don't use Redis because we don't need clustering, we use `MapSessionRepository`

**Comment by praveen12bnitt** [comment]
+1

**Comment by bmorris591** [comment]
+1 from me.

We use the SessionDestroyedEvent to get information about the user. This information is stored in a "login history table" - so we need the information stored on the `Session` to build the data.

Happy to use a workaround - but cannot think of one at the moment...

**Comment by rwinch** [comment]
With the attention this is receiving, I believe we will be looking into support for this feature in 1.1 or 1.2 (it really depends on how much time I have). I've been giving this some thought and the way I think we might be able to support this is doing something like this:

# Ensure that the Session Exists After Expires

Set the Redis expires on the actual session to be +10 minutes from the actual expires. This will differ from the key that contains the actual expiration in it.

# Ensure that if the Session is Expired, we don't return it through the API

When we retrieve a Session from Redis see if the value associated to the expires key is actually expired.

# Ensure that Sessions are cleaned up appropriately

When creating a session, we will also create another key value pair that has the "real" Redis expiration time on it. Whenever we perform any operations on the actual session, we will need to update this expiration too.

If we detect that this session expired (by listening for notifications), then we can retrieve the real session using a convention. For example, if we see the key `abc123-notify` expire, we would retrieve the session under abc123, send an event with its information, and then manually delete abc123.

If anyone wants to look into submitting a PR it would be most welcome! If you have any questions please don't hesitate to reach out via this issue and mentioning me.

**Comment by rwinch** [comment]
I have moved this to be added in 1.1 M1 since we are going to need to support this feature for #7

**Comment by rwinch** [comment]
I added HttpSessionListener support for the Redis based implementation. To use it you create your HttpSessionListener as a Spring bean instead of registering it with the Servlet Container. Details will be available in the docs as soon as they deploy (about 30 min) at http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#httpsession-httpsessionlistener

**Comment by sanketmeghani** [comment]
@rwinch Does spring-session supports session listener for redis cluster configuration? In our application we are using redis cluster and it seems we are not receiving session-created/session-destroyed call back. We are receiving the session HttpSessionListener call back if we use stand-alone instance of redis server.

**Comment by rwinch** [comment]
@sanketmeghani Yes. You must be using Spring Session 1.1+ You can find additional details at http://docs.spring.io/spring-session/docs/current/reference/html5/#httpsession-httpsessionlistener

**Comment by sanketmeghani** [comment]
@rwinch Thank you for quick response. We are using spring-session 1.2.0.RC1 and spring-data-redis 1.7.0.RC1. Somehow we are not getting the listener call back if we use **redis cluster**. It works perfect if we use a stand-alone redis server. I have uploaded a sample [springSessionContext.xml ](https://github.com/sanketmeghani/spring-session/blob/master/src/main/webapp/WEB-INF/spring-context.xml). 

On one of the nodes in redis cluster, we see "SUBSCRIBE" "__keyevent@*:expired" "spring:session:event:created:*" "__keyevent@*:del" command. So it does subscribe on one node. Should it subscribe to all nodes in the cluster? Or this is expected behavior?

**Comment by rwinch** [comment]
@sanketmeghani Sorry I missed the Redis cluster part. Let's create a distinct issue to discuss this please.

**Comment by sanketmeghani** [comment]
Created a distinct issue #478 to discuss this.
