### ISSUE TITLE
DefaultSavedRequest is lost when session expires

### ISSUE THREAD

**Issue by baspet** [spring-projects/spring-session#401]
it seems that DefaultSavedRequest  is lost when session expires. 
If session is not present everything works as expected.

V.

**Comment by chrylis** [comment]
The `SavedRequest` is usually saved into the HTTP session in `HttpSessionRequestCache`.

**Comment by rwinch** [comment]
@baspet Thanks for the report! @chrylis is correct. The default implementation of  `RequestCache` is to save in the `HttpSession` which means if the HTTP session expires, the saved request is gone.

**Comment by rwinch** [comment]
Closing this issue as it has been answered as "works as designed". If you have follow up questions, please reopen the issue.

**Comment by baspet** [comment]
the problem is that when session is **expired** (cookie is still here) and user refreshes his page HttpSessionRequestCache returns null.

**Comment by baspet** [comment]
please, let me explain further.
the problem occurs when session is **expired ** (cookie still there) and user **refreshes **his page.

**Comment by rwinch** [comment]
@baspet Yes this is still expected. If the user refreshes the page after session expiration, then the cookie is expired and it will only request the log in page which means the originally saved URL is not saved again.

**Comment by baspet** [comment]
i still i cannot understand what's the difference between an 'expired' session and an 'empty' session.
you can reproduce it also, if you manually modify the cookie on browser and refresh page

ps
i tried also setting cookie maxAge = redis_timeout but no luck.

**Comment by rwinch** [comment]
@baspet In this instance there is no difference between no session and expired session. In either case there is no data associated with the session id. If you modify the cookie then the browser is no longer associated with the session so it will fail.

> i tried also setting cookie maxAge = redis_timeout but no luck.

I'm not sure what you mean here

**Comment by baspet** [comment]
ok, let's show my steps
1) user opens browser and goes to /a.html (protected)
2) user is redirected to login page
3) user logs in
4) **user is redirected to /a.html**
everything is fine here

the bad case:
1) session is expired (cookie is not valid in redis)
2) user tries to go to /a.html (protected)
3) user is redirected to login page
4) user logs in
5) **user is redirected to /**

thanks for your help

**Comment by rwinch** [comment]
@baspet Thank you. This makes it more clear.

**Comment by baspet** [comment]
How are you integrating with Redis? 
using @EnableRedisHttpSession 
also, i customize CookieHttpSessionStrategy like:

```
	@Bean
	public CookieHttpSessionStrategy httpSessionStrategy() {
		DefaultCookieSerializer cookieSerializer = new DefaultCookieSerializer();
		cookieSerializer.setCookieName("X_SESSION_COOKIE");

		CookieHttpSessionStrategy httpSessionStrategy = new CookieHttpSessionStrategy();
		httpSessionStrategy.setCookieSerializer(cookieSerializer);
		
		return httpSessionStrategy;
	}

```

Is the request to /a.html an HTTP GET?
yeap

**Comment by rwinch** [comment]
@baspet Thank you for the additional details. 

Does the issue occur when you are not using Spring Session? Have you tried clearing all your cookies and then rerunning the test? Spring Session has a known issue that if multiple session cookies are submitted with the request that it will fail to find the session. 

For example, the session cookie with the name X_SESSION_COOKIE may be saved in the browser in multiple matching domains or along multiple matching paths. This would mean the X_SESSION_COOKIE is submitted multiple times to the server. In that instance, the first cookie is used. For details refer to spring-projects/spring-session#275

**Comment by baspet** [comment]
you are right!!

than you for your help

**Comment by rwinch** [comment]
@baspet Was it an issue with multiple cookie values being sent then?

**Comment by baspet** [comment]
i try to figure it out as my case is a little bit complex.
i am playing around with oauth2 and my requirements are to have the cookie set to domain '**a.b.c**' when user is **presented** with login screen and set it to domain'**.b.c**' after login (so this cookie can be visible to other apps).
to implement this i have to expire 'a.b.c' after login and here something went wrong..!

i didn't intend to occupy your time but the same scenario was playing before switching to redis session.

**Comment by rwinch** [comment]
Thanks for the response. Given your feedback, I'm closing this
