### ISSUE TITLE
Actuator Endpoint to Delete Sessions

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#407]
It would be nice to add an actuator [Endpoint](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-customizing-endpoints-programmatically) that:
- Allows finding sessions by username
- Displays the resulting sessions
- Then allows deleting the session

I think an HTML version of this would be awesome for administrators, but we would likely want to support all the various Actuator endpoint styles (i.e. JMX, JSON, etc)

Related #408

**Comment by vpavic** [comment]
This is scheduled to be implemented in Boot 2.0 via spring-projects/spring-boot#8342.
