### ISSUE TITLE
Add Actuator Endpoint to Change Log Level

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#408]
It would be nice to add an actuator endpoint that:
- Allows finding sessions by username
- Displays the resulting sessions
- Then allows changing the log level for the session. See [rwinch/spring-session-logging](https://github.com/rwinch/spring-session-logging)

I think an HTML version of this would be awesome for administrators, but we would likely want to support all the various Actuator endpoint styles (i.e. JMX, JSON, etc)

Related #407

**Comment by vpavic** [comment]
Closing in favor of spring-projects/spring-boot#11018 as this should be considered for implementation in Boot's Actuator (same like with #407).
