### ISSUE TITLE
Is it possible to add custom data to session cookie?

### ISSUE THREAD

**Issue by fehmicansaglam** [spring-projects/spring-session#411]
I have searched for this in the docs and the source code but I could not find an answer. Along with the session id I need to put some user related insensitive data to the session cookie which is going to be parsed by a load balancer. Is this somehow possible? Or should I use a different cookie?

**Comment by rwinch** [comment]
@fehmicansaglam Can you elaborate on exactly what you are putting in the cookie? Are you looking to add a jvmRoute? Perhaps the [Custom Cookie Guide](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/custom-cookie.html#custom-cookie-options) would help?

**Comment by fehmicansaglam** [comment]
@rwinch thanks, I have read that guide. I want to set a memberKey value which is unique for each user. As far as I can see jvmRoute is set across the whole application. I need to set a different value for each user. In other words I need to set a unique value after sessionId in the cookie.

**Comment by rwinch** [comment]
You can create a custom `CookieSerializer` that either delegates to or overrides the `DefaultCookieSerializer`.

**Comment by fehmicansaglam** [comment]
I have also tried that. But the problem is that the session cookie is set
before the user logs in and cannot be changed after that because
writecookievalue is called only once. Do I miss smth?

**Comment by rwinch** [comment]
@fehmicansaglam Typically the session id should change after a user authenticates to prevent session fixation attacks. If you are using Spring Security this would be done for you. So if the session id changes, the cookie should be updated.

If this does not work for you, I'd suggest adding a hook at the time of log in to your application to include the information in a separate cookie.

**Comment by fehmicansaglam** [comment]
I see. I'll go with a separate cookie. Thanks.

**Comment by rwinch** [comment]
Thanks. I'll close this. Feel free to ping again if you have further questions.
