### ISSUE TITLE
Use Embedded Mongo for integration tests & samples

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#419]
Currently a simple ```./gradlew build``` requires having an instance of MongoDB running for build to complete successfully.

IMO this is not the greatest development experience, and it should be considered to move the integration tests for Mongo support to use somethling like an [embedded MongoDB](https://flapdoodle-oss.github.io/de.flapdoodle.embed.mongo/).

/cc @jkubrynski

**Comment by jkubrynski** [comment]
I see two solutions here:
1. Use flapdoodle
2. Use docker to control external services like Redis, Mongo, GemFire, etc

**Comment by chrylis** [comment]
I'd suggest considering Fongo. It's not a full-featured replacement for an external Mongo instance, but I've been using it successfully for some time, and the functionality required here is basic.

**Comment by rwinch** [comment]
@vpavic Thanks for the suggestion! Do you know how this works? Is it using an executable and starting a process? I'm asking because historically this hasn't gone so well for us (we tried it with Redis and it didn't work on various flavors of Linux, Windows, etc).

**Comment by vpavic** [comment]
@rwinch I actually don't have any first-hand experiences with Flapdoodle Embedded MongoDB.

I do know that Spring Boot provides auto-configuration for it (see spring-projects/spring-boot#1794, spring-projects/spring-boot#2002), and based on my experience contributing to Boot multiple times I've never encountered any problems with Flapdoodle related integration tests while building the project. Hence my idea of using it in Spring Session for integration tests as well.

From a broader perspective, another advantage for Flapdoodle vs other possible solutions is that it is already part of Spring Platform as far as dependency management is concerned.

**Comment by rwinch** [comment]
@vpavic Let's go ahead and give Flapdoodle a try. So long as we keep it to the samples & integration tests it isn't going to hurt anything (we can always roll back).

Anyone that is interested in picking this up, please comment that you would like to submit the PR :)

**Comment by vpavic** [comment]
@rwinch :+1:
