### ISSUE TITLE
Session is saved two times per request if onResponseCommitted is triggered

### ISSUE THREAD

**Issue by oyvindhorneland** [spring-projects/spring-session#424]
When SessionRepositoryResponseWrapper's onResponseCommitted is triggered, the session is saved to repository. The session is saved again in the SessionRepositoryFilter's doFilterInternal finally block.

Would it be possible to have the doFilterInternal finally block check if the session had already been saved due to onResponseCommitted?

Version: 1.2.0 SNAPSHOT

**Comment by rwinch** [comment]
This is typically left up to specific SessionRepository implementations. What implementation are you using?

**Comment by oyvindhorneland** [comment]
I was trying the new JdbcOperationsSessionRepository on Spring Boot 1.3.3 with Jetty 9.3 and Oracle database. It seemed to me at the time that the behavior was not session repository implementation dependant since both save invocations were executed from SessionRepositoryFilter, but I'll take another look and see if I can reproduce with MapSessionRepository.

**Comment by rwinch** [comment]
@oyvindhorneland Typically the SessionRepository should keep track of if anything has changed. If nothing has changed, then it should not write to the database again.

**Comment by oyvindhorneland** [comment]
Aha. You are absolutely correct :-) The repository's save method is called twice, but the last call detects that there are no changes and does not touch the database. Apparently I didn't check all the way.

Nothing to see here, move along..

**Comment by rwinch** [comment]
Thanks for the fast follow up!

**Comment by vpavic** [comment]
@oyvindhorneland thanks for testing the ```JdbcOperationsSessionRepository```.
It's great to see feedback so quickly after this feature was merged to the master.

**Comment by oyvindhorneland** [comment]
Thank you, @vpavic , for a great addition to Spring Session! I was just itching to try it out as soon as you and @rwinch got this new feature merged :-)
