### ISSUE TITLE
How to autowire exact RedisConnectionFactory instance to RedisHttpSessionConfiguration if I have more than one instances?

### ISSUE THREAD

**Issue by Sunshow** [spring-projects/spring-session#438]
one instance for HttpSession
one for cache
and others

**Comment by vpavic** [comment]
@Sunshow you need to configure and register a ```RedisOperations``` bean named ```sessionRedisTemplate```.

This will override the default ```RedisTemplate``` instance provided by ```RedisHttpSessionConfiguration```.
Take care to configure the serializers since in this case you need to do that part manually.

**Comment by Sunshow** [comment]
@vpavic 
RedisHttpSessionConfiguration declared amount of Beans using RedisConnectionFactory, is it enough to override sessionRedisTemplate?

**Comment by vpavic** [comment]
@Sunshow yes, but it is important that your ```RedisOperations``` bean is named ```sessionRedisTemplate```.

You can verify this easily - place two breakpoints in ```RedisHttpSessionConfiguration```, one in ```sessionRedisTemplate``` method and the other in ```sessionRepository``` method. Once you provide your ```RedisOperations``` bean is named ```sessionRedisTemplate``` you won't hit the breakpoint placed in ```RedisHttpSessionConfiguration.sessionRedisTemplate``` but you will the other one.

**Comment by Sunshow** [comment]
@vpavic yes, it works! thank you!

**Comment by rwinch** [comment]
Thanks for answering this one @vpavic!

**Comment by navykoo** [comment]
@rwinch , I'm facing the same issue. But I am not quite clear about the detailed implementation. I tried to create a new Class extends RedisTemplate. 

public class SessionRedisTemplate extends RedisTemplate <Object, Object>{
	    
	public SessionRedisTemplate(RedisConnectionFactory connectionFactory){
		this.setKeySerializer(new StringRedisSerializer());
		this.setHashKeySerializer(new StringRedisSerializer());
		this.setConnectionFactory(connectionFactory);
	}

}


and then add below line into applicationContext.xml,

       <bean id="sessionRedisTemplate" class="com.bosir.messaging.SessionRedisTemplate">
		<constructor-arg ref="jedisConnectionFactory">
            	</constructor-arg>
	</bean>

-------


but it still failed :(

**Comment by navykoo** [comment]
Finally I found a working answer from https://github.com/spring-projects/spring-session/issues/448. Although it doesn't look grace as someone commented.
