### ISSUE TITLE
Spring Session REST support

### ISSUE THREAD

**Issue by mkopylec** [spring-projects/spring-session#439]
What do you think about adding [Data REST](https://github.com/spring-projects/spring-data-rest) support, similarly to Redis, Hazelcast etc.?

**Comment by rwinch** [comment]
@mkopylec I like the idea :)

**Comment by vpavic** [comment]
Is introducing HTTP as a transport layer towards session store really a wise idea?
This could incur all sorts of potential issues, starting from performance... which is something that's IMO crucial for session store, together with reliability.

**Comment by rwinch** [comment]
@vpavic Like most things this is a tradeoff (not much different than a microservice)

**Comment by mkopylec** [comment]
@vpavic I agree, but in case of microservices architecture you can benefit from having a service for managing HTTP session, because you can have detailed logs in one place and you can monitor your global HTTP session state just like you monitor other microservices in your system.

**Comment by vpavic** [comment]
Closing due to reasons explained in #768.
