### ISSUE TITLE
Session alias lost from url on redirect

### ISSUE THREAD

**Issue by anupriyachhabra** [spring-projects/spring-session#447]
My application uses a post- redirect - get pattern. I create a new session alias in post method of my controller and pass it to the redirect url as :redirect/app/next?_s=1 . But the redirect looses the _s=1 part and I end up with just /app/next? . I did some debugging and it looks like the RedirectView.class is calling MultiSessionHttpServletResponse method encodeRedirectURL which in turn calls CookieHttpSessionStrategy.this.encodeURL and the replace logic in CookieHttpSessionStrategy.this.encodeURL removes my sessionAlias in end of url. Any ideas on how to get around this limitation

**Comment by rwinch** [comment]
Thanks for the report @anupriyachhabra!

How are you performing the redirect after you get the POST? Can you put a small sample application together?

**Comment by anupriyachhabra** [comment]
Below is my controller post method in groovy

`@RequestMapping(value = '/{listingId}',method = RequestMethod.POST)
    def initiateFlow(@ModelAttribute('flow') Flow flow, @ModelAttribute('transaction') Transaction
            transaction, HttpServletRequest httpRequest, RedirectAttributes attr) {
  
        def alias = sessionStrategy.getNewSessionAlias(httpRequest)
        sessionStrategy.encodeURL("redirect:/details/$transaction.listingId", alias)
      
    }

**Comment by rwinch** [comment]
> I am working on uploading a sample application. Added this just to explain the problem better

Thanks for the explanation. I will take a look at the sample once you are able to get one.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
