### ISSUE TITLE
multiple redis config in application

### ISSUE THREAD

**Issue by vivisidea** [spring-projects/spring-session#448]
the demo project requires SINGLE JedisConnectionFactory bean, with multiple JedisConnectionFactory config in my application, how can I specify which factory to use? 

any help would be appreciated.

```
<bean class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration" />

<bean id="jedisConnectionFactory1" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"/>
<bean id="jedisConnectionFactory2" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"/>
```

the exception:
```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.data.redis.connection.RedisConnectionFactory] is defined: expected single matching bean but found 2:
```

**Comment by rwinch** [comment]
You can use `primary="true"` on the Bean you wish to use with Spring Session. For example, the following will use `jedisConnectionFactory1`:

```xml
<bean class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration" />

<bean id="jedisConnectionFactory1" primary="true" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"/>
<bean id="jedisConnectionFactory2" class="org.springframework.data.redis.connection.jedis.JedisConnectionFactory"/>
```

**Comment by rwinch** [comment]
I'm going to mark this as closed. Please feel free to reopen if this does not help

**Comment by vivisidea** [comment]
It worked, thanks!

**Comment by Drizzt321** [comment]
I'm just facing the same issue, but having to mark it as @Primary is a bit messy for me. @EnableRedisHttpSession should allow taking in a bean name, or modify RedisHttpSessionConfiguration to use a specific bean name for the connection factory that can then be used by client applications to configure it.

**Comment by hahlalu** [comment]
Some advice:
RedisHttpSessionConfiguration  should use a ConnectionFactory bean with specified name, for example 'sessionRedisFactory'. Then a user-defined ConnectionFactory bean with a different name will not conflict with it.
