### ISSUE TITLE
Customizable session timeout

### ISSUE THREAD

**Issue by leofromgroza** [spring-projects/spring-session#449]
At one project with multi-tenancy architecture I had to resolve one interesting task: I should set custom session timeout for users from different tenants. I found that in the end of method `org.springframework.session.web.http.SessionRepositoryFilter#doFilterInternal` session is saved into `sessionRepository `(`wrappedRequest#commitSession()`). Session object  is extracted from request by custom attribute:
`private final String CURRENT_SESSION_ATTR = HttpServletRequestWrapper.class.getName();`
So the only solution that I found for my task is to update that request attribute using reflections (`HttpSessionWrapper` is private final class) in `org.springframework.security.web.authentication.AuthenticationSuccessHandler`.
I want to ask Spring-Session developers to make SessionRepositoryFilter more open for customization (remove private final for classes, provide some API, etc).

**Comment by rwinch** [comment]
@leofromgroza Thanks for the report! 

Did you consider setting [HttpSession.html#setMaxInactiveInterval(int)](http://docs.oracle.com/javaee/5/api/javax/servlet/http/HttpSession.html#setMaxInactiveInterval(int)) which would allow a custom expiration for the session?

**Comment by leofromgroza** [comment]
Yes, I used that method. Here is my code:
```
Object sessionWrapper = request.getAttribute(HttpServletRequestWrapper.class.getName());
Field sessionFiled = sessionWrapper.getClass().getSuperclass().getDeclaredField("session");
sessionFiled.setAccessible(true);
ExpiringSession session = (ExpiringSession) sessionFiled.get(sessionWrapper);
session.setMaxInactiveIntervalInSeconds(customSessionExpirationTimeoutSec);
```
But that code is not looking like code from best practices. What bad things I did? 
- I used HttpServletRequestWrapper.class.getName() as attribute name because I do not have access to original `org.springframework.session.web.http.SessionRepositoryFilter.SessionRepositoryRequestWrapper#CURRENT_SESSION_ATTR`. So if somebody will change that attribute name in Spring Session library in future version - I will receive errors in our project;
- Using of Reflection API in such cases is bad practice. It will be better to use API. But currently there is no such API in Spring Session library.

**Comment by rwinch** [comment]
You don't need reflection to access the `HttpSession`. Try the following:

```java
HttpSession httpSession = httpServletRequest.getSession();
httpSession.setMaxInactiveInterval(customSessionExpirationTimeoutSec);
```

**Comment by leofromgroza** [comment]
I tried such solution and it is not working and I even know why. As I mention in first post, after processing request on controller's side, session is committed by `org.springframework.session.web.http.SessionRepositoryFilter` that invokes `org.springframework.session.web.http.SessionRepositoryFilter.SessionRepositoryRequestWrapper#commitSession`. In that method session is extracted from request attribute (**not from request directly** `httpServletRequest.getSession()`) and stored into sessionRepository. So if i made changes in httpServletRequest.getSession() they will be ignored by `commitSession` method.

**Comment by rwinch** [comment]
@leofromgroza The request attribute is where httpServletRequest.getSession() is getting the underlying spring session.

Can you provide a sample that reproduces the problem?

**Comment by leofromgroza** [comment]
Very strangely, but I cannot reproduce that issue. Sorry for inconvenience.

**Comment by rwinch** [comment]
@leofromgroza Thanks for the follow up. I'm glad you were able to get this resolved :)
