### ISSUE TITLE
I now use the Shiro, how to integrate?

### ISSUE THREAD

**Issue by xiaolongyuan** [spring-projects/spring-session#455]
http://shiro.apache.org

**Comment by rwinch** [comment]
We do not currently provide support for Shiro. This could be done by implementing Shiro's [SessionManager](http://shiro.apache.org/session-management.html). If this is something that you end up putting together, I'd be interested in seeing the results :)

Relates to #310

**Comment by fige135** [comment]
@xiaolongyuan ,use shiro's default ServletContainerSessionManager. assure spring session filter lies before shiro filter in web.xml
