### ISSUE TITLE
Spring Session JDBC does not seem to commit transaction after session creation

### ISSUE THREAD

**Issue by flomorgen** [spring-projects/spring-session#459]
I have a Spring Boot application using an Oracle database and I'm trying to integrate Spring Session JDBC to enable several application instances to share user sessions. For user authentication Spring Security and for database access Spring Data JPA is used. The database connection pool configuration is done via _spring.datasource.*_ properties in the application.properties.
The application is configured with having _spring.datasource.default-auto-commit=false_, declaring all transactions via the @_Transactional_ annotation.

After logging in the client receives a session cookie as expected, but the database session table seems to be still empty, although the JdbcTemplate logs execution of an insert statement. Further requests using the session cookie fail because the session cannot be found in the database.(the database isolation level is READ_COMMITTED) When shutting the application down the session becomes visible in the database table. (seems like transactions are committed on shutdown)
Having _spring.datasource.default-auto-commit=true_ the session handling works fine, but this is not an option for the application.
I took a look into the Spring Session JDBC code and to me it looks like the JdbcTemplate actually does not work in context of transactions yet. Is this correct? If yes, is it possible to integrate transaction handling to Spring Session JDBC?
I could reproduce the behaviour with a slightly adapted variant of the Spring Boot example too.

**Comment by vpavic** [comment]
@flomorgen thanks for testing the JDBC support and reporting this issue.

Take a look at #446, it is a different problem but the root cause is the same and its resolution is in progress.
