### ISSUE TITLE
performance issues using redis repository

### ISSUE THREAD

**Issue by baspet** [spring-projects/spring-session#466]

**Comment by rwinch** [comment]
A few questions/comments:

* What version are you using?
* It sounds as though methods are being called, but what numbers are you seeing?
* I have seen lots of additional calls if you have an HTML page that requests additional resources (i.e. css, javascript etc)
* Saving the session is a no op if nothing has changed.
* getSession is cached once per request

**Comment by baspet** [comment]
What version are you using?
1.1.0.RELEASE

I have seen lots of additional calls if you have an HTML page that requests additional resources (i.e. css, javascript etc)
it's just an empty html page

It sounds as though methods are being called, but what numbers are you seeing?
1 for getSession (indeed it's cached)
7 for SessionRepositoryResponseWrapper.onResponseCommitted
these are:
getSessionBoundHashOperations(sessionId).putAll(delta);
redis.boundSetOps(expireKey);
expireOperations.add(keyToExpire);
expireOperations.expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);
redis.delete(sessionKey);
redis.boundHashOps(getSessionKey(session.getId())).expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);

7 wrappedRequest.commitSession()
same as above

Saving the session is a no op if nothing has changed
it happens due to lastAccessedTime.

**Comment by rwinch** [comment]
Thanks for the report. I took a look and there is a lot of unnecessary overhead. I went ahead and created #467 to address this

**Comment by rwinch** [comment]
I'm closing this in favor of #467
