### ISSUE TITLE
RedisSession optimization

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#467]
If nothing has changed on `RedisSession`, we should return immediately in `saveDelta`

**Comment by tsachev** [comment]
l think expirations are also updated in `saveDelta`, so make sure this still happens on every response commit.

**Comment by rwinch** [comment]
@tsachev Thanks for the review. 

The expiration will only be updated if one of the attributes has changed. For example, if the last accessed time was modified.

**Comment by tsachev** [comment]
@rwinch Yes you are correct. Update of last accessed time will ensure that expiration policy is called.

**Comment by baspet** [comment]
please, also have in mind that save operation is triggered from two different entry points:
a) SessionRepositoryResponseWrapper.onResponseCommitted and
b) wrappedRequest.commitSession()

maybe a guard like OnCommittedResponseWrapper.disableOnCommitted should help?

**Comment by rwinch** [comment]
@tsachev Thanks for the feedback!

@baspet Thanks for the feedback!

The problem is that we want to write again if the user changes the session in the meantime. Instead we can allow the method to be invoked, but immediately return if no updates are necessary.

**Comment by rwinch** [comment]
@tsachev @baspet I pushed a fix to master. You can try with 2.1.0.BUILD-SNAPSHOT. You can find directions for using the SNAPSHOT in http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/httpsession.html#updating-dependencies

Please provide feedback to see if this resolves the problem for you!

**Comment by baspet** [comment]
just tested and it seems that already updated session is not re updated unless necessary.
so, what about last accessed time? is is necessary to update its value on every request and trigger expiration policy?

**Comment by baspet** [comment]
please, update 2.1.0.BUILD-SNAPSHOT to 1.2.0.BUILD-SNAPSHOT..!

**Comment by rwinch** [comment]
@baspet Thanks for the response. 

> just tested and it seems that already updated session is not re updated unless necessary.

Great to hear!

> so, what about last accessed time? is is necessary to update its value on every request and trigger expiration policy?

You do not need to update the last accessed time because `SessionRepositoryFilter` [does this for you](https://github.com/spring-projects/spring-session/blob/7c616a1adf0a0c0c98e6b2e3be29953f2564f719/spring-session/src/main/java/org/springframework/session/web/http/SessionRepositoryFilter.java#L330).

**Comment by jviladrich** [comment]
@rwinch this changes will fix [this ](http://stackoverflow.com/questions/36432503/spring-rest-webservice-and-session-persistence)?

**Comment by rwinch** [comment]
@jviladrich I don't think it will address that issue since this prevents the session from being written. I'm guessing this might be a duplicate of #311
