### ISSUE TITLE
Session variables always are saved

### ISSUE THREAD

**Issue by jviladrich** [spring-projects/spring-session#469]
I have a session variable with a counter on a controller with two methods one changes the value of the session variable and the other only returns the session variable after a sleep of ten seconds. 
During the execution of the method that sleeps all the changes done on the session variable by the other method are lost because when the method that sleeps when finishes persists the session variable with the values. I do not understand why is doing that because the object is just read and there is no reason to persist. I am using spring session with redis. I think that the problem is on the proxy of the session object.

**Comment by rwinch** [comment]
Thank you for your question. What Spring Session implementation are you using?

**Comment by jviladrich** [comment]
Version 3.1.1. Same behavior with redis and hazelcast.

**Comment by rwinch** [comment]
Spring Session doesn't have a 3.1.1 Can you clarify which version of Spring Session you are using?

**Comment by jviladrich** [comment]
1.1.1.RELEASE. Also tested in a previous version

**Comment by jviladrich** [comment]
The previous was 1.0.2.RELEASE

**Comment by rwinch** [comment]
Thanks for the fast response. Spring Session's Redis support will only write session attributes if `setAttribute` has been invoked. I think you are going to need to provide a sample the reproduces the problem for me to look at.

**Comment by jviladrich** [comment]
Every variable declared using session scope when it is referenced is put to a list of pending attributes to be modified and therefore will be persisted by spring session. If I do not use session scoped variables and instead of that I use HttpSession directly there is no problem

**Comment by rwinch** [comment]
Thanks for the fast follow up!

Ahh...I missed that you were using Spring Session scope (I thought you were just writing the variable to session manually). Yes Spring Session Scope will always write the attributes in the event that a property on it has changed.

Given this I don't think there is anything on the Spring Session side we can do. Therefore I'm going to close this. If you disagree, please reopen the issue.
