### ISSUE TITLE
Spring session timeout issue

### ISSUE THREAD

**Issue by AdithShenoy** [spring-projects/spring-session#479]
Hi,

@rwinch 
I'm using spring session 1.1.1.RELEASE to manage my applications session. I have my custom HttpListener which overrides session created and destroyed events. I have set the timeout as 30 seconds using maxInactiveIntervalInSeconds = 30 in the HttpSessionConfig file.

I see that after 30 seconds, session destroyed event is called as expected.

However, the issue is that the SESSION key in the REDIS is not getting deleted after 30 seconds. It stays there for a longer time. No idea why! Can you please look into this?

**Comment by rwinch** [comment]
@AdithShenoy Thank you for your question. Have you read the [Session Expiration](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration) section of the reference? Does this help answer your question or is it still unclear?

**Comment by rwinch** [comment]
I'm going to close this issue since I think the link should clear it if. If you are still having problems, please feel free to reopen the issue.

**Comment by AdithShenoy** [comment]
Hi @rwinch 

Ah, somehow missed that. Thank you!

Yes you can close the issue. Just a quick final question though, so to check if the session is still active or expired on a httpservletrequest, is this the right way? 

To check if request.getSession(false) is null?

Or is there a better way?

**Comment by rwinch** [comment]
@AdithShenoy That works fine. In general, the Servlet APIs (i.e. `HttpSession`) should act as they do with the servlet.

**Comment by AdithShenoy** [comment]
Awesome. Thank you!

**Comment by AdithShenoy** [comment]
Hi @rwinch ,

I had 2 questions:

1. Does Spring issue a new SESSION cookie even on a redirect? Does redirecting to a log in page handle session fixation?
2. Should i write my custom filter to handle session management check - whether session is still alive or expired or is there a better way?

**Comment by AdithShenoy** [comment]
Hi @rwinch ,

One more query-

I have the gradle dependencies, spring session, spring security, spring boot starter web and spring boot starter redis in my build gradle file and a Spring Application class. When i run this spring boot app, the SESSION cookie does not get created.

However, when I add something to redis using, request.getSession().setAttribute("","");

then the SESSION cookie is being created and sent to the browser. 
Is this the expected behaviour?
Or am I doing something wrong?

P.S - If i remove the Sprign security gradle dependency, then the SESSION cookie gets created without any addition to the session. Please check.

**Comment by rwinch** [comment]
@AdithShenoy Yes. The session (thus the cookie) is lazily created.
