### ISSUE TITLE
Independent update of attributes for JDBC Implemetation

### ISSUE THREAD

**Issue by cemo** [spring-projects/spring-session#486]
from #398 

> I'm wondering if in practice we are going to need to change the JDBC implementation to write attributes > independently so we can only write attributes that have changed. Can you create a new ticket?

**Comment by rwinch** [comment]
cc @vpavic

**Comment by vpavic** [comment]
Are we talking about some specific subset of session attributes or session attributes in general?

**Comment by rwinch** [comment]
@vpavic Attributes in general. For this to work we would have to write each attribute to a join table

**Comment by rwinch** [comment]
PS: This is intended for discussion not to state that we must do it. Given the number of people reporting issues like this lately. I do think this is something to consider strongly though.

**Comment by vpavic** [comment]
> For this to work we would have to write each attribute to a join table

Yes, but this is quite painful to solve with relational databases.

Since this table would effectively act as a key-value store, how do we define the type of a "value" column? Some session attributes are primitive, some are complex, do we serialize them all? Sounds like a big overhead to me. Supporting multiple value columns with a metadata column to indicate attribute type is also possible, but that's even more overhead.

Couldn't we take an entirely different approach and try to deal with this by employing some sort of optimistic locking strategy? After all, the problem we're trying to address here is a race condition.

**Comment by rwinch** [comment]
What do you do when the lock fails though? You can't have a client handle the failure

**Comment by vpavic** [comment]
> We would have a table of session_attributes with columns of sessionid, name, and value. The value column would be written as a blob. So rather than writing the entire session attribute map as a blob. Only individual attributes would be written.

Yes, that's what I had in mind when I said "serialize them all". It's a big overhead IMO since we'd be serializing and creating a BLOB for a lot of attributes.

> What do you do when the lock fails though? You can't have a client handle the failure. I think the failures are going to be quite common in a highly concurrent environment.

We'd have to deal with a failure ourselves. Not sure if that's possible in all situations though, I just threw it in as an idea.

**Comment by rwinch** [comment]
>  It's a big overhead IMO since we'd be serializing and creating BLOBs for a lot of attributes.

Its really the same amount of serialization. Its just done one attribute at a time. I think the bigger concern might be joins.

Another option might be to design to support this in the future, but keep the existing layout.

**Comment by vpavic** [comment]
I've got a working prototype for individual attribute persistence in [my fork](https://github.com/vpavic/spring-session/tree/gh-486).

Tested on H2 and PostgreSQL.

**Comment by rwinch** [comment]
@vpavic Can you submit this as a PR? This will ensure I don't lose track of the fact there is code available.

**Comment by vpavic** [comment]
@rwinch Sure thing, but I first need to update the rest of schema scripts. And run the tests on a few more databases since the implementation has become a bit more complex now.

I plan to finish these tasks and submit the PR by the end of the day.

**Comment by rwinch** [comment]
Thanks!

**Comment by rwinch** [comment]
This is fixed via 00e7110594e39bd81da79934719ad491275ddb80
