### ISSUE TITLE
JdbcHttpSessionConfiguration should expose setters for annotation attributes

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-session#488]
I am trying to integration spring session based on a PR. I am moving away from the current proposal to extend from each configuration classes (which allows me to customize the store specific settings exposed by each individual annotation).

`HazelcastHttpSessionConfiguration` has a `setMaxInactiveIntervalInSeconds` but `JdbcHttpSessionConfiguration` doesn't. There is no setter to customize the `tableName`

**Comment by snicoll** [comment]
`MongoHttpSessionConfiguration` is also affected. I can submit a PR if needed.

**Comment by rwinch** [comment]
This is fixed via #490
