### ISSUE TITLE
Multiple clients to share data in a session, but is not the same sessionid

### ISSUE THREAD

**Issue by dzhai** [spring-projects/spring-session#497]
**As such**
**spring:session:userid:cache**                                  ---- The user cache information  
**spring:session:userid:login_pc_XXXX**                    ---- Sessionid of cookies and custom data  
**spring:session:userid:login_IOS_XXXX**                  ---- Sessionid of cookies and custom data  
**spring:session:userid:login_Android_XXXX**            ---- Sessionid of cookies and custom data  
**spring:session:userid:login_pc_XXXX**                    ---- Sessionid of cookies and custom data  
....

thanks

**Comment by rwinch** [comment]
I do not understand the issue. Please provide more details

**Comment by dzhai** [comment]
sorry, My English is not good.

Suppose there is such a scene:
A user login through IE browser, through session.setAttribute( "user", user) cache user information, log on after the adoption of chrome browser settings agree session.setAttribute ( "user", user); by the same login firefox browser setting session.setAttribute ( "user", user);
A user has changed the user information through chrome, how to change the user information synchronized to the other session?
This time requires a plurality of user session, jointly hold a public cache information.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
