### ISSUE TITLE
Null HttpSessionManager with HeaderHttpSessionStrategy in Spring session

### ISSUE THREAD

**Issue by josepul** [spring-projects/spring-session#502]
I've a problem with spring-session to allow multiple sessions in same browser. I'm using MapSessionRepository to store sessions and CookieHttpSessionStrategy. With this configutation everything's working fine.

I've been asked to change CookieHttpSessionStrategy to HeaderHttpSessionStrategy. Now I get a NullPointerException when I try to get HttpSessionManager from request.

This is my previous config (I'ts working):

```
@Configuration
@ComponentScan(basePackages = { "com.company.name" }, excludeFilters = @ComponentScan.Filter(type = FilterType.REGEX, pattern = { "com.company.name.web*" }))
@EnableScheduling
@EnableAspectJAutoProxy
@EnableCaching
@EnableSpringHttpSession
public class Config {
    ....
    ....
    @Bean
    public MapSessionRepository sessionRepository() {
        return new MapSessionRepository();
    }

    @Bean
    public HttpSessionStrategy httpSessionStrategy() {
        return new CookieHttpSessionStrategy(); 
    }
}
```
This is my new config:

```
@Configuration
@ComponentScan(basePackages = { "com.company.name" }, excludeFilters = @ComponentScan.Filter(type = FilterType.REGEX, pattern = { "com.company.name.web*" }))
@EnableScheduling
@EnableAspectJAutoProxy
@EnableCaching
@EnableSpringHttpSession
public class Config {
    ....
    ....
    @Bean
    public MapSessionRepository sessionRepository() {
        return new MapSessionRepository();
    }

    @Bean
    public HttpSessionStrategy httpSessionStrategy() {
        return new HeaderHttpSessionStrategy(); 
    }
}
```
I get SessionManager object with:

```
//Se obtiene el manager de sesiones de spring session
HttpSessionManager sessionManager = (HttpSessionManager) httpRequest.getAttribute(HttpSessionManager.class.getName());
```
When I use header strategy there's no org.springframework.session.web.http.HttpSessionManager attribute on request. Am I doing something wrong? I thought I could change my strategy just returning a HeaderHttpSessionStrategy object or implementing a new custom strategy.

Thanks for your help!

**Comment by rwinch** [comment]
`HeaderHttpSessionStrategy` does not support multiple sessions

**Comment by rwinch** [comment]
I'm going to close this issue. If you feel like I did not answer the question, please reopen.
