### ISSUE TITLE
Why SessionKey(from keyToExpire) contain "expires:" in version 1.1.1 ?

### ISSUE THREAD

**Issue by pigthink** [spring-projects/spring-session#504]
Thanks for developers
I don't understand below codes, why to use variable "keyToExpire" as key to set redis and in cleanExpiredSessions method will to touch it ? but it is not directly related to the real session object.
keyToExpire:     "spring:session:sessions:expires:5984fd82-dee2-4a61-b5bd-baf7d439147a"
sessionKey: "spring:session:sessions:5984fd82-dee2-4a61-b5bd-baf7d439147a"
`public void onExpirationUpdated(Long originalExpirationTimeInMilli, ExpiringSession session) {
		String keyToExpire = "expires:" + session.getId();
		long toExpire = roundUpToNextMinute(expiresInMillis(session));

		if(originalExpirationTimeInMilli != null) {
			long originalRoundedUp = roundUpToNextMinute(originalExpirationTimeInMilli);
			if(toExpire != originalRoundedUp) {
				String expireKey = getExpirationKey(originalRoundedUp);
				redis.boundSetOps(expireKey).remove(keyToExpire);
			}
		}

		String expireKey = getExpirationKey(toExpire);
		BoundSetOperations<Object, Object> expireOperations = redis.boundSetOps(expireKey);
		expireOperations.add(keyToExpire);

		long sessionExpireInSeconds = session.getMaxInactiveIntervalInSeconds();
		long fiveMinutesAfterExpires = sessionExpireInSeconds + TimeUnit.MINUTES.toSeconds(5);
		String sessionKey = getSessionKey(keyToExpire);

		expireOperations.expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);
		if(sessionExpireInSeconds == 0) {
			redis.delete(sessionKey);
		} else {
			redis.boundValueOps(sessionKey).append("");
			redis.boundValueOps(sessionKey).expire(sessionExpireInSeconds, TimeUnit.SECONDS);
		}
		redis.boundHashOps(getSessionKey(session.getId())).expire(fiveMinutesAfterExpires, TimeUnit.SECONDS);
	}
`

**Comment by rwinch** [comment]
Does this help http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-storage

**Comment by pigthink** [comment]
Ok, thanks
