### ISSUE TITLE
MapSession in sessionCreated listener

### ISSUE THREAD

**Issue by grayros** [spring-projects/spring-session#506]
We are using Spring Session version 1.2.0.RC2 with Redis and can not set an attribute successfully because session was created as `MapSession `rather than `RedisOperationSessionRepository`.

**Comment by vpavic** [comment]
Each ```SessionRepository``` repository has its own internal implementation of the ```Session```. This is due to persistence considerations which differ from implementation to implementation.

For this reason ```Session```s are required to be created by ```SessionRepository#createSession```.

**Comment by rwinch** [comment]
Thanks for your help answering this @vpavic! I'm closing this one as outlined in the previous comment
