### ISSUE TITLE
Update Jdbc sessionRepository method sig to avoid conflicts with spring-data

### ISSUE THREAD

**Issue by denov** [spring-projects/spring-session#509]
I'm trying to use the new @EnableJdbcHttpSession to find that that the sessionRepository method in JdbcHttpSessionConfiguration autowires in my spring-data JPA transactionManager.   To avoid this conflict could a qualtifier be added?

from
`JdbcOperationsSessionRepository sessionRepository(@Qualifier("springSessionJdbcOperations") JdbcOperations jdbcOperations, PlatformTransactionManager transactionManager)`

to
`JdbcOperationsSessionRepository sessionRepository(@Qualifier("springSessionJdbcOperations") JdbcOperations jdbcOperations, @Qualifier("springSessionTransactionManager") PlatformTransactionManager transactionManager)`

**Comment by vpavic** [comment]
@denov Why do you consider this a conflict? Are you experiencing any concrete issue with this configuration?

It is actually a normal thing to reuse the ```JpaTransactionManager``` for plain JDBC data access too, assuming they operate on the same ```DataSource```. Refer to [```JpaTransactionManager``` javadoc](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/jpa/JpaTransactionManager.html) for more details.

**Comment by denov** [comment]
i'm following https://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/guides/httpsession-jdbc.html

I was going to try to use H2 for local dev and Redis (elastiCache) in AWS.

**Comment by vpavic** [comment]
I see. The configuration sample uses ```DataSourceTransactionManager``` since it does not assume the use of JPA. As explained above, you can safely use your ```JpaTransactionManager``` in plain JDBC data access scenarios (which includes Spring Session JDBC).

Generally, if you have multiple ```DataSource```s in your app, you should have a dedicated ```PlatformTransactionManager``` for each one. This would require some manual config for Spring Session JDBC.

IMO these are all general Spring transaction management things, but I wonder if we should add something about this in our docs? Thoughts @rwinch?

**Comment by rwinch** [comment]
> MO these are all general Spring transaction management things, but I wonder if we should add something about this in our docs? Thoughts @rwinch?

@vpavic I think it would be good to link to the Spring documentation in this case.

**Comment by vpavic** [comment]
@rwinch OK - I'll submit the PR to address this within the next few days.

**Comment by denov** [comment]
I decided to ditch H2 and just use MySql (my app's main db) for local dev.   Here's my config is case it helps somebody else


```
@Configuration
public class SessionConfig extends AbstractHttpSessionApplicationInitializer {

    private static final Logger log = LoggerFactory.getLogger(SessionConfig.class);


    @LocalDev @Configuration
    @EnableJdbcHttpSession
    public static class LocalConfig {

        public LocalConfig() {
            log.info("local sessions config using JPA");
        }

    }


    @Aws @Configuration
    @EnableRedisHttpSession
    public static class AwsConfig {

        public AwsConfig() {
            log.info("aws sessions config using ElasticCache");
        }

        @Bean
        public JedisConnectionFactory connectionFactory() {
            return new JedisConnectionFactory();
        }

    }

}

```

**Comment by rwinch** [comment]
Closing...With the pull request merged. I think this is resolved.
