### ISSUE TITLE
Session persistance optimization (Hazelcast as storage)

### ISSUE THREAD

**Issue by stojsavljevic** [spring-projects/spring-session#516]
Hi,

I'm using version 1.1.1.RELEASE of Spring Session and Hazelcast 3.6.2 as session storage (_MapSessionRepository_).
I would like to have session persistence highly optimized.

So, it would be great if a session gets persisted only if it has been changed.
Currently, session is always committed.
In my mind, session implementation would have to keep track if something has been changed.

Further, it would be great to have configuration option to choose if we want a repo to be updated immediately upon change (after _session.setAttribute()_ for example) or once per request.
This way we will be able to fine tune performance depending on application's needs.
Also, with immediate write we can avoid some potential concurrent issues.

Hazelcast's _SpringAwareWebFilter_ has both features. Later one is called deferred-write - http://docs.hazelcast.org/docs/3.6.1/manual/html-single/index.html#caching-locally-with-deferred-write-

What do you think about this?
Do you maybe have plans for that?

I would like to have these features in Spring Session because it is a great project!
Thanks for the great work!

**Comment by rwinch** [comment]
@stojsavljevic We'd love to get a pull request for such enhancements. Is this something you would be interested in doing?

**Comment by vpavic** [comment]
:+1:

Similar optimizations for Hazelcast support came across my mind too, especially considering that session implementations for other stores keep track of the changes to optimize their write operations.

If @stojsavljevic can't I'd consider fitting this into my schedule.

**Comment by stojsavljevic** [comment]
Hi guys,

I got green light from my boss to start working on this.

I will contact @vpavic for the way forward.

Thanks!
