### ISSUE TITLE
Session attributes not saved on the Websocket handshake 

### ISSUE THREAD

**Issue by BogdanEM** [spring-projects/spring-session#523]
I have an application using websockets (with my own `TextWebSocketHandler`, without STOMP) and I want to add distributed sessions with Hazelcast. 

I have defined a `HazelcastHttpSessionConfiguration` instance and configured a hazelcast instance and it seems to be working. Except for one thing....

I have a custom `HandshakeInterceptor` that I'm using to store certain stuff in the associated HTTP session (with `setAttribute`). These attributes get lost. I add them during the handshake and later when I try to read them they are null. If I add attributes on MVC controllers I can retrieve them later with no issue, but those I set in the Websocket handshake are lost. 

I'm using Spring Session 1.2.0.RELEASE with hazelcast 3.6.2

I know Spring Session has it's own `SessionRepositoryMessageInterceptor` interceptor, which I'm not using, but looking at its source code it doesn't seem to be doing anything special to persist attributes (except on `preSend`).

I have the most basic of configurations so I'm guessing that's OK.

    <bean id="hazelcastHttpSessionConfiguration" class="org.springframework.session.hazelcast.config.annotation.web.http.HazelcastHttpSessionConfiguration">
        <property name="maxInactiveIntervalInSeconds" value="60" />
        <property name="sessionMapName" value="hazelcastUserSessions" /> 
    </bean>

    ...

    @Component
    public class HazelcastInstanceConfigurer {
        @Bean(name = "hazelcastInstance", destroyMethod = "shutdown")
        public HazelcastInstance embeddedHazelcast() {
            Config hazelcastConfig = new Config();
            return Hazelcast.newHazelcastInstance(hazelcastConfig);
        }
    }

    .....

    <filter>
        <filter-name>springSessionRepositoryFilter</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>

Am I missing something?

**Comment by rwinch** [comment]
Thank you for your feedback!

At the time this was initially implemented there wasn't a hook to override the way session information was retrieved. All the integration is doing is keeping the session alive when messages are received.

There is an issue to store the session with Spring Session #207 

I'm going to close this as a duplicate since this is being tracked by another issue.
