### ISSUE TITLE
Any plans of supporting Hazelcast Replicated Maps?

### ISSUE THREAD

**Issue by BogdanEM** [spring-projects/spring-session#524]
Hazelcast adds a new type of map (in beta), the [`ReplicatedMap`](http://docs.hazelcast.org/docs/3.5/manual/html/replicatedmap.html).

Any plans of supporting this in the near future? The `HazelcastHttpSessionConfiguration` is using `IMap` right now so no way to use Spring Session with the new hazlecast features.

**Comment by shakuzen** [comment]
@BogdanEM Is there any issue that you ran into with the current Spring Session Hazelcast implementation that made you want to use `ReplicatedMap` instead?

For everyone's benefit looking at this issue, here is some relevant information from the Hazelcast documentation:

> A replicated map is a weakly consistent, distributed key-value data structure provided by Hazelcast.

> Weak consistency compared to eventually consistency means that replication is done on a best efforts basis. Lost or missing updates are neither tracked nor resent. This kind of data structure is suitable for immutable objects, catalogue data, or idempotent calculable data (like HTML pages).

I'm not sure I personally see a compelling reason to support `ReplicatedMap` at this point, especially given that session data seems like it should be strongly consistent.
@rwinch WDYT?

**Comment by BogdanEM** [comment]
@shakuzen Although consistency is not enforced for the replicated map, it can still be useful in certain cases, say very small session information with faster reads and writes (since the data is on the local node no matter the node). it's more of a curiosity mostly :)

**Comment by rwinch** [comment]
I tend to agree with @shakuzen.

`ReplicatedMap` doesn't appear well suited for Spring Session. The problem would be if a user authenticates on one node and then is sent to a new node, the session would not be present. This might work for applications that use sticky sessions. However, it is likely it would still cause problems on node failure.

If anyone wants to try `ReplicatedMap`, you can aways use an instance of `MapSessionRepository`. For example, you can leverage [@EnableSpringHttpSession](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-enablespringhttpsession)

```java
@EnableSpringHttpSession
@Configuration
public class SpringHttpSessionConfig {
        @Bean
        public MapSessionRepository sessionRepository() {
                Map<String,ExpringSession> sessions = createReplicatedMap();
                return new MapSessionRepository(sessions);
        }
}
```

Of course you would need to be sure you create / destroy the `ReplicatedMap` properly, but this should be pretty minimal effort.

**Comment by rwinch** [comment]
I'm going to close this issue as it doesn't seem to fit well with sessions. If someone, has additional evidence that this is a good idea I would be willing to reconsider (please log a new ticket referencing this issue).
