### ISSUE TITLE
MongoOperationsSessionRepository should only save if something has changed

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#526]
We should improve MongoOperationsSessionRepository to only perform a save if something has changed. This will improve performance when multiple saves are invoked per request (i.e. once on response committed and once on the SessionRepositoryFilter completion).

**Comment by rwinch** [comment]
@jkubrynski Quite often actually. The session is written once when the response is committed and once when the Filter is done executing. See #508

**Comment by jkubrynski** [comment]
OK, but it looks it's something that should be handled generically for all repositories. It will probably also affect Jdbc.

**Comment by rwinch** [comment]
@jkubrynski We cannot generically handle it as it is implementation specific. For example Redis tracks each individual attribute because the data store supports it.

> It will probably also affect Jdbc.

Thanks. JDBC already handles this. See 
* https://github.com/spring-projects/spring-session/blob/1.2.0.RELEASE/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L314 
* https://github.com/spring-projects/spring-session/blob/1.2.0.RELEASE/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L330

**Comment by vpavic** [comment]
Closing due to Mongo support being deprecated in `1.4.x` and removed in `2.0.x`.
See #768 for more background.

**Comment by rwinch** [comment]
The new repo is at https://github.com/spring-projects/spring-session-data-mongodb
