### ISSUE TITLE
Add support for Hazelcast SessionRepository

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-session#53]
Adding Hazelcast to the list of session repository providers would be a great addition. This would be similar in style and implementation to `RedisOperationsSessionRepository` but implemented using http://docs.hazelcast.org/docs/3.0/manual/html/ch02.html#Map instead. The implementation should be pretty straightforward but please let me know if you need assistance.

**Comment by rwinch** [comment]
There is a Hazelcast sample application that demonstrates this works now. See http://docs.spring.io/spring-session/docs/current/reference/html5/#api-mapsessionrepository-hazelcast
