### ISSUE TITLE
Sugested Imporvement make the Session Repositories Beans

### ISSUE THREAD

**Issue by virtualdogbert** [spring-projects/spring-session#530]
I'm using version 1.2.0 Release in a Grails 3 app and it would be nice if the session repository was a spring bean, so that I could inject it into an admin service, and manage/kill(properly) a given session.

The repositories I'm talking about are:
AbstractGemFireOperationsSessionRepository, GemFireOperationsSessionRepository, JdbcOperationsSessionRepository, MapSessionRepository, MongoOperationsSessionRepository, RedisOperationsSessionRepository

**Comment by rwinch** [comment]
@virtualdogbert The SessionRepository should be exposed as a Bean. For example, see https://github.com/spring-projects/spring-session/blob/1.2.0.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java#L114

**Comment by virtualdogbert** [comment]
Yeah... that might help. I'm using the JdbcOperationsSessionRepository, which doesn't have the bean annotations. I don't know about the other implementations though. Thanks.

**Comment by rwinch** [comment]
@virtualdogbert JdbcOperationsSessionRepository is exposed as a bean if you use the provided configuration support. See https://github.com/spring-projects/spring-session/blob/1.2.0.RELEASE/spring-session/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L74-L75

I'm going to close this. Please reopen if you can provide details of how to reproduce the problem
