### ISSUE TITLE
AbstractGemFireOperationsSessionRepository class contains an error writing 

### ISSUE THREAD

**Issue by zhangmeng0426** [spring-projects/spring-session#538]
when I use glassfish2.1 webcontainer , I find a error for SimpleDateformat YYYY.
The SimpleDateformat  required date format 'y' ,but in AbstractGemFireOperationsSessionRepository.java use 'Y', some webContainers not support.

such as:  line 351
 protected static final DateFormat TO_STRING_DATE_FORMAT = new SimpleDateFormat(
                "YYYY-MM-dd-HH-mm-ss");

**Comment by rwinch** [comment]
Thanks for the report. Can you provide a complete stacktrace please?

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
