### ISSUE TITLE
Add support for JDBC SessionRepository

### ISSUE THREAD

**Issue by btiernay** [spring-projects/spring-session#54]
This could work very similar to how Spring Security OAuth support currently works. Please see `JdbcClientTokenServices`, `JdbcClientDetailsService`, `JdbcTokenStore`, et. al.

**Comment by brentonr** [comment]
+1. We implemented something similar to this by wrapping Tomcat's JDBCStore and using it as a fallback when Redis was unavailable (something that's necessary in AWS with Multi-AZ read replica failovers taking a few minutes to come back online, or to handle temporary hiccups).

**Comment by chenjianjx** [comment]
+1.  Relation database may not be performing as well as No-SQL databases in this case, but a lot of low-concurrency applications don't need to worry about performance problem. And as a lightweight application, it doesn't want to set up another database i.e. Redis than MySQL it already has.

**Comment by rwinch** [comment]
Closing to move this as duplicate of #364 (Sorry I missed this when I crated the new ticket)
