### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by nickus** [spring-projects/spring-session#547]
Having:
        spring.version: 4.2.5.RELEASE
        spring.security.version: 4.0.3.RELEASE
        spring-session.version: 1.2.0.RELEASE

And have two tomcat v8.0.33 in cluster mode + redis (redis_version:3.0.7)
Problem: Sometimes org.springframework.security.web.authentication.session.
SessionFixationProtectionStrategy#applySessionFixation don't change prevois invalidated anonymus sessionId. I.e. after

		session.invalidate();
		session = request.getSession(true); 

we have old session.

Help me please! Thanks!

**Comment by nickus** [comment]
Temporary solved problem by setting flush mode to IMMEDIATE

<beans:bean         class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration">
        <beans:property name="maxInactiveIntervalInSeconds" value="..."/>
        <beans:property name="redisFlushMode" value="IMMEDIATE"/>
    </beans:bean>

**Comment by rwinch** [comment]
@nickus Can you provide more details on how to reproduce this? Are you making lots of requests under a high load? What sort of requests are you making at the same time? Perhaps even a sample application?

**Comment by rwinch** [comment]
Closing due to lack of feedback and unable to reproduce

**Comment by hhfdna** [comment]
I encountered the same problem, also solved by changing flush mode to immediately. I am using spring session 1.3.3 with spring 4.2.1. I think this might be a bug. I am waiting for official answer still

**Comment by hhfdna** [comment]
https://github.com/spring-projects/spring-session/issues/1540
