### ISSUE TITLE
MultiHttpSessionStrategyAdapter does not call delegate.wrapRequest and delegate.wrapResponse

### ISSUE THREAD

**Issue by ssi-paulsideleau** [spring-projects/spring-session#550]
Using Spring 1.2.0.RELEASE. 

It looks like MultiHttpSessionStrategyAdapter  in SessionRepoistory filter does not call delegate.wrapRequest and delegate.wrapResponse in public HttpServletRequest wrapRequest and public  HttpServletResponse wrapResponse, respectively. 

This causes any code that is doing custom logic to not get called, such as using this work around to support URL encoding. https://github.com/spring-projects/spring-session/issues/265.

In order for this to work correctly you have to make sure the correct overloaded method setHttpSessionStrategy  is called so that  MultiHttpSessionStrategyAdapter is not used.

**Comment by rwinch** [comment]
Thanks for the report. This is as expected. You need to inject it on the proper method.
