### ISSUE TITLE
Spring Session \w JDBC throws exception:  No converter found capable of converting from type [java.lang.Object] to type [byte[]]

### ISSUE THREAD

**Issue by vraptorche** [spring-projects/spring-session#556]
I'm using Spring Session version 1.2.0.RELEASE with JDBC support, but it throws conversion exception when tries to serialize session data:  org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Object] to type [byte[]]

**Comment by rwinch** [comment]
@vraptorche Sounds like you probably need to make the object that is being placed into session implement Serializable or provide a custom strategy for serializing your object.

**Comment by vraptorche** [comment]
I see that it is trying to serialize CSRF token and this is String -
otherwise - yes it should be serializable

Best

~E



Dipl. Eng. Emil Korladinov M.Sc. EE
JurassicWare Ltd

http://www.automobilnik.com

**Comment by vraptorche** [comment]
Nevertheless I found this code:

private void serialize(PreparedStatement ps, int paramIndex, Object
attributeValue)
      throws SQLException {
   this.lobHandler.getLobCreator().setBlobAsBytes(ps, paramIndex,
         (byte[]) this.conversionService.convert(attributeValue,
               TypeDescriptor.valueOf(Object.class),
               TypeDescriptor.valueOf(byte[].class)));
}


But the conversion service does not have such converter by default


Best


~E




Dipl. Eng. Emil Korladinov M.Sc. EE
JurassicWare Ltd

http://www.automobilnik.com

**Comment by rwinch** [comment]
Thanks! I will give this a look as soon as you provide a way to reproduce the issue.

**Comment by miguelsauza** [comment]
Error stack details:

`2016-11-14 18:10:20 - Initiating transaction rollback on application exception
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Object] to type [byte[]]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.serialize(JdbcOperationsSessionRepository.java:522)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.access$200(JdbcOperationsSessionRepository.java:130)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$1$2.setValues(JdbcOperationsSessionRepository.java:300)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:960)
	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:950)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$1.doInTransactionWithoutResult(JdbcOperationsSessionRepository.java:292)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:274)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:130)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:244)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:214)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)`

**Comment by sayan-chaliha** [comment]
I'm getting the exact same exception when trying to use Spring Session 1.3.0.RELEASE with Spring Security 4.2.x.

I tried to dig a little further and figure out what was causing the conversion failure -- it was really unclear from the logs and the stack trace. I added my own Object to byte[] converter and what it yielded was surprising: SPRING_SECURITY_CONTEXT was the session attribute that failed to serialise. Now, I'm using an absolutely standard security context with org.springframework.security.core.userdetails.User object (not overriden in anyway). All the objects within SecurityContextImpl implements Serializable. How is this failing then? Stack:

[tomcat:launch] DEBUG [http-nio-9443-exec-10] 2017-04-26 15:35:01.383 TransactionTemplate:162 - Initiating transaction rollback on application exception
[tomcat:launch] org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Object] to type [byte[]]
[tomcat:launch] 	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:313)
[tomcat:launch] 	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.serialize(JdbcOperationsSessionRepository.java:627)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.access$400(JdbcOperationsSessionRepository.java:129)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$1$2.setValues(JdbcOperationsSessionRepository.java:403)
[tomcat:launch] 	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:960)
[tomcat:launch] 	at org.springframework.jdbc.core.JdbcTemplate$4.doInPreparedStatement(JdbcTemplate.java:950)
[tomcat:launch] 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
[tomcat:launch] 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
[tomcat:launch] 	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$1.doInTransactionWithoutResult(JdbcOperationsSessionRepository.java:395)
[tomcat:launch] 	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
[tomcat:launch] 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:377)
[tomcat:launch] 	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:129)
[tomcat:launch] 	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:245)
[tomcat:launch] 	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:217)
[tomcat:launch] 	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:170)
[tomcat:launch] 	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
[tomcat:launch] 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
[tomcat:launch] 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[tomcat:launch] 	at com.amazon.build.brazil.filters.HttpsFilter.doFilter(HttpsFilter.java:173)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[tomcat:launch] 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
[tomcat:launch] 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[tomcat:launch] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[tomcat:launch] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
[tomcat:launch] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
[tomcat:launch] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
[tomcat:launch] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
[tomcat:launch] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
[tomcat:launch] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
[tomcat:launch] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
[tomcat:launch] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1114)
[tomcat:launch] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
[tomcat:launch] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
[tomcat:launch] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
[tomcat:launch] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[tomcat:launch] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[tomcat:launch] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[tomcat:launch] 	at java.lang.Thread.run(Thread.java:745)

**Comment by vpavic** [comment]
As we were unable to reproduce this problem so far, please consider putting together a minimal sample app.

**Comment by sayan-chaliha** [comment]
So, it looks like an integration issue. I went through the session code and I realised that a bean named "conversionService" was defined implicitly someplace else. So I defined a new bean named "springSessionConversionService" and just added the two filters from the generic conversion service in the code, and it worked.

Thanks,
Sayan.

**Comment by vpavic** [comment]
Thank you @sayan-chaliha, with the information you provided I was able to reproduce the problem using a simple Spring Boot app:

```gradle
dependencies {
	compile 'org.springframework.boot:spring-boot-starter-web'
	compile 'org.springframework.boot:spring-boot-starter-security'
	compile 'org.springframework.session:spring-session-jdbc'
	compile 'com.h2database:h2'
}
```

```java
@SpringBootApplication
@RestController
public class SessionJdbcSampleApp {

	public static void main(String[] args) {
		SpringApplication.run(SessionJdbcSampleApp.class, args);
	}

	@GetMapping(path = "/")
	public String home(HttpSession session) {
		return session.getId();
	}

	@Configuration
	@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
	static class SecurityConfig extends WebSecurityConfigurerAdapter {
	}

	@Bean
	public ConversionService conversionService() {
		return new DefaultConversionService();
	}

}
```

```properties
spring.session.store-type=jdbc
```

By default, `JdbcOperationsSessionRepository` takes care of setting up required (de)serialization facilities in `JdbcOperationsSessionRepository#createDefaultConversionService` while also providing an option to use a custom `ConversionService`.

However, JDBC configuration support (i.e. `JdbcHttpSessionConfiguration`) will try to pick up the `ConversionService` `@Bean` named `conversionService` if it's available in the application context and configure the `JdbcOperationsSessionRepository` to use if. If this `ConversionService` instance doesn't have the [required converters](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L598-L603) registered you'll face the error reported here, as demonstrated by the sample above.

The solution is either to configure the required converters with default `ConversionService` or, as in @sayan-chaliha's case, provide the Spring Session specific `ConversionService` `@Bean` named `springSessionConversionService` with the required converters. These customization options for `ConversionService` are described in the [reference manual](http://docs.spring.io/spring-session/docs/current/reference/html5/#custom-conversionservice).

With this, I'm closing the issue as answered.
