### ISSUE TITLE
MongoExpiringSession auto recreate

### ISSUE THREAD

**Issue by zjdyxxktc0721** [spring-projects/spring-session#559]
I found it was very strange the session document stored in Mongo database will delete and then auto recreate a new document when i use SessionRepository.delete(String id), and all the attributes in the previous session were cleared.

**Comment by rwinch** [comment]
cc @jkubrynski

**Comment by jkubrynski** [comment]
@zjdyxxktc0721 Could you please tell how can I reproduce this issue? We have integration tests which are calling repository.delete(id) and after this call there is no session in repository
