### ISSUE TITLE
spring-security and spring-session seem to be incompatible 'out of the box'

### ISSUE THREAD

**Issue by danwashusen** [spring-projects/spring-session#567]
spring.version=4.2.6.RELEASE
spring-security.version=4.1.0.RELEASE
spring-session.version=1.2.0.RELEASE

It looks like the spring-security classes o.s.security.web.authentication.session.AbstractSessionFixationProtectionStrategy and o.s.security.web.authentication.session.ChangeSessionIdAuthenticationStrategy are incompatible with spring-session unless org.springframework.web.util.HttpSessionMutexListener is configured.

Code in AbstractSessionFixationProtectionStrategy#onAuthentication uses `WebUtils.getSessionMutex(session)` to get the mutex lock object, without HttpSessionMutexListener configured the session instance is used. However spring-session seems to be using a different instance of SessionRepositoryFilter$SessionRepositoryRequestWrapper$HttpSessionWrapper for each request.

**Comment by rwinch** [comment]
Thanks for the report. What problem is this causing you?

NOTE: Spring Session must have a new instance of the session. This is because we do not want to keep the session on the heap as this is one of the main points of Spring Session.

**Comment by danwashusen** [comment]
> What problem is this causing you?
We're seeing random (ajax) requests fail in our single page app when two requests happen to execute at the same/similar times. The first request goes through the ChangeSessionIdAuthenticationStrategy class (which expects to have exclusive access to the session) which calls SessionRepository#delete while its creating the replacement session. This in turn causes the second request to fail because the session its been associated with has been deleted. 

The core of the issue seems to be that WebUtils.getSessionMutex(session) doesn't work 'out of the box' with spring-session because the 'session' instance keeps changing from request to request. If you take a look at the synchronized block in AbstractSessionFixationProtectionStrategy#onAuthentication it should hopefully be self explanatory.

Its taken me a few (frustrating) days to track down the cause of the failing requests. In the end I 'solved' the issue by adding `session.setAttribute(WebUtils.SESSION_MUTEX_ATTRIBUTE, new Mutex())` to our (custom) impl. of org.springframework.session.SessionRepository#createSession.

**Comment by danwashusen** [comment]
> This is because we do not want to keep the session on the heap as this is one of the main points of Spring Session

I should also mention that we use an instance of com.google.common.cache.LoadingCache in conjunction with sticky sessions in our SessionRepository impl so the mutex is good while the ExpiringSession instance is in the cache.

**Comment by rwinch** [comment]
@danwashusen Thanks for the details.

> We're seeing random (ajax) requests fail in our single page app when two requests happen to execute at the same/similar times. The first request goes through the ChangeSessionIdAuthenticationStrategy class (which expects to have exclusive access to the session) which calls SessionRepository#delete while its creating the replacement session. This in turn causes the second request to fail because the session its been associated with has been deleted.

How/why does it fail without a session?

Typically the `ChangeSessionIdAuthenticationStrategy` is only going to be invoked at the time of authentication. This means that if a request is made before the authentication is completed, it should not expect to be authenticated (it will have the wrong session id).

So is it failing because it needs authentication information and it isn't present? Are there additional items in the session that are expected?

> Its taken me a few (frustrating) days to track down the cause of the failing requests. In the end I 'solved' the issue by adding session.setAttribute(WebUtils.SESSION_MUTEX_ATTRIBUTE, new Mutex()) to our (custom) impl. of org.springframework.session.SessionRepository#createSession.

Thanks for explaining your work around. I'm interested in how this solved the issue. Each session would be serialized and deserialized creating a new instance of `Mutex` so I'm not sure how this fixed the issue.

**Comment by SlimeQ** [comment]
i've been getting an error very similar to this. after a random number of logouts/logins, my main page will load, then it tries to load a bunch of assets at the same time and some of them fail with a null Authorization, causing chaos and an eventual logout. looking into redis reveals that spring-security is storing the security is storing the security context correctly, but it is null in the session.

- spring-session:1.1.1
- spring-security-oauth2:2.0.9

**Comment by rwinch** [comment]
@SlimeQ See http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/util/HttpSessionMutexListener.html

NOTE This isn't true in a distributed session though

**Comment by danwashusen** [comment]
> How/why does it fail without a session?
@rwinch right you are, an issue with our session repository impl. was causing ChangeSessionIdAuthenticationStrategy to be executed for each request. That definitely exacerbated the issue...

> Each session would be serialized and deserialized creating a new instance of Mutex
We have an in-memory cache in our session repository which combined with sticky sessions ensures that the Mutex is live for at least 10 minutes before its replaced. The instance only changes if the user is inactive for a while (or they switch hosts).

Not really sure what the solution is for the WebUtils.getSessionMutex(session) incompatibility. Maybe log something to indicate that the mutex isn't working..

**Comment by rwinch** [comment]
I don't think there is really anything we can do. How would we know that it works / doesn't work? In most scenarios a distributed lock is not really what you want.

Can you respond to https://github.com/spring-projects/spring-session/issues/567#issuecomment-229665035 Perhaps we need to figure out a better way to resolve the issue rather than having a lock (which is generally bad for performance in a distributed environment)

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please comment back if you can provide more details and we can re-open the issue.
