### ISSUE TITLE
Session not readable with JdkSerializationRedisSerializer

### ISSUE THREAD

**Issue by YLombardi** [spring-projects/spring-session#568]
I have a Spring boot (1.3.5.Release) project that use Spring Security (4.1.0.Release) and Spring Session (1.2.0.Release).
When a user log in the application, the session is stored is Redis.

My issue is that the session is not readable by a human because of the default JdkSerializationRedisSerializer.

[Unreadable session in Redis Desktop Manager](http://img15.hostingpics.net/pics/289387sessionWithDefaultSerializer.png)

If I want a readable session, I need to set defaultRedisSerializer to use GenericJackson2JsonRedisSerializer.

```java
@Bean
    public RedisSerializer springSessionDefaultRedisSerializer() {
        return new GenericJackson2JsonRedisSerializer();
    }
```

[Readable session in Redis Desktop Manager](http://img15.hostingpics.net/pics/640819sessionWithJacksonSerializer.png)

But If I do this, the serializer crash when it try to deserialize the session.

```
java.lang.RuntimeException: org.springframework.data.redis.serializer.SerializationException: Could not read JSON: No suitable constructor found for type [simple type, class org.springframework.security.authentication.UsernamePasswordAuthenticationToken]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?) at [Source: [B@4355ea77; line: 1, column: 184] (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.springframework.security.authentication.UsernamePasswordAuthenticationToken]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?) at [Source: [B@4355ea77; line: 1, column: 184] (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"])
```

What can I do to have a readable session without crash ?

Here is my project : https://github.com/YLombardi/Redis-session-issue
I use the class RedisConfiguration to test the serializer.
I run the project with IntelliJ and Wildfly-10.

**Comment by rwinch** [comment]
You need to register custom MixIn's to support serializing non default constructors. See https://github.com/spring-projects/spring-security/pull/3812/files for some help.

Eventually this will get merged and we will provide first class support

**Comment by rwinch** [comment]
Closing this question as I believe it is answered. If you have additional questions or feel it is not answered, please re-open

**Comment by rwinch** [comment]
@YLombardi Yes. See the [javadoc](https://github.com/spring-projects/spring-security/pull/3812/files#diff-fe0eb617ba8337629f80ca6616f05612R35) in the Pull Request on how to add it to the `ObjectMapper`. Then you can inject the ObjectMapper into `GenericJackson2JsonRedisSerializer`. For example:

```java
@Bean
public RedisSerializer springSessionDefaultRedisSerializer() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.addMixIn(Collections.unmodifiableSet(Collections.EMPTY_SET).getClass(), UnmodifiableSetMixin.class);
    mapper.addMixIn(SimpleGrantedAuthority.class, SimpleGrantedAuthorityMixin.class);
    mapper.addMixIn(User.class, UserMixin.class);
    mapper.addMixIn(UsernamePasswordAuthenticationToken.class, UsernamePasswordAuthenticationTokenMixin.class);
    // .. other mixins ...
    return new GenericJackson2JsonRedisSerializer(mapper);
}
```
