### ISSUE TITLE
spring-session-jdbc-1.2.1.RELEASE.jar contains just MANIFEST

### ISSUE THREAD

**Issue by mgarmash** [spring-projects/spring-session#569]
Here is proof link:

http://central.maven.org/maven2/org/springframework/session/spring-session-jdbc/1.2.1.RELEASE/

The jar contains just a MANIFEST.

And `@EnableJdbcHttpSession` is not resolved after adding dependencies mentioned in documentation.

**Comment by rwinch** [comment]
@mgarmash It seems the problem is that this should not even be a jar. It is just a pom file that brings in optional dependencies to support jdbc. All the code is in spring-session jar itself.

**Comment by vpavic** [comment]
@mgarmash As @rwinch explains there's no code in ```spring-session-jdbc``` artifact itself (the same is with ```spring-session-data-redis```, ```spring-session-data-gemfire``` and ```spring-session-data-mongo```). The ```spring-session``` artifact which holds the code should be pulled in transitively.

You can refer to ```basic-jdbc``` module from [this repo](https://github.com/vpavic-demos/javacro16-spring-session) as a sample that uses ```spring-session-jdbc``` dependency.

**Comment by mgarmash** [comment]
Thanks for such quick reply!

I understood my mistake, but problem still exists. Here is details:

Here is my dependency:
 
```
compile("org.springframework.session:spring-session-jdbc:1.2.1.RELEASE")
```

It brings 1 transitive dep:

<img width="518" alt="2016-07-07 23 08 58" src="https://cloud.githubusercontent.com/assets/453401/16664024/38d013f8-44a0-11e6-912e-3215662f4acd.png">

But it looks strange (no jdbc package) according to this:

<img width="685" alt="2016-07-07 23 10 37" src="https://cloud.githubusercontent.com/assets/453401/16664093/7bb76b1c-44a0-11e6-8a88-5c83fb4f122e.png">

**Comment by rwinch** [comment]
Please update your spring-session version to be 1.2.1.RELEASE too

**Comment by mgarmash** [comment]
Oh, something went wrong with dependency resolution in my Gradle. After explicit adding spring-session 1.2.1.RELEASE  dependency the issue resolved. It's strange that pom has correct version of dependency and Gradle just after cleaning it's caches didn't resolve it correctly.

Thanks, guys!

**Comment by rwinch** [comment]
@mgarmash Glad you got it sorted out!
