### ISSUE TITLE
spring session redis consume cpu 100%

### ISSUE THREAD

**Issue by cc4dogman** [spring-projects/spring-session#574]
My Code Env is
Spring-session：1.2.0
Spring：4.2.5
spring-data-redis：1.7.1
redis server:3.2.1

my project used env to production,then watched redis-cli --stat 

100000 request per seconds ,cpu used 100%, monitor command show sadd used many times,

I try to used 
./redis-benchmark -h 127.0.0.1 -p 6392 -t SADD -n 100000 -q -l 
to test my redis server,then cpu up to 100%

why every time session save need sadd op??

![Uploading QQ图片20160722202719.jpg…]()

**Comment by rwinch** [comment]
I'm unable to reproduce the 100% CPU usage problem. Can you provide more details?

You can find storage details at http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-storage

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
