### ISSUE TITLE
Spring Session with JDBC (Postgreql 9.5) - SPRING_SESSION_ATTRIBUTES_PK  duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by loskultos** [spring-projects/spring-session#575]
I hava a setup of 2 spring-boot web applications that share a session via spring-session with JDBC backed by a Postgres 9.5 database.

From time to  time saving attributes in the session leads to a uniqe constraint violation of the spring_session_attributes_pk (columns session_id and attibute_name).

For me this seems to be a race condition between the two applications. Is this a bug or do i need a datasource with isolation level SERIALIZABLE or is there another advice ?

spring-session version: 1.2.0

**Comment by vpavic** [comment]
Generally speaking, having multiple different apps share the same underlying session store without configuring a namespace for each app is not recommended. Namespace feature was introduced exactly to address this and make possible for users to have multiple apps the same session store.

For more background on that matter, see #165 and this [SO answer](http://stackoverflow.com/a/31924352/3944191).

With JDBC backed session introducing namespace means using a different table for each app. You can easily configure this using ```@EnableJdbcHttpSession```'s ```tableName``` attribute.

Regarding race condition situation, are your apps under a high load with big number of concurrent requests?

JDBC backed session store certainly isn't the most performant option, compared to NoSQL stores such as Redis, and while many efforts have been made to reduce the possibility of race condition situations (see #495) it's still possible to encounter such situation under high load. Your use case (no namespaces) certainly increases the possibility.

**Comment by loskultos** [comment]
sorry, i think my description was misleading. 
I have running two instances of the same app on two servers and use spring session, so it shouldn't matter from which of the two instances a request from a logged in (authenticated user with session)  user is handled. 

For example:
-  Login/Authentication and session creation (let's say session id 4711)  is executed by Instance 1
- The following request 2 in session 4711 is handled by instance 2. Via Spring-Session instance 2 gets the session information out of the database
- Request 3 then could again be handled by instance 1 and so on

So it's not a namespace issue - i want to use the same session in different runtime instances of the same application (without the "hassle" of sticky sessions e.g. routed by a reverse proxy and also enabling continous deployment without affecting logged in users).

Is this a valid scenario with spring-session?

Regarding the load - at the moment i have no high load on the system. but when load increases i tend to switch to redis.

**Comment by vpavic** [comment]
OK, it's the same app, I misunderstood you - sorry for the confusion. In that case disregard the namespace part of my previous comment.

Your use case is perfectly valid and is exactly one of the challenges Spring Session aims to help you address.

Can you please share the sample that reproduces the issue and provide more details about the concrete flow that leads to the constraint violation? The error suggests that concurrent requests are trying to add the same attribute to the session.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.

**Comment by billbarni** [comment]
I have the same issue.

https://github.com/billbarni/camunda-redis-memcache

1 - build the project "greenfield-camunda-springjdbcsession" using maven
2 - docker-compose up

nginx will create a load balancer for 2 spring boots at localhost/

if I try to access it, Spring Sessions JDBC will throw errors at me, as if there is some cuncurrency issue between the 2 "camunda_bpm_X" instances.
