### ISSUE TITLE
Session attribute name in spring-session-jdbc with MySQL is always written to MySQL in lowercase.

### ISSUE THREAD

**Issue by shogo-osawa** [spring-projects/spring-session#591]
I'm using spring-session-jdbc 1.2.1.RELEASE with MySQL. When I tried to use uppercase characters (like `USER`) as a session attribute name, it seems written in lowercase in MySQL (e.g. `user`). After that, if I try to retrieve the session attribute with the name in uppercase, the session object returns null. This does not happens if I use only lowercase characters for a session attribute name.

Is this a bug or an intended behavior?

**Comment by vpavic** [comment]
I was unable to reproduce your problem.

What exact version of MySQL you're using? Did you use the database schema provided by Spring Session or did you customize the scripts?

Output of following commands would be useful as well:

```bash
> show full columns from SPRING_SESSION;
> show full columns from SPRING_SESSION_ATTRIBUTES;
> show create table SPRING_SESSION\G
> show create table SPRING_SESSION_ATTRIBUTES\G
```

**Comment by shogo-osawa** [comment]
My MySQL version is `mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3
`. I used the database schema provided by Spring Session.

Output of the commands you listed follows.

I have found that the collation for `ATTRIBUTE_NAME` column is `latin1_swedish_ci` (I did not set it by myself, it is probably a default). Is this the cause?

```
> show full columns from SPRING_SESSION;
+-----------------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| Field                 | Type         | Collation         | Null | Key | Default | Extra | Privileges                      | Comment |
+-----------------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| SESSION_ID            | char(36)     | latin1_swedish_ci | NO   | PRI |         |       | select,insert,update,references |         |
| CREATION_TIME         | bigint(20)   | NULL              | NO   |     | NULL    |       | select,insert,update,references |         |
| LAST_ACCESS_TIME      | bigint(20)   | NULL              | NO   | MUL | NULL    |       | select,insert,update,references |         |
| MAX_INACTIVE_INTERVAL | int(11)      | NULL              | NO   |     | NULL    |       | select,insert,update,references |         |
| PRINCIPAL_NAME        | varchar(100) | latin1_swedish_ci | YES  |     | NULL    |       | select,insert,update,references |         |
+-----------------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+

> show full columns from SPRING_SESSION_ATTRIBUTES;
+-----------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| Field           | Type         | Collation         | Null | Key | Default | Extra | Privileges                      | Comment |
+-----------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| SESSION_ID      | char(36)     | latin1_swedish_ci | NO   | PRI |         |       | select,insert,update,references |         |
| ATTRIBUTE_NAME  | varchar(200) | latin1_swedish_ci | NO   | PRI |         |       | select,insert,update,references |         |
| ATTRIBUTE_BYTES | blob         | NULL              | YES  |     | NULL    |       | select,insert,update,references |         |
+-----------------+--------------+-------------------+------+-----+---------+-------+---------------------------------+---------+

> show create table SPRING_SESSION\G
*************************** 1. row ***************************
       Table: SPRING_SESSION
Create Table: CREATE TABLE `SPRING_SESSION` (
  `SESSION_ID` char(36) NOT NULL DEFAULT '',
  `CREATION_TIME` bigint(20) NOT NULL,
  `LAST_ACCESS_TIME` bigint(20) NOT NULL,
  `MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
  `PRINCIPAL_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`),
  KEY `SPRING_SESSION_IX1` (`LAST_ACCESS_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)

> show create table SPRING_SESSION_ATTRIBUTES\G
*************************** 1. row ***************************
       Table: SPRING_SESSION_ATTRIBUTES
Create Table: CREATE TABLE `SPRING_SESSION_ATTRIBUTES` (
  `SESSION_ID` char(36) NOT NULL DEFAULT '',
  `ATTRIBUTE_NAME` varchar(200) NOT NULL DEFAULT '',
  `ATTRIBUTE_BYTES` blob,
  PRIMARY KEY (`SESSION_ID`,`ATTRIBUTE_NAME`),
  KEY `SPRING_SESSION_ATTRIBUTES_IX1` (`SESSION_ID`),
  CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.00 sec)
```

**Comment by vpavic** [comment]
@shogo-osawa I tried reproducing your problem using MySQL 5.5.50 running in Docker container. Default schema scripts generated tables with the same charset/collation as yours, but my session attribute named TEST was still persisted correctly, in uppercase.

Can you provide the sample that reproduces the problem?

**Comment by shogo-osawa** [comment]
Now I've found how it went wrong.

At first I was using a session attribute name in lowercase `user` and tested some user creation/login behaviors. By doing this the session attirbute named `user` is written to MySQL for a session ID. After that I changed my code to use a different session attribute name like `USER` then the problem happens.

 In case I use a session attribute name in uppercase from the very first, it works fine.

**Comment by shogo-osawa** [comment]
In addition, if I tried to write session attribute with the new name `USER` when the old session attribute name `user` exists, it does not overwrite/create the new session attribute name.

**Comment by vpavic** [comment]
Thanks for the feedback.

This is due to MySQL's default string comparison behavior, from the [reference manual](https://dev.mysql.com/doc/refman/5.5/en/case-sensitivity.html):

> The default character set and collation are latin1 and latin1_swedish_ci, so nonbinary string comparisons are case insensitive by default. This means that if you search with col_name LIKE 'a%', you get all column values that start with A or a. To make this search case sensitive, make sure that one of the operands has a case sensitive or binary collation.

**Comment by shogo-osawa** [comment]
@vpavic Now I know why it does not overwrite/create the new session attribute. But then why doesn't it retrieve the old session attribute named `user` with the name `USER`? I ran the following command in MySQL console:

```
mysql> SELECT SESSION_ID, ATTRIBUTE_NAME FROM cross_antenna.SPRING_SESSION_ATTRIBUTES where ATTRIBUTE_NAME = 'USER';
+--------------------------------------+----------------+
| SESSION_ID                           | ATTRIBUTE_NAME |
+--------------------------------------+----------------+
| aa86c61d-abb2-4ec4-aef9-a0d8ce3b109b | User           |
+--------------------------------------+----------------+
1 row in set (0.00 sec)
```

and I could see its case insensitive behavior. Spring Session does not behaves like this.

**Comment by vpavic** [comment]
@shogo-osawa Take a look [this part](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L346-L369) of `JdbcOperationsSessionRepository#save`.

When attribute change is detected, `JdbcOperationsSessionRepository` will attempt to first execute `UPDATE` statement for the given session attribute. In your case, attribute stored in database is named `test` and you're attempting to save attribute named `TEST`. Due to above described behavior, `WHERE attribute_name = 'TEST'` clause will match the existing record with attribute name `test`, updating its attribute value. This means that `UPDATE` statement returned 1 affected row, so `JdbcOperationsSessionRepository` will interpret this as update of existing attribute, instead of addition of new attribute.

Therefore subsequent `SELECT` of session attributes will still get the `test` attribute name.

**Comment by shogo-osawa** [comment]
@vpavic Well, even if subsequent `SELECT` uses the new attribute name `test`, Spring Session can retrieve the session attribute of the old name `TEST` if the collation is case insensitive and it uses MySQL's case insensitive comparison, doesn't it?

By the way, my observation of MySQL's general_log tells that Spring Session may not use

```
SELECT ... WHERE ATTRIBUTE_NAME = ...
```

to retrieve session attribute, but instead uses a query like

```
SELECT S.SESSION_ID, S.CREATION_TIME, S.LAST_ACCESS_TIME, S.MAX_INACTIVE_INTERVAL, SA.ATTRIBUTE_NAME, SA.ATTRIBUTE_BYTES FROM SPRING_SESSION S LEFT OUTER JOIN SPRING_SESSION_ATTRIBUTES SA ON S.SESSION_ID = SA.SESSION_ID WHERE S.SESSION_ID = ...
```

So chances are, Spring Session uses the SQL's comparison when updating a session attribute, but uses Java's case sensitive comparison when retrieving a session attribute.

In my humble opinion, it should use a query like `SELECT ... WHERE ATTRIBUTE_NAME = ...` to respect collations set for tables.

**Comment by vpavic** [comment]
> Well, even if subsequent SELECT uses the new attribute name test, Spring Session can retrieve the session attribute of the old name TEST if the collation is case insensitive and it uses MySQL's case insensitive comparison, doesn't it?

`JdbcOperationsSessionRepository` does not use `attribute_name` in `WHERE` clause of `SELECT` statement used for retrieval of session from the database as there's no need for that. See [here](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L146-L150).

Sorry, but this is a limitation of MySQL and I don't think `JdbcOperationsSessionRepository` should be changed in any way. There is a way in MySQL to work around this easily, as per already linked [reference manual](https://dev.mysql.com/doc/refman/5.5/en/case-sensitivity.html):

> If you want a column always to be treated in case-sensitive fashion, declare it with a case sensitive or binary collation.

**Comment by shogo-osawa** [comment]
> I don't think JdbcOperationsSessionRepository should be changed in any way.

OK. Anyway my problem has been solved. Thank you for your time.
