### ISSUE TITLE
Consider using embedded Redis for integration tests & samples

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#592]
Similar to #419, we could use an embedded Redis instance for integration tests and samples which would make the build completely independent of external services.

Spring Boot is also likely to get support for embedded Redis in 1.5 (see spring-projects/spring-boot#6497).

WDYT @rwinch?

**Comment by rwinch** [comment]
@vpavic Thanks for the report.

We have had a long history with embedded Reids. I removed int as part of #248

If these issues have since been solved, I think we can consider it. Otherwise, I do not like the idea of adding it back.

**Comment by vpavic** [comment]
@rwinch Thanks for the info - however, it seems this one is based on a different library from the one you've used before, see my [comment on spring-projects/spring-boot#6497](https://github.com/spring-projects/spring-boot/pull/6497#issuecomment-239565729).

It's at least worth looking into it IMO.

**Comment by vpavic** [comment]
This was effectively made obsolete by #795.
