### ISSUE TITLE
Unregistered GemFire Instantiator causes deserialization issues on app restarts.

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#596]
Merge fixes for #594 into master

NOTE: #595 doesn't cleanly merge

**Comment by jxblum** [comment]
This issue has been fixed and the changes for #594 & #595 have been merged into `master` in commits  [acf37fc](https://github.com/spring-projects/spring-session/commit/acf37fc8f4297571bf58227011f82c775cc8da96) & [3ee4c5b](https://github.com/spring-projects/spring-session/commit/3ee4c5b5d0f6deca0f5623dfb69f4e7bb5890fdd).
