### ISSUE TITLE
Allow custom Redis namespace prefix

### ISSUE THREAD

**Issue by driverpt** [spring-projects/spring-session#597]
Allow customization of Default Redis Namespace.

e.g.: `spring:session:` to `foo:bar:`.

Currently `spring:session:` is hardcoded

The scenario is that i currently have multiple services that will consult the Session Data within Redis and i don't want the Namespace to begin with `spring:session:`

Even if i customize it through `@EnableRedisHttpSession(redisNamespace = "foo")` i still get `spring:session:foo` instead of `foo`.

I suggest creating an extra property on the Annotation like `defaultPrefix` to set this value, that defaults to `spring:session:`

**Comment by starflash** [comment]
Strongly Agree.

Now data in redis is set by php, the namespace cannot begin with spring:session.

**Comment by vpavic** [comment]
Closing in favor of PR #919.
