### ISSUE TITLE
Allow custom cron expression for cleanup task

### ISSUE THREAD

**Issue by ajthom90** [spring-projects/spring-session#616]
I have a Spring Boot application using Spring Session 1.2.1.RELEASE.  I have two servers running the application behind a load balancer, and the session information is stored in MySQL databases that use master-master replication.  When the Scheduled task runs to delete sessions (JdbcOperationsSessionRepository.cleanUpExpiredSessions()), it runs on both web servers, which then tries to run on both databases and the replication runs into issues.  

It would be nice to be able to set a system property so the scheduled cleanUpExpiredSessions() method will only run on one database, and MySQL replication will take care of the rest behind the scenes.

**Comment by rwinch** [comment]
Thanks for the report!

I'm not sure it is quite that simple since you need fail-over. What happens when one of the server instances crashes? Nothing is cleaning up expired sessions then.

**Comment by ajthom90** [comment]
Ahh, very good point!  Hadn't thought about what would happen if the server in charge of cleaning up sessions goes down.

**Comment by vpavic** [comment]
@rwinch We could expose the cron expression used by `JdbcOperationsSessionRepository#cleanUpExpiredSessions` as a configurable parameter. Users could then adjust the expression to ensure the executions on multiple nodes do not overlap.

**Comment by ajthom90** [comment]
I created Pull Request #621 with @vpavic's suggestion about exposing the cron expression.  Let me know what you think

(sorry it took me so many commits to get a passing build... apparently I decided to ignore Checkstyle today)

**Comment by vpavic** [comment]
@ajthom90 Having in mind this situation can be viewed as an edge case, perhaps it's not worth the complexity it would add to the configuration support. IMO it falls in the same category as custom SQL queries which will be introduced as a part of #613. Setting custom SQL will require users to manually declare `JdbcOperationsSessionRepository` bean.

That being said, you could easily work around your problem with a custom `JdbcOperationsSessionRepository` like this example:

```java
public class CustomJdbcOperationsSessionRepository
		extends JdbcOperationsSessionRepository {

	public CustomJdbcOperationsSessionRepository(JdbcOperations jdbcOperations,
			PlatformTransactionManager transactionManager) {
		super(jdbcOperations, transactionManager);
	}

	@Override
	@Scheduled(cron = "desired cron expression")
	public void cleanUpExpiredSessions() {
		super.cleanUpExpiredSessions();
	}

}
```

When registering the custom repository, make sure the bean is named `sessionRepository` so it overrides the bean defined in `JdbcHttpSessionConfiguration`. Here's an example of such config:

```java
@EnableJdbcHttpSession
public class HttpSessionConfig {

	@Bean
	public CustomJdbcOperationsSessionRepository sessionRepository(
			@Qualifier("springSessionJdbcOperations") JdbcOperations jdbcOperations,
			PlatformTransactionManager transactionManager) {
		return new CustomJdbcOperationsSessionRepository(
				jdbcOperations, transactionManager);
	}

}
```

**Comment by ajthom90** [comment]
Thanks @rwinch!!  That was much simpler than I proposed :)  Thanks for your help!!!

**Comment by rwinch** [comment]
@ajthom90 Thanks for the report and helping to make Spring Session better :)

**Comment by vpavic** [comment]
@rwinch Great solution to this problem, I like it! :+1:

**Comment by littlehome-eugene** [comment]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method sessionRepository in com.example.AportalApplication required a bean of type 'org.springframework.jdbc.core.JdbcOperations' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.jdbc.core.JdbcOperations' in your configuration.


How to solve this?

**Comment by vpavic** [comment]
@littlehome-eugene Commeting on closed issue isn't the best way to report problem. Please open a new issue and provide as much information (related configurations, versions of Spring Session, Boot, etc. you use) as possible to help us diagnose the problem.
