### ISSUE TITLE
every time change with SESSION 

### ISSUE THREAD

**Issue by liuanxin** [spring-projects/spring-session#623]
project build with spring boot with 1.3.6.R

``` xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.6.RELEASE</version>
    <relativePath/>
</parent>
```

and with

``` xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-redis</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session</artifactId>
</dependency>
```

first request

> request headers : nil
> response headers : `Set-Cookie:SESSION=41de189d-1528-42cd-a355-87c0d3be19d0; Path=/; HttpOnly`

second:

> request headers : `Cookie:SESSION=41de189d-1528-42cd-a355-87c0d3be19d0`
> response headers : `Set-Cookie:SESSION=546f5bed-09aa-4672-8af6-4089d07f4863; Path=/; HttpOnly`

**The result is that every new request overwrites the cookie requested the previous time**

With the simplest configuration, noting to change, It's ok, not this problem. I can't determine is not the other jar package causes the response conflict.

or config the `spring.session.domain: http://127.0.0.1:8080/` in the application.yml, but not same config in [SessionProperties](https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/SessionProperties.java)

comment `spring-session` package, use the tomcat native session, not this problem too.

have a good day, thanks!

**Comment by liuanxin** [comment]
New version does not have this problem in my project, default version is 1.0.2.R in spring boot 1.3.6.R

```xml
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session</artifactId>
    <version>1.2.2.RELEASE</version>
</dependency>
```

**Comment by ncastrocosta** [comment]
I have this same "problem". Apparently, this is okay, because the filter SessionManagementFilter applies a strategy called ChangeSessionIdAuthenticationStrategy. This would prevent session fixation attack.

And, according to what I've been reading, the replaced Session ID will not be deleted from Redis. It will be marked to expire in the next minute. 

I think is that.

Thanks!

**Comment by eleftherias** [comment]
@liuanxin I'm going to close this issue given the comment above.
If this is causing a problem for you, please let me know and I will reopen it.
