### ISSUE TITLE
RedisSessionExpirationPolicy Violates ExpiringSession API

### ISSUE THREAD

**Issue by atreides322** [spring-projects/spring-session#628]
I am using Spring Session 1.2.0.RELEASE. According to the Javadocs for `org.springframework.session.ExpiringSession#setMaxInactiveIntervalInSeconds`, "A negative time indicates that the session will never timeout." However, `org.springframework.session.data.redis.RedisSessionExpirationPolicy#onExpirationUpdated` takes this negative value and adds five minutes (300) to it. This causes the TTL for the Redis entry to expire in less than five minutes. If anything, `org.springframework.data.redis.core.RedisOperations#persist` should be called if `maxInactiveIntervalInSeconds < 0`.

**Comment by atreides322** [comment]
Looking at the source code to try to create a bug fix and pull request, it looks like of the other classes implementing `ExpiringSession`, `org.springframework.session.data.mongo.MongoExpiringSession` also suffers from this bug. However, it looks like the fix for it is much more straightforward.

**Comment by vpavic** [comment]
This was resolved as a part of #629.
