### ISSUE TITLE
Making DefaultCookieSerializer extendable

### ISSUE THREAD

**Issue by beku8** [spring-projects/spring-session#631]
I've created `RememberMeServices` implementation by extending the `maxInactiveInterval`, as suggested in https://github.com/spring-projects/spring-security/issues/3147. Only problem was to make set max-age on the session cookie.

So I created a custom `CookieSerializer` copying `DefaultCookieSerializer` and modifying the section of setting max-age on the cookie. It is a lot of boilerplate. If we could make all the properties to be `protected`, and add an extension point like:

```
protected int calculateMaxAge(CookieValue cookieValue) {...}
```

it would be really nice.

**Comment by vpavic** [comment]
`RememberMeServices` implementation backed by Spring Session was added in recently released `1.3.0.RELEASE`. Please refer to the [reference manual on this topic](http://docs.spring.io/spring-session/docs/1.3.0.RELEASE/reference/html5/#spring-security-rememberme) and #667 for more details.

Closing this as obsolete.
