### ISSUE TITLE
save in db: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by liuanxin** [spring-projects/spring-session#637]
Save in Redis, so many `Unexpected end of stream`(sprint boot 1.4.0 + spring session 1.2.1)

T_T

Then try to write into the database(MariaDB).

If database charset was utf8mb4, can't create table.
`Specified key was too long; max key length is 767 bytes` == varchar(255)

Problem was `CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME),` with create table `SPRING_SESSION_ATTRIBUTES`

[session in db](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/resources/org/springframework/session/jdbc/schema-mysql.sql)

If the defalut chatset was utf8: char(1) = 3 bytes, so  (36 + 200) \* 3 = 708,
If was utf8mb4:  chat(1) = 4 bytes,   (36 + 200) \* 4 = 944

Just Explicit declaration: 

``` sql
CREATE TABLE SPRING_SESSION (
    SESSION_ID CHAR(36),
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (SESSION_ID)
) ENGINE=InnoDB;

CREATE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (LAST_ACCESS_TIME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_ID CHAR(36),
    ATTRIBUTE_NAME VARCHAR(200),
    ATTRIBUTE_BYTES BLOB,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME), -- ** this line error **
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID) REFERENCES SPRING_SESSION(SESSION_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=UTF8; -- add this

CREATE INDEX SPRING_SESSION_ATTRIBUTES_IX1 ON SPRING_SESSION_ATTRIBUTES (SESSION_ID);
```

or engine use maria(MariaDB)

**Comment by vpavic** [comment]
@liuanxin You need to customize the schema scripts provided by Spring Session to match your use case/database setup. Due to the sheer amount of configuration settings each RDBMS offers, it's difficult to ensure the provided scripts will work for each setup.

Alternatively, you could take a look if some of the RDBMS settings can help you work around your problem. For example:
https://mariadb.com/kb/en/mariadb/xtradbinnodb-server-system-variables/#innodb_large_prefix
http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

**Comment by liuanxin** [comment]
> it's difficult to ensure the provided scripts will work for each setup.

@vpavic Yeah, Your are right

It now appears that explicitly set the character with table(```DEFAULT CHARSET=UTF8```) is the most easy way to deal with

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
