### ISSUE TITLE
Infinispan integration - design, code and documentation

### ISSUE THREAD

**Issue by slaskawi** [spring-projects/spring-session#639]
Hey!

I'm Sebastian from Infinispan Team and I would like ask you for opinion how to implement Spring Session integration.

Long time ago we implemented [Spring Caching Integration module](https://github.com/infinispan/infinispan/tree/master/spring/spring4) in our codebase. This approach works pretty well since the integration bit it tied with our release process. 

I decided to go this direction further and proposed Spring Session integration (here is the [Pull Request](https://github.com/infinispan/infinispan/pull/4562) and [JIRA](https://issues.jboss.org/browse/ISPN-7009)). 

Again, putting the code in our repository makes a lot of sense since it's tied to our release schedule. But the main problem is documentation - users looking for Spring Session documentation are very unlikely to go to our web page.

Would it be possible to put some documentation on Spring Session guide pointing to our web page and code? Of course I volunteer to implement this...

Thanks
Sebastian

**Comment by vpavic** [comment]
Hey @slaskawi - take a look at #642 as it similar to your request.

**Comment by slaskawi** [comment]
Thanks @vpavic! I'll create PR as soon as https://github.com/infinispan/infinispan/pull/4562 is merged.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
