### ISSUE TITLE
Why there's no Spring Cache backend implementation?

### ISSUE THREAD

**Issue by slaskawi** [spring-projects/spring-session#640]
This is probably a conceptual question - I'm just wondering why there's no Spring Cache backend provider for Spring Session? 

The only missing bit is that [Cache](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/Cache.html) interface doesn't have a `put` method with lifespan. But I assume this could be fixed very easily.

**Comment by rwinch** [comment]
Thanks for the issue. We really haven't investigated it.

What are your thoughts on this @snicoll?

**Comment by vpavic** [comment]
Closing due to reasons explained in #768.
