### ISSUE TITLE
why not support url rewrite

### ISSUE THREAD

**Issue by xiaojiejava** [spring-projects/spring-session#647]
in firefox,jquery uploadify do not  support cookie ,so my  url is 'uploadify;jsessionid='  .

but  spring session do not   support url rewrite. how?

**Comment by xiaojiejava** [comment]
anybody?

**Comment by rwinch** [comment]
I think we need more details to be of any help.

**Comment by xiaojiejava** [comment]
in my project,i replace tomcat sessionManager with Spring Session,In some scenarios,firefox can't carray cookie,so my url is 'http://domain/uploadify;jsessionid=xxxx?',tomcat sessionManager can handle this,but Spring Session can not.

so how can i resolve this problem?thanks

**Comment by vpavic** [comment]
@xiaojiejava It looks like you need to provide custom `HttpSessionStrategy` implementation which is able to resolve the session id from the URL query string parameter.

**Comment by xiaojiejava** [comment]
@vpavic thanks,but Can you tell me how to do it?

**Comment by xiaojiejava** [comment]
i know Spring Session supports CookieStrategy and HeaderStrategy,but it only supports one strategy,if i write one custom HttpSessionStrategy,how do i compatible with all cases?  and also Unless i change source code otherwise  there is no convenient way to add HttpSessionStrategy.

**Comment by xiaojiejava** [comment]
i can use sessionRepository with sessionid to get the session which i think it   not very good.

**Comment by vpavic** [comment]
Your custom `HttpSessionStrategy` implementation could delegate work to `CookieHttpSessionStrategy` instance, with the exception of `HttpSessionStrategy#getRequestedSessionId` where you could check the URL query string parameter if the delegate returned `null`.

**Comment by quzhongqiang** [comment]
好吧

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
