### ISSUE TITLE
request.getInputStream is empty

### ISSUE THREAD

**Issue by zwfflying** [spring-projects/spring-session#649]
I submit a post request.
when i use request.getInputStream to get parameters, but find nothing.
## by watching the source code, i find this line maybe the reason:

CookieHttpSessionStrategy.java line 165 
## String u = request.getParameter(this.sessionParam);

the inputStream has already read;
link:[http://blog.csdn.net/lchpersonal521/article/details/52104959](url)

**Comment by panchenko** [comment]
If your request has `application/x-www-form-urlencoded` content type then request body is parsed during the first call of methods like `getParameter()`. 

It feels a bit unusual if you would like to parse this content type manually, however if you have such an use case - the call above can be disabled by contributing an own `CookieHttpSessionStrategy` bean having `setSessionAliasParamName(null)`.

**Comment by rwinch** [comment]
If you are using multi part requests you need to ensure that you have Spring's [MultipartFilter](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/multipart/support/MultipartFilter.html) placed before Spring Session's filter

**Comment by zwfflying** [comment]
@panchenko 
"the call above can be disabled by contributing an own CookieHttpSessionStrategy bean having setSessionAliasParamName(null)."
if I need to modify the source code “CookieHttpSessionStrategy.java” to setSessionAliasParamName(null)?

**Comment by panchenko** [comment]
@zwfflying I mean your application should provide such a bean, for example like this:

```java
@Bean
public static CookieHttpSessionStrategy httpSessionStrategy() {
    final CookieHttpSessionStrategy strategy = new CookieHttpSessionStrategy();
    strategy.setSessionAliasParamName(null);
    return strategy;
}
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
