### ISSUE TITLE
Spring Security Concurrent Session Integration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#65]
Spring Security allows for ensuring only one user with a given username is authenticated at a time through the [concurrency control](http://docs.spring.io/spring-security/site/docs/current/reference/html/session-mgmt.html#concurrent-sessions). This is nice for something that is a subscription model (i.e. pay per user) to ensure that people are not sharing usernames.

If two sessions exist with the same username, Spring Security will invalidate one of the sessions. Currently it does this by marking a session as invalid and the next time the user visits the page the session is actually invalidated. This is necessary due to Java EE limitations. 

Spring Security should provide an implementation of concurrency control that will use Spring Session's APIs to immediately invalidate a session.

**Comment by yacota** [comment]
Is there any plan to include this issue in a release?
From one of your comments at https://spring.io/blog/2014/11/18/spring-session-1-0-0-rc1-released#comment-1699673845 ... we'll have to wait until 1.1.0 at least.

**Comment by rwinch** [comment]
@yacota Thanks for your interest. At this time there are no concrete plans of when this integration would be made. Of course a good PR with proper testing would almost guarantee inclusion in the next feature release :)

One other question is...does integration between Spring Session & Security belong in Spring Security or in Spring Session? This will be something that we can easily change later, but it is something I may want feedback from @wilkinsona on.

**Comment by yacota** [comment]
Thanks @rwinch for your rapid answer.
I see your point about where does this integration belong to. 
Another point I am afraid of is that implementation details could vary "a lot" depending on which session repository is used (Redis, Hazelcast, ...), maybe a core API interface that deals with main concepts like session invalidation, .... with other jars that really implement it (-redis.jar, -hazelcast.jar) could work.
I think that this is a similar approach took in Spring Social design

Thanks

**Comment by dnang** [comment]
Hello, I am new here. Can anyone explain what this issue about? I was confused when it links to a section in Spring Security official doc that I am reading.

**Comment by rwinch** [comment]
@dnang See if the updated description answers your question.

**Comment by dnang** [comment]
Excellent @rwinch, it's clear now.

**Comment by rwinch** [comment]
@dnang As an FYI this is now supported in the latest snapshot (indirectly) through resolving #4 See the updated documentation http://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/#httpsession-httpsessionlistener

We still plan on adding an improved implementation as described in this issue, but I wanted to communicate that you can somewhat work around the limitation now.

**Comment by mohsen-mahmoudi** [comment]
Hi Mr. @rwinch ..
with your remarks, is this problem (#281) solved? if solved!, what i must do?
is solved in spring security 4.1?

**Comment by dllongo** [comment]
Hi @rwinch , I'm trying to make the spring session/security works with the ```maxSessionsPreventsLogin(true)```, but in my login page, even after call logout url the response in login is:
*Your login attempt was not successful, try again.
Reason: Maximum sessions of 1 for this principal exceeded*
can you help me?

**Comment by rwinch** [comment]
Are you using 1.1.0.M1? Did you follow the instructions in the reference?
http://docs.spring.io/spring-session/docs/1.1.0.M1/reference/html5/#httpsession-httpsessionlistener

**Comment by dllongo** [comment]
I'm was using Snapshot, changing to 1.1.0.M1 the same error occurred, I published the project on github
https://github.com/dllongo/LoginSpring

I would appreciate if you could take a look, Tks!

**Comment by rwinch** [comment]
@dllongo I sent a PR https://github.com/dllongo/LoginSpring/issues/1

**Comment by dllongo** [comment]
@rwinch your PR works, tks!

**Comment by rwinch** [comment]
@dllongo I'm glad that helps!

**Comment by jkubrynski** [comment]
I see few problems here:
1. There is no feature in `SessionRepository` to retrieve all sessions/principals
2. `SessionRegistry` operates a lot on `principal` which is available on `Session` only via attribute.
3. Information like `lastRequest` is available only for `ExpiringSession`

The hardest to do is currently 1 because it needs changes in all repositories.

**Comment by rwinch** [comment]
@jkubrynski Thank you for your analysis. I think we have a couple options here:

- Extract a simplified interface out. Many of the methods on `SessionRegistry` are not actually used by the framework. For this reason, I think we could likely extract a simplified interface from `SessionRegistry`. Then all the locations that use `SessionRegistry` would leverage that.
- We could create a new improved API (i.e. one that doesn't rely on `SessionInformation.expireNow()` with only the methods necessary. We could then provide an adapter to adapt the old API to the new API (and vice versa). We would also deprecate the old API. This option is probably ideal, but a bit more ambitious that the first option. 
- We could provide different implementations of all the logic for session control. This seems like the less attractive option.

**Comment by jkubrynski** [comment]
It looks like first solution is optimal as there is not too much side work to do, and we still get full functionality. As I understand there should be a dedicated ticket for this in SpringSecurity project?

**Comment by rwinch** [comment]
@jkubrynski Thanks! I have yet to create any Spring Security issues for this (I hadn't fully planned everything out yet). You will likely want to create one for any refactoring that needs done.

**Comment by dreis2211** [comment]
+1

**Comment by rwinch** [comment]
Fixed via #473

**Comment by savinov** [comment]
Usefull feature, good job!
