### ISSUE TITLE
Do it support different contextPath?

### ISSUE THREAD

**Issue by letorn** [spring-projects/spring-session#650]
I use it in SpringBoot, and when I set the same server.contextPath, the web session will be same. But I want to use different server.contextPath, do it support ?

**Comment by rwinch** [comment]
Can you clarify what the problem is?

**Comment by letorn** [comment]
appA:
server.port = 8081
server.contextPath = /aaa
appB:
server.port = 8082
server.contextPath = /aaa
appC:
server.port = 8083
server.contextPath = /bbb
appA appB session will be same, but appC is not.

**Comment by letorn** [comment]
I use it in spring-boot by spring-boot-starter-redis,and spring-session-data-redis, setting @EnableRedisHttpSession

**Comment by rwinch** [comment]
Are you working in a browser? If you are, then none of these match the same origin policy, so none of the cookies would be shared. This means that each app would have it's own session.

**Comment by letorn** [comment]
ok, I want to share the session in different webapp, how can I do it?could you give me some suggest?
