### ISSUE TITLE
how can i get the "request" object in the MapSessionRepository

### ISSUE THREAD

**Issue by zwfflying** [spring-projects/spring-session#655]
how can i get the "request" object in the MapSessionRepository ?

**Comment by panchenko** [comment]
@zwfflying It is a little bit not clear what you would like to achieve, this is class is a storage of sessions and has nothing to do with requests.

**Comment by rwinch** [comment]
@zwfflying I agree with @panchenko This ticket is not clear to me. Please provide more details.
