### ISSUE TITLE
Spring session exclude some url which has been authenticated by spring security.

### ISSUE THREAD

**Issue by codergh** [spring-projects/spring-session#658]
Hi,

I noticed that SessionManagementFilter will be filtered after Spring security's authenticated. But for some static content I don't want to do the session filter for it. Is it possible to do this?

**Comment by panchenko** [comment]
In one of the projects I've added it as custom security filter only in the corresponding `<security:http>` configuration:
```xml
<security:custom-filter ref="springSessionRepositoryFilter" before="SECURITY_CONTEXT_FILTER"/>
```
and static content doesn't use security: `<http pattern="/resources/**" security="none"/>`

**Comment by codergh** [comment]
How can I do this configure  in Java, not in xml?

**Comment by codergh** [comment]
I solved the problem by setting the path for Cookie.
`
@Bean
    public CookieSerializer cookieSerializer() {
        DefaultCookieSerializer serializer = new DefaultCookieSerializer();
        serializer.setCookieName("***");
        serializer.setCookiePath("***");
        return serializer;
    }`
