### ISSUE TITLE
How can I add SessionListner in spring session

### ISSUE THREAD

**Issue by zwfflying** [spring-projects/spring-session#659]
How can I add SessionListner in spring session？like SessionCreatedEvent,SessionDestroyedEvent?

**Comment by panchenko** [comment]
Since [spring framework 4.2](https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2) it's possible like this:

```java
@EventListener
public void onCreate(org.springframework.session.events.SessionCreatedEvent event) {
    System.out.println(event);
}

@EventListener
public void onDestroy(org.springframework.session.events.SessionDestroyedEvent event) {
    System.out.println(event);
}
```

The old way would be implementing ApplicationListener.

**Comment by rwinch** [comment]
Thanks @panchenko this is exactly how I would answer it!

@zwfflying I'm closing this as resolved. If you feel it has not been answered, please reopen and expand on your question

**Comment by taozhaolib** [comment]
I have problem in catching the session events:

```java
@Component
public class SessionCreatedListener {
    @EventListener
    public void onCreate(org.springframework.session.events.SessionCreatedEvent event) {
        System.out.println(event);
    }

    @EventListener
    public void onDestroy(org.springframework.session.events.SessionDestroyedEvent event) {
        System.out.println(event);
    }
}
```

The session config class:

```java
@Configuration
@EnableRedisHttpSession
public class SessionConfig  extends AbstractHttpSessionApplicationInitializer {
    
    @Bean
    public HttpSessionStrategy httpSessionStrategy() {
        return new CookieHttpSessionStrategy();
    }
}
```

I use redis based spring session and all others work fine. However, when I sign in and out, no session change events are caught. Am I missing anything there?
