### ISSUE TITLE
Support for using Apache Ignite as replacement for HttpSession in Spring Session

### ISSUE THREAD

**Issue by sri420** [spring-projects/spring-session#660]
Hi,

We are using Apache Ignite as IMDG for our micro services based on Spring Boot. I want to use spring-session backed by Ignite Cache.

Currently, is there support for using Ignite as a replacement store for HttpSession.

If not, when is it planned to be added. 

Thanks,
Sridhar

**Comment by vpavic** [comment]
There are no plans to add first-class support for Apache Ignite backed session repository within Spring Session itself ATM. Also note that any dependencies we do add need to be a part of [Spring IO platform](http://platform.spring.io/platform/).

We do however promote 3rd party Spring Session integrations via [Community Extensions](http://docs.spring.io/spring-session/docs/current/reference/html5/#community-extensions) section of the reference manual.

Of course, there is always an option of implementing `SessionRepository` yourself using the underlying data store of your choice. In such case you can easily reuse existing Spring Session infrastructure by configuring it using something like this:

```java
@EnableSpringHttpSession
class SessionConfig {

    @Bean
    MySessionRepository sessionRepository() {
        return new MySessionRepository();
    }

}
```

Also if Apache Ignite provides an API that extends `java.util.Map` (similar to Hazlecast's `IMap`) you can use [`MapSessionRepository`](http://docs.spring.io/spring-session/docs/1.3.0.RELEASE/reference/html5/#api-mapsessionrepository) provided by Spring Session.

**Comment by 180254** [comment]
Thanks @vpavic for the tips!

https://gist.github.com/180254/0866b155a27add56cd02f65407ee0a1c
Class like that^ seems to be simple solution.

Bean registration:
```java
@Bean
public SessionRepository sessionRepository(Ignite ignite) {
  IgniteCache<String, ExpiringSession> igCache = ignite.cache("someCache");
  IgniteCacheMapView<String, ExpiringSession> igcMapView = new IgniteCacheMapView<>(igCache);
  return new MapSessionRepository(igcMapView);
}
```

**Comment by Raghavender** [comment]
Hi,
I am trying to implement the above logic to use session management with ignite, but it is not working. May I know store-type: value. with JDBC store-type everything is working fine. 

Regards,
Raghavender
