### ISSUE TITLE
Jsr107SessionRepository 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#67]
From Patrick Peralta:

You may want to consider adding a session implementation backed by JSR 107 in a future release. This will allow you to issue an [EntryProcessor](https://github.com/jsr107/jsr107spec/blob/master/src/main/java/javax/cache/processor/EntryProcessor.java) against a [Cache](https://github.com/jsr107/jsr107spec/blob/master/src/main/java/javax/cache/Cache.java). The benefit is that it allows you to send (atomic) modifications to a cache/map entry instead of updating the entire value so that you can target just the attributes that change (similar to what you do with Redis).

**Comment by vpavic** [comment]
Closing due to reasons explained in #768.
