### ISSUE TITLE
FindByIndexNameSessionRepository sublink doesn't work

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-session#670]
I was reading up on fetching a session id via a repository and hit a broken link.

<img width="695" alt="screen shot 2016-11-12 at 9 53 41 am" src="https://cloud.githubusercontent.com/assets/311040/20239096/1b0cc640-a8be-11e6-88b5-864a369f6f53.png">

<img width="1013" alt="screen shot 2016-11-12 at 9 53 46 am" src="https://cloud.githubusercontent.com/assets/311040/20239097/1e6fbca2-a8be-11e6-9551-1c4e868bae5e.png">

**Comment by vpavic** [comment]
Thanks for the report @gregturn, this is now fixed in the `master`.
