### ISSUE TITLE
Convert All Groovy Tests to Java

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#673]
It would be best to switch our tests to Groovy to Java. This would give a better experience in Eclipse since the Groovy Eclipse plugin is not maintained.

**Comment by eddumelendez** [comment]
@sylvermining and me will work on this

**Comment by rwinch** [comment]
Thanks for volunteering! @eddumelendez and @sylvermining

Please ensure that the Geb tests are converted to using WebDriver tests with pages similar to https://github.com/pivotalsoftware/pivotal-cla/tree/master/src/test/java/io/pivotal/cla/webdriver

**Comment by rwinch** [comment]
@eddumelendez Any updates on this? Depending on where you are at I was thinking about doing this (or some of this) myself

**Comment by eddumelendez** [comment]
@rwinch next week I will send the PR

**Comment by vpavic** [comment]
This was fixed in `master` via #697 and in `1.4.x` via #703.
