### ISSUE TITLE
`JdbcOperationsSessionRepository` cleanup fails with big max inactive interval values

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#679]
Specifically, I've encountered this with PostgreSQL if there are sessions with max inactive interval set to at least `Integer.MAX_VALUE / 1000 + 1`:

```stacktrace
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [DELETE FROM SPRING_SESSION WHERE LAST_ACCESS_TIME < ? - MAX_INACTIVE_INTERVAL * 1000]; ERROR: integer out of range; nested exception is org.postgresql.util.PSQLException: ERROR: integer out of range
```

This occurs due to `MAX_INACTIVE_INTERVAL * 1000` part of the SQL statement's `WHERE` clause expression being evaluated as `INT` (since `MAX_INACTIVE_INTERVAL` column is of type `INT`).

Workaround is to configure custom SQL with `CAST` - see [alternative statement](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L101-L102) used for H2 and Derby.

We need to test this scenario with other RDBMS vendors as well.

**Comment by leon** [comment]
I'm getting the same problem with azure sql server

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [DELETE FROM SPRING_SESSION WHERE LAST_ACCESS_TIME < ? - MAX_INACTIVE_INTERVAL * 1000]; Arithmetic overflow error converting expression to data type int.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Arithmetic overflow error converting expression to data type int.
```

**Comment by vpavic** [comment]
Thanks for sharing this info @leon.

**Comment by vpavic** [comment]
I've fixed this by refactoring the problematic SQL statement to avoid the possibility of arithmetic overflow. As a side effect this fix also removed the need for customized statement for H2 and Derby which was introduced while fixing #580.

@leon I'd appreciate it if you could test the latest `1.3.0.BUILD-SNAPSHOT`.

**Comment by leon** [comment]
@vpavic Sorry totally forgot to test this.
It's working with BUILD-SNAPSHOT :)
