### ISSUE TITLE
Spring Boot Autoconfigure Support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#69]

**Comment by wilkinsona** [comment]
Auto-configuration support for Spring Session is now available in Spring Boot 1.3.0 snapshots: https://github.com/spring-projects/spring-boot/commit/fd6d61e8b4901e398717d59cf6a57eb250368862

**Comment by rwinch** [comment]
@wilkinsona Thanks for your work on this!

Per the previous comment closing this issue.
