### ISSUE TITLE
No qualifying bean of type 'org.springframework.session.FindByIndexNameSessionRepository<org.springframework.session.ExpiringSession>'

### ISSUE THREAD

**Issue by sadanyoyo** [spring-projects/spring-session#694]
I have tried with "support for Spring Security’s concurrent session management" example . When i start my project, An exception comes out. 
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.session.FindByIndexNameSessionRepository<org.springframework.session.ExpiringSession>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`
My framework.version is 4.3.4.RELEASE, session.version is 1.3.0.RELEASE, security.version is 4.2.0.RELEASE.
`@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Autowired
	private FindByIndexNameSessionRepository<ExpiringSession> sessionRepository;

	@Override
	protected void configure(HttpSecurity http) throws Exception {

		http.headers().frameOptions().sameOrigin().and().csrf().ignoringAntMatchers("/websockt/**").and()
				.authorizeRequests().antMatchers("/resources/**", "/").permitAll().anyRequest().authenticated().and()
				.formLogin().permitAll().and().logout().permitAll().and().sessionManagement().maximumSessions(2)
				.sessionRegistry(sessionRegistry());
	}

	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication().withUser("admin").password("admin").roles("ADMIN", "USER").and().withUser("user")
				.password("user").roles("USER");
	}

	@Bean
	public SessionRegistry sessionRegistry() {
		return new SpringSessionBackedSessionRegistry(this.sessionRepository);
	}

}

@Configuration
@EnableRedisHttpSession
public class HttpSessionConfig {

	  @Bean
      public HttpSessionEventPublisher httpSessionEventPublisher() {
              return new HttpSessionEventPublisher();
      }
}`

**Comment by sadanyoyo** [comment]
I did some dig. SpringContext do have a bean named "sessionRepository" which defined in class "RedisHttpSessionConfiguration". But it seams FindByIndexNameSessionRepository<ExpiringSession> not "AssignableFrom" RedisOperationsSessionRepository, while FindByIndexNameSessionRepository do "AssignableFrom" RedisOperationsSessionRepository. So I suppose it shuld be FindByIndexNameSessionRepository instead of FindByIndexNameSessionRepository<ExpiringSession>?

**Comment by vpavic** [comment]
Hi @sadanyoyo, you should use `FindByIndexNameSessionRepository<? extends ExpiringSession>`. For example:

```java
@Autowired
FindByIndexNameSessionRepository<? extends ExpiringSession> sessionRepository;
```

You can refer to [Find by Username sample](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/findbyusername.html#finding-sessions-for-a-specific-user) for more detailed `FindByIndexNameSessionRepository` usage example.

**Comment by sadanyoyo** [comment]
Thank you!
