### ISSUE TITLE
Resolve circular dependency between Spring Session and Spring Boot

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session#710]
Remove the circular dependency between _Spring Session_ and _Spring Boot_, when the versions are synced.

_Spring Boot_ has many integration points with _Spring Session_ (e.g. auto-configuration support, starter, etc).  If _Spring Session_ is set to build with _Spring Boot_ `2.0.0`, then _Spring Boot_ `2.0.0.RELEASE` cannot be released unless _Spring Session_ `2.0.0.RELEASE` is released first.  However, since _Spring Session_ is building on and using _Spring Boot_ `2.0.0`, then _Spring Session_ `2.0.0.RELEASE` cannot be released until _Spring Boot_ `2.0.0.RELEASE` is out, and we end up with the [Buttered Cat Paradox](https://en.wikipedia.org/wiki/Buttered_cat_paradox) as both _Spring Boot_ and _Spring Session_ approach GA.

Since the only code dependencies in Spring Session on Spring Boot are in the **samples**, possible solutions to this problem as discussed with @rwinch include...

1. Moving the _Spring Session_ **Samples** to a separate project dependent on _Spring Session_ core and _Spring Boot_.

2. Move the _Spring Session_ **Samples** to the _Spring Boot_ project.

3. Set _Spring Session_ to a release version of _Spring Boot_ (e.g. `1.5.0.RELEASE` in _Spring Session_ `2.0.0`, which is not really the desired solution, but listed here for the sake of completeness).

**Comment by vpavic** [comment]
This is resolved for `2.0.0.M1` by going with option no. 3 at the moment - downgrade to Boot `1.5.3.RELEASE`.

After Boot `2.0.0.M1` is released we'll pick it up for our `2.0.0.M2`.
