### ISSUE TITLE
HeaderHttpSessionStrategy class has headerKey needs getter method.

### ISSUE THREAD

**Issue by ajainy** [spring-projects/spring-session#722]
Ref: https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/web/http/HeaderHttpSessionStrategy.java

One of my use case needed access to headerName field value. 
`private String headerName = "x-auth-token";` being private and not any get method, it's not possible to find value of headerName.  I think, headerName needs to be protected or have getHeaderName() method Or both.

**Comment by rwinch** [comment]
It does not need a getter and we do not wish to provide a getter as this reduces encapsulation. Instead, inject a value and keep a reference to the original value. For example:

```
String headerName = "x-auth-token";
strategy.setHeaderName(headerName);
other.setHeaderName(headerName);
```
