### ISSUE TITLE
Fix compilation error caused by improper use of Assert.notNull(..)

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session#724]
Currently, the _Spring Session_ codebase contains improper uses of the `Assert.notNull(..)` method invocation in [JdbcOperationSessionRepository](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/JdbcOperationsSessionRepository.java#L661) and in [RedisOperationsSessionRepository](https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L697) that are not actually performing the **null** check.

**Comment by vpavic** [comment]
I've backported this to `1.4.x` in #726.

**Comment by jxblum** [comment]
Thank you @vpavic.  I got distracted and forgot to come back to that.

**Comment by vpavic** [comment]
Not a problem at all. :smile:
