### ISSUE TITLE
Add possibility to extend classes

### ISSUE THREAD

**Issue by leofromgroza** [spring-projects/spring-session#725]
I want to ask you to make [org.springframework.session.data.redis.RedisOperationsSessionRepository.RedisSession](https://github.com/spring-projects/spring-session/blob/1.3.0.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L670) extendable (public and non-final separate class). 
Maybe you want to know why we need this. In our API there are some methods that should not prolong our session. So we have some custom logic in current implementation of org.springframework.session.ExpiringSession#setLastAccessedTime. It checks should the session be prolonged or not. But we want to extend RedisOperationsSessionRepository and use it with a little bit modified RedisSession.
We tried to handle our issue by adding logic into places where method org.springframework.session.ExpiringSession#setLastAccessedTime is calling. For now in Spring Web there are 3 such places in two different classes. Such approach is not suitable for us, because in future it could be much more places where that method will be calling and where we should add our custom logic.

**Comment by rwinch** [comment]
Have you tried using  [composition](https://en.wikipedia.org/wiki/Composition_over_inheritance) ?

**Comment by leofromgroza** [comment]
I've tried something like this:
```
package org.springframework.session.data.redis;

import javax.servlet.http.HttpServletRequest;

import org.springframework.data.redis.connection.MessageListener;
import org.springframework.session.ExpiringSession;
import org.springframework.session.SessionRepository;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

@RequiredArgsConstructor
public class MyRedisSessionRepository
        implements SessionRepository<MyRedisSessionRepository.MyRedisSession>, MessageListener {

    @Delegate(excludes = DelegateExclude.class)
    private final RedisOperationsSessionRepository delegate;

    private final SessionRefreshLogic sessionRefreshLogic;

    public static class MyRedisSession implements ExpiringSession {
        @Getter
        @Delegate(excludes = { DelegateExclude.class })
        private final RedisOperationsSessionRepository.RedisSession delegate;
        private final SessionRefreshLogic sessionRefreshLogic;

        public MyRedisSession(RedisOperationsSessionRepository.RedisSession delegate,
                sessionRefreshLogicSessionConfig sessionRefreshLogic) {
            this.delegate = delegate;
            this.sessionRefreshLogic = sessionRefreshLogic;
        }

        public interface DelegateExclude {
            void setLastAccessedTime(long lastAccessedTime);
        }

        @Override
        public void setLastAccessedTime(long lastAccessedTime) {
            if(sessionRefreshLogic.refresh())
				delegate.setLastAccessedTime(lastAccessedTime);
        }
    }

    @Override
    public MyRedisSession createSession() {
        return new MyRedisSession(delegate.createSession(), sessionRefreshLogic);
    }

    @Override
    public void save(MyRedisSession session) {
        delegate.save(session.getDelegate());
    }

    @Override
    public MyRedisSession getSession(String id) {
        return new MyRedisSession(delegate.getSession(id), sessionRefreshLogic);
    }

    interface DelegateExclude {
        MyRedisSession createSession();		
		void save(MyRedisSession session);
        MyRedisSession getSession(String id);
    }
}
```
But I receive java.lang.IllegalAccessError: org/springframework/session/data/redis/RedisOperationsSessionRepository$RedisSession every time when my code access MyRedisSession.delegate.

**Comment by leofromgroza** [comment]
Still have issues with that. Is it possible to make [org.springframework.session.data.redis.RedisOperationsSessionRepository.RedisSession](https://github.com/spring-projects/spring-session/blob/1.3.1.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L670) extendable (public and non-final separate class).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
