### ISSUE TITLE
When the contextPath set and the @EnableRedisHttpSession use, Then cookie cannot shared.

### ISSUE THREAD

**Issue by yoster0520** [spring-projects/spring-session#730]
Now I use zuul ,spring security,spring session and redis to share http session.<br>
I have two applications.<br>
The first: Zuul server, I use it store static resource<br>
The last: Use Auth server, I use it to auth. This server's contextPath is /ac/v1/.<br>
Then, When I do auth, then the server will return cookie: sessionId=***, path=/ac/v1/.<br>
Then, Chrome cannot share the cookie, because the session has been special path.

**Comment by mrvelibor** [comment]
Hi, I fixed this by creating a bean like this
`
@Bean
    public CookieSerializer cookieSerializer() {
        DefaultCookieSerializer serializer = new DefaultCookieSerializer();
        serializer.setCookieName("SESSION");
        serializer.setCookiePath("/");
        serializer.setDomainNamePattern("^.+?\\.(\\w+\\.[a-z]+)$");
        return serializer;
    }
`

Then all the cookies should use the / path.

**Comment by rwinch** [comment]
Glad you figured this out
