### ISSUE TITLE
DefaultCookieSerializer.useBase64Encoding=true default

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#736]
We should update to use base 64 encoding by default since Tomcat 8.5 requires it and we are moving to 2.x

**Comment by eddumelendez** [comment]
Hi @rwinch , it means session id should be created encoded right?

**Comment by vpavic** [comment]
Hi @eddumelendez - this means we will use Base64 encoding as default cookie encoding in 2.x (it's currently optional). This shouldn't affect session id generation.
