### ISSUE TITLE
why the 'RedisOperationsSessionRepository.RedisSession' is a inner class?

### ISSUE THREAD

**Issue by jintianxiayu** [spring-projects/spring-session#744]
why the 'RedisOperationsSessionRepository.RedisSession' is a inner class? as a resut I can not use the result of method:
```
public Map<String, RedisSession> findByIndexNameAndIndexValue(String indexName,
			String indexValue)
```

**Comment by vpavic** [comment]
`RedisSession` is an implementation of `ExpiringSession` that's specific to the `RedisOperationsSessionRepository`. That shouldn't prevent you from using 
 the `FindByIndexNameSessionRepository`.

Here's a usage example from [find by username sample app guide](http://docs.spring.io/spring-session/docs/1.3.0.RELEASE/reference/html5/guides/findbyusername.html#finding-sessions-for-a-specific-user):

```java
@Autowired
FindByIndexNameSessionRepository<? extends ExpiringSession> sessions;

@RequestMapping("/")
public String index(Principal principal, Model model) {
    Collection<? extends ExpiringSession> usersSessions = this.sessions
            .findByIndexNameAndIndexValue(
                    FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME,
                    principal.getName())
            .values();
    model.addAttribute("sessions", usersSessions);
    return "index";
}
```

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.

**Comment by mrshawn191** [comment]
How would you approach this if you want to save/update session ??

**Comment by vpavic** [comment]
See [#849 (comment)](https://github.com/spring-projects/spring-session/issues/849#issuecomment-321742866).
