### ISSUE TITLE
Expose Default CookieHttpSessionStrategy as Bean

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#75]
We could do that using the following:

``` java
ConfigurableApplicationContext configurableApplicationContext = 
    (ConfigurableApplicationContext) wac;
ConfigurableListableBeanFactory bf = 
    configurableApplicationContext.getBeanFactory();
bf.registerResolvableDependency(CookieHttpSessionStrategy.class, strategy);
```

**Comment by vpavic** [comment]
I don't think we should do anything there, especially now since Spring Boot has added support for auto-configuring `DefaultCookieSerializer` (see spring-projects/spring-boot#15163) which is dependent on presence of `HttpSessionIdResolver` and `CookieSerializer` beans.

Thoughts @rwinch?
