### ISSUE TITLE
Create table statements for DB2 give error

### ISSUE THREAD

**Issue by smackfu** [spring-projects/spring-session#750]
Using spring-session-jdbc 1.3.0.RELEASE, and running the SQL to create the tables on DB2, found here:
https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/resources/org/springframework/session/jdbc/schema-db2.sql

On DB2 v10.5.0.5, the first CREATE TABLE gives the following error:
[2017-04-15 18:40:07] [42831][-542] The column named "SESSION_ID" cannot be a column of a primary key or unique key constraint because it can contain null values.. SQLCODE=-542, SQLSTATE=42831, DRIVER=4.7.85

Changing the primary key columns on both tables to NOT NULL fixes the issue, and I wouldn't expect SESSION_ID or ATTRIBUTE_NAME to be null, so that seems like a valid change, but wanted to verify.

**Comment by vpavic** [comment]
Thanks for the report @smackfu.

The cause is indeed in the schema script - most RDBMSs will implicitly apply the `NOT NULL` constraint to `PRIMARY KEY` declared columns but that's not the case with DB2 it seems.

**Comment by vpavic** [comment]
This is fixed in the `master` and backported to `1.4.x` (#766) and `1.3.x` (#765).
[`1.3.1.RELEASE`](https://github.com/spring-projects/spring-session/milestone/21) which will contain this fix is currently scheduled for this Friday (Apr 28th).
