### ISSUE TITLE
No qualifying bean of type 'org.springframework.session.SessionRepository<?>' available

### ISSUE THREAD

**Issue by petrdvorak** [spring-projects/spring-session#751]
I have followed the tutorial for [Spring Session integration with a Spring Boot app](https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot.html).

Namely, I have:

1) Added following dependencies in my `pom.xml` file:

```xml
<!-- Spring Session -->
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session</artifactId>
    <version>1.3.0.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
```

2) Created a class file called `Config.java` that looks like so:

```java
@EnableRedisHttpSession
public class Config {
}
```

3) Added following line to my `application.properties` file:

```sh
spring.session.store-type=redis
```

Despite all this, my application fail to launch in Tomcat 8.5.13, with following root cause:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.session.SessionRepository<?>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 41 more
```

I can also see a following info message in my log:

```
Spring Data Redis - Could not safely identify store assignment for repository candidate interface io.getlime.security.powerauth.app.webauth.repository.SessionRepository.
```

Finally, there is a nicely formatted message in the log:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method springSessionRepositoryFilter in org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration required a bean of type 'org.springframework.session.SessionRepository' that could not be found.
	- Bean method 'sessionRepository' not loaded because Session Condition found spring.session.store-type property REDIS


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.session.SessionRepository' in your configuration.
```

Could you point me in the right direction, or maybe update the Spring Session docs for Spring Boot 1.5.2? Thank you, keep up the great work! :)

**Comment by vpavic** [comment]
@petrdvorak Could you please share a sample app that reproduces the problem? That would help greatly in diagnosing the cause.

I've got a few observations from the snippets you provided - `spring.session.store-type=redis` has no effect since you've used `@EnableRedisHttpSession` which signals Boot to back-off with Spring Session auto-config since you're configuring it yourself. Admittedly, our Boot samples are a bit out of date but there's a PR to address this (see #720).

```
Spring Data Redis - Could not safely identify store assignment for repository candidate interface io.getlime.security.powerauth.app.webauth.repository.SessionRepository.
```

Other thing is that the log record from above makes me think that maybe you've got a bean named `sessionRepository` registered in your app context which, due to same name, overrides `sessionRepository` `@Bean` Spring Session registers in `RedisHttpSessionConfiguration`.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
