### ISSUE TITLE
SpringSessionRememberMeServices removes Spring Security's Saved Request

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-session#752]
Currently we invalidate existing session when handling login failure in `SpringSessionRememberMeServices#loginFail`. As a consequence of this, original `SavedRequest` is lost with the invalidated session so Spring Security is unable to redirect user to originally requested resource after subsequent successful login attempts.

I think we should be safe to make `SpringSessionRememberMeServices#loginFail` a no-op. Any thoughts @rwinch? To my knowledge no other `RememberMeServices` invalidates existing session when handling login failure.

**Comment by rwinch** [comment]
I updated this to just remove the `HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY` session attribute
