### ISSUE TITLE
additional data to store in redis 

### ISSUE THREAD

**Issue by wtaccuracy** [spring-projects/spring-session#758]
spring:session:sessions:expires:xxxxx
xxxx is session id
if i want to know whether user A is login，i should store on other place，
it is wonderful if spring session can provide a api to make it  spring:session:sessions:A:expires:xxxxx

**Comment by eleftherias** [comment]
@wtaccuracy Could you provide some additional details about what you are requesting?
Perhaps something like [Session.setAttribute()](https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/Session.html#setAttribute-java.lang.String-java.lang.Object-) is what you're looking for?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
