### ISSUE TITLE
Question about PropertySourcesPlaceholderConfigurer Bean in JdbcHttpSession

### ISSUE THREAD

**Issue by sayan-chaliha** [spring-projects/spring-session#775]
Hey,

I'm looking at https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L192

This bean definition here is messing up placeholder resolution in my application. Is it really necessary?

**Comment by vpavic** [comment]
Hi @sayan-chaliha - this was introduced while addressing #616 (see also #621 and 5ecf390).

Can you explain in more detail how is it messing up placeholder resolution in your app? Sample app would also be nice to have.

**Comment by sayan-chaliha** [comment]
Hey @vpavic -- thanks for the pointers! I'll go through them.

I'll need some time before I can get a sample working for you. The libraries I'm using are internal to the company I'm working for. Briefly though, the company has it's own infrastructure for file based configuration of applications (which is injected based on the environment the app is deployed to). The library class in question extends PropertyPlaceholderConfigurer. On instantiating a bean of this library class, I expect that all placeholders are resolved by it. However, randomly (on some environments) https://github.com/spring-projects/spring-session/blob/master/spring-session/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L192 gets instantiated first and doesn't resolve any of the configuration placeholders that I define.

Would it be possible to ignore placeholders it cannot resolve so that another resolver can kick in?

**Comment by vpavic** [comment]
@sayan-chaliha Could you use the same workaround as suggested in [#867 (comment)](https://github.com/spring-projects/spring-session/issues/867#issuecomment-328095462)?

> Can you attempt to override the `PropertySourcesPlaceholderConfigurer` provided by Spring Session configuration by assigning the `propertySourcesPlaceholderConfigurer` id to your `PropertySourcesPlaceholderConfigurer` bean?

**Comment by sayan-chaliha** [comment]
Sure... works for me.

Thanks,
Sayan.

**Comment by vpavic** [comment]
@sayan-chaliha There are proposed changes to Spring Session JDBC configuration which would eliminate the need for having `PropertySourcesPlaceholderConfigurer` bean registered. You can track that effort in #907.
