### ISSUE TITLE
SessionRepositoryFilter - problem with changeSessionId

### ISSUE THREAD

**Issue by christiankissig** [spring-projects/spring-session#779]
I have a Spring Boot web application (Spring Boot 1.5.2.RELEASE) with embedded Jetty that uses Spring Session (1.3.0.RELEASE). I would like to programmatically change the session ID in an API handler method as follows

```java
public void handler(HttpServletRequest request) {
  request.changeSessionId();
}
```

The `javax.servlet` API delegates this request to `SessionRepositoryFilter.changeSessionId(request)`, which attempts to change the session ID by creating a new session and detaching the old one:

```java
SessionRepositoryFilter.this.sessionRepository.delete(session.getId());
HttpSessionWrapper original = getCurrentSession();
setCurrentSession(null);

HttpSessionWrapper newSession = getSession();
original.setSession(newSession.getSession());
```

The issue is that `getSession()`->`getSession(true)` calls `getRequestedSessionId()` which uses the configured `HttpSessionStrategy`, which by default is `CookieHttpSessionStrategy`, which returns the session cookie value with the same session ID as before.

The session ID is not changed as described in the contract of https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html

**Comment by zymen** [comment]
+1

**Comment by rwinch** [comment]
I am unable to reproduce the issue. Please refer to [these tests](https://github.com/rwinch/spring-session-sample/blob/gh-779-change-id/src/test/java/sample/SpringSessionSampleApplicationTests.java) which demonstrate that it is working.

**Comment by rwinch** [comment]
Closing due to lack of feedback. Please reopen with a sample to reproduce the problem ifyou encounter this issue
