### ISSUE TITLE
Tomcat access log valve cannot retrieve session attribute value when using spring-session

### ISSUE THREAD

**Issue by chanjarster** [spring-projects/spring-session#800]
Hello, I tried to configure tomcat access log valve to log a specified session attribute value like this:

```xml
<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%{xxx}s" />
```

According to the [doc][1]:

> %{xxx}s write value of HttpSession attribute with name xxx

But I just got `-` in the log.

I think that may be when I call `HttpSession.setAttribute` I actually call on an `HttpSessionWrapper`, and that doesn't call container's, like Tomcat, `HttpSession` implementation. 

So my question is: Is there any workaround or solution to this problem? Can I get the *raw* `HttpSession`? Or can `HttpSessionWrapper` make call on the *raw* `HttpSession`?

[1]: http://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Access_Log_Valve/Attributes

**Comment by rwinch** [comment]
The only workaround is to have the logging occur within the application itself rather than externally. This is because the AccessLogValve occurs before the request is wrapped.
