### ISSUE TITLE
Session not saved after creation while using IMMEDIATE flush mode

### ISSUE THREAD

**Issue by fcjreed** [spring-projects/spring-session#822]
I have tested using spring session 1.3.0 like so:
@enableredishttpsession(redisFlushMode=RedisFlushMode.IMMEDIATE)

HttpSession session = httpRequest.getSession(true);

String sessionId = session.getId();

Session session = sessionRepository.getSession(sessionId);

Session here is null..

**Comment by fcjreed** [comment]
Closing issue as it doesn't seem like it will be addressed.

**Comment by vpavic** [comment]
@fcjreed Could you clarify the problem you were facing with more details? And possibly a minimal sample app.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
