### ISSUE TITLE
Mysql Driver does not support a 13 digit Timestamp

### ISSUE THREAD

**Issue by cosbor11** [spring-projects/spring-session#823]
When retrieving `spring_sessions` using spring data and the mysql driver does support the timestamp generated by System.currentTimeMillis() which is fed to the `JdbcOperationsSessionRepository` by `SessionRepositoryFilter`.

Throws the following error: 

      java.sql.SQLException: Bad format for Timestamp '1499362413586' in column 2.
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1155)

**Comment by cosbor11** [comment]
This was more of a JPA Entity setup. 

I changed it to use TemporalType.DATE instead of TemporalType.TIMESTAMP: 

       @Column(
            name = "last_access_time",
            columnDefinition = "BIGINT NOT NULL",
            nullable = false,
            length = 42,
            insertable = true,
            updatable = false
        )
        @Temporal(TemporalType.DATE)
        public Date getLastAccessTime()
        {
           return lastAccessTime;
        }

**Comment by vpavic** [comment]
Hi @cosbor11 - could you clarify how does this relate to Spring Session JDBC, since the code snippet you provided is JPA based? Ideally, [a minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve) would be the best way to help us get familiar with the problem.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
