### ISSUE TITLE
Support non-primary JDBC datasources

### ISSUE THREAD

**Issue by bvulaj** [spring-projects/spring-session#828]
Currently, spring-session-jdbc uses the primary DataSource to connect, persist and read session data.  There isn't a way to provide an alternative DataSource, in a multi-datasource project, without overriding some of the session classes.

Can some application property be provided to override this?  `spring.session.jdbc.datasource`, or otherwise?

**Comment by vpavic** [comment]
Hi @bvulaj - to address this requirement you need to register your own `JdbcTemplate` bean named `springSessionJdbcOperations` that works on the desired `DataSource`.

Note that `JdbcHttpSessionConfiguration` registers `JdbcOperationsSessionRepository` that depends on `JdbcTemplate` bean with [qualified with `@Qualifier("springSessionJdbcOperations")`](https://github.com/spring-projects/spring-session/blob/master/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L88) - by default this configuration registers such [`JdbcTemplate` bean](https://github.com/spring-projects/spring-session/blob/master/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/config/annotation/web/http/JdbcHttpSessionConfiguration.java#L82) (which does pick up the primary `DataSource`) but once you register your instance it'll take precedence.

**Comment by bvulaj** [comment]
Hey @vpavic - I've gone down that hole, but was hoping to request a feature that made it a bit simpler.  I can live with how it is for now, but thought the feature might be worthwhile.  Thanks!

**Comment by eshiett1995** [comment]
@vpavic is there a way to show us how to configure this. i am in need of it. and will be grateful

**Comment by bvulaj** [comment]
@eshiett1995 - you need to register the bean that @vpavic mentions with your own DataSource.

```
	@Bean
	@ConfigurationProperties(prefix = "secondary.datasource")
	public DataSource secondaryDataSource() {
		return DataSourceBuilder.create()
				.build();
	}

	@Bean(name = "springSessionJdbcOperations")
	public JdbcTemplate springSessionJdbcOperations(@Qualifier("secondaryDataSource") DataSource secondaryDataSource) {
		return new JdbcTemplate(secondaryDataSource);
	}
```

**Comment by eshiett1995** [comment]
@bvulaj @vpavic it didnt work as i wanted. it created the session tables in the h2 database as i wanted, but instead of creating my entities in PostgreSQL,  it created them in h2 also.

**Comment by vpavic** [comment]
@eshiett1995 Can you provide a minimal sample app that demonstrates your problem?

**Comment by eshiett1995** [comment]
@vpavic  www.github.com/eshiett1995/SessionProject this is the github link

**Comment by vpavic** [comment]
@eshiett1995 Your app doesn't provide the necessary configuration as outlined by both @bvulaj's and my comments. Also you are switching of Boot's `DataSource` auto-config by providing your own instance.

Please take time to get familiar with [Configure Two DataSources](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources) of Boot's reference manual, and after that to the comments from above that describe how to make Spring Session use a non-primary `DataSource`.

**Comment by eshiett1995** [comment]
@vpavic i erased the configurations,  so that I could see how you could help me out. i was a lil bit frustrated i swear.  Is it possible to to get your skype handle and also @bvulaj own. i will be honoured.

**Comment by eshiett1995** [comment]
@vpavic @bvulaj Thanks alot, it worked. I am grateful

**Comment by vpavic** [comment]
@bvulaj I've proposed some improvements to JDBC configuration (see #863) that would introduce the `@SpringSessionDataSource` qualifier for selecting `DataSource` that Spring Session should use in scenarios with multiple data sources. I believe this would be simpler way to configure things you were seeking for.
