### ISSUE TITLE
Respect cookie properties in application.properties

### ISSUE THREAD

**Issue by natetyler** [spring-projects/spring-session#848]
Although #299 allows for creating a custom cookie strategy, I think it would be useful and more "correct" to respect the existing cookie property definitions in the server.session.cookie config namespace (or at least a subset):

    server.session.cookie.name
    server.session.cookie.domain
    server.session.cookie.path
    server.session.cookie.comment
    server.session.cookie.httpOnly
    server.session.cookie.secure
    server.session.cookie.maxAge

**Comment by vpavic** [comment]
Hi @natetyler, I assume you're referring to Spring Boot configuration properties here - the support for configuring session cookie using `SessionCookieConfig` was addressed via #87 and will be available in 1.4 and 2.0 releases.

**Comment by natetyler** [comment]
Perfect, thanks
