### ISSUE TITLE
Provide IMMEDIATE session updates on a method level of RedisOperationsSessionRepository

### ISSUE THREAD

**Issue by beku8** [spring-projects/spring-session#849]
We wanted to update the session, as new role granted for the user.  We can achieve this with the combination of ```findByIndexNameAndIndexValue``` methond and by setting ```RedisOperationsSessionRepository``` on ```IMMEDIATE``` flush mode. Since we can't call ```save```, due to the package access of ```RedisSession```. But I think its not necessary to convert to  ```IMMEDIATE``` just for this purpose.

Would it be possible to provide a method like ```setAttributeImmidiate(sessionId, name, value)``` on ```RedisOperationsSessionRepository```?

**Comment by vpavic** [comment]
Hi @beku8 - can you explain why you cannot call `SessionRepository#save`?

**Comment by beku8** [comment]
Hello, I tried to configure with
```
 @Autowired
  public UserSessionRefreshHandler(RedisOperationsSessionRepository sessionRepository,
      SessionRepository<Session> repository) {
    this.sessionRepository = sessionRepository;
  }
```

but it throws exception on the start up

```
Parameter 0 of constructor in com.nomadays.evento.UserSessionRefreshHandler required a bean of type 'org.springframework.session.SessionRepository' that could not be found.

'sessionRepository' not loaded because Session Condition found spring.session.store-type property REDIS
```

we are on spring boot 1.5.3, thus spring session 1.3.1.

I've tried with also couple of compinations of FindByIndexNameSessionRepository, RedisOperationsSessionRepository, SessionRepository. I thought they were somehow mutually exclusive.

But as you mentioned, I noticed that I autowired SessionRepository, in other classes successfully.

Any idea why this might be happening?

**Comment by vpavic** [comment]
There are basically two ways you can inject a `FindByIndexNameSessionRepository` instance - either to inject and use raw type, or parameterized (respecting the original contract of `FindByIndexNameSessionRepository<S extends Session>`).

Raw type approach:

```java
class RawConsumer {

	@Autowired
	private FindByIndexNameSessionRepository sessionRepository;

	void consume() {
		Session session = (Session) this.sessionRepository
				.findByIndexNameAndIndexValue(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, "principal")
				.values().iterator().next();
		session.setAttribute("test", UUID.randomUUID().toString());
		this.sessionRepository.save(session);
	}

}
```

Parameterized type approach:

```java
class ParameterizedConsumer<S extends Session> {

	@Autowired
	private FindByIndexNameSessionRepository<S> sessionRepository;

	void consume() {
		S session = this.sessionRepository
				.findByIndexNameAndIndexValue(FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME, "principal")
				.values().iterator().next();
		session.setAttribute("test", UUID.randomUUID().toString());
		this.sessionRepository.save(session);
	}

}
```

**Comment by beku8** [comment]
It works, and I feel stupid. Thanks :)
