### ISSUE TITLE
Simultaneously requests with the same SESSION cookie id

### ISSUE THREAD

**Issue by ncastrocosta** [spring-projects/spring-session#865]
Hi!

I have a Spring Boot and AngularJS application. I have OAuth2 set up, so AngularJS app requests access tokens (implicit mode) to made requests to protected resources. That's working fine.

Then, I decided to use HttpSession to manage OAuth2 app session. To the problem I describe below, I've tested on Redis and JDBC. Please, consider there is just one user, one browser (tab).

I understand that on very request the session id is changed. However, in a certain situation, my AngularJS app makes two requests at the same time (simultaneously), then both have the same session id. As result, for each response I have a new and different session id returned. 

That's still not the problem I imagine. 

The problem is that when this happen, the new sessions are created on Redis (or JDBC impl) and the old sessions are not removed, they stay there as valid sessions that will be removed only when they expire as normal sessions. Then, if I try to check my sessions using FindByIndexNameSessionRepository, I'll find a high number of opened sessions just because of that.

Normally, as I undestand, I should find none, because the session is removed in the begining of the request and created on the reponse. Then, in the mean time, when I use FindByIndexNameSessionRepository, I will not find my own session. And that's not a problem.

So, should that behavior be expected? Is there anything should I change or configure?

Please, let me know if something is not well explained.

Thanks!!

Spring boot: 1.5.6.RELEASE
Spring Session: 1.3.1.RELEASE

**Comment by vpavic** [comment]
Hi @ncastrocosta, can you clarify this part a bit:

> I understand that on very request the session id is changed.

**Comment by ncastrocosta** [comment]
Hi @vpavic, I mean "on **e**very request".

**Comment by vpavic** [comment]
Can you post your Spring Session configuration? It seems you didn't set up `HeaderHttpSessionStrategy` correctly and/or that your frontend doesn't send the correct HTTP header that identifies the session on the backend.

You might find some useful information on using Spring Session in an AngularJS app in [this tutorial](https://spring.io/guides/tutorials/spring-security-and-angular-js/).

**Comment by ncastrocosta** [comment]
Hi, @vpavic. 

You're right, I didn't set up HeaderHttpSessionStrategy, because I already have an OAuth2 security enabled for this project (which is also an OAuth2 provider for others systems) and I'm using access tokens (implicit mode) to authenticate.

So, even if I'm using OAuth2 access tokens to authenticate, should I use HeaderHttpSessionStrategy too?

Many thanks!

**Comment by vpavic** [comment]
So if I understand correctly your backend (the Spring Boot app) is both OAuth2 Authorization Server and Resource Server? Can you clarify a bit what was your motivation for adding Spring Session to the stack? The Resource Server APIs should be stateless and you should use Access Token to access those. Can you provide a sample app that demonstrates the problem you're having?

**Comment by ncastrocosta** [comment]
Hi, vpavic! Nice to hear from you! I'm still curious about this.

Yes, I have both OAuth2 Authorization Server and Resource Server in the same Spring Boot app.

For now, let's forget about Spring Session and let me give you an example about what I experienced using OAuth2 (implicit mode):

> 1. I request an access token;
> 2. The server redirects me to the login page;
> 3. After I log in, **a JSESSION cookie is created**;
> 4. I request an access token (with the JSESSION cookie);
> 5. The server gives me an access token;
> 6. **I delete** JSESSION cookie and try to request an access token again;
> 7. The server redirects me to the login page.

So, I concluded, JSESSION cookie is there to guarantee the session is valid and I can request an access token only with it.

Now, If you tell me that JSESSION cookie should not be there after I log in and I don't need it to request access tokens, that will be clarifying and something is wrong in my configuration. Otherwise, I want to have control over session cookies. And that's the reason I added Spring Session to my stack.

Many thanks!

**Comment by vpavic** [comment]
Thanks for the quick feedback @ncastrocosta, your use case is now much clearer.

Yes, it is perfectly reasonable to have your OAuth2 Authorization flow backed by Spring Session. But at the same time, since your app is also a Resource Server, you need to take care that its APIs are stateless.

So this is effectively a Spring Security configuration issue - you need a separate `WebSecurityConfigurerAdapter`s for Authorization flow and the API. The Authorization flow security config should configure a `requestMatcher` such that handles login page and Authorization Endpoint, while API security config should configure a `requestMatcher` that handles API endpoints and declares session management with `SessionCreationPolicy.STATELESS` option.

**Comment by ncastrocosta** [comment]
Hi, @vpavic!

I don't have two `WebSecurityConfigurerAdapter`s. I have one `WebSecurityConfigurerAdapter` and one `ResourceServerConfigurerAdapter`.

They go as follow.

```
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private SessionRegistry registry;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
	// @formatter:off
	http
	    .formLogin().loginPage("/login")
	.and()
	    .logout().logoutSuccessHandler(new HttpStatusReturningLogoutSuccessHandler())
	.and()
	    .csrf().disable()
	    .sessionManagement()
	    	.maximumSessions(1).sessionRegistry(registry)
	;
	// @formatter:on
    }
}
```
```
@Configuration
@EnableResourceServer
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

    @Override
    public void configure(HttpSecurity http) throws Exception {
	// @formatter:off
	http
	    .antMatcher("/api/**")
	    .authorizeRequests()
	    	.antMatchers("/api/user/me").authenticated()
	    	.anyRequest().hasAnyRole("SECURITY")
	.and()
	    .httpBasic().disable()
	    .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
	;		
	// @formatter:on
    }
}
```

Should I change `ResourceServerConfigurerAdapter` to `WebSecurityConfigurerAdapter`?

**Comment by vpavic** [comment]
> Should I change ResourceServerConfigurerAdapter to WebSecurityConfigurerAdapter?

No you should not, that's the correct way to configure the Resource Server security, so all good there.

Regarding the web security config, which should secure Authorization Endpoint, this is using form login and session. So going back to your question from one of earlier comments:

> So, even if I'm using OAuth2 access tokens to authenticate, should I use HeaderHttpSessionStrategy too?

Yes, you do need `HttpSessionStrategy` of some kind for the web part of your app that is using session, in order to correlate user's request with the session on the server side. The access tokens are used to authenticate on your API, which is the resource server part.

Hopefully this clears things a bit.

**Comment by ncastrocosta** [comment]
Ok, @vpavic!

Thank you for your time!

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
