### ISSUE TITLE
RedisHttpSessionConfiguration breaks application due to PropertyPlaceholderConfigurer

### ISSUE THREAD

**Issue by mrusinak** [spring-projects/spring-session#867]
Using Spring Session 1.3.1

`RedisHttpSessionConfiguration` defines a default `PropertyPlaceholderConfigurer` - this can cause an application to fail to initialize if the app defines it's own `PropertyPlaceholderConfigurer` that looks for properties in non-standard locations.

For example, consider a custom configurer that looks in two non-standard locations (one for defaults bundled with the app, another to allow for overrides):

    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:context="http://www.springframework.org/schema/context"
           xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                               http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd">
    
        <context:component-scan/>
    
        <bean class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
            <property name="ignoreResourceNotFound" value="true" />
            <property name="locations">
                <list>
                    <value>classpath:spring/defaults.properties</value>
                    <value>file:${catalina.base}/conf/overrides.properties</value>
                </list>
            </property>
            <property name="ignoreUnresolvablePlaceholders" value="true"/>
        </bean>
    
    </beans>

And a dumb configuration object that uses `@Value`:

    @Component
    public class AppProperties {
        @Value( "${value1}" )
        private String value1;
    
        @Value( "${value2}" )
        private String value2;
    
        public String getValue1() {
            return value1;
        }
    
        public String getValue2() {
            return value2;
        }
    }

(And of course, with a /spring/defaults.properties under src/main/resources, with value1 and value2 set)

Once `<bean class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration"/>` is added as a bean, the app fails to initialize with being unable to resolve the values for `AppProperties`, as the `PropertyPlaceholderConfigurer` from `RedisHttpSessionConfiguration` gets tried and dies resolving them.

**Comment by vpavic** [comment]
This seems to be the same problem as in #775.

Can you attempt to override the `PropertySourcesPlaceholderConfigurer` provided by Spring Session configuration by assigning the `propertySourcesPlaceholderConfigurer` id to your `PropertySourcesPlaceholderConfigurer` bean?

**Comment by mrusinak** [comment]
Changing the app's configurer definition to `<bean id="propertySourcesPlaceholderConfigurer" class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">` unfortunately still causes the error

**Comment by vpavic** [comment]
Thanks for the quick feedback @mrusinak - I'll take a closer look at this.

**Comment by mrusinak** [comment]
I apologize, I was incorrect in my previous statement. Setting the ID does allow the application to start properly (didn't notice earlier that my test hadn't actually used the updated spring context).

Sorry about that!

**Comment by vpavic** [comment]
Thanks for the update. So I guess this works around the original problem then?

**Comment by mrusinak** [comment]
It does. Thanks!

**Comment by viraj071** [comment]
@vpavic Any suggestions to get around this problem if you already have multiple PropertySourcesPlaceholderConfigurer beans with each having 'ignoreUnresolvablePlaceholders' field set to true and a unique id. (Its a legacy app) ?

**Comment by vpavic** [comment]
@viraj071 Assuming you cannot change the id of any of your existing `PropertySourcesPlaceholderConfigurer` beans, you could still use essentially the same approach as described in previous comments - declare another `PropertySourcesPlaceholderConfigurer` bean, name it `propertySourcesPlaceholderConfigurer` and set the `ignoreUnresolvablePlaceholders` to `true`. That bean definition will override the one provided by Spring Session configuration.

Does that work for you?

**Comment by vpavic** [comment]
@mrusinak @viraj071 We've made some changes to Redis configuration support that eliminated the need for having `PropertySourcesPlaceholderConfigurer` bean registered - see #910.

**Comment by hhfdna** [comment]
we are stuck by this issue. in our project, we dont allow duplicated bean definitions. we turn `allow-bean-definition-overriden` to false,
so how to fix it? thx

**Comment by hhfdna** [comment]
thanks@vpavic
