### ISSUE TITLE
Configure Session Cookie using SessionCookieConfig

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#87]
The configuration for the Session Cookie (i.e. SessionCookieConfig) should impact Spring Session's settings.

**Comment by marcelalburg** [comment]
Hello,

is there someting new about this topic ?

How can i set the CookieDomain in a SpringBootProject with Spring Session 1.0.0.RELEASE ?

Thanks
Marcel

**Comment by rwinch** [comment]
At the moment you need to create a custom implementation of `HttpSessionManager`. You can base the implementation off of [CookieHttpSessionStrategy](https://github.com/spring-projects/spring-session/blob/1.0.0.RELEASE/spring-session/src/main/java/org/springframework/session/web/http/CookieHttpSessionStrategy.java). Then you would expose your CookieHttpSessionStrategy as a Bean:

```java
@Bean
public ExtendedCookieHttpSessionStrategy httpSessionStrategy() {
    return new ExtendedCookieHttpSessionStrategy();
}
```

This feature will be added in the 1.1 release which is not yet scheduled.

**Comment by marcelalburg** [comment]
Ok, thanks for the Information. I do it like you sayed. But i've one more question. Why is this class final ? I don't know exactly, but maybe i wanna override some function without copy the hole class ...

Thanks for you help.

**Comment by rwinch** [comment]
@marcelalburg It is marked as final to ensure we can more easily evolve the class and to encourage users (and the framework) to favor composition over inheritance.

**Comment by marcelalburg** [comment]
Thanks, for the info and for the tipp.

Marcel

**Comment by rwinch** [comment]
In the latest snapshots you can now create a DefaultCookieSerializer and expose it as a Bean. See #299 

Since there is a way to do this now, I'm going to push this back as a lower priority.

**Comment by jgogstad** [comment]
Workaround that doesn't require snapshot-dependency (tested on spring boot 1.4.0, spring-session 1.2.1)

    @Configuration
    @Order(1)
    public class SpringCacheConfig implements EmbeddedServletContainerCustomizer {
    
        @Bean
        public DefaultCookieSerializer cookieSerializer() {
            return new DefaultCookieSerializer();
        }
    
        @Override
        public void customize(ConfigurableEmbeddedServletContainer container) {
            container.addInitializers(new SpringCacheConfigurer());
        }
    
        private class SpringCacheConfigurer implements ServletContextInitializer {
    
            @Override
            public void onStartup(ServletContext servletContext) throws ServletException {
                SessionCookieConfig sessionCookieConfig = servletContext.getSessionCookieConfig();
                DefaultCookieSerializer serializer = cookieSerializer();
                serializer.setCookieMaxAge(sessionCookieConfig.getMaxAge());
                serializer.setCookieName(sessionCookieConfig.getName());
                serializer.setCookiePath(sessionCookieConfig.getPath());
                serializer.setDomainName(sessionCookieConfig.getDomain());
                serializer.setUseHttpOnlyCookie(sessionCookieConfig.isHttpOnly());
                serializer.setUseSecureCookie(sessionCookieConfig.isSecure());
            }
        }
    }

Use `server.session.cookie`-properties from spring boot ([documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)) to configure.

**Comment by stevestorey** [comment]
I've discovered what is _sort of_ a regression as a result of this change. If you are using Undertow, then its default session cookie configuration uses a maxAge of 0 (possibly incorrectly? https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/session/SessionCookieConfig.java#L44) which is passed on through to the DefaultCookieSerializer created here, and later on in Undertow's processing writing out the session cookie, if the maxAge = 0 (https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/Connectors.java#L189), then an Expires header is set, which then causes the cookie to be immediately invalidated by the browser - and so sessions no longer work.

Undertow itself deals with the situation correctly when writing out the session ID by only adding an expires header if maxAge > 0 (https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/session/SessionCookieConfig.java#L62)

So it's not entirely clear whether the problem is with Undertow's slightly mismatched handling of the session cookie config, or a regression in Spring Session (well it _is_ a regression ;) - but not quite sure who should fix it).

I _think_ that as it stands this will make it impossible to use Spring Session out of the box with Undertow / Wildfly ?

**Comment by vpavic** [comment]
Thanks for the report @stevestorey - I've opened #805.

**Comment by stevestorey** [comment]
And for completeness for anyone else ending up here, there is a fairly simple workaround, which  is just to define your own serializer as a bean in the configuration on which you're applying `@EnableSpringHttpSession` / `@EnableRedisHttpSession` / etc.
```
@Bean
CookieSerializer cookieSerializer() {
    return new DefaultCookieSerializer();
}
```

**Comment by littlehome-eugene** [comment]
```
 @EnableJdbcHttpSession // <1>
 public class HttpSessionConfig {

   // tag::cookie-serializer[]
   @Bean
   public CookieSerializer cookieSerializer() {
     DefaultCookieSerializer serializer = new DefaultCookieSerializer();
     return serializer;
   }
   // end::cookie-serializer[]

 }
```

I'm getting error 

> 
> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) on project social-simple: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to
> start embedded Tomcat: Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': Unsatisfied dependency expressed through method 'customize' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.session-org.springframework.boot.autoconfigure.session.SessionProperties': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.session.SessionProperties]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/session/hazelcast/HazelcastFlushMode: org.springframework.session.hazelcast.HazelcastFlushMode
