### ISSUE TITLE
spring session support spring 3?

### ISSUE THREAD

**Issue by rainplus** [spring-projects/spring-session#873]

**Comment by vpavic** [comment]
Hi @rainplus,

The minimum requirements are documented in the [Minimum Requirements section](https://docs.spring.io/spring-session/docs/current/reference/html5/#minimum-requirements) of reference manual. For the current `1.3.1.RELEASE` requirements are:

- Java 5
- Servlet 2.5
- Spring 3.2.14

The upcoming Spring Session 2.0 will raise these to Java 8 and Spring 5.

**Comment by rainplus** [comment]
@vpavic thanks
