### ISSUE TITLE
Using spring session with angular for a rest app

### ISSUE THREAD

**Issue by eshiett1995** [spring-projects/spring-session#874]
i am new to spring session but i am very confused and even the documentation is not robust. i am trying to make a logging app. but i am confused because on request of the index page, spring sends the session ID in the X-Auth-token header (after this i am confused, because i don't know how to use this information). please can i get a step by step walk through of how i can work with this header when making a Rest call. and how do i get to use this x-Auth-token cause i heard javascript can not take the header of a rendered HTML page. My aim is to make a single page application without spring security. SO how do i parse session ID from Rest-request to Rest- request. Thank you

**Comment by vpavic** [comment]
@eshiett1995 The use of Spring Session with RESTful APIs is described in a [dedicated chapter](https://docs.spring.io/spring-session/docs/current/reference/html5/#httpsession-rest) of reference manual, which also contains a link to related sample app. You should also refer to the `HeaderHttpSessionStrategy` javadoc.

Regarding the AngularJS part that's outside of scope of Spring Session documentation but you can refer to [Spring Security and Angular JS](https://spring.io/guides/tutorials/spring-security-and-angular-js/) guide from spring.io (search for `X-Auth-Token` references).

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
