### ISSUE TITLE
How do I inject the specified ConnectionFactory bean in the RedisHttpSessionConfiguration?

### ISSUE THREAD

**Issue by linsudeer** [spring-projects/spring-session#876]

**Comment by vpavic** [comment]
@linsudeer At the moment we don't have an explicit support for customizing `RedisConnectionFactory` used in `RedisHttpSessionConfiguration` but you can work around that by overriding `sessionRedisTemplate` and `redisMessageListenerContainer` beans with your own definitions that use the desired `RedisConnectionFactory` - just make sure your beans are using the same id as the ones declared in `RedisHttpSessionConfiguration`.

Note that we plan to make some improvements to Redis configuration in #864.

**Comment by linsudeer** [comment]
works for me.

Thanks,
@vpavic
