### ISSUE TITLE
Adding Max-Age to the Session Cookie.

### ISSUE THREAD

**Issue by johridevesh** [spring-projects/spring-session#879]
Hi,

Spring Security creates a cookie "SESSION" and with iOS11 release, SESSION cookie needs to have Max-Age attribute (e.g. Max-Age=86400) once we set the cookie. The max-age attribute holds the validity of the cookie in seconds (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).

Is there a way we can override the default SESSION cookie and add an attribute Max-Age?

Thanks and Regards,
Devesh Johri

**Comment by vpavic** [comment]
Hi @johridevesh, you need to provide your own `CookieSerializer` which will have Max-Age configured according to you requirements (see `DefaultCookieSerializer#setCookieMaxAge`).

**Comment by johridevesh** [comment]
That's correct, I already added it:

/**
     * Overriding the Session cookie to set the max age.
     */
    @Bean
    public CookieSerializer cookieSerializer() {
            DefaultCookieSerializer serializer = new DefaultCookieSerializer();
            serializer.setCookieName("SESSION"); 
            serializer.setCookiePath("/"); 
            serializer.setDomainNamePattern("^.+?\\.(\\w+\\.[a-z]+)$"); 
            serializer.setCookieMaxAge(7200);
            return serializer;
    }

This will set Expiry to the 7200 seconds from the time session is created. I would like to know, is there a way I can explicitly add max-age attribute, the reason I am asking it some browsers do not look for Expiry but need max-age attribute in SESSION cookie.

Thanks,
Devesh Johri

**Comment by vpavic** [comment]
Thanks for clarification.

This works as expected for me, i.e. with `DefaultCookieSerializer` configured with `Integer.MAX_VALUE` for `cookieMaxAge` I'm getting the following cookie: `sid=MmEyYWMzOTktNGVjMC00ZmRhLThmMTgtZmVlMjI4MTQzNjdl; Max-Age=2147483647; Expires=Sun, 07-Oct-2085 09:46:19 GMT; Path=/`

Can you provide a sample that reproduces the problem?

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.

**Comment by rohitkrishna094** [comment]
Can this be done? To use 

server.servlet.session.cookie.max-age = xxx

similar to how they change the name in the below question?
https://stackoverflow.com/questions/25918556/spring-boot-configure-custom-jsessionid-for-embedded-server
