### ISSUE TITLE
HeaderHttpSessionStrategy and Cookies

### ISSUE THREAD

**Issue by eshiett1995** [spring-projects/spring-session#883]
i am trying to create a mini social media, since i am using angularJs  i am using spring session HeaderHttpSessionStrategy  so i can pass the tokens through rest. But my problem is; Is there a way to remember the user who logged in, suppose he closes  and re-opens his browser and hits the link. i wanted to try cookies, but i don't think the HeaderHttpSessionStrategy of spring session allows cookies. Please i need help, i am stuck or is there a way HeaderHttpSessionStrategy  can work with cookies.

**Comment by vpavic** [comment]
@eshiett1995 This question is more about the design of your AngularJS client. Sounds like the client itself needs to handle the auth token persistence in a cookie or local store.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
