### ISSUE TITLE
Navbar not visible in Users sample app

### ISSUE THREAD

**Issue by kkoehler** [spring-projects/spring-session#885]
Hi

i to run the "users" sample app (samples/javaconfig/users/) with 'gradle tomcatRun' and encountered problems with the navbar. It's not visible for me running Chromium Version 60.0.3112.113 or Firefox 55.0.2.

I removed the 'collapse' class from https://github.com/spring-projects/spring-session/blob/master/samples/javaconfig/users/src/main/webapp/index.jsp#L23

and 

https://github.com/spring-projects/spring-session/blob/master/samples/javaconfig/users/src/main/webapp/link.jsp#L23

So the navbar is visible for me and everthing works. 
Bootstrap version used is 2.3.2 in my case.

Thanks,
Kristian

**Comment by vpavic** [comment]
Thanks for the report @kkoehler, I've confirmed your findings.

Would you be interested in submitting a PR to address this?

**Comment by vpavic** [comment]
This was a regression caused by inadvertent downgrade of Bootstrap in e4fe53a.
