### ISSUE TITLE
Spring Session Snapshot Metadata

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#895]
### Summary

Spring Session is experiencing issues with Spring Security's SNAPSHOT Maven metadata due to https://www.jfrog.com/jira/browse/RTFACT-12507

Related https://github.com/spring-projects/spring-boot/issues/10559 https://github.com/spring-projects/spring-security/issues/4609

**Comment by eleftherias** [comment]
Closing since this has been fixed in Artifactory https://www.jfrog.com/jira/browse/RTFACT-12507
