### ISSUE TITLE
Harmonize naming of reactive components

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-session#897]
I've experienced the Reactive features in Spring projects, including Spring Session and its subprojects(`spring-session-data-redis`, `spring-session-data-mongodb`).

In Spring 5, by default, when `Reactive` labeled(prefixed class or methods) facilities, in most of cases, it used **Project Reactor** internally.

So it is better to rename `ReactorSessionRepository` to `ReactiveSessionRepository`?

And there are some inconsistent naming annotations in Spring Session umbrella projects. 
* `@EnableSpringWebSession`(spring-session-core)
* `@EnalbeRedisReactorSession`(spring-session-data-redis)
* `@EnableMongoWebSession` (spring-session-data-mongodb)

For `@EnalbeRedisReactorSession`, I think use `@EnableRedisWebSession` is better.

 I was using Spring Session 2.0.0.M5(used Spring Boot 2.0.0.M5 for dependency management).

**Comment by vpavic** [comment]
Thanks for the feedback @hantsy!

I agree we should take a closer look at naming of our components, and provide consistency both considering the Spring Session's Servlet API vs Reactive components, as well as Spring Session vs Spring Framework.

We'll use this issue to track that effort.

**Comment by vpavic** [comment]
I've pushed the following key changes in 00ede81:

- rename `ReactorSessionRepository` to `ReactiveSessionRepository`
- rename `EnableRedisReactorSession` to `EnableRedisWebSession`

See also #900 and #901.

/cc @gregturn @jxblum

**Comment by gregturn** [comment]
Spring Session MongoDB adjusts per https://github.com/spring-projects/spring-session-data-mongodb/commit/53bd6f65ac9d43a8195c569d97037bc342699eda
