### ISSUE TITLE
Spikes in Spring Session Redis every minute

### ISSUE THREAD

**Issue by odedia** [spring-projects/spring-session#899]
I'm trying to understand the reasoning for defining the cron in spring session redis to be once a minute.

Basically, it appears that the server registers for expiration events, and when the event comes, the server goes back to redis to download the session details.

In parallel, spring session redis runs a cron job  once a minute to expire old sessions.

So:

This means that in a reasonable production environment with ~100 instances, a cron job could easily expire 1,000 users in a given minute. The cron job is set to expire ALL those users _at the same second_ (the 00 seconds mark).

Think about it: 100 spring boot instances * 1000 expiration events *  potentially two activities against redis (expire + get session details) - that's 200,000 operations per _second_.

Imagine a scenario where a system needs to "kick out" the users for some reason - that would trigger millions of events at the same second.

This is not theory - we notice this behaviour in production, a huge spike occurs at the beginning of every minute, reaching the 200,000 ops per second range.

I know that with newer versions of Spring Session Redis the cron is property based (we still use a version based on Spring Boot Starter 1.4.5), however I feel the above explanation is a good reason to change the defaults as well.

- Change the default of Redis Notification to be NO_OP, so servers will not remotely change redis config to notify of expiration events. If some application needs these events for cleaning up web sockets (that's the only reason I found for this implementation), they will change to the notification registration.
- Change the default cron job to be random, not hitting the server at the same split-second
- Consider allowing a NO_OP RedisMessageListener instead of the existing default. This listener would not process events even if they come.
- Ideally, only one server in production should handle these cleanup tasks, but I can't be sure of how to allow a single instance among many to behave differently (Perhaps using spring profiles is the solution).

Thanks.

**Comment by odedia** [comment]
Also - please provide documentation that defines the risks of disabling this behavior. Will spring session continue functioning as expected, or are there limitations when the listener is not active?

Thank you.

**Comment by vpavic** [comment]
Hi @odedia - did you read the reference manual's section on [`RedisOperationsSessionRepository` session expiration](https://docs.spring.io/spring-session/docs/2.0.0.RC1/reference/html5/#api-redisoperationssessionrepository-expiration)? This info is also available on `RedisOperationsSessionRepository` class level javadoc. It provides in-depth explanation of session expiration mechanics for this particular `SessionRepository` implementation and should provide the information you're seeking for. Let us know if you feel something is still unclear.

Regarding the disabling of `MessageListener` capability by default, this is something that could be considered, however the problematic part is that among this handler's responsibilities is also cleanup of principal index that's used to provide `FindByIndexNameSessionRepository` capabilities.

Note that we've also recently improved configuration capabilities of a cleanup cron in #910.

**Comment by odedia** [comment]
Thanks vpavic,

Yes I did read the documentation. 

The problem was that the cron is for the exact same simultaneous second and then each one ran the listener as well. 

The result were spikes that could have caused redis timeout exceptions. 

The biggest concern was that the more servers we added, the bigger the problem got.

We solved the problem by disabling the listener and the cron job by implementing our own custom operations repository. 

We created a separate daemon microservice that used the default 1-minute timeout that handled the cleanup and the listener, including the IndexName handling. We put two instances to make sure it is always executed. 

The result was a decrease from 150,000 ops per second to 50,000 ops per second. I believe it is quite a difference. 

Thanks for the help!

**Comment by vpavic** [comment]
Yes, we realized that running the cleanup job at the same time might not be desirable, for example due to concerns similar to yours, and that's why the configuration for this setting has been promoted to `@EnableRedisHttpSession`.

Regarding the need to run the cleanup job at all nodes in the first place, this is of course needed for session events to be published on all nodes - if this is not of critical value, your solution with disabling the listener and running it in one place is certainly valid approach.

In any case, thanks for sharing your concerns and feedback.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
