### ISSUE TITLE
Fix package tangles SpringWebSessionConfiguration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#900]
Fix tangles in SpringWebSessionConfiguration

**Comment by rwinch** [comment]
FYI @gregturn @jxblum this may impact you two

**Comment by gregturn** [comment]
Spring Session MongoDB adapted via https://github.com/spring-projects/spring-session-data-mongodb/commit/e86e991c9723c0f6d2f562b7ba3ab003b5b94818.
