### ISSUE TITLE
Using JacksonMongoSessionConverter with Spring Security causes IllegalArgumentException

### ISSUE THREAD

**Issue by rougou** [spring-projects/spring-session#913]
Hi, I'm trying to use JacksonMongoSessionConverter to convert my session data to json. Because I'm using Spring Security, I add the modules from SecurityJackson2Modules and initialize the converter as follows:

```
@Bean
public AbstractMongoSessionConverter mongoSessionConverter() {
  List<Module> securityModules = SecurityJackson2Modules.getModules(getClass().getClassLoader());
  return new JacksonMongoSessionConverter(securityModules);
}
```
This gives me the following error when JacksonMongoSessionConverter tries to convert the data back to a MongoExpiringSession object:
```
java.lang.IllegalArgumentException: The class with org.springframework.session.data.mongo.MongoExpiringSession and name of org.springframework.session.data.mongo.MongoExpiringSession is not whitelisted. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details
	at org.springframework.security.jackson2.SecurityJackson2Modules$WhitelistTypeIdResolver.typeFromId(SecurityJackson2Modules.java:193)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:150)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1082)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at org.springframework.session.data.mongo.JacksonMongoSessionConverter.convert(JacksonMongoSessionConverter.java:100)
...
```
Looking at the redis converter (GenericJackson2JsonRedisSerializer), it calls `enableDefaultTyping()` which solves this problem, but there is no way to modify the ObjectMapper with JacksonMongoSessionConverter.

On a side note, I think the javadoc for [SecurityJackson2Modules ](https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/jackson2/SecurityJackson2Modules.html) is wrong where it says `Above code is equivalent to`, since `enableDefaultTyping()` is no longer called after [this change](https://github.com/spring-projects/spring-security/commit/b43c6d0c8f32f82e2ad1fd0d44f4578d1b7505a4).

Any help on how to solve this (without rewriting the entire converter) and guidance on the security implications is appreciated.

(version: spring-session-1.3.1.RELEASE, used with spring-security-core-4.2.3.RELEASE)

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-session-data-mongodb/commit/7a4e14cfbff3235fe87cc559d807f147818cbef8.

**Comment by gregturn** [comment]
From here on, you'll simply have to create the following in your Boot app

```
@Bean
JacksonMongoSessionConverter sessionConverter() {
    return new JacksonMongoSessionCoverter();
}
```

Put that in your application, and Spring Session MongoDB will pick up that bean and wire it, whether you are using our Reactive Spring or classic Spring.

**Comment by vpavic** [comment]
@gregturn Do you think we could have this fix back ported to the `1.3.x` branch as well?

**Comment by gregturn** [comment]
Uncertain. It required a patch to Spring Security as well to handle deserializing "null" values properly.

**Comment by gregturn** [comment]
No. 

Spring Session MongoDB only supports version 2.0 since it was resurrected. There is no 1.x branch for this project that supports backports.

**Comment by rougou** [comment]
@gregturn This solves the issue with the MongoSession object itself but what is the proper way to whitelist our custom session scoped classes? See https://github.com/spring-projects/spring-session-data-mongodb/issues/27

**Comment by gregturn** [comment]
Digging into the stack trace, you should see an error message documenting to either mark up the POJOs with any Jackson annotation extending @JsonAnnotation (their meta annotation) or applying a mixin.

I'm currently making it possible to inject your own `ObjectMapper` into `JacksonMongoSessionConverter`.
