### ISSUE TITLE
Add ReactiveFindByIndexNameSessionRepository

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#914]
A reactive equivalent to `FindByIndexNameSessionRepository`

**Comment by goosmurf** [comment]
Could this issue be prioritised given that it has security implications?

Consider that if a user's account is compromised (e.g. through cookie or other credential theft) it's typically expected that a password change would also have the effect of (optionally) invalidating all existing sessions.

Without this interface it's difficult to properly address session hijacking.

**Comment by igorbolic** [comment]
Are there any plans of when `ReactiveFindByIndexNameSessionRepository` will be available? 
Are there any guidelines of how someone could achieve the same functionality (invalidation & cleanup of all principal sessions) before this is released?

**Comment by yangdq1** [comment]
Are there any plans of this issue?

**Comment by rwinch** [comment]
Not at this time

**Comment by adamalexandru4** [comment]
Could anyone please provide at least a workaround in the meantime ?

**Comment by HJK181** [comment]
5 years, and still nothing.

**Comment by ChiragMoradiya** [comment]
We also encountered this issue. All of our micro-services are on Webflux, and we can't use this feature to invalidate all sessions of a User, when needed.

**Comment by marcusdacoregio** [comment]
Hi everyone, I'll be revisiting this issue as soon as https://github.com/spring-projects/spring-security/issues/6192 is complete in order to integrate Spring Session WebFlux with the concurrent sessions control.

**Comment by marcusdacoregio** [comment]
Hi everyone, this has been closed via https://github.com/spring-projects/spring-session/issues/2700.
This first implementation is based on Redis, please try it out and report any bugs or improvements suggestions.
