### ISSUE TITLE
Absolute session timeouts

### ISSUE THREAD

**Issue by sirianni** [spring-projects/spring-session#922]
The [OWASP Session Management](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Automatic_Session_Expiration) best practices recommend using an absolute session timeout in addition to an idle timeout.

Spring Session currently supports only inactivity timeouts.  It would be nice for the library to accommodate absolute timeouts as well.

**Comment by rwinch** [comment]
@sirianni Thanks for the report. I don't think that makes sense to have every feature in Spring Session itself. There is already a [Session.getCreationTime()](https://github.com/spring-projects/spring-session/blob/f2ba773ec24b70c2d043b73f0493e2108a57313f/spring-session-core/src/main/java/org/springframework/session/Session.java#L119) that allows you to determine how long the session has been around. With this information, you can calculate an absolute timeout of our choice. If the timeout has occurred, you can invalidate the session.

**Comment by rwinch** [comment]
@sirianni You can also implement this by providing a `DefaultCookieSerializer` that has the `maxAge` property set to the absolute timeout. Keep in mind that this just removes the cookie reference after that amount of time. This means a user interacting with the application through a browser would experience it as though the session has a max expiration because the cookie would be discarded after that max timeout. However, if a malicious user got a hold of the session id, they could continue to use that session past the max expiration.

**Comment by oliversaggau** [comment]
@rwinch I tried implementing a delegating implementation like you proposed. Currently we are using Redis as a backend for storing the sessions, so we are using `@EnableRedisHttpSession`. But as far as I understood to provide our own (delegating) `SessionRepository` we would need to fall back to using `@EnableSpringHttpSession` and provide a Bean named `sessionRepository`. But how exactly are we supposed to get an instance of the `RedisIndexedSessionRepository` we then can delegate to? Of course I could simply create my own instance by using `new RedisIndexedSessionRepository()` but what about all the stuff around it like the `RedisHttpSessionConfiguration.SessionCleanupConfiguration`, etc.? So I basically copied the whole `RedisHttpSessionConfiguration` to create an instance the same way it would have been originally created. But is that really how we are supposed to do this, by copying a whole class? 🤔

**Comment by rwinch** [comment]
There are likely a lot of ways of going about this, but the easiest one that comes to mind is using a `BeanPostProcessor`. Something like:

```java
public class AbsoluteSessionRepositoryBeanPostProcessor implements BeanPostProcessor {

    public Object postProcessAfterInitialization(Object bean, String beanName) {
        if (bean instanceof SessionRepository) {
           return new AbsoluteSessionRepository((SessionRepository) bean);
        }
        return bean;
    }
}
```

Then you need to expose the `BeanPostProcessor` on a `@Configuration` (to avoid circular bean dependencies I recommend doing this in it's own configuration with a static method).

```java
@Configuration
public class AbsoluteSessionRepositoryBeanPostProcessorConfiguration {

    @Bean
    public static AbsoluteSessionRepositoryBeanPostProcessor AbsoluteSessionRepositoryBeanPostProcessor() {
        return new AbsoluteSessionRepositoryBeanPostProcessor();
    }
}
```

**Comment by oliversaggau** [comment]
It wasn't just as simply as that, but it was definitely a push in right direction for me. I had to return a CGLIB proxy in the `BeanPostProcessor` otherwise `RedisHttpSessionConfiguration$SessionCleanupConfiguration` would give a `BeanNotOfRequiredTypeException` for it's constructor because the `AbsoluteSessionRepository` is not of type `RedisIndexedSessionRepository`

**Comment by gbear605** [comment]
Another solution, assuming you're using a SessionRepository based on a database, is to use a SessionRepositoryCustomizer to update the database query.

This uses MySQL specific behavior, but it should be pretty easy to make it worth with a different database.

```
@Configuration
class SessionConfiguration {

	public static final Duration ABSOLUTE_SESSION_TIMEOUT = Duration.of(10, ChronoUnit.HOURS);

	/**
	 * Configures the session repository to have all sessions timeout after
	 * {@link SessionConfiguration#ABSOLUTE_SESSION_TIMEOUT}.
	 *
	 * Requires the session repository to be a JdbcIndexedSessionRepository and for the database to be MySQL.
	 * The customizer sets a custom query that relies on the MySQL-specific UNIX_TIMESTAMP function.
	 *
	 * UNIX_TIMESTAMP() returns the current time in seconds since the epoch while the session's CREATION_TIME is in
	 * milliseconds since the epoch, so we need to multiply the current time by 1000 to get comparable numbers.
	 * See https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_unix-timestamp for more
	 */
	@Bean
	public SessionRepositoryCustomizer<JdbcIndexedSessionRepository> absoluteTimeoutSessionRepositoryCustomizer() {
		return sessionRepository -> {
			String query = "SELECT S.PRIMARY_ID, S.SESSION_ID, S.CREATION_TIME, S.LAST_ACCESS_TIME, "
					+ "S.MAX_INACTIVE_INTERVAL, SA.ATTRIBUTE_NAME, SA.ATTRIBUTE_BYTES "
					+ "FROM %TABLE_NAME% S "
					+ "LEFT JOIN %TABLE_NAME%_ATTRIBUTES SA ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID "
					+ "WHERE S.SESSION_ID = ? AND (UNIX_TIMESTAMP() * 1000 - S.CREATION_TIME) < "
					+ ABSOLUTE_SESSION_TIMEOUT.toMillis();
			sessionRepository.setGetSessionQuery(query);
		};
	}

}
```

**Comment by Flame239** [comment]
Similar Query for postgres:
```
"SELECT S.PRIMARY_ID, " +
"    S.SESSION_ID, " +
"    S.CREATION_TIME, " +
"    S.LAST_ACCESS_TIME, " +
"    S.MAX_INACTIVE_INTERVAL, " +
"    SA.ATTRIBUTE_NAME, " +
"    SA.ATTRIBUTE_BYTES " +
"FROM " +
"    %TABLE_NAME% S " +
"LEFT JOIN " +
"    %TABLE_NAME%_ATTRIBUTES SA " +
"ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID " +
"WHERE S.SESSION_ID = ? " +
"AND (extract(epoch from LOCALTIMESTAMP)::bigint - CREATION_TIME / 1000) < " + ABSOLUTE_SESSION_TIMEOUT.toSeconds();
```

**Comment by xodiumluma** [comment]
> There are likely a lot of ways of going about this, but the easiest one that comes to mind is using a `BeanPostProcessor`. Something like:
> 
> ```java
> public class AbsoluteSessionRepositoryBeanPostProcessor implements BeanPostProcessor {
> 
>     public Object postProcessAfterInitialization(Object bean, String beanName) {
>         if (bean instanceof SessionRepository) {
>            return new AbsoluteSessionRepository((SessionRepository) bean);
>         }
>         return bean;
>     }
> }
> ```
> 
> Then you need to expose the `BeanPostProcessor` on a `@Configuration` (to avoid circular bean dependencies I recommend doing this in it's own configuration with a static method).
> 
> ```java
> @Configuration
> public class AbsoluteSessionRepositoryBeanPostProcessorConfiguration {
> 
>     @Bean
>     public static AbsoluteSessionRepositoryBeanPostProcessor AbsoluteSessionRepositoryBeanPostProcessor() {
>         return new AbsoluteSessionRepositoryBeanPostProcessor();
>     }
> }
> ```

Hi, @rwinch, in what possible circular dependency scenarios does this `AbsoluteSessionRepositoryBeanPostProcessor` get involved in? Or, it's a general precaution? 

How does Spring Session know how to swap out a `JdbcIndexedSessionRepository` with `AbsoluteSessionRepository`? Both are `SessionRepository` instances. Or is that why we rewrite bits of the sole `JdbcIndexedSessionRepository` itself, since we can't indicate to Spring that we prefer our `SessionRepository` version?
