### ISSUE TITLE
how to custom session for spring boot

### ISSUE THREAD

**Issue by mrvon2015** [spring-projects/spring-session#934]
spring xml
`<bean id="lettuceConnectionFactory" class="org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory" >
        <constructor-arg index="0" ref="lettucePool" />
    </bean>

	<bean id="defaultCookieSerializer" class="org.springframework.session.web.http.DefaultCookieSerializer">
		<property name="cookieName" value="${session.cookie.name}" />
		<property name="cookiePath" value="${session.cookie.path}" />
		<property name="domainName" value="${session.domain.name}" />
	</bean>

	<bean id="cookieHttpSessionStrategy" class="org.springframework.session.web.http.CookieHttpSessionStrategy">
		<property name="cookieSerializer" ref="defaultCookieSerializer" />
	</bean>

	<bean class="org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration">
		<property name="httpSessionStrategy" ref="cookieHttpSessionStrategy" />
	</bean>`

if spring boot, how to do it?
cookieName, cookiePath, domainName

**Comment by vpavic** [comment]
@mrvon2015 If you're using Spring Boot, you should rely on it's [auto-configuration capabilities for Spring Session](https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#boot-features-session). To customize cookie serialization you then only need to provide a `DefaultCookieSerializer` which will be automatically picked up by `SpringHttpSessionConfiguration`.

**Comment by mrvon2015** [comment]
thanks！
`@Configuration
public class SpringSessionConfiguration {
	@Bean
	public DefaultCookieSerializer defaultCookieSerializer() {
		DefaultCookieSerializer defaultCookieSerializer = new DefaultCookieSerializer();
		defaultCookieSerializer.setCookieName("SESSION"); // session
		defaultCookieSerializer.setCookiePath("/"); 
		defaultCookieSerializer.setDomainName(“spring.io”); // 指定顶级域名
		return defaultCookieSerializer;
	}
}`
