### ISSUE TITLE
Spring session not insert values in database

### ISSUE THREAD

**Issue by SiNick1** [spring-projects/spring-session#937]
Spring-session make selects and drop querys but never insert in database. I think maybe some configuration is wrong in my login i use a xml configuration.

``` xml
<http auto-config="true" create-session="always" use-expressions="true">

        <form-login
                login-page="/login.htm"
                default-target-url="/home.htm"
                authentication-failure-url="/login.htm?errorDetails"
                username-parameter="username"
                password-parameter="password"
                always-use-default-target="true"/>

        <logout invalidate-session="true" logout-success-url="/login.htm" delete-cookies="JSESSIONID"/>

        <session-management session-fixation-protection="newSession" invalid-session-url="/"
                            session-authentication-error-url="/login.htm">     
            <concurrency-control max-sessions="10" session-registry-alias="sessionRegistry"
                                 expired-url="/" error-if-maximum-exceeded="true"/>
        </session-management>
        <access-denied-handler error-page="/403"/>
        <csrf disabled="true"/>
    </http>

    <authentication-manager>
        <authentication-provider user-service-ref="userDaoImpl">
            <password-encoder ref="passwordEncoder">
                <salt-source ref="saltSource"/>
            </password-encoder>
        </authentication-provider>
        <authentication-provider ref="multipleLdapProvider"/>
    </authentication-manager> 
```

**Comment by vpavic** [comment]
@SiNick1 Any chance you provide us with a sample app that demonstrates the situation you're describing?

**Comment by SiNick1** [comment]
Hi vpavic, i was make a mistake in my configuration, the most important config is in web.xml the first filter must be the session filter.

<--! FIRST-->
<filter>
        <filter-name>springSessionRepositoryFilter</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSessionRepositoryFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

<--! SECOND-->
    <filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSecurityFilterChain</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

**Comment by vpavic** [comment]
Thanks for following up @SiNick1. Yes, that should work, Session filter needs to go first to ensure the `HttpSession` is backed by Spring Session's implementation before any session consumers interact with it.

Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
