### ISSUE TITLE
I have problem in catching session change events

### ISSUE THREAD

**Issue by taozhaolib** [spring-projects/spring-session#946]
I have problem in catching the session events:

```java
@Component
public class SessionCreatedListener {
    @EventListener
    public void onCreate(org.springframework.session.events.SessionCreatedEvent event) {
        System.out.println(event);
    }

    @EventListener
    public void onDestroy(org.springframework.session.events.SessionDestroyedEvent event) {
        System.out.println(event);
    }
}
```

The session config class:

```java
@Configuration
@EnableRedisHttpSession
public class SessionConfig  extends AbstractHttpSessionApplicationInitializer {
    
    @Bean
    public HttpSessionStrategy httpSessionStrategy() {
        return new CookieHttpSessionStrategy();
    }
}
```

I use redis based spring session and all others work fine. However, when I sign in and out, no session change events are caught. Am I missing anything there?

I am using the newest Spring session 1.3.1 and Spring security 4.2, plus the new Spring boot.

**Comment by taozhaolib** [comment]
I also noticed there was the issue which was closed : https://github.com/spring-projects/spring-session/issues/659. Even if I tried the classic way of using "implements ApplicationListener<SessionDestroyedEvent>" I still got nothing working.

**Comment by taozhaolib** [comment]
Just found some config issues and fixed this. But still cannot set up the session maxInactiveIntervalInSeconds. I am closing this now though.

**Comment by vpavic** [comment]
@taozhaolib Thanks for following up, glad to see you have it resolved. If you have further configuration problems feel free to re-open the issue, and ideally provide a sample app that reproduces the problem.
