### ISSUE TITLE
FindByIndexNameSessionRepository#findByIndexNameAndIndexValue signature does not reflect its implementation.

### ISSUE THREAD

**Issue by mld-ger** [spring-projects/spring-session#953]
I want to use the `FindByIndexNameSessionRepository` to find sessions based on specific attributes that I filled with my business logic. But after finishing the implementation I noticed that (at least) the `RedisOperationsSessionRepository` as well as the `JdbcOperationsSessionRepository` check if the index is different than `PRINCIPAL_NAME_INDEX_NAME` and return `Collections.emptyMap()`. This behavior is not obvious when viewing the method signature.

Therefore I would propose to either change the signature of this function to reflect this behavior or the existing implementations should offer the behavior to find any attribute by its name and value.

edit: After thinking more about this issue I realized that actually the signature is speaking about an index instead of attributes in general and therefore indexes are database and implementation related. So the signature is actually reflecting what it does. But anyway I got confused by that and I would like to see a comment about this limitation on the interface to make it clear and also I still think that the behavior is wrong to return an empty map when the attribute is not indexed on the implementation but instead an error should be thrown.

**Comment by vpavic** [comment]
Thanks for the report @mld-ger. As you've said yourself in the update of your original comment, `FindByIndexNameSessionRepository` is based on indexes and not attributes and the supported indexes are specific to each implementation.

Regarding the behavior of `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue`, it's documented in the method's javadoc:

```javadoc
Find a Map of the session id to the {@link Session} of all sessions that contain
the session attribute with the name
{@link FindByIndexNameSessionRepository#PRINCIPAL_NAME_INDEX_NAME} and the value of
the specified principal name.

@param indexName the name if the index (i.e.
{@link FindByIndexNameSessionRepository#PRINCIPAL_NAME_INDEX_NAME})
@param indexValue the value of the index to search for.
@return a Map (never null) of the session id to the {@link Session} of all sessions
that contain the session specified index name and the value of the specified index
name. If no results are found, an empty Map is returned.
```

So returning an empty Map in the provided index isn't matched is clearly documented. This behavior is also much more friendly to the consumer than throwing an exception would be.

That being said, I'm closing this as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
