### ISSUE TITLE
specify cookie domain for session id ?

### ISSUE THREAD

**Issue by littlehome-eugene** [spring-projects/spring-session#955]
I'm new to spring/spring-boot/spring-session.

I'm trying to share cookie between `a.example.com` and `b.example.com`

Below is code I have,

```
 @EnableJdbcHttpSession // <1>
 public class HttpSessionConfig {

   // tag::cookie-serializer[]
   @Bean
   public CookieSerializer cookieSerializer() {
     DefaultCookieSerializer serializer = new DefaultCookieSerializer();
     // serializer.setCookieName("JSESSIONID"); // <1>
     // serializer.setCookiePath("/"); // <2>
     // serializer.setDomainNamePattern("^.+?\\.(\\w+\\.[a-z]+)$"); // <3>
     return serializer;
   }
   // end::cookie-serializer[]

 }
```

I'm getting error

> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.4.RELEASE:run (default-cli) on project social-simple: An exception occurred while running. null: InvocationTargetException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to
> start embedded Tomcat: Error creating bean with name 'org.springframework.boot.autoconfigure.session.JdbcSessionConfiguration$SpringBootJdbcHttpSessionConfiguration': Unsatisfied dependency expressed through method 'customize' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.session-org.springframework.boot.autoconfigure.session.SessionProperties': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.session.SessionProperties]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/session/hazelcast/HazelcastFlushMode: org.springframework.session.hazelcast.HazelcastFlushMode

What should I do to fix this?

- edit

I found I needed `spring-session` not `spring-session-jdbc` so I changed

from 

         <dependency>
           <groupId>org.springframework.session</groupId>
           <artifactId>spring-session-jdbc</artifactId>
           <version>2.0.0.RC2</version>
         </dependency>

to

         <dependency>
           <groupId>org.springframework.session</groupId>
           <artifactId>spring-session</artifactId>
           <version>2.0.0.M2</version>
         </dependency>

Although they are not compatible with mysql schema i use.. 

When is 2.0.0.RC2 being released?

**Comment by vpavic** [comment]
Thanks for the report @littlehome-eugene.

Could you please clarify this statement:

> I found I needed `spring-session` not `spring-session-jdbc`

If you want to use the Spring Session JDBC the artifact you need is `spring-session-jdbc`, whose most recent milestone is `2.0.0.RC2`.

Note that `spring-session` artifact does not exist since `2.0.0.M3` (see [this blog post](https://spring.io/blog/2017/07/25/spring-session-2-0-m3-released)) as it has been superseded by `spring-session-core`, which is being pulled in as a transitive dependency of `spring-session-jdbc`.

Can you provide a sample that demonstrates the problem you're facing?

**Comment by littlehome-eugene** [comment]
I solved it by using
```

     <dependency>                                                                                                                                                                                                                                                       │·······
       <groupId>org.springframework.session</groupId>                                                                                                                                                                                                                   │·······
       <artifactId>spring-session-jdbc</artifactId>                                                                                                                                                                                                                     │·······
       <version>2.0.0.RELEASE</version>                                                                                                                                                                                                                                 │·······
     </dependency>
```
