### ISSUE TITLE
SessionRepositoryFilter.doFilterInternal

### ISSUE THREAD

**Issue by mayras** [spring-projects/spring-session#957]
SessionRepositoryFilter.doFilterInternal, line 170:

wrappedRequest.commitSession();

But should be:

strategyRequest.commitSession();

I'm not able to make necessary overrides

**Comment by vpavic** [comment]
Thanks for the report @mayras. Can you provide more information about the actual problem you're facing?

Note that you cannot invoke `commitSession` on `strategyRequest` as it's an `HttpServletRequest` (and not `SessionRepositoryRequestWrapper` which actually provides `commitSession` operation).

**Comment by mayras** [comment]
Actually, I have quite big JS framework and it's really hard to introduce parameter "_s" for every link to server. I just did own http servlet wrapper and managing value "_s" depends on context path. Solution looks quite ugly - I added new filter above SessionRepositoryFilter, because I can't use wrapRequest() and manage "_s" how I want, there is error because of commitSession() is invoked for strategyRequest, which isn't my implementation. I think - you need to introduce some server-side way to manage value "_s" how developers want, but not by JS client...

**Comment by vpavic** [comment]
We've removed the support for multiple browser sessions in 2.0 as a part of #906, and 1.3 line will only receive bugfixes until its EOL. You can watch #917 where we consider the introduction of improved support for multiple browser sessions, and feel free to vote on it.
