### ISSUE TITLE
Project 'samples' not found in root project 'spring-session-build' 

### ISSUE THREAD

**Issue by utsavkansara** [spring-projects/spring-session#969]

**Comment by utsavkansara** [comment]
Hi,

I am following examples from Spring session documentation:
https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-findbyusername.html

While trying to run the application as per the documentation by running following command
./gradlew :samples:findbyusername:tomcatRun

I get following error:

FAILURE: Build failed with an exception.

What went wrong:
Project 'samples' not found in root project 'spring-session-build'.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 1s

Can someone help me with this ?
I am running this on MacOS High Sierra.

**Comment by vpavic** [comment]
Thanks for the report @utsavkansara. It seems that the samples documentation wasn't updated to follow changes to project structure. We'll address this.

You can run `$ ./gradlew projects` to get the accurate listing of all the projects. Specifically, for sample app you're interested you should run `$ ./gradlew :spring-session-sample-boot-findbyusername:bootRun`.
