### ISSUE TITLE
Add support for AWS Elasticache 

### ISSUE THREAD

**Issue by dwelch2344** [spring-projects/spring-session#97]
We would love to see support for both the Redis and Memcached flavors of Elasticache. I'd be happy to spend some time working on it, if you could point me in the right direction. 

I believe the trickiest part will be handling the elasticity of the nodes (though there are already tool kits to help manage that)

**Comment by rwinch** [comment]
Thanks @dwelch2344 for your willingness to contribute! I have no experience working with Elasticache, so I will probably not be of much help in that respect.

I have outlined the steps below:

* The first step would be to implement the `SessionRepository<ExpiringSession>`. Currently there are two implementations that you can refer to:
  * [MapSessionRepository](https://github.com/spring-projects/spring-session/blob/1c829ae78a0e1b6d8e4f768bc26d27fe2a6295ae/spring-session/src/main/java/org/springframework/session/MapSessionRepository.java) - uses a Map implementation as the datastore
  * [RedisOperationsSessionRepository](https://github.com/spring-projects/spring-session/blob/1.0.0.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java) - uses Spring Data Redis as the implementation.
* Are you using Spring Session with WebSockets or just for HttpSession support? If you want to support WebSocket's you will need to ensure that a [SessionDestroyedEvent](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent) is fired. The `RedisOperationsSessionRepository` does this by [listening to Redis keyspace notifications](http://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration). Specifically this is done using [SessionMessageListener](https://github.com/spring-projects/spring-session/blob/1c829ae78a0e1b6d8e4f768bc26d27fe2a6295ae/spring-session/src/main/java/org/springframework/session/data/redis/SessionMessageListener.java)
* Last you will need to know how to configure it. You can base your configuration off of [RedisHttpSessionConfiguration](https://github.com/spring-projects/spring-session/blob/1c829ae78a0e1b6d8e4f768bc26d27fe2a6295ae/spring-session/src/main/java/org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.java)

Please feel free to post any questions here and I will be sure to answer than as fast as possible. Thanks again!

**Comment by rwinch** [comment]
@dwelch2344 It looks like @danveloper has Spring Session working with Amazon ElasticCache. See https://github.com/spring-projects/spring-session/issues/124#issuecomment-71525940

Obviously we need to resolved #124 but does this get you what you need?

**Comment by andirdju** [comment]
@dwelch2344, @rwinch
the issue with aws elasticache is that not all commands are allowed.
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ClientConfig.html
-- Restricted Commands

**Comment by andirdju** [comment]
@dwelch2344, @rwinch 
finally got it working on aws elasticache redis using guide from @danveloper:
https://github.com/spring-projects/spring-session/issues/124#issuecomment-71525940

In my setup I just need to adjust the spring-el syntax to something like this,
it won't work with the ```$``` sign:

    @Value("#{systemProperties['spring_session_redis_expiration'] ?: 1800}")

test it using aws beanstalk with 5 instance, load balanced, no sticky session.
no need to relogin after restarting the tomcat server :smile:.
Previously I was using https://github.com/jcoleman/tomcat-redis-session-manager to handle the centralized session storage.

the config I use (besides the ```RedisHttpSessionConfiguration``` subclass):
```
    @Order(100)
    public class SpringSessionInitializer extends AbstractHttpSessionApplicationInitializer {
    }
```

```
    @Configuration
    public class Config {

      @Bean
      public static JedisConnectionFactory jedisConnectionFactory() {
        JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(jedisPoolConfig());
        jedisConnectionFactory.setHostName(System.getProperty("spring_session_redis_host"));
        jedisConnectionFactory
            .setPort(Integer.parseInt(System.getProperty("spring_session_redis_port")));
        jedisConnectionFactory.setPassword(System.getProperty("spring_session_redis_password"));
        jedisConnectionFactory.setDatabase(Integer.parseInt(System
            .getProperty("spring_session_redis_database")));
        jedisConnectionFactory.setTimeout(Integer.parseInt(System
            .getProperty("spring_session_redis_timeout")));
        jedisConnectionFactory.setUsePool(Boolean.parseBoolean(System
            .getProperty("spring_session_redis_use_pool")));
        return jedisConnectionFactory;
      }

      @Bean
      public static JedisPoolConfig jedisPoolConfig() {
        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        jedisPoolConfig.setTestOnBorrow(Boolean.parseBoolean(System
            .getProperty("spring_session_redis_pool_test_on_borrow")));
        jedisPoolConfig.setMaxTotal(Integer.parseInt(System
            .getProperty("spring_session_redis_pool_max_total")));
        jedisPoolConfig.setMaxIdle(Integer.parseInt(System
            .getProperty("spring_session_redis_pool_max_idle")));
        jedisPoolConfig.setMinIdle(Integer.parseInt(System
            .getProperty("spring_session_redis_pool_min_idle")));
        return jedisPoolConfig;
      }

    }
```

**Comment by dwelch2344** [comment]
Very cool to see this @andirdju. Nice work! 

I had attempted to follow @danveloper's work but ran into a few subtle issues that we couldn't dig into (due to time requirements on our end). We ended up switching to a stateless JWT solution for this project so I haven't had a chance to try it again in a little while. That being said, we will likely try to replicate with @andirdju listed above.

**Comment by rwinch** [comment]
AWS and Redis are now supported in 1.0.1 now that #124 is fixed. For detailed setup refer to the instructions provided at https://github.com/spring-projects/spring-session/issues/124#issuecomment-71525940
