### ISSUE TITLE
spring session jdbc for session sharing for multiple machines?

### ISSUE THREAD

**Issue by littlehome-eugene** [spring-projects/spring-session#970]
I'm trying to let two machines with the same base domain (subdomains differ) to share session.  

spring-session-jdbc seems to be a solution I could use to achieve the goal.

When a user logs into `server-a`, session info is stored in SPRING_SESSION db.  
What worries me is the fact that custom `org.springframework.security.core.userdetails.UserDetails` class is stored in that db as well.  

When `server-b` tries to read session data from the db, it has to use the same custom subclass of the `org.springframework.security.core.userdetails.UserDetails`.

So I'm copying codes that relates to the `UserDetails` class from `server-a` to `server-b`.  

I'm feeling a little awkward doing this, because `server-a` and `server-b` might want different `UserDetails` in general.  

Is this really intended way of using `spring-session-jdbc` ? 

Another question is, is it mandatory to use `spring-security` for both `server-a` and `server-b`?

**Comment by vpavic** [comment]
> Is this really intended way of using `spring-session-jdbc` ?

I'd avoid using Spring Session to have different apps share the same session store. While it might seem convenient initially, such arrangement is usually very problematic. It also couples the involved apps through the session store, as you noted yourself with the `UserDetails` example.

Spring Session is meant to easily enable session clustering, i.e. have the multiple instances of the same app share the external session store. For the problem you are trying to solve I'd suggest to use an appropriate protocol such as OAuth 2.0 and OpenID Connect.

Another question is, is it mandatory to use `spring-security` for both `server-a` and `server-b`?

Spring Security is not required to be used with Spring Session.

**Comment by littlehome-eugene** [comment]
I've decided to use spring-session-jdbc only to store session in db from `server-a`.

A user logs in at `server-a`
`server-a` stores session in jdbc and store `user-id` as session property.
The user gets redirected to `server-b`
`server-b` reads the session data stored in the db and get user data using the `user-id` and authententicate the user if session data is there.

**Comment by vpavic** [comment]
@littlehome-eugene With this being a case of sharing the same session store between different apps I can only repeat the recommendations from my previous comment.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
