### ISSUE TITLE
Question on CookieSerializer.CookieValue visibility

### ISSUE THREAD

**Issue by elartigue** [spring-projects/spring-session#978]
Hi, I'm in Spring Session 1.2.2 and I'm trying to move up to 2.x
I noticed CookeSerializer.CookieValue changed visibility from public to package.

sorry if this is super basic, but in new version how could I update the CookieValue from the already configured CookieSerializer.CookieValue?

in 1.2.2 I was doing
myCookieSerializer.writeCookieValue(new CookieSerializer.CookieValue(request, response, "some value"));

thank you in advance.

**Comment by vpavic** [comment]
Thanks for the report @elartigue.

It seems that `public` visibility on `CookeSerializer.CookieValue` was accidentally dropped in 7f33022 however that change was a part of `1.2.0.RC1` milestone. Can you clarify how this works for you in `1.2.2.RELEASE`?

**Comment by vpavic** [comment]
Actually my previous comment was wrong, the problem was actually introduced in 8e3371a (which was a part of `2.0.0.M4`).

**Comment by elartigue** [comment]
hello, yeah I noticed this when I moved up to 2.x   so do you think we are making this back to public ?

**Comment by vpavic** [comment]
@elartigue Yes, I've just pushed a fix for this to `master`.
