### ISSUE TITLE
Confusing readme in sample for FindByUsername

### ISSUE THREAD

**Issue by mrshawn191** [spring-projects/spring-session#989]
https://github.com/spring-projects/spring-session/tree/master/samples/boot/findbyusername

"The sample provides a hook to add the current username to the session (required for finding the user) by providing a custom implementation of Spring Security’s AuthenticationSuccessHandler."

I couldn't find any custom implementation of AuthenticationSuccessHandler. 

Is this sample complete?

**Comment by vpavic** [comment]
Thanks for the report @mrshawn191.

This is an outdated documentation dating to very early releases of Spring Session.

**Comment by mrshawn191** [comment]
Thanks for the response.
