### ISSUE TITLE
Create a pair of serializers / deserializers supporting mixed versions of Spring Sessions among projects

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-session#991]
While evaluating an idea for migrating an older project to a set of self contained systems by gradually replacing parts of it, I stumbled upon the following issue:

The project is on plain Spring 4.x and especially on an older Hibernate version. It's no option to upgrade it to Spring 5 right now. Parts of it shall be gradually replaced by not so small Spring Boot 2.0 applications with their own UI. Integration shall be done via service side includes when applicable. 

The idea was to use Spring Session (Redis) to share sessions between the instances. 

This poses at least two problems: First I the custom principal has probably to be duplicated or put in a shared library. Easy to solve.

The second problem is hard: In the old project I can only use Spring Session 1.3.x and when I want to use Spring Boot 2 for all new development, I'll have to Stick with Spring Session 2 (I guess it's possible to override versions until it works, but that feels to fragile). 

It turns out that approach is not possible at the moment. Spring Session 1.3.x and Spring Session 2.x serialize way different objects (2.x a context AFAIK / seen).

The question or issue here is how much effort it would be, to provide a pair of  serializers / deserializers into and from JSON, that facilitate that use case. 

Possible solutions would be
* A common JSON format that could be read and written on both sides
* Only work on the 2.x side of things so that an older model could be read and written

I could pursue that topic on my own, but reached out to @rwinch to see wether that is a realistic possibility or not.

**Comment by vpavic** [comment]
Thanks for the report @michael-simons.

For starters, did you perhaps take a look a [Redis with JSON serialization sample app](https://github.com/spring-projects/spring-session/tree/2.0.1.RELEASE/samples/boot/redis-json) and does that help you with what you're trying to achieve?

> Spring Session 1.3.x and Spring Session 2.x serialize way different objects (2.x a context AFAIK / seen).

Can you clarify this a bit? I might be wrong, but I think we managed to keep the same storage format with Redis session store between 1.x and 2.x. Are you maybe referring to Spring Security context which is stored in the session?

Also, by your description it seems to me that you're attempting to share the same session store between different. Is this assumption correct?

**Comment by michael-simons** [comment]
Hi.

> Are you maybe referring to Spring Security context which is stored in the session?

Yes.

> Also, by your description it seems to me that you're attempting to share the same session store between different

There's something missing.

I want to share the session between at least two different applications, correct.

**Comment by vpavic** [comment]
> There's something missing.

Thanks, I've updated the comment. Your assumption on the missing part (application) was correct though.

Generally, sharing a session store between different apps is quite problematic (as you've seen yourself) and actually isn't among Spring Session's intended use cases. Preferably such problem would be addressed at a higher level, using protocols like OAuth2/OIDC.

Having said that, many users still do opt to share the sessions between different apps and the only advice in that case is to use JSON based serialization (for instance by using Spring Security's [`SecurityJackson2Modules`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/jackson2/SecurityJackson2Modules.html), like in the sample from the previous comment) and be careful what the involved apps store in the session.

**Comment by rwinch** [comment]
I'm wondering if the best approach here is to ensure that Spring Session 1.3.x works with Spring Framework 5.x line of code. This is generally something we like to do anyways to ensure that migrations are easier.

**Comment by vpavic** [comment]
@michael-simons Do you still require this? IIRC at Spring I/O this May you mentioned something about you addressing this problem at a different/higher level?

**Comment by michael-simons** [comment]
Hey. Thanks for reaching out. It’s probably not worth the effort, especially one doesn’t promote exactly best practices. I didn’t pursue this this year due to personal time constraints.

**Comment by vpavic** [comment]
Thanks for following up! :+1:
